Repository payloadcms/payload, pull requests merged in 2023-10, with the labels that each got.

#3307 fix(2.0): greater than or equal filter
  packages/payload/src/admin/components/elements/WhereBuilder/field-types.tsx
  test/fields/config.ts
  test/fields/e2e.spec.ts
Labels: 2.0

#3424 fix: secures the user response from the me auth route
  packages/payload/src/auth/operations/me.ts
  packages/payload/src/auth/strategies/jwt.ts
  test/auth/config.ts
  test/auth/int.spec.ts
  test/auth/payload-types.ts
Labels: 2.0

#3443 chore(examples/testing): builds testing example
  examples/testing/.env.example
  examples/testing/README.md
  examples/testing/jest.config.ts
  examples/testing/nodemon.json
  examples/testing/package.json
  examples/testing/src/payload-types.ts
  examples/testing/src/payload.config.ts
  examples/testing/src/server.ts
  examples/testing/src/tests/credentials.ts
  examples/testing/src/tests/globalSetup.ts
  examples/testing/src/tests/login.spec.ts
  examples/testing/tsconfig.json
  examples/testing/yarn.lock
  jest.config.js
Labels: 2.0

#3444 fix: doc title not rendering in breadcrumbs
  packages/payload/src/admin/components/views/collections/Edit/SetStepNav.tsx
Labels: 2.0

#3447 chore: style adjustments for api tab
  packages/payload/src/admin/components/forms/field-types/Checkbox/index.scss
  packages/payload/src/admin/components/views/API/index.scss
  packages/payload/src/admin/components/views/API/index.tsx
  packages/payload/src/admin/components/views/RestAPI/index.scss
  packages/payload/src/admin/components/views/RestAPI/index.tsx
Labels: 2.0

#3449 feat: breaking: richtext-lexical: block node validations
  package.json
  packages/payload/src/admin/components/elements/DocumentDrawer/DrawerContent.tsx
  packages/payload/src/admin/components/forms/Form/buildStateFromSchema/addFieldStatePromise.ts
  packages/payload/src/admin/components/forms/Form/buildStateFromSchema/index.ts
  packages/payload/src/admin/components/forms/Form/buildStateFromSchema/iterateFields.ts
  packages/payload/src/admin/components/forms/Form/index.tsx
  packages/payload/src/admin/components/forms/Form/types.ts
  packages/payload/src/admin/components/forms/field-types/RichText/index.tsx
  packages/payload/src/admin/components/forms/field-types/RichText/types.ts
  packages/payload/src/admin/components/forms/useField/index.tsx
  packages/payload/src/admin/components/views/Account/index.tsx
  packages/payload/src/admin/components/views/Global/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/index.tsx
  packages/payload/src/admin/components/views/collections/List/Cell/field-types/Richtext/index.tsx
  packages/payload/src/config/schema.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/schema.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/validations.ts
  packages/payload/src/graphql/schema/buildObjectType.ts
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-lexical/src/field/features/Blocks/component/BlockContent.tsx
  packages/richtext-lexical/src/field/features/Blocks/component/FormSavePlugin.tsx
  packages/richtext-lexical/src/field/features/Blocks/component/index.tsx
  packages/richtext-lexical/src/field/features/Blocks/drawer/index.tsx
  packages/richtext-lexical/src/field/features/Blocks/index.tsx
  packages/richtext-lexical/src/field/features/Blocks/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/field/features/Blocks/validate.ts
  packages/richtext-lexical/src/field/features/Link/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/field/features/Upload/component/ExtraFieldsDrawer/index.tsx
  packages/richtext-lexical/src/field/features/types.ts
  packages/richtext-lexical/src/field/index.scss
  packages/richtext-lexical/src/field/lexical/LexicalEditor.scss
  packages/richtext-lexical/src/field/lexical/config/sanitize.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/populate/defaultValue.ts
  packages/richtext-lexical/src/populate/validation.ts
  packages/richtext-lexical/src/validate/index.ts
  packages/richtext-lexical/src/validate/validateNodes.ts
  packages/richtext-slate/src/data/validation.ts
  packages/richtext-slate/src/field/RichText.tsx
  packages/richtext-slate/src/field/elements/link/Button/index.tsx
  packages/richtext-slate/src/field/elements/link/Element/index.tsx
  packages/richtext-slate/src/field/elements/upload/Element/UploadDrawer/index.tsx
  packages/richtext-slate/src/index.ts
  pnpm-lock.yaml
  test/fields/collections/RichText/index.ts
Labels: 2.0

#3435 chore: renders id column as code cell
  packages/payload/src/admin/components/views/collections/List/Cell/field-types/Code/index.scss
  packages/payload/src/admin/components/views/collections/List/Cell/field-types/Code/index.tsx
  packages/payload/src/admin/components/views/collections/List/Cell/index.tsx
  test/admin/e2e.spec.ts
Labels: 2.0

#3433 feat: 2.0 upload enhancements
  docs/upload/overview.mdx
  package.json
  packages/payload/src/admin/components/elements/Drawer/index.tsx
  packages/payload/src/admin/components/elements/Drawer/types.ts
  packages/payload/src/admin/components/elements/Dropzone/index.scss
  packages/payload/src/admin/components/elements/Dropzone/index.tsx
  packages/payload/src/admin/components/elements/EditUpload/index.scss
  packages/payload/src/admin/components/elements/EditUpload/index.tsx
  packages/payload/src/admin/components/elements/FileDetails/index.scss
  packages/payload/src/admin/components/elements/FileDetails/index.tsx
  packages/payload/src/admin/components/elements/FileDetails/types.ts
  packages/payload/src/admin/components/elements/PreviewSizes/index.scss
  packages/payload/src/admin/components/elements/PreviewSizes/index.tsx
  packages/payload/src/admin/components/elements/Thumbnail/index.tsx
  packages/payload/src/admin/components/elements/Thumbnail/types.ts
  packages/payload/src/admin/components/utilities/FormQueryParams/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/Default/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/Upload/index.scss
  packages/payload/src/admin/components/views/collections/Edit/Upload/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/Upload/types.ts
  packages/payload/src/admin/components/views/collections/Edit/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/types.ts
  packages/payload/src/collections/config/schema.ts
  packages/payload/src/translations/ar.json
  packages/payload/src/translations/az.json
  packages/payload/src/translations/bg.json
  packages/payload/src/translations/cs.json
  packages/payload/src/translations/de.json
  packages/payload/src/translations/en.json
  packages/payload/src/translations/es.json
  packages/payload/src/translations/fa.json
  packages/payload/src/translations/fr.json
  packages/payload/src/translations/hr.json
  packages/payload/src/translations/hu.json
  packages/payload/src/translations/it.json
  packages/payload/src/translations/ja.json
  packages/payload/src/translations/my.json
  packages/payload/src/translations/nb.json
  packages/payload/src/translations/nl.json
  packages/payload/src/translations/pl.json
  packages/payload/src/translations/pt.json
  packages/payload/src/translations/ro.json
  packages/payload/src/translations/ru.json
  packages/payload/src/translations/sv.json
  packages/payload/src/translations/th.json
  packages/payload/src/translations/tr.json
  packages/payload/src/translations/translation-schema.json
  packages/payload/src/translations/ua.json
  packages/payload/src/translations/vi.json
  packages/payload/src/translations/zh.json
  packages/payload/src/uploads/cropImage.ts
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/imageResizer.ts
  packages/payload/src/uploads/types.ts
  pnpm-lock.yaml
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
Labels: 2.0

#3454 2 0/doc updates p
  docs/admin/overview.mdx
  docs/typescript/generating-types.mdx
Labels: 2.0

#3226 Rich Text toolbar not rendered if leaves and elements are empty
  src/admin/components/forms/field-types/RichText/RichText.tsx
Labels: base:1.x

#3342 Fix ctrl s on global section
  src/admin/components/views/Global/index.tsx
  test/_community/e2e.spec.ts
Labels: base:1.x

#3638 fix(richtext-lexical): Blocks: Nested Blocks having incorrect initial data (e.g. missing rows property)
  packages/payload/src/admin/components/forms/Form/fieldReducer.ts
  packages/payload/src/admin/components/forms/Form/index.tsx
  packages/payload/src/admin/components/forms/Form/types.ts
  packages/payload/src/admin/components/forms/RenderFields/index.tsx
  packages/payload/src/admin/components/forms/useField/index.tsx
  packages/richtext-lexical/src/field/features/Blocks/component/BlockContent.tsx
  packages/richtext-lexical/src/field/features/Blocks/component/index.tsx
  test/fields/collections/Lexical/blocks.ts
  test/fields/collections/Lexical/generateLexicalRichText.ts
  test/fields/collections/Lexical/index.ts
  test/fields/collections/Lexical/loremIpsum.ts
  test/fields/config.ts
Labels: lexical

#3696 fix(richtext-*): link drawer form receiving incorrect field schema
  packages/richtext-lexical/src/field/features/Link/drawer/index.tsx
  packages/richtext-slate/src/field/elements/link/LinkDrawer/index.tsx
Labels: plugin:richtext-lexical, plugin:richtext-slate

#3805 fix(richtext-lexical): missing use client markers required for next.js compatibility
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-lexical/src/field/features/BlockQuote/index.ts
  packages/richtext-lexical/src/field/features/Blocks/component/index.tsx
  packages/richtext-lexical/src/field/features/Blocks/drawer/index.tsx
  packages/richtext-lexical/src/field/features/Blocks/index.ts
  packages/richtext-lexical/src/field/features/Blocks/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/field/features/Blocks/plugin/index.tsx
  packages/richtext-lexical/src/field/features/Heading/index.ts
  packages/richtext-lexical/src/field/features/Link/index.ts
  packages/richtext-lexical/src/field/features/Link/plugins/autoLink/index.tsx
  packages/richtext-lexical/src/field/features/Link/plugins/clickableLink/index.tsx
  packages/richtext-lexical/src/field/features/Link/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/field/features/Link/plugins/floatingLinkEditor/index.tsx
  packages/richtext-lexical/src/field/features/Link/plugins/link/index.tsx
  packages/richtext-lexical/src/field/features/Paragraph/index.ts
  packages/richtext-lexical/src/field/features/Relationship/drawer/index.tsx
  packages/richtext-lexical/src/field/features/Relationship/index.ts
  packages/richtext-lexical/src/field/features/Relationship/nodes/components/RelationshipComponent.tsx
  packages/richtext-lexical/src/field/features/Relationship/plugins/index.tsx
  packages/richtext-lexical/src/field/features/Upload/component/index.tsx
  packages/richtext-lexical/src/field/features/Upload/drawer/index.tsx
  packages/richtext-lexical/src/field/features/Upload/index.ts
  packages/richtext-lexical/src/field/features/Upload/plugin/index.tsx
  packages/richtext-lexical/src/field/features/debug/TreeView/plugin.tsx
  packages/richtext-lexical/src/field/features/indent/index.ts
  packages/richtext-lexical/src/field/features/lists/CheckList/index.ts
  packages/richtext-lexical/src/field/features/lists/CheckList/plugin/index.tsx
  packages/richtext-lexical/src/field/features/lists/OrderedList/index.ts
  packages/richtext-lexical/src/field/features/lists/UnorderedList/index.ts
  packages/richtext-lexical/src/field/features/lists/plugin/index.tsx
  packages/richtext-lexical/src/field/features/types.ts
  packages/richtext-lexical/src/field/lexical/LexicalEditor.tsx
  packages/richtext-lexical/src/field/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/field/lexical/config/EditorConfigProvider.tsx
  packages/richtext-lexical/src/field/lexical/plugins/FloatingSelectToolbar/ToolbarButton/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/FloatingSelectToolbar/ToolbarDropdown/DropDown.tsx
  packages/richtext-lexical/src/field/lexical/plugins/FloatingSelectToolbar/ToolbarDropdown/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/FloatingSelectToolbar/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/MarkdownShortcut/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/LexicalMenu.tsx
  packages/richtext-lexical/src/field/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/types.ts
  packages/richtext-lexical/src/field/lexical/plugins/SlashMenu/defaultGroups.ts
  packages/richtext-lexical/src/field/lexical/plugins/SlashMenu/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/handles/AddBlockHandlePlugin/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/handles/DraggableBlockPlugin/index.tsx
  packages/richtext-lexical/src/index.ts
Labels: plugin:richtext-lexical

#3413 fix: ensures valid value is always passed to value prop, e.g. reset t…
  src/admin/components/views/Version/Compare/index.tsx
Labels: base:1.x
