Repository payloadcms/payload, pull requests merged in 2023-08, with the labels that each got.

#2500 feat: improve admin panel file's caching
  src/bundlers/webpack/configs/prod.ts
  src/bundlers/webpack/scripts/serve.ts
Labels: merge-priority-3

#2839 feat: make PAYLOAD_CONFIG_PATH optional
  docs/configuration/overview.mdx
  src/config/find.ts
Labels: merge-priority-3

#2951 feat: allow async relationship filter options
  docs/fields/relationship.mdx
  src/admin/components/forms/field-types/getFilterOptionsQuery.ts
  src/admin/components/utilities/GetFilterOptions/index.tsx
  src/fields/config/types.ts
  src/fields/validations.ts
  src/translations/ar.json
  src/translations/bg.json
  src/translations/cs.json
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fa.json
  src/translations/fr.json
  src/translations/hr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/ja.json
  src/translations/my.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pl.json
  src/translations/pt.json
  src/translations/ro.json
  src/translations/ru.json
  src/translations/sv.json
  src/translations/th.json
  src/translations/tr.json
  src/translations/translation-schema.json
  src/translations/ua.json
  src/translations/vi.json
  src/translations/zh.json
  test/fields-relationship/config.ts
  test/fields-relationship/e2e.spec.ts
Labels: merge-priority-1

#1821 feat: add support for hotkeys
  src/admin/components/elements/Button/index.tsx
  src/admin/components/elements/ReactSelect/Control/index.tsx
  src/admin/components/elements/Save/index.tsx
  src/admin/components/elements/SaveDraft/index.tsx
  src/admin/components/forms/Submit/index.tsx
  src/admin/components/forms/field-types/RichText/elements/link/LinkDrawer/index.tsx
  src/admin/hooks/useHotkey.tsx
  src/admin/utilities/setsAreEqual.ts
  test/admin/e2e.spec.ts
  test/fields/e2e.spec.ts
  test/helpers.ts
Labels: merge-priority-1

#3164 feat: Added Azerbaijani language file
  src/translations/az.json
  src/translations/index.ts
Labels: merge-priority-3

#2697 feat: add afterOperation hook
  docs/hooks/collections.mdx
  src/auth/operations/forgotPassword.ts
  src/auth/operations/login.ts
  src/auth/operations/refresh.ts
  src/collections/config/defaults.ts
  src/collections/config/schema.ts
  src/collections/config/types.ts
  src/collections/operations/create.ts
  src/collections/operations/delete.ts
  src/collections/operations/deleteByID.ts
  src/collections/operations/find.ts
  src/collections/operations/findByID.ts
  src/collections/operations/update.ts
  src/collections/operations/updateByID.ts
  src/collections/operations/utils.ts
  test/hooks/collections/AfterOperation/index.ts
  test/hooks/config.ts
  test/hooks/int.spec.ts
  test/hooks/payload-types.ts
  types.d.ts
Labels: merge-priority-1

#3087 fix: WhereBuilder component does not accept all valid Where queries
  src/admin/components/elements/ListControls/index.tsx
  src/admin/components/elements/WhereBuilder/index.tsx
  src/admin/components/elements/WhereBuilder/transformWhereQuery.ts
  src/admin/components/elements/WhereBuilder/validateWhereQuery.ts
  src/admin/components/views/collections/List/index.tsx
  src/types/index.ts
  test/admin/e2e.spec.ts
Labels: bug, merge-priority-1

#3181 chore(test): adds test to ensure relationship returns over 10 docs
  test/relationships/config.ts
  test/relationships/int.spec.ts
  test/relationships/payload-types.ts
Labels: merge-priority-1

#3053 feat: Improve admin dashboard accessibility
  package.json
  scripts/translateNewKeys.ts
  src/admin/components/elements/Button/index.tsx
  src/admin/components/elements/Button/types.ts
  src/admin/components/elements/Card/index.scss
  src/admin/components/elements/Card/index.tsx
  src/admin/components/elements/Card/types.ts
  src/admin/components/elements/ColumnSelector/index.tsx
  src/admin/components/elements/ListControls/index.tsx
  src/admin/components/elements/Logout/index.tsx
  src/admin/components/elements/Nav/index.tsx
  src/admin/components/elements/Pill/index.tsx
  src/admin/components/elements/Pill/types.ts
  src/admin/components/elements/ReactSelect/types.ts
  src/admin/components/elements/SortColumn/index.tsx
  src/admin/components/forms/field-types/Checkbox/Input.tsx
  src/admin/components/forms/field-types/Checkbox/index.scss
  src/admin/components/views/Account/Default.tsx
  src/admin/components/views/Dashboard/Default.tsx
  src/admin/components/views/collections/List/Default.tsx
  src/admin/components/views/collections/List/SelectAll/index.scss
  src/admin/components/views/collections/List/SelectAll/index.tsx
  src/admin/components/views/collections/List/SelectRow/index.tsx
  src/translations/ar.json
  src/translations/az.json
  src/translations/bg.json
  src/translations/cs.json
  src/translations/de.json
  src/translations/en.json
  src/translations/es.json
  src/translations/fa.json
  src/translations/fr.json
  src/translations/hr.json
  src/translations/hu.json
  src/translations/it.json
  src/translations/ja.json
  src/translations/my.json
  src/translations/nb.json
  src/translations/nl.json
  src/translations/pl.json
  src/translations/pt.json
  src/translations/ro.json
  src/translations/ru.json
  src/translations/sv.json
  src/translations/th.json
  src/translations/tr.json
  src/translations/translation-schema.json
  src/translations/ua.json
  src/translations/vi.json
  src/translations/zh.json
  test/access-control/e2e.spec.ts
  test/admin/e2e.spec.ts
  test/refresh-permissions/e2e.spec.ts
  test/versions/e2e.spec.ts
Labels: merge-priority-1

#3183 feat: query support for geo within and intersects + dynamic GraphQL operator types
  src/admin/components/elements/WhereBuilder/field-types.tsx
  src/graphql/schema/buildWhereInputType.ts
  src/graphql/schema/operators.ts
  src/graphql/schema/withOperators.ts
  src/mongoose/buildQuery.ts
  src/mongoose/operatorMap.ts
  src/mongoose/sanitizeQueryValue.ts
  src/types/constants.ts
  src/utilities/flattenWhereConstraints.ts
  test/admin/config.ts
  test/admin/e2e.spec.ts
  test/collections-graphql/config.ts
  test/collections-graphql/int.spec.ts
  test/collections-rest/int.spec.ts
Labels: enhancement, merge-priority-1

#3153 feat: option to disable auto pluralization for the mongoose adapter
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/init.ts
  packages/db-mongodb/src/models/buildGlobalModel.ts
Labels: merge-priority-1

#2698 chore: upgrade pino (v6 => v8) and pino-pretty (v9 => v10)
  package.json
  src/utilities/logger.ts
  yarn.lock
Labels: 2.0, merge-priority-1

#3203 docs: adds minRow and maxRow to array and blocks pages
  docs/fields/array.mdx
  docs/fields/blocks.mdx
Labels: merge-priority-3

#3197 Fix: correct out of order dark-mode color variables
  src/admin/scss/colors.scss
Labels: merge-priority-3
