Repository payloadcms/payload, pull requests merged in 2024-03, with the labels that each got.

#5221 chore: remove outdated config properties
  packages/next/src/pages/List/Default/index.tsx
  packages/payload/src/auth/getExecuteStaticAccess.ts
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/config/schema.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/collections/operations/local/update.ts
  packages/payload/src/config/defaults.ts
  packages/payload/src/config/schema.ts
  packages/payload/src/config/types.ts
  packages/payload/src/exports/utilities.ts
  packages/payload/src/payload.ts
  packages/payload/src/uploads/formatFilesize.ts
  packages/payload/src/uploads/getBaseFields.ts
  packages/payload/src/uploads/types.ts
  packages/plugin-cloud-storage/src/adapters/azure/staticHandler.ts
  packages/plugin-cloud-storage/src/utilities/getFilePrefix.ts
  packages/ui/src/elements/FileDetails/FileMeta/index.scss
  packages/ui/src/elements/FileDetails/FileMeta/index.tsx
  packages/ui/src/elements/FileDetails/FileMeta/types.ts
  packages/ui/src/elements/FileDetails/index.tsx
  packages/ui/src/elements/PreviewSizes/index.tsx
Labels: 3.x

#5258 fix(richtext-lexical): Link: add open-in-new-tab to html converter
  packages/plugin-form-builder/src/utilities/lexical/converters/link.ts
Labels: plugin: richtext-lexical

#5259 fix(richtext-lexical): Blocks: generated output schema is not correct
  packages/payload/src/admin/components/forms/field-types/RichText/types.ts
  packages/payload/src/bin/generateTypes.ts
  packages/payload/src/exports/utilities.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  packages/payload/src/utilities/getCollectionIDFieldTypes.ts
  packages/richtext-lexical/src/field/features/Blocks/index.ts
  packages/richtext-lexical/src/field/features/types.ts
  packages/richtext-lexical/src/index.ts
  test/fields/payload-types.ts
Labels: plugin: richtext-lexical

#5293 fix (alpha): `auth.strategies` schema and removal of auth functions from client config
  packages/payload/src/collections/config/schema.ts
  packages/payload/src/config/createClientConfig.ts
Labels: 3.x-alpha

#5279 chore (alpha): removes `schemaOutputFile` prop
  docs/graphql/graphql-schema.mdx
  docs/graphql/overview.mdx
  packages/payload/src/config/defaults.ts
  packages/payload/src/config/schema.ts
  packages/payload/src/config/types.ts
  test/_community/config.ts
  test/collections-graphql/config.ts
  test/field-error-states/config.ts
  test/graphql-schema-gen/config.ts
Labels: 3.x-alpha

#5308 fix(ui): field label htmlFor
  packages/ui/src/forms/Label/index.tsx
  packages/ui/src/forms/fields/Checkbox/index.tsx
  packages/ui/src/utilities/buildComponentMap/mapFields.tsx
  packages/ui/src/utilities/generateFieldID.ts
Labels: 3.x-alpha
