Repository payloadcms/payload, pull requests merged in 2024-11, with the labels that each got.

#8983 chore: add project id source
  packages/payload/src/utilities/telemetry/index.ts
Labels: v3, created-by: Payload team

#9010 docs: improves clarity for better readability of document-locking docs
  docs/admin/locked-documents.mdx
Labels: v3, created-by: Payload team

#9011 fix: list drawer relationship not displaying
  packages/payload/src/admin/components/views/collections/List/Cell/field-types/Relationship/index.tsx
Labels: created-by: Payload team

#9014 fix: querying relationships by `id` path with REST
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  test/relationships/int.spec.ts
Labels: created-by: Payload team

#9013 fix: querying relationships by `id` path with REST
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  test/relationships/int.spec.ts
Labels: v3, created-by: Payload team

#8991 fix: invalid `select` type with `strictNullChecks: true`
  packages/payload/src/utilities/addSelectGenericsToGeneratedTyoes.spec.ts
  packages/payload/src/utilities/addSelectGenericsToGeneretedTypes.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  templates/website/src/payload-types.ts
  test/select/payload-types.ts
Labels: v3, created-by: Payload team

#8987 fix: graphql missing options route resulting in failed cors preflight checks in production
  app/(payload)/api/graphql/route.ts
  examples/auth/payload/src/app/(payload)/api/graphql/route.ts
  examples/custom-components/src/app/(payload)/api/graphql/route.ts
  examples/form-builder/payload/src/app/(payload)/api/graphql/route.ts
  examples/hierarchy/src/app/(payload)/api/graphql/route.ts
  examples/live-preview/payload/src/app/(payload)/api/graphql/route.ts
  examples/multi-tenant/src/app/(payload)/api/graphql/route.ts
  examples/tailwind-shadcn-ui/src/app/(payload)/api/graphql/route.ts
  examples/virtual-fields/src/app/(payload)/api/graphql/route.ts
  examples/whitelabel/src/app/(payload)/api/graphql/route.ts
  templates/_template/src/app/(payload)/api/graphql/route.ts
  templates/blank/src/app/(payload)/api/graphql/route.ts
  templates/vercel-postgres/src/app/(payload)/api/graphql/route.ts
  templates/website/src/app/(payload)/api/graphql/route.ts
  templates/with-payload-cloud/src/app/(payload)/api/graphql/route.ts
  templates/with-postgres/src/app/(payload)/api/graphql/route.ts
  templates/with-vercel-mongodb/src/app/(payload)/api/graphql/route.ts
  templates/with-vercel-postgres/src/app/(payload)/api/graphql/route.ts
  test/admin-root/app/(payload)/api/graphql/route.ts
  test/app/(payload)/api/graphql/route.ts
  test/live-preview/app/(payload)/api/graphql/route.ts
Labels: v3, created-by: Payload team

#9020 fix: prefetch causing stale data
  packages/next/src/elements/DocumentHeader/Tabs/Tab/TabLink.tsx
  packages/next/src/elements/Nav/index.client.tsx
  packages/next/src/views/ForgotPassword/index.tsx
  packages/next/src/views/Login/LoginForm/index.tsx
  packages/next/src/views/ResetPassword/index.tsx
  packages/next/src/views/Versions/cells/CreatedAt/index.tsx
  packages/ui/src/elements/AppHeader/index.tsx
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Logout/index.tsx
  packages/ui/src/elements/Popup/PopupButtonList/index.tsx
  packages/ui/src/elements/StepNav/index.tsx
  packages/ui/src/elements/Table/DefaultCell/index.tsx
Labels: v3, created-by: Payload team

#8992 feat: add skip population of individual joins, execute access for joins, `sanitizeJoinQuery`
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/next/src/routes/rest/utilities/sanitizeJoinParams.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/database/getLocalizedPaths.ts
  packages/payload/src/database/queryValidation/validateQueryPaths.ts
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  packages/payload/src/database/sanitizeJoinQuery.ts
  packages/payload/src/types/index.ts
  test/joins/int.spec.ts
Labels: created-by: Payload team

#9027 feat: adds x-powered-by Payload header in next config
  packages/next/src/withPayload.js
Labels: v3, created-by: Payload team

#9026 fix(ui): `updatedAt` field in locked-docs collection able to be updated by non-owner
  packages/ui/src/utilities/buildFormState.ts
  test/locked-documents/collections/Posts/fields/DocumentLoaded.tsx
  test/locked-documents/collections/Posts/index.ts
Labels: v3, created-by: Payload team

#9016 fix(db-postgres): sort by localized fields
  packages/db-postgres/src/count.ts
  packages/db-postgres/src/find/findMany.ts
  packages/db-postgres/src/queries/getTableColumnFromPath.ts
  test/localization/int.spec.ts
Labels: created-by: Payload team

#9036 feat(templates): website template now has configured image sizes, updated readme and simplified env vars for setting up
  templates/website/.env.example
  templates/website/README.md
  templates/website/src/collections/Media.ts
  templates/website/src/environment.d.ts
  templates/website/src/payload-types.ts
  templates/website/src/payload.config.ts
Labels: v3, created-by: Payload team

#9038 docs: improves jobs queue
  docs/jobs-queue/overview.mdx
Labels: v3, created-by: Payload team

#9018 fix(ui): json fields can now take a maxHeight in admin props and there's a mininum height of 3 lines
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/CodeEditor/CodeEditor.tsx
  packages/ui/src/elements/CodeEditor/types.ts
  packages/ui/src/fields/JSON/index.tsx
  test/fields/collections/JSON/index.tsx
Labels: v3, created-by: Payload team

#9035 fix: type augmentation of `RequestContext`
  packages/payload/src/admin/RichText.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/collections/operations/local/count.ts
  packages/payload/src/collections/operations/local/create.ts
  packages/payload/src/collections/operations/local/delete.ts
  packages/payload/src/collections/operations/local/duplicate.ts
  packages/payload/src/collections/operations/local/find.ts
  packages/payload/src/collections/operations/local/findByID.ts
  packages/payload/src/collections/operations/local/findVersionByID.ts
  packages/payload/src/collections/operations/local/findVersions.ts
  packages/payload/src/collections/operations/local/restoreVersion.ts
  packages/payload/src/collections/operations/local/update.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterChange/index.ts
  packages/payload/src/fields/hooks/afterChange/promise.ts
  packages/payload/src/fields/hooks/afterChange/traverseFields.ts
  packages/payload/src/fields/hooks/afterRead/index.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/afterRead/traverseFields.ts
  packages/payload/src/fields/hooks/beforeChange/index.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/hooks/beforeChange/traverseFields.ts
  packages/payload/src/fields/hooks/beforeDuplicate/index.ts
  packages/payload/src/fields/hooks/beforeDuplicate/promise.ts
  packages/payload/src/fields/hooks/beforeDuplicate/traverseFields.ts
  packages/payload/src/fields/hooks/beforeValidate/index.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/fields/hooks/beforeValidate/traverseFields.ts
  packages/payload/src/globals/config/types.ts
  packages/payload/src/types/index.ts
  test/_community/int.spec.ts
  test/_community/types.d.ts
Labels: v3, created-by: Payload team

#9037 fix: custom endpoints with `method: 'put'`
  packages/next/src/exports/routes.ts
  packages/next/src/routes/rest/index.ts
  templates/_template/src/app/(payload)/api/[...slug]/route.ts
  templates/blank/src/app/(payload)/api/[...slug]/route.ts
  templates/vercel-postgres/src/app/(payload)/api/[...slug]/route.ts
  templates/website/src/app/(payload)/api/[...slug]/route.ts
  templates/with-payload-cloud/src/app/(payload)/api/[...slug]/route.ts
  templates/with-postgres/src/app/(payload)/api/[...slug]/route.ts
  templates/with-vercel-mongodb/src/app/(payload)/api/[...slug]/route.ts
  templates/with-vercel-postgres/src/app/(payload)/api/[...slug]/route.ts
  test/collections-rest/config.ts
  test/collections-rest/int.spec.ts
  test/helpers/NextRESTClient.ts
Labels: v3, created-by: Payload team

#8973 feat: add join field config `where` property
  docs/fields/join.mdx
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/next/src/routes/rest/utilities/sanitizeJoinParams.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/database/sanitizeJoinQuery.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/types/index.ts
  packages/ui/src/fields/Join/index.tsx
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
  test/access-control/config.ts
  test/access-control/int.spec.ts
  test/joins/collections/Categories.ts
  test/joins/collections/Posts.ts
  test/joins/config.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
  test/joins/shared.ts
Labels: v3, created-by: Payload team

#9050 fix(ui): dedupes custom id fields
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
Labels: v3, created-by: Payload team

#9006 fix(richtext-slate, ui): use `PointerEvents` to show tooltips on enabled / disabled buttons
  packages/richtext-slate/src/field/elements/Button.tsx
  packages/ui/src/elements/Button/index.tsx
Labels: plugin: richtext-slate, area: ui

#9052 fix: handle bulk upload sequentially to prevent conflicts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/BulkUpload/FormsManager/index.tsx
Labels: v3, created-by: Payload team

#9022 fix(db-postgres): handle special characters in `createDatabase`
  packages/drizzle/src/postgres/createDatabase.ts
Labels: v3, created-by: Payload team

#8719 fix: handle publish locale with autosave enabled and close dropdown
  packages/next/src/views/Version/Restore/index.tsx
  packages/payload/src/collections/operations/updateByID.ts
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Button/types.ts
  packages/ui/src/elements/PublishButton/index.tsx
Labels: v3, created-by: Payload team

#9054 feat: generate types for `joins`
  packages/payload/src/collections/operations/local/find.ts
  packages/payload/src/collections/operations/local/findByID.ts
  packages/payload/src/index.ts
  packages/payload/src/types/index.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  test/joins/payload-types.ts
  test/select/payload-types.ts
Labels: v3, created-by: Payload team

#9039 fix: allow workflows to be empty or undefined
  packages/payload/src/queues/config/jobsCollection.ts
  packages/payload/src/queues/config/types/index.ts
  packages/payload/src/queues/operations/runJobs/index.ts
Labels: v3, created-by: Payload team

#9055 chore: updates flaky locked-documents e2e tests
  test/locked-documents/e2e.spec.ts
Labels: v3, created-by: Payload team

#9059 feat(templates): add adminThumbnail to media in website template
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(payload)/admin/importMap.js
  templates/website/src/collections/Media.ts
  templates/website/src/payload-types.ts
Labels: v3, created-by: Payload team

#8970 ci: build templates with packed deps
  .github/workflows/main.yml
  scripts/build-template-with-local-pkgs.ts
Labels: v3, created-by: Payload team

#9067 docs: closes <strong> tags properly on jobs queue documentation
  docs/jobs-queue/overview.mdx
Labels: v3, created-by: Payload team

#9068 chore: database transactions docs formatting
  docs/database/transactions.mdx
Labels: v3, created-by: Payload team

#9064 test: naming with matrix
  .github/workflows/main.yml
Labels: v3, created-by: Payload team

#9072 fix(templates): fix website template's missing paragraph feature allowing you to change text from headings
  templates/website/src/app/(payload)/admin/importMap.js
  templates/website/src/payload.config.ts
Labels: v3, created-by: Payload team

#9076 perf: upgrade json-schema-to-typescript and various other dependencies
  examples/testing/package.json
  package.json
  packages/db-postgres/package.json
  packages/db-sqlite/package.json
  packages/db-vercel-postgres/package.json
  packages/drizzle/package.json
  packages/graphql/package.json
  packages/payload/package.json
  packages/payload/src/bin/index.ts
  packages/ui/package.json
  pnpm-lock.yaml
  test/package.json
Labels: v3, created-by: Payload team

#9089 fix(docs): auth page email broken link
  docs/authentication/email.mdx
Labels: v3, created-by: Payload team

#9087 fix: `populate` with find operation
  packages/payload/src/collections/operations/local/find.ts
  test/select/int.spec.ts
Labels: v3, created-by: Payload team

#9070 chore: correctly redirects after in-activity
  packages/next/src/views/Login/index.tsx
  packages/next/src/views/Logout/LogoutClient.tsx
  packages/ui/src/providers/Auth/index.tsx
Labels: v3, created-by: Payload team

#9071 fix(db-mongodb): write migrations index file
  packages/db-mongodb/src/createMigration.ts
  test/database/int.spec.ts
Labels: v3, created-by: Payload team

#8990 fix: login redirect missing route
  packages/next/src/utilities/initPage/handleAuthRedirect.ts
Labels: v3, created-by: Payload team

#9056 fix(db-mongodb): `totalDocs` with joins
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/queryDrafts.ts
  test/joins/int.spec.ts
Labels: v3, created-by: Payload team

#9025 fix: modifying a doc with the document drawer should not affect the initial doc
  packages/ui/src/fields/Relationship/index.tsx
  test/fields-relationship/e2e.spec.ts
Labels: v3, created-by: Payload team

#9069 fix!: handle custom id logic in mongodb adapter
  docs/fields/overview.mdx
  packages/db-mongodb/src/create.ts
  packages/payload/src/collections/operations/create.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: v3, created-by: Payload team

#9073 fix: migrateRefresh migrates without previously ran migrations
  packages/payload/src/database/migrations/migrateRefresh.ts
  test/database/int.spec.ts
Labels: v3, created-by: Payload team

#9078 feat(db-postgres): add point field support
  .github/workflows/main.yml
  docs/database/overview.mdx
  docs/fields/point.mdx
  package.json
  packages/db-mongodb/src/models/buildSchema.ts
  packages/db-postgres/package.json
  packages/db-postgres/src/connect.ts
  packages/db-postgres/src/index.ts
  packages/db-postgres/src/types.ts
  packages/db-sqlite/package.json
  packages/db-vercel-postgres/package.json
  packages/db-vercel-postgres/src/connect.ts
  packages/db-vercel-postgres/src/index.ts
  packages/db-vercel-postgres/src/types.ts
  packages/drizzle/package.json
  packages/drizzle/src/exports/postgres.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/migrate.ts
  packages/drizzle/src/migrateFresh.ts
  packages/drizzle/src/postgres/createExtensions.ts
  packages/drizzle/src/postgres/defaultSnapshot.ts
  packages/drizzle/src/postgres/schema/geometryColumn.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/withDefault.ts
  packages/drizzle/src/postgres/types.ts
  packages/drizzle/src/queries/operatorMap.ts
  packages/drizzle/src/queries/parseParams.ts
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  packages/drizzle/src/transform/write/traverseFields.ts
  packages/drizzle/src/types.ts
  packages/drizzle/src/utilities/pushDevSchema.ts
  pnpm-lock.yaml
  test/_community/payload-types.ts
  test/collections-graphql/int.spec.ts
  test/collections-rest/int.spec.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
  test/fields/int.spec.ts
  test/package.json
  test/select/collections/Points/index.ts
  test/select/config.ts
  test/select/int.spec.ts
  test/select/payload-types.ts
Labels: v3, created-by: Payload team

#9091 fix: custom id field not shown depending on field and db types
  packages/next/src/utilities/initPage/handleAdminPage.ts
  packages/next/src/utilities/initPage/index.ts
Labels: v3, created-by: Payload team

#9106 fix: empty publish dropdown when localization is false
  packages/ui/src/elements/PublishButton/index.tsx
Labels: v3, created-by: Payload team

#9120 docs: fix queue docs examples, link to qs-esm instead of qs [skip ci]
  docs/jobs-queue/overview.mdx
  docs/queries/overview.mdx
  docs/queries/select.mdx
Labels: v3, created-by: Payload team

#9124 feat(docs): add example for customising the filename of an upload via hooks
  docs/upload/overview.mdx
Labels: v3, created-by: Payload team

#9117 fix(ui): error in filtered relationship field component while scrolling, if the select option label is a number
  packages/ui/src/fields/Relationship/index.tsx
Labels: v3, created-by: Payload team

#9126 feat(richtext-lexical)!: upgrade lexical from 0.18.0 to 0.20.0
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/index.ts
  pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  test/package.json
Labels: v3, created-by: Payload team

#9127 perf: upgrade pino-pretty. This reduces bundle size and total amount of dependencies from 94 => 85
  packages/payload/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#9116 fix(db-mongodb): destructuring error when trying to filter date fields by string query
  packages/db-mongodb/src/queries/buildSearchParams.ts
Labels: v3, created-by: Payload team

#9118 docs: improves component paths and import map
  docs/admin/components.mdx
  docs/admin/overview.mdx
  docs/admin/views.mdx
  docs/fields/array.mdx
  docs/fields/json.mdx
  docs/fields/overview.mdx
Labels: v3, created-by: Payload team

#9129 feat(richtext-lexical): backport relevant from lexical playground between 0.18.0 and 0.20.0
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableHoverActionsPlugin/index.tsx
  packages/richtext-lexical/src/features/format/bold/feature.client.tsx
  packages/richtext-lexical/src/features/format/inlineCode/feature.client.tsx
  packages/richtext-lexical/src/features/format/italic/feature.client.tsx
  packages/richtext-lexical/src/features/format/strikethrough/feature.client.tsx
  packages/richtext-lexical/src/features/format/subscript/feature.client.tsx
  packages/richtext-lexical/src/features/format/superscript/feature.client.tsx
  packages/richtext-lexical/src/features/format/underline/feature.client.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/LexicalMenu.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/index.tsx
Labels: v3, created-by: Payload team

#8718 feat(richtext-lexical): add `useAsTitle` to the popup links label
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/features/link/server/i18n.ts
  test/fields/collections/RichText/e2e.spec.ts
Labels: v3

#9102 feat(db-postgres): deep querying on json and rich text fields
  packages/db-postgres/src/index.ts
  packages/db-vercel-postgres/src/index.ts
  packages/drizzle/src/exports/postgres.ts
  packages/drizzle/src/postgres/createJSONQuery/convertPathToJSONTraversal.ts
  packages/drizzle/src/postgres/createJSONQuery/formatJSONPathSegment.ts
  packages/drizzle/src/postgres/createJSONQuery/index.ts
  packages/drizzle/src/queries/parseParams.ts
  packages/drizzle/src/types.ts
  test/fields/collections/JSON/index.tsx
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#9137 fix(ui): pass correct relationTo to locked documents creation
  packages/ui/src/utilities/handleFormStateLocking.ts
Labels: v3, created-by: Payload team

#9139 fix(next, ui): respect access of `user` for document locking
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Document/getIsLocked.ts
  packages/next/src/views/Document/index.tsx
  packages/ui/src/utilities/handleFormStateLocking.ts
Labels: v3, created-by: Payload team

#9141 fix(cpa): use proper branch tag
  packages/create-payload-app/src/lib/create-project.ts
  packages/create-payload-app/src/lib/download-template.ts
  packages/create-payload-app/src/lib/templates.ts
  packages/create-payload-app/src/main.ts
Labels: v3, created-by: Payload team

#9131 chore: adjust abort controller logic for server functions
  packages/next/src/views/CreateFirstUser/index.client.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/DrawerContent.tsx
  packages/richtext-slate/src/field/elements/link/Button/index.tsx
  packages/richtext-slate/src/field/elements/link/Element/index.tsx
  packages/richtext-slate/src/field/elements/upload/Element/UploadDrawer/index.tsx
  packages/ui/src/elements/BulkUpload/EditForm/index.tsx
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/elements/EditMany/index.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/providers/ServerFunctions/index.tsx
  packages/ui/src/utilities/abortAndIgnore.ts
  packages/ui/src/views/Edit/index.tsx
  test/access-control/e2e.spec.ts
Labels: v3, created-by: Payload team

#9142 chore: docs improvements
  docs/jobs-queue/jobs.mdx
  docs/jobs-queue/overview.mdx
  docs/jobs-queue/queues.mdx
  docs/jobs-queue/tasks.mdx
  docs/jobs-queue/workflows.mdx
  docs/queries/select.mdx
Labels: v3, created-by: Payload team

#9148 docs: next 15 requirement disclaimer
  docs/getting-started/installation.mdx
Labels: v3, created-by: Payload team

#9146 fix: incorrectly looking for schema paths when upload is not enabled
  packages/richtext-slate/src/field/elements/upload/Element/index.tsx
  packages/ui/src/elements/EditMany/index.tsx
  packages/ui/src/views/List/index.tsx
Labels: v3, created-by: Payload team

#9155 feat: adds option to mongoose to ensure indexes
  packages/db-mongodb/src/connect.ts
  packages/db-mongodb/src/index.ts
  test/generateDatabaseAdapter.ts
Labels: v3, created-by: Payload team

#9151 fix: allow specifying queue
  packages/payload/src/queues/config/jobsCollection.ts
  packages/payload/src/queues/config/types/workflowTypes.ts
  packages/payload/src/queues/localAPI.ts
  test/queues/int.spec.ts
Labels: v3, created-by: Payload team

#9147 fix(next): disable turbopack serverExternalPackages warnings
  packages/next/src/withPayload.js
Labels: v3, created-by: Payload team

#9158 fix(richtext-lexical): inline blocks drawer not rendering any fields due to incorrect schemapath suffix
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
Labels: v3, created-by: Payload team

#9149 chore: updates flaky `uploads` tests
  test/uploads/e2e.spec.ts
Labels: v3, created-by: Payload team

#9157 docs: updates custom components and field props
  docs/admin/collections.mdx
  docs/admin/components.mdx
  docs/admin/fields.mdx
  docs/admin/globals.mdx
  docs/admin/hooks.mdx
  docs/fields/join.mdx
  docs/fields/overview.mdx
  docs/fields/select.mdx
  docs/fields/ui.mdx
  docs/migration-guide/overview.mdx
  packages/payload/src/admin/types.ts
  test/_community/collections/Posts/MyClientField.tsx
  test/_community/collections/Posts/MyServerField.tsx
Labels: v3, created-by: Payload team

#9161 feat(templates): update config structure in website template to be more clear
  templates/website/pnpm-lock.yaml
  templates/website/src/collections/Categories.ts
  templates/website/src/collections/Users/index.ts
  templates/website/src/fields/defaultLexical.ts
  templates/website/src/payload.config.ts
  templates/website/src/plugins/index.ts
Labels: v3, created-by: Payload team

#9159 fix: expose server and client props to custom list slot components
  packages/next/src/views/List/index.tsx
  packages/next/src/views/List/renderListViewSlots.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/views/List/types.ts
Labels: v3, created-by: Payload team

#9145 feat(next): initializes nav group prefs on the server and consolidates records
  packages/next/src/elements/Nav/getNavPrefs.ts
  packages/next/src/elements/Nav/index.client.tsx
  packages/next/src/elements/Nav/index.tsx
  packages/next/src/layouts/Root/index.tsx
  packages/payload/src/admin/elements/Nav.ts
  packages/payload/src/admin/types.ts
  packages/ui/src/elements/Nav/NavToggler/index.tsx
  packages/ui/src/elements/NavGroup/index.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/providers/Preferences/index.tsx
  packages/ui/src/utilities/groupNavItems.ts
Labels: v3, created-by: Payload team

#9156 feat: customize log levels and downgrade common errors to info
  docs/configuration/overview.mdx
  packages/next/src/routes/rest/routeError.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/config/types.ts
  packages/payload/src/errors/types.ts
Labels: v3, created-by: Payload team

#9169 chore(templates): update lock file for website template
  templates/website/pnpm-lock.yaml
Labels: v3, created-by: Payload team

#9168 fix(next): safely check for `state` when creating first user
  packages/next/src/views/CreateFirstUser/index.client.tsx
Labels: v3, created-by: Payload team

#8591 fix: fallbackLocale not respecting default settings, locale specific fallbacks and not respecting 'none' or false
  docs/configuration/localization.mdx
  examples/multi-tenant/src/app/components/Login/client.page.tsx
  examples/multi-tenant/src/collections/Pages/hooks/ensureUniqueSlug.ts
  examples/multi-tenant/src/collections/Pages/index.ts
  examples/multi-tenant/src/collections/Tenants/access/read.ts
  examples/multi-tenant/src/collections/Users/access/create.ts
  examples/multi-tenant/src/collections/Users/access/isAccessingSelf.ts
  examples/multi-tenant/src/collections/Users/access/updateAndDelete.ts
  examples/multi-tenant/src/collections/Users/hooks/ensureUniqueUsername.ts
  examples/multi-tenant/src/fields/TenantField/hooks/autofillTenant.ts
  examples/multi-tenant/src/fields/TenantField/index.ts
  examples/multi-tenant/src/utilities/getTenantAccessIDs.ts
  packages/next/src/utilities/addLocalesToRequest.ts
  packages/next/src/utilities/createPayloadRequest.ts
  packages/next/src/utilities/getRequestLocales.ts
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initReq.ts
  packages/next/src/views/Document/getDocumentData.ts
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/LivePreview/index.tsx
  packages/payload/src/admin/forms/Form.ts
  packages/payload/src/collections/operations/local/create.ts
  packages/payload/src/collections/operations/local/delete.ts
  packages/payload/src/collections/operations/local/duplicate.ts
  packages/payload/src/collections/operations/local/find.ts
  packages/payload/src/collections/operations/local/findByID.ts
  packages/payload/src/collections/operations/local/findVersionByID.ts
  packages/payload/src/collections/operations/local/findVersions.ts
  packages/payload/src/collections/operations/local/restoreVersion.ts
  packages/payload/src/collections/operations/local/update.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/config/types.ts
  packages/payload/src/globals/operations/local/findOne.ts
  packages/payload/src/globals/operations/local/findVersionByID.ts
  packages/payload/src/globals/operations/local/findVersions.ts
  packages/payload/src/globals/operations/local/restoreVersion.ts
  packages/payload/src/globals/operations/local/update.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/createLocalReq.ts
  packages/payload/src/utilities/sanitizeFallbackLocale.ts
  packages/ui/src/providers/ServerFunctions/index.tsx
  test/localization/int.spec.ts
Labels: v3, created-by: Payload team

#9177 feat: adds ability to define base filter for list view
  docs/admin/collections.mdx
  packages/next/src/views/List/index.tsx
  packages/payload/src/collections/config/client.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/index.ts
  test/admin/collections/BaseListFilter.ts
  test/admin/config.ts
  test/admin/e2e/2/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/seed.ts
Labels: v3, created-by: Payload team

#9123 fix: add inline <head><style> to ensure the order of declared css layers as much as possible
  packages/next/src/layouts/Root/index.tsx
Labels: v3, created-by: Payload team

#9178 fix(db-postgres, db-vercel-postgres): relationship migration v2-v3 dirname
  packages/db-postgres/src/index.ts
  packages/db-vercel-postgres/src/index.ts
  packages/drizzle/src/postgres/createMigration.ts
  packages/payload/src/database/migrations/getPredefinedMigration.ts
  packages/payload/src/database/types.ts
Labels: v3, created-by: Payload team

#9186 chore: fix community test
  test/_community/int.spec.ts
Labels: v3, created-by: Payload team

#9187 chore: fix community e2e test
  test/_community/e2e.spec.ts
Labels: v3, created-by: Payload team

#9192 docs: note about passing req to local operations
  docs/local-api/overview.mdx
Labels: v3, created-by: Payload team

#9194 docs: add `within` and `intersects` operators documentation
  docs/fields/point.mdx
  docs/queries/overview.mdx
Labels: v3, created-by: Payload team

#9188 chore: improve custom server cell types
  packages/payload/src/admin/elements/Cell.ts
  packages/payload/src/admin/types.ts
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
Labels: v3, created-by: Payload team

#9184 fix(ui): fixes layout shift when form is submitted
  packages/richtext-lexical/src/field/index.scss
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/scss/vars.scss
Labels: v3, created-by: Payload team

#9182 feat(db-mongodb): migrate relationships v2-v3
  packages/db-mongodb/package.json
  packages/db-mongodb/src/exports/migration-utils.ts
  packages/db-mongodb/src/predefinedMigrations/migrateRelationshipsV2_V3.ts
  packages/db-mongodb/src/predefinedMigrations/migrateVersionsV1_V2.ts
  packages/db-mongodb/src/predefinedMigrations/relationships-v2-v3.ts
  packages/db-mongodb/src/predefinedMigrations/versions-v1-v2.js
  packages/db-mongodb/src/predefinedMigrations/versions-v1-v2.ts
  pnpm-lock.yaml
  test/database/config.ts
  test/database/int.spec.ts
  test/package.json
Labels: created-by: Payload team

#9206 chore: misc cleanup
  packages/db-mongodb/package.json
  packages/db-mongodb/src/queries/mock.js
  packages/db-mongodb/src/utilities/buildProjectionFromSelect.ts
  packages/db-postgres/src/predefinedMigrations/v2-v3/traverseFields.ts
  packages/db-sqlite/src/connect.ts
  packages/db-sqlite/src/schema/build.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/traverseFields.ts
  packages/plugin-form-builder/src/collections/FormSubmissions/hooks/sendEmail.ts
  packages/plugin-search/src/Search/hooks/syncWithSearch.ts
  packages/ui/src/utilities/buildTableState.ts
Labels: v3, created-by: Payload team

#9207 feat!: re-order DefaultCellComponentProps generics
  packages/payload/src/admin/elements/Cell.ts
  packages/richtext-lexical/src/types.ts
  packages/ui/src/elements/Table/DefaultCell/fields/Array/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Blocks/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Checkbox/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Code/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Date/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/File/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/JSON/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Select/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Textarea/index.tsx
Labels: v3, created-by: Payload team

#9209 perf: removes i18n.supportedLanguages from client config
  packages/payload/src/config/client.ts
Labels: v3, created-by: Payload team

#9208 chore: clean up types for HiddenField and WatchCondition
  packages/next/src/views/ResetPassword/ResetPasswordForm/index.tsx
  packages/payload/src/admin/fields/Hidden.ts
  packages/ui/src/fields/Hidden/index.tsx
  packages/ui/src/fields/index.tsx
  packages/ui/src/forms/RenderFields/RenderField.tsx
  packages/ui/src/forms/withCondition/WatchCondition.tsx
  packages/ui/src/forms/withCondition/index.tsx
Labels: v3, created-by: Payload team

#9195 perf: removes undefined props from rsc requests
  packages/payload/src/collections/config/client.ts
  packages/payload/src/config/client.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/globals/config/client.ts
  packages/payload/src/utilities/deepCopyObject.ts
  packages/payload/src/utilities/removeUndefined.ts
  packages/ui/src/elements/RenderServerComponent/index.tsx
  packages/ui/src/utilities/removeUndefined.ts
Labels: v3, created-by: Payload team

#9198 fix(ui): jumping hasmany uploads when form is submitting or in readonly mode
  packages/ui/src/fields/Upload/HasMany/index.scss
  packages/ui/src/fields/Upload/HasMany/index.tsx
  packages/ui/src/fields/Upload/Input.tsx
Labels: v3, created-by: Payload team

#9218 feat(richtext-lexical): add tooltips to toolbar dropdown items
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/DropDown.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.scss
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Button/types.ts
Labels: v3, created-by: Payload team

#9217 chore: export ListHeaderProps
  packages/ui/src/exports/client/index.ts
  packages/ui/src/views/List/ListHeader/index.tsx
Labels: v3, created-by: Payload team

#9211 feat(richtext-lexical, ui): add icon if link opens in new tab
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/index.scss
  packages/ui/src/exports/client/index.ts
  packages/ui/src/graphics/ExternalLink/index.scss
  packages/ui/src/graphics/ExternalLink/index.tsx
Labels: v3, created-by: Payload team

#9222 docs: fixes incorrect useField example
  docs/admin/hooks.mdx
Labels: v3, created-by: Payload team

#9224 docs: removes root endpoints from migration guide
  docs/configuration/overview.mdx
  docs/migration-guide/overview.mdx
Labels: v3, created-by: Payload team

#9115 feat(db-mongodb)!: update mongoose to 8.8.1
  packages/db-mongodb/package.json
  packages/db-mongodb/src/connect.ts
  packages/db-mongodb/src/count.ts
  packages/db-mongodb/src/countGlobalVersions.ts
  packages/db-mongodb/src/countVersions.ts
  packages/db-mongodb/src/createVersion.ts
  packages/db-mongodb/src/exports/migration-utils.ts
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/init.ts
  packages/db-mongodb/src/models/buildCollectionSchema.ts
  packages/db-mongodb/src/models/buildGlobalModel.ts
  packages/db-mongodb/src/models/buildSchema.ts
  packages/db-mongodb/src/predefinedMigrations/migrateRelationshipsV2_V3.ts
  packages/db-mongodb/src/predefinedMigrations/migrateVersionsV1_V2.ts
  packages/db-mongodb/src/predefinedMigrations/relationships-v2-v3.ts
  packages/db-mongodb/src/predefinedMigrations/versions-v1-v2.js
  packages/db-mongodb/src/predefinedMigrations/versions-v1-v2.ts
  packages/db-mongodb/src/queries/buildSearchParams.ts
  packages/db-mongodb/src/queries/parseParams.ts
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
  packages/db-mongodb/src/queryDrafts.ts
  packages/db-mongodb/src/utilities/sanitizeRelationshipIDs.spec.ts
  packages/db-mongodb/src/utilities/sanitizeRelationshipIDs.ts
  packages/payload/src/utilities/deepMerge.ts
  packages/payload/src/utilities/traverseFields.ts
  pnpm-lock.yaml
  test/collections-rest/int.spec.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/helpers/seed.ts
  test/package.json
  test/relationships/config.ts
  test/relationships/int.spec.ts
  test/relationships/payload-types.ts
Labels: v3, created-by: Payload team

#9227 chore: adds `email-nodemailer` to area-affected dropdown in issue template
  .github/ISSUE_TEMPLATE/1.bug_report_v3.yml
Labels: v3, created-by: Payload team

#9215 chore(examples): migrates `email` example to 3.0 [skip-lint]
  .github/workflows/main.yml
  examples/email/.env.example
  examples/email/.eslintrc.cjs
  examples/email/.swcrc
  examples/email/README.md
  examples/email/next-env.d.ts
  examples/email/next.config.mjs
  examples/email/nodemon.json
  examples/email/package.json
  examples/email/pnpm-lock.yaml
  examples/email/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  examples/email/src/app/(payload)/admin/[[...segments]]/page.tsx
  examples/email/src/app/(payload)/admin/importMap.js
  examples/email/src/app/(payload)/api/[...slug]/route.ts
  examples/email/src/app/(payload)/api/graphql-playground/route.ts
  examples/email/src/app/(payload)/api/graphql/route.ts
  examples/email/src/app/(payload)/custom.scss
  examples/email/src/app/(payload)/layout.tsx
  examples/email/src/collections/Newsletter.ts
  examples/email/src/collections/Users.ts
  examples/email/src/email/generateEmailHTML.ts
  examples/email/src/email/generateForgotPasswordEmail.ts
  examples/email/src/email/generateVerificationEmail.ts
  examples/email/src/email/template.ejs
  examples/email/src/email/template.html
  examples/email/src/email/transport.ts
  examples/email/src/emptyModule.js
  examples/email/src/payload-types.ts
  examples/email/src/payload.config.ts
  examples/email/src/server.ts
  examples/email/tsconfig.json
  examples/email/yarn.lock
Labels: v3, created-by: Payload team

#9185 fix: duplicate list preferences stored
  packages/ui/src/utilities/buildTableState.ts
Labels: v3, created-by: Payload team

#8311 fix!: improve collection / global slugs type-safety in various places
  docs/migration-guide/overview.mdx
  docs/upload/storage-adapters.mdx
  packages/create-payload-app/src/lib/replacements.ts
  packages/payload-cloud/src/types.ts
  packages/payload/src/auth/types.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/database/types.ts
  packages/payload/src/globals/config/types.ts
  packages/payload/src/index.ts
  packages/plugin-cloud-storage/src/types.ts
  packages/plugin-nested-docs/src/types.ts
  packages/plugin-stripe/src/types.ts
  packages/storage-azure/README.md
  packages/storage-azure/src/index.ts
  packages/storage-gcs/README.md
  packages/storage-gcs/src/index.ts
  packages/storage-s3/README.md
  packages/storage-s3/src/index.ts
  packages/storage-uploadthing/README.md
  packages/storage-uploadthing/src/index.ts
  packages/storage-vercel-blob/README.md
  packages/storage-vercel-blob/src/index.ts
  packages/ui/src/elements/ListDrawer/types.ts
  templates/vercel-postgres/src/payload.config.ts
  templates/with-vercel-mongodb/src/payload.config.ts
  templates/with-vercel-postgres/src/payload.config.ts
Labels: v3

#9221 feat!: bumps `date-fns` to `4.1.0`
  docs/fields/date.mdx
  packages/translations/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#9231 chore: removes `examples` dir from jobs workflow
  .github/workflows/main.yml
Labels: v3, created-by: Payload team

#9235 fix(templates): vercel website migrations
  templates/with-vercel-postgres/pnpm-lock.yaml
  templates/with-vercel-postgres/src/payload.config.ts
  templates/with-vercel-website/pnpm-lock.yaml
  templates/with-vercel-website/src/migrations/20241115_213226_initial.json
  templates/with-vercel-website/src/migrations/20241115_213226_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
  templates/with-vercel-website/src/migrations/initial.json
  templates/with-vercel-website/src/migrations/initial.ts
  templates/with-vercel-website/src/payload-types.ts
Labels: v3, created-by: Payload team

#9237 fix(ui): lexical was incorrectly set to readonly in blocks
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  test/access-control/collections/RichText/index.ts
  test/access-control/config.ts
  test/access-control/e2e.spec.ts
  test/access-control/payload-types.ts
Labels: v3, created-by: Payload team

#9238 feat(templates): programmatic migration gen
  .github/workflows/main.yml
  scripts/build-template-with-local-pkgs.ts
  scripts/generate-template-variations.ts
  templates/website/pnpm-lock.yaml
  templates/with-postgres/src/migrations/20241116_000912_initial.json
  templates/with-postgres/src/migrations/20241116_000912_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-postgres/src/migrations/initial.json
  templates/with-postgres/src/migrations/initial.ts
  templates/with-postgres/src/payload-types.ts
  templates/with-vercel-postgres/pnpm-lock.yaml
  templates/with-vercel-postgres/src/migrations/20241116_000907_initial.json
  templates/with-vercel-postgres/src/migrations/20241116_000907_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/initial.json
  templates/with-vercel-postgres/src/migrations/initial.ts
  templates/with-vercel-postgres/src/payload-types.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/pnpm-lock.yaml
  templates/with-vercel-website/src/collections/Categories.ts
  templates/with-vercel-website/src/collections/Users/index.ts
  templates/with-vercel-website/src/fields/defaultLexical.ts
  templates/with-vercel-website/src/migrations/20241116_000910_initial.json
  templates/with-vercel-website/src/migrations/20241116_000910_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
  templates/with-vercel-website/src/payload.config.ts
  templates/with-vercel-website/src/plugins/index.ts
  test/storage-vercel-blob/payload-types.ts
Labels: v3, created-by: Payload team

#9245 fix: corrects cases of false positive identification of custom id fields
  packages/payload/src/index.ts
  test/database/config.ts
  test/database/int.spec.ts
Labels: v3, created-by: Payload team

#9241 ci: bump templates post release
  .github/workflows/post-release.yml
Labels: v3, created-by: Payload team

#9247 fix(next): custom default root views
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/payload/src/bin/generateImportMap/parsePayloadComponent.ts
Labels: v3, created-by: Payload team

#9248 fix!: proper casing for default root views
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/payload/src/config/types.ts
Labels: v3, created-by: Payload team

#9249 feat: deprecates getPayloadHMR in favor of simpler getPayload
  docs/getting-started/concepts.mdx
  docs/live-preview/server.mdx
  docs/local-api/outside-nextjs.mdx
  docs/local-api/overview.mdx
  examples/auth/payload/README.md
  examples/auth/payload/src/app/(app)/account/page.tsx
  examples/auth/payload/src/app/(app)/create-account/page.tsx
  examples/auth/payload/src/app/(app)/login/page.tsx
  examples/auth/payload/src/app/(app)/logout/page.tsx
  examples/auth/payload/src/app/(app)/page.tsx
  examples/auth/payload/src/app/(app)/recover-password/page.tsx
  examples/auth/payload/src/app/(app)/reset-password/page.tsx
  examples/live-preview/payload/README.md
  examples/live-preview/payload/src/app/(app)/[slug]/page.tsx
  examples/live-preview/payload/src/app/(app)/_components/Header/index.tsx
  examples/multi-tenant/src/app/(app)/[tenant]/[...slug]/page.tsx
  packages/next/package.json
  packages/next/src/exports/utilities.ts
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/routes/rest/routeError.ts
  packages/next/src/utilities/createPayloadRequest.ts
  packages/next/src/utilities/getPayloadHMR.ts
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initReq.ts
  packages/payload/package.json
  packages/payload/src/index.ts
  pnpm-lock.yaml
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/next/preview/route.ts
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/page.tsx
  templates/website/src/app/(frontend)/posts/page/[pageNumber]/page.tsx
  templates/website/src/app/(frontend)/search/page.tsx
  templates/website/src/blocks/ArchiveBlock/Component.tsx
  templates/website/src/utilities/getDocument.ts
  templates/website/src/utilities/getGlobals.ts
  templates/website/src/utilities/getRedirects.ts
  templates/with-vercel-website/src/app/(frontend)/[slug]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/next/preview/route.ts
  templates/with-vercel-website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/posts/page.tsx
  templates/with-vercel-website/src/app/(frontend)/posts/page/[pageNumber]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/search/page.tsx
  templates/with-vercel-website/src/blocks/ArchiveBlock/Component.tsx
  templates/with-vercel-website/src/utilities/getDocument.ts
  templates/with-vercel-website/src/utilities/getGlobals.ts
  templates/with-vercel-website/src/utilities/getRedirects.ts
  test/app/(app)/test/page.tsx
  test/fields/int.spec.ts
  test/helpers/initPayloadInt.ts
  test/live-preview/app/live-preview/_api/getDoc.ts
  test/live-preview/app/live-preview/_api/getDocs.ts
  test/live-preview/app/live-preview/_api/getFooter.ts
  test/live-preview/app/live-preview/_api/getHeader.ts
  test/live-preview/prod/app/live-preview/_api/getDoc.ts
  test/live-preview/prod/app/live-preview/_api/getDocs.ts
  test/live-preview/prod/app/live-preview/_api/getFooter.ts
  test/live-preview/prod/app/live-preview/_api/getHeader.ts
Labels: v3, created-by: Payload team

#9234 feat(richtext-lexical): allow replacing entire blocks with custom components
  docs/fields/blocks.mdx
  packages/payload/src/admin/forms/Form.ts
  packages/payload/src/bin/generateImportMap/iterateFields.ts
  packages/payload/src/fields/config/types.ts
  packages/richtext-lexical/src/exports/client/index.ts
  packages/richtext-lexical/src/features/blocks/client/component/BlockContent.tsx
  packages/richtext-lexical/src/features/blocks/client/component/FormSavePlugin.tsx
  packages/richtext-lexical/src/features/blocks/client/component/components/BlockCollapsible.tsx
  packages/richtext-lexical/src/features/blocks/client/component/components/BlockEditButton.tsx
  packages/richtext-lexical/src/features/blocks/client/component/components/BlockRemoveButton.tsx
  packages/richtext-lexical/src/features/blocks/client/component/index.scss
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/components/InlineBlockContainer.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/components/InlineBlockEditButton.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/components/InlineBlockLabel.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/components/InlineBlockRemoveButton.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/blocks/client/index.tsx
  packages/richtext-lexical/src/features/blocks/client/plugin/commands.ts
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
  packages/richtext-lexical/src/features/blocks/server/index.ts
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.scss
  packages/richtext-lexical/src/utilities/fieldsDrawer/useLexicalDrawer.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Submit/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/utilities/buildTableState.ts
  test/fields/collections/Lexical/blockComponents/BlockComponent.tsx
  test/fields/collections/Lexical/blockComponents/LabelComponent.tsx
  test/fields/collections/Lexical/index.ts
  test/fields/collections/Lexical/inlineBlockComponents/BlockComponent.tsx
  test/fields/collections/Lexical/inlineBlockComponents/LabelComponent.tsx
Labels: v3, created-by: Payload team

#9251 docs: updates migration guide
  docs/migration-guide/overview.mdx
Labels: v3, created-by: Payload team

#9255 perf(richtext-lexical)!: significantly reduce lexical rerendering and amount of network requests from blocks
  packages/payload/src/admin/forms/Field.ts
  packages/richtext-lexical/src/features/blocks/client/component/BlockContent.tsx
  packages/richtext-lexical/src/features/blocks/client/component/FormSavePlugin.tsx
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/blocks/client/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/features/typesClient.ts
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-lexical/src/field/rscEntry.tsx
  packages/richtext-lexical/src/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/lexical/config/client/sanitize.ts
  packages/richtext-lexical/src/types.ts
  packages/richtext-lexical/src/utilities/buildInitialState.ts
  packages/richtext-lexical/src/utilities/fieldsDrawer/DrawerContent.tsx
  packages/ui/package.json
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/forms/fieldSchemasToFormState/types.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/helpers.ts
Labels: v3, created-by: Payload team

#9253 feat: support relationship writes using objects instead of IDs
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  test/relationships/config.ts
  test/relationships/int.spec.ts
  test/relationships/payload-types.ts
Labels: v3, created-by: Payload team

#9256 fix(ui): avoid calling `getTableState` from join field on create
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/fields/Join/index.tsx
  test/joins/e2e.spec.ts
Labels: v3, created-by: Payload team

#9279 fix: getPayload node exits on webpack-hmr websocket failure
  packages/payload/src/index.ts
Labels: v3, created-by: Payload team

#9292 fix(db-mongodb): potential errors in `sanitizeRelationshipIDs` with `ref` being a non object
  packages/db-mongodb/src/utilities/sanitizeRelationshipIDs.ts
Labels: v3, created-by: Payload team

#9286 perf!: removes unnecessary field styles from initial page response
  packages/payload/src/fields/config/client.ts
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-slate/src/field/RichText.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/fields/Checkbox/index.tsx
  packages/ui/src/fields/Code/index.tsx
  packages/ui/src/fields/Collapsible/index.tsx
  packages/ui/src/fields/DateTime/index.tsx
  packages/ui/src/fields/Email/index.tsx
  packages/ui/src/fields/Group/index.tsx
  packages/ui/src/fields/JSON/index.tsx
  packages/ui/src/fields/Join/index.tsx
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/Password/index.tsx
  packages/ui/src/fields/Point/index.tsx
  packages/ui/src/fields/RadioGroup/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Select/Input.tsx
  packages/ui/src/fields/Select/index.tsx
  packages/ui/src/fields/Text/Input.tsx
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/fields/Text/types.ts
  packages/ui/src/fields/Textarea/Input.tsx
  packages/ui/src/fields/Textarea/index.tsx
  packages/ui/src/fields/Textarea/types.ts
  packages/ui/src/fields/Upload/Input.tsx
  packages/ui/src/fields/Upload/index.tsx
  packages/ui/src/fields/mergeFieldStyles.ts
Labels: v3, created-by: Payload team

#9296 fix: sanitize sub block field permissions correctly
  packages/payload/src/auth/types.ts
  packages/payload/src/utilities/sanitizePermissions.spec.ts
  packages/payload/src/utilities/sanitizePermissions.ts
Labels: v3, created-by: Payload team

#9297 fix(next): initialize payload with importMap
  packages/next/src/layouts/Root/index.tsx
Labels: v3, created-by: Payload team

#9301 fix: nav jumping around if no nav preferences are set
  packages/next/src/layouts/Root/index.tsx
Labels: v3, created-by: Payload team

#9302 fix(next): passes doc through edit view handler
  docs/admin/views.mdx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/LivePreview/index.tsx
  packages/payload/src/admin/views/types.ts
Labels: v3, created-by: Payload team

#9281 fix: queues types with `strict: true`
  packages/payload/src/queues/config/generateJobsJSONSchemas.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  test/queues/payload-types.ts
Labels: v3, created-by: Payload team

#9306 fix(templates): seed from url
  templates/website/src/endpoints/seed/index.ts
  templates/with-vercel-website/src/endpoints/seed/index.ts
Labels: v3, created-by: Payload team

#9300 chore(examples): migrates multi-tenant example to latest beta
  examples/multi-tenant/package.json
  examples/multi-tenant/pnpm-lock.yaml
  examples/multi-tenant/src/app/(app)/[tenant]/[...slug]/page.tsx
  examples/multi-tenant/src/app/(app)/[tenant]/login/page.tsx
  examples/multi-tenant/src/app/(app)/[tenant]/page.tsx
  examples/multi-tenant/src/app/(app)/layout.tsx
  examples/multi-tenant/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  examples/multi-tenant/src/app/(payload)/admin/[[...segments]]/page.tsx
  examples/multi-tenant/src/app/(payload)/admin/importMap.js
  examples/multi-tenant/src/app/(payload)/layout.tsx
  examples/multi-tenant/src/collections/Pages/hooks/ensureUniqueSlug.ts
  examples/multi-tenant/src/collections/Users/endpoints/externalUsersLogin.ts
  examples/multi-tenant/src/collections/Users/hooks/ensureUniqueUsername.ts
  examples/multi-tenant/src/fields/TenantField/components/Field.client.tsx
  examples/multi-tenant/src/fields/TenantField/components/Field.tsx
  examples/multi-tenant/src/payload-types.ts
  examples/multi-tenant/src/payload.config.ts
Labels: v3, created-by: Payload team

#9308 chore: updates multi tenant example to use baseListFilter
  examples/multi-tenant/src/collections/Pages/access/baseListFilter.ts
  examples/multi-tenant/src/collections/Pages/access/readAccess.ts
  examples/multi-tenant/src/collections/Pages/index.ts
Labels: v3, created-by: Payload team

#9305 docs: migration guide more info
  docs/admin/customizing-css.mdx
  docs/admin/overview.mdx
  docs/configuration/i18n.mdx
  docs/fields/rich-text.mdx
  docs/getting-started/installation.mdx
  docs/getting-started/what-is-payload.mdx
  docs/graphql/graphql-schema.mdx
  docs/jobs-queue/overview.mdx
  docs/jobs-queue/tasks.mdx
  docs/lexical/building-custom-features.mdx
  docs/lexical/overview.mdx
  docs/migration-guide/overview.mdx
  docs/plugins/form-builder.mdx
  docs/plugins/nested-docs.mdx
  docs/plugins/redirects.mdx
  docs/plugins/search.mdx
  docs/plugins/sentry.mdx
  docs/plugins/seo.mdx
  docs/plugins/stripe.mdx
  docs/production/deployment.mdx
  docs/queries/select.mdx
  docs/rich-text/overview.mdx
  docs/upload/storage-adapters.mdx
Labels: v3, created-by: Payload team

#9318 perf(richtext-lexical): do not send default lexical editor config to client
  packages/richtext-lexical/src/field/index.tsx
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/config/types.ts
  packages/richtext-lexical/src/types.ts
Labels: v3, created-by: Payload team

#9319 chore: remove unused transaction in website seed
  templates/website/src/endpoints/seed/index.ts
  templates/website/src/endpoints/seedHandler.ts
  templates/with-vercel-website/src/endpoints/seed/index.ts
  templates/with-vercel-website/src/endpoints/seedHandler.ts
Labels: v3, created-by: Payload team

#9323 chore: make uploads e2e test suite not flaky
  test/uploads/e2e.spec.ts
Labels: v3, created-by: Payload team

#9321 perf: significantly reduce HTML we send to the client. Up to 4x smaller
  packages/next/src/elements/DocumentHeader/Tabs/Tab/index.tsx
  packages/next/src/elements/DocumentHeader/Tabs/index.tsx
  packages/next/src/elements/Logo/index.tsx
  packages/next/src/elements/Nav/index.tsx
  packages/next/src/layouts/Root/NestProviders.tsx
  packages/next/src/routes/rest/og/image.tsx
  packages/next/src/templates/Default/index.tsx
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Dashboard/Default/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/Document/renderDocumentSlots.tsx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/List/renderListViewSlots.tsx
  packages/next/src/views/Login/index.tsx
  packages/next/src/views/Root/index.tsx
  packages/payload/src/fields/config/sanitize.ts
  packages/richtext-lexical/src/field/rscEntry.tsx
  packages/richtext-slate/src/field/rscEntry.tsx
  packages/ui/src/elements/RenderServerComponent/index.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/elements/WithServerSideProps/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/utilities/renderTable.tsx
  test/admin/components/AfterDashboardClient/index.tsx
Labels: v3, created-by: Payload team

#9325 fix: could not save selection from upload has many drawer
  packages/ui/src/views/List/index.tsx
Labels: v3, created-by: Payload team

#9324 fix(ui): addFieldRow set modified
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/forms/Form/index.tsx
  test/_community/payload-types.ts
  test/fields/collections/Array/AddRowButton.tsx
  test/fields/collections/Array/CustomField.tsx
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Array/index.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#9334 fix(templates): website logo not showing
  templates/website/src/Footer/Component.tsx
  templates/website/src/components/Logo/Logo.tsx
Labels: v3, created-by: Payload team

#9170 chore(examples): migrates `custom-component` example to latest beta [skip-lint]
  examples/custom-components/README.md
  examples/custom-components/next-env.d.ts
  examples/custom-components/package.json
  examples/custom-components/pnpm-lock.yaml
  examples/custom-components/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  examples/custom-components/src/app/(payload)/admin/[[...segments]]/page.tsx
  examples/custom-components/src/app/(payload)/admin/importMap.js
  examples/custom-components/src/app/(payload)/layout.tsx
  examples/custom-components/src/collections/Fields/array/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/array/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/array/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/array/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/blocks/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/blocks/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/blocks/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/blocks/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/checkbox/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/checkbox/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/checkbox/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/checkbox/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/date/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/date/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/date/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/date/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/email/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/email/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/email/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/email/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/number/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/number/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/number/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/number/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/point/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/point/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/point/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/point/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/radio/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/radio/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/radio/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/radio/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/relationship/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/relationship/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/relationship/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/relationship/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/select/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/select/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/select/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/select/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/text/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/text/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/text/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/text/components/server/Label.tsx
  examples/custom-components/src/collections/Fields/textarea/components/client/Field.tsx
  examples/custom-components/src/collections/Fields/textarea/components/client/Label.tsx
  examples/custom-components/src/collections/Fields/textarea/components/server/Field.tsx
  examples/custom-components/src/collections/Fields/textarea/components/server/Label.tsx
  examples/custom-components/src/payload-types.ts
Labels: v3, created-by: Payload team

#9114 fix: ensure api code preview indentation is correct
  packages/next/src/views/API/RenderJSON/index.scss
  packages/next/src/views/API/RenderJSON/index.tsx
  packages/next/src/views/API/index.scss
Labels: v3, created-by: Payload team

#9348 fix(ui): show required indicator for select fields
  packages/ui/src/fields/Select/Input.tsx
  packages/ui/src/fields/Select/index.tsx
Labels: area: ui

#9340 fix(ui): client side doc data not updating after save
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/DocumentInfo/types.ts
  packages/ui/src/views/Edit/index.tsx
Labels: created-by: Payload team

#9336 chore(templates): adds `getURL` util to website & with-vercel-website templates
  templates/website/src/app/(frontend)/layout.tsx
  templates/website/src/blocks/Form/Component.tsx
  templates/website/src/collections/Pages/index.ts
  templates/website/src/collections/Posts/index.ts
  templates/website/src/components/AdminBar/index.tsx
  templates/website/src/components/LivePreviewListener/index.tsx
  templates/website/src/components/Media/ImageMedia/index.tsx
  templates/website/src/components/Media/VideoMedia/index.tsx
  templates/website/src/environment.d.ts
  templates/website/src/payload.config.ts
  templates/website/src/plugins/index.ts
  templates/website/src/utilities/generateMeta.ts
  templates/website/src/utilities/getMeUser.ts
  templates/website/src/utilities/getURL.ts
  templates/website/src/utilities/mergeOpenGraph.ts
  templates/with-vercel-website/src/app/(frontend)/layout.tsx
  templates/with-vercel-website/src/blocks/Form/Component.tsx
  templates/with-vercel-website/src/collections/Pages/index.ts
  templates/with-vercel-website/src/collections/Posts/index.ts
  templates/with-vercel-website/src/components/AdminBar/index.tsx
  templates/with-vercel-website/src/components/LivePreviewListener/index.tsx
  templates/with-vercel-website/src/components/Media/ImageMedia/index.tsx
  templates/with-vercel-website/src/components/Media/VideoMedia/index.tsx
  templates/with-vercel-website/src/environment.d.ts
  templates/with-vercel-website/src/payload.config.ts
  templates/with-vercel-website/src/plugins/index.ts
  templates/with-vercel-website/src/utilities/generateMeta.ts
  templates/with-vercel-website/src/utilities/getMeUser.ts
  templates/with-vercel-website/src/utilities/getURL.ts
  templates/with-vercel-website/src/utilities/mergeOpenGraph.ts
Labels: created-by: Payload team

#9360 fix: allow self referencing relationships when adding new collections to config
  packages/payload/src/collections/config/sanitize.ts
Labels: created-by: Payload team

#9364 fix(next): autosave document rendering
  packages/next/src/views/Document/index.tsx
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/providers/ServerFunctions/index.tsx
  test/fields-relationship/e2e.spec.ts
  test/helpers/e2e/trackNetworkRequests.ts
  test/versions/e2e.spec.ts
  tsconfig.json
Labels: created-by: Payload team

#9379 fix: prioritize server rendered Actions in ActionsProvider
  packages/ui/src/providers/Actions/index.tsx
Labels: created-by: Payload team

#9381 fix(next): properly sets doc id types when using postgres
  packages/next/src/utilities/initPage/handleAdminPage.ts
  test/joins/payload-types.ts
Labels: created-by: Payload team

#9382 fix(richtext-lexical): use copy of @lexical/markdown that does not install @lexical/code
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/blockquote/markdownTransformer.ts
  packages/richtext-lexical/src/features/blocks/client/markdownTransformer.ts
  packages/richtext-lexical/src/features/blocks/server/markdownTransformer.ts
  packages/richtext-lexical/src/features/experimental_table/markdownTransformer.ts
  packages/richtext-lexical/src/features/format/bold/markdownTransformers.ts
  packages/richtext-lexical/src/features/format/inlineCode/markdownTransformers.ts
  packages/richtext-lexical/src/features/format/italic/markdownTransformers.ts
  packages/richtext-lexical/src/features/format/strikethrough/markdownTransformers.ts
  packages/richtext-lexical/src/features/heading/markdownTransformer.ts
  packages/richtext-lexical/src/features/horizontalRule/client/markdownTransformer.ts
  packages/richtext-lexical/src/features/horizontalRule/server/markdownTransformer.ts
  packages/richtext-lexical/src/features/link/markdownTransformer.ts
  packages/richtext-lexical/src/features/lists/checklist/markdownTransformers.ts
  packages/richtext-lexical/src/features/lists/orderedList/markdownTransformer.ts
  packages/richtext-lexical/src/features/lists/shared/markdown.ts
  packages/richtext-lexical/src/features/lists/unorderedList/markdownTransformer.ts
  packages/richtext-lexical/src/features/typesClient.ts
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical-proxy/@lexical-markdown.ts
  packages/richtext-lexical/src/lexical/plugins/MarkdownShortcut/index.tsx
  packages/richtext-lexical/src/lexical/utils/markdown/createBlockNode.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/LICENSE
  packages/richtext-lexical/src/packages/@lexical/markdown/MarkdownExport.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/MarkdownImport.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/MarkdownShortcuts.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/MarkdownTransformers.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/index.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/utils.ts
  packages/richtext-lexical/src/utilities/jsx/lexicalMarkdownCopy.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#9366 fix(ui): invalid permissions passed to group and named tab sub-fields
  packages/graphql/src/resolvers/collections/docAccess.ts
  packages/graphql/src/resolvers/globals/docAccess.ts
  packages/next/src/views/Document/getDocumentPermissions.tsx
  packages/payload/src/auth/types.ts
  packages/payload/src/collections/operations/docAccess.ts
  packages/payload/src/globals/operations/docAccess.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/sanitizePermissions.spec.ts
  packages/payload/src/utilities/sanitizePermissions.ts
  packages/ui/src/fields/Blocks/BlockRow.tsx
  packages/ui/src/forms/RenderFields/index.tsx
  packages/ui/src/forms/RenderFields/types.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/forms/fieldSchemasToFormState/types.ts
  test/access-control/collections/Regression-1/index.ts
  test/access-control/collections/Regression-2/index.ts
  test/access-control/config.ts
  test/access-control/e2e.spec.ts
  test/access-control/payload-types.ts
  test/fields/collections/LexicalLocalized/textToLexicalJSON.ts
Labels: created-by: Payload team

#9392 fix: error when opening admin panel without any permissions
  packages/payload/src/collections/operations/docAccess.ts
  packages/payload/src/globals/operations/docAccess.ts
  packages/payload/src/utilities/sanitizePermissions.ts
Labels: created-by: Payload team

#9393 fix(ui): error when collapsing sidebar groups
  packages/ui/src/providers/Preferences/index.tsx
Labels: created-by: Payload team

#9394 perf(richtext-lexical): fix all eslint errors to get react compiler running on all files, enable strict: true
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/server/graphQLPopulationPromise.ts
  packages/richtext-lexical/src/features/converters/html/converter/defaultConverters.ts
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableHoverActionsPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/utils/useDebounce.ts
  packages/richtext-lexical/src/features/lists/checklist/server/index.ts
  packages/richtext-lexical/src/features/lists/orderedList/server/index.ts
  packages/richtext-lexical/src/features/lists/unorderedList/server/index.ts
  packages/richtext-lexical/src/features/relationship/server/nodes/RelationshipNode.tsx
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarButton/index.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/DropDown.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx
  packages/richtext-lexical/src/features/typesClient.ts
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/features/upload/client/nodes/UploadNode.tsx
  packages/richtext-lexical/src/features/upload/client/plugin/index.tsx
  packages/richtext-lexical/src/features/upload/server/nodes/UploadNode.tsx
  packages/richtext-lexical/src/lexical/config/client/sanitize.ts
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/LexicalMenu.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/index.tsx
  packages/richtext-lexical/tsconfig.json
  test/fields/payload-types.ts
Labels: created-by: Payload team

#9165 fix(richtext-lexical): preserve indent and text-align when converting Lexical <-> HTML
  packages/plugin-form-builder/src/utilities/lexical/converters/heading.ts
  packages/plugin-form-builder/src/utilities/lexical/converters/quote.ts
  packages/richtext-lexical/src/features/blockquote/server/index.ts
  packages/richtext-lexical/src/features/converters/html/converter/converters/paragraph.ts
  packages/richtext-lexical/src/features/heading/server/index.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team
