Repository payloadcms/payload, pull requests merged in 2024-09, with the labels that each got.

#7964 fix(richtext-lexical): incorrect error check in TableActionMenu
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.tsx
Labels: v3

#8023 fix: padding on the right of the default padding when scrollbars are enabled in the browser
  packages/next/src/templates/Default/index.scss
Labels: v3, created-by: Contributor

#8024 fix(plugin-seo): meta image selection not working
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
Labels: v3, created-by: Contributor

#7936 fix(richtext-lexical): toolbar styles
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.scss
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.scss
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarButton/index.scss
Labels: v3

#8042 chore: lint entire codebase including db packages
  .git-blame-ignore-revs
  packages/db-mongodb/src/connect.ts
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/models/buildSchema.ts
  packages/db-mongodb/src/queries/buildSearchParams.ts
  packages/db-mongodb/src/queries/parseParams.ts
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
  packages/db-mongodb/src/transactions/commitTransaction.ts
  packages/db-mongodb/src/types.ts
  packages/db-mongodb/src/utilities/getDBName.ts
  packages/db-mongodb/src/withSession.ts
  packages/db-postgres/src/connect.ts
  packages/db-postgres/src/predefinedMigrations/v2-v3/fetchAndResave/traverseFields.ts
  packages/db-postgres/src/predefinedMigrations/v2-v3/migrateRelationships.ts
  packages/db-postgres/src/types.ts
  packages/db-sqlite/src/connect.ts
  packages/db-sqlite/src/schema/build.ts
  packages/db-sqlite/src/schema/createIndex.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/db-sqlite/src/schema/withDefault.ts
  packages/db-sqlite/src/types.ts
  packages/db-vercel-postgres/src/connect.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/fetchAndResave/traverseFields.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/migrateRelationships.ts
  packages/db-vercel-postgres/src/types.ts
  packages/drizzle/src/count.ts
  packages/drizzle/src/createTableName.ts
  packages/drizzle/src/createVersion.ts
  packages/drizzle/src/destroy.ts
  packages/drizzle/src/findMigrationDir.ts
  packages/drizzle/src/migrateReset.ts
  packages/drizzle/src/postgres/createJSONQuery/convertPathToJSONTraversal.ts
  packages/drizzle/src/postgres/schema/build.ts
  packages/drizzle/src/postgres/schema/createIndex.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/withDefault.ts
  packages/drizzle/src/postgres/types.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/drizzle/src/queries/operatorMap.ts
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  packages/drizzle/src/transactions/commitTransaction.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/drizzle/src/transform/write/blocks.ts
  packages/drizzle/src/transform/write/relationships.ts
  packages/drizzle/src/transform/write/traverseFields.ts
  packages/drizzle/src/types.ts
  packages/drizzle/src/upsertRow/deleteExistingRowsByPath.ts
  packages/drizzle/src/upsertRow/index.ts
  packages/drizzle/src/utilities/createBlocksMap.ts
  packages/drizzle/src/utilities/createRelationshipMap.ts
  packages/drizzle/src/utilities/hasLocalesTable.ts
  packages/eslint-config/index.mjs
  packages/plugin-seo/src/translations/index.ts
  templates/website/src/app/(payload)/admin/importMap.js
Labels: v3, created-by: Payload team

#8041 perf(richtext-lexical)!: greatly simplify lexical loading and improve performance
  packages/richtext-lexical/src/cell/index.tsx
  packages/richtext-lexical/src/exports/client/index.ts
  packages/richtext-lexical/src/features/createClientComponent.tsx
  packages/richtext-lexical/src/features/createFeaturePropComponent.tsx
  packages/richtext-lexical/src/features/migrations/slateToLexical/feature.client.tsx
  packages/richtext-lexical/src/features/typesClient.ts
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/features/upload/client/component/index.tsx
  packages/richtext-lexical/src/field/index.tsx
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/config/client/loader.ts
  packages/richtext-lexical/src/lexical/config/client/sanitize.ts
  packages/richtext-lexical/src/lexical/plugins/handles/DraggableBlockPlugin/setTargetLine.ts
  packages/richtext-lexical/src/types.ts
  packages/richtext-lexical/src/utilities/createClientFeature.ts
  packages/richtext-lexical/src/utilities/generateComponentMap.tsx
  scripts/utils/updateChangelog.ts
Labels: v3, created-by: Payload team

#8033 fix(db-postgres): querying by text/number hasMany nested to array/blocks
  packages/db-postgres/src/queries/getTableColumnFromPath.ts
  test/fields/collections/Number/index.ts
  test/fields/collections/Text/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: db-postgres, v2

#8003 fix(db-postgres): querying by text/number hasMany nested to array/blocks
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  test/buildConfigWithDefaults.ts
  test/fields/collections/Number/index.ts
  test/fields/collections/Text/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: db-postgres, v3, db-sqlite

#8066 fix: only show restore as draft option when drafts enabled
  packages/next/src/views/Version/Restore/index.tsx
Labels: v3, created-by: Payload team

#7675 feat: collections can use custom database operations
  packages/payload/src/auth/strategies/local/register.ts
  packages/payload/src/collections/config/schema.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/collections/operations/create.ts
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/deleteByID.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/collections/operations/restoreVersion.ts
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/collections/operations/updateByID.ts
  packages/payload/src/versions/getLatestCollectionVersion.ts
  test/collections-db/config.ts
  test/collections-db/int.spec.ts
Labels: created-by: Payload team

#8063 fix(ui): significantly optimizes relationship field
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Relationship/optionsReducer.ts
  packages/ui/src/fields/Relationship/types.ts
  packages/ui/src/hooks/useIgnoredEffect.ts
  test/databaseAdapter.ts
  test/fields-relationship/config.ts
  test/fields-relationship/e2e.spec.ts
  test/helpers/e2e/trackNetworkRequests.ts
Labels: v3, created-by: Payload team

#8082 chore: add jsdocs for authentication types and add missing config to docs
  docs/authentication/overview.mdx
  packages/payload/src/auth/types.ts
Labels: v3, created-by: Contributor

#8084 ci: release comment mod
  .github/actions/release-commenter/.eslintrc.js
  .github/actions/release-commenter/.prettierrc.js
  .github/actions/release-commenter/README.md
  .github/actions/release-commenter/action.yml
  .github/actions/release-commenter/dist/index.js
  .github/actions/release-commenter/jest.config.js
  .github/actions/release-commenter/package.json
  .github/actions/release-commenter/pnpm-lock.yaml
  .github/actions/release-commenter/src/__snapshots__/index.test.ts.snap
  .github/actions/release-commenter/src/index.test.ts
  .github/actions/release-commenter/src/index.ts
  .github/actions/release-commenter/tsconfig.json
  .github/pnpm-lock.yaml
  .github/pnpm-workspace.yaml
  .github/workflows/post-release.yml
  .gitignore
Labels: created-by: Payload team

#8087 fix(cpa): detect package manager from command execution environment
  packages/create-payload-app/src/lib/get-package-manager.ts
  packages/create-payload-app/src/main.ts
Labels: v3, create-payload-app

#8009 fix(db-postgres): sanitize tab/group path for table name
  packages/drizzle/src/find/buildFindManyArgs.ts
  packages/drizzle/src/find/traverseFields.ts
  test/fields/collections/Group/index.ts
  test/fields/collections/Tabs/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v3

#8010 fix(db-postgres): sanitize tab/group path for table name
  packages/db-postgres/src/find/buildFindManyArgs.ts
  packages/db-postgres/src/find/traverseFields.ts
  test/fields/collections/Group/index.ts
  test/fields/collections/Tabs/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v2

#8095 fix(ui): handles falsey relationship options on reset
  packages/ui/src/fields/Relationship/optionsReducer.ts
Labels: v3, created-by: Payload team

#8094 fix(ui): optimizes the relationship field by sharing a single document drawer across all values
  packages/ui/src/elements/ReactSelect/types.ts
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Relationship/select-components/MultiValueLabel/index.scss
  packages/ui/src/fields/Relationship/select-components/MultiValueLabel/index.tsx
  packages/ui/src/fields/Relationship/select-components/SingleValue/index.scss
  packages/ui/src/fields/Relationship/select-components/SingleValue/index.tsx
  test/admin/e2e/1/e2e.spec.ts
Labels: v3, created-by: Payload team

#8097 chore: adds docs for collection db operations
  docs/configuration/collections.mdx
  docs/database/overview.mdx
Labels: created-by: Payload team

#8101 fix(ui): better responsiveness for upload fields in sidebar
  packages/ui/src/elements/Upload/index.scss
  packages/ui/src/fields/Upload/index.scss
Labels: v3, created-by: Payload team

#8102 fix(ui): missing thumbnail for non-image files in bulk upload sidebar
  packages/ui/src/elements/BulkUpload/FileSidebar/index.scss
  packages/ui/src/elements/BulkUpload/FileSidebar/index.tsx
Labels: v3, created-by: Payload team

#8081 fix(ui): various issues around documents lists, listQuery provider and search params
  packages/next/src/views/List/Default/index.tsx
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/elements/ListDrawer/DrawerContent.tsx
  packages/ui/src/elements/SearchFilter/index.tsx
  packages/ui/src/elements/SortColumn/index.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/hooks/useThrottledEffect.ts
  packages/ui/src/providers/ListQuery/index.tsx
  test/fields/components/AfterNavLinks.tsx
  test/fields/config.ts
Labels: v3, created-by: Contributor

#8105 chore: proper error log format
  examples/multi-tenant/src/collections/Users/hooks/recordLastLoggedInTenant.ts
  packages/db-postgres/src/connect.ts
  packages/db-sqlite/src/connect.ts
  packages/db-vercel-postgres/src/connect.ts
  packages/drizzle/src/transactions/beginTransaction.ts
Labels: v3, created-by: Payload team

#8122 feat: add validation for useAsTitle to throw an error if it's an invalid or nested field
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/config/useAsTitle.spec.ts
  packages/payload/src/collections/config/useAsTitle.ts
  test/fields-relationship/config.ts
  test/fields/collections/Email/index.ts
  test/live-preview/collections/Users.ts
Labels: v3, created-by: Contributor

#8124 fix(ui): thumbnails when serverURL config is provided
  packages/ui/src/fields/Upload/HasMany/index.tsx
  packages/ui/src/fields/Upload/HasOne/index.tsx
Labels: v3, created-by: Contributor

#8126 fix(ui): bulk select checkbox being selected by default when in drawer
  packages/ui/src/providers/Selection/index.tsx
Labels: v3, created-by: Contributor

#7963 fix(ui): wrong block indication when an error occurred
  packages/ui/src/fields/Blocks/index.tsx
Labels: v3

#8137 fix: removes transactions wrapping auth strategies and login
  packages/payload/src/auth/operations/auth.ts
  packages/payload/src/auth/operations/login.ts
Labels: v3, created-by: Contributor

#8100 fix!: multiple preferences for the same user and entry
  packages/payload/src/preferences/operations/delete.ts
  packages/payload/src/preferences/operations/findOne.ts
  packages/payload/src/preferences/operations/update.ts
  packages/payload/src/preferences/requestHandlers/delete.ts
  packages/payload/src/preferences/requestHandlers/findOne.ts
  packages/payload/src/preferences/requestHandlers/update.ts
Labels: v3, created-by: Contributor

#8140 fix: #6800, graphql parallel queries with different fallback locales
  packages/payload/src/collections/dataloader.ts
Labels: v3, created-by: Payload team

#8138 fix(richtext-lexical): indent regression
  packages/richtext-lexical/src/lexical/theme/EditorTheme.scss
Labels: v3

#8144 fix: beforeDuplicate localized blocks and arrays
  packages/payload/src/fields/baseFields/baseBeforeDuplicateArrays.ts
  packages/payload/src/fields/config/sanitize.ts
  test/localization/config.ts
  test/localization/int.spec.ts
Labels: v3, created-by: Contributor

#8155 fix: extends server props onto field component types
  packages/payload/src/admin/forms/Field.ts
  packages/payload/src/fields/config/types.ts
  test/_community/collections/Posts/MyClientComponent.tsx
  test/_community/collections/Posts/MyServerComponent.tsx
Labels: v3, created-by: Payload team

#8154 fix(richtext-lexical): hover style of the button to remove blocks
  packages/richtext-lexical/src/features/blocks/client/component/index.scss
Labels: v3

#8088 fix(cpa): detect package manager from command execution environment
  packages/create-payload-app/src/main.ts
Labels: create-payload-app, v2

#8157 fix: upload.defParamCharset: utf8 by default
  packages/next/src/fetchAPI-multipart/index.ts
Labels: v3

#8135 fix(next): set the user data before redirect after login
  packages/next/src/views/Login/LoginForm/index.tsx
Labels: v3

#8165 fix: useAsTitle validation now accounts for default and base fields
  packages/payload/src/collections/config/sanitize.ts
Labels: v3, created-by: Contributor

#8148 feat(drizzle): add support for in and not_in operators on json field
  package.json
  packages/drizzle/src/queries/parseParams.ts
  test/fields/int.spec.ts
Labels: v3, created-by: Contributor

#7679 feat: document drawer controls
  packages/next/src/views/Edit/Default/index.tsx
  packages/ui/src/elements/DeleteDocument/index.tsx
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/elements/DocumentDrawer/types.ts
  packages/ui/src/elements/Drawer/index.tsx
  packages/ui/src/elements/DuplicateDocument/index.tsx
  packages/ui/src/elements/ReactSelect/types.ts
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Relationship/optionsReducer.ts
  packages/ui/src/fields/Relationship/types.ts
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/DocumentInfo/types.ts
  test/access-control/e2e.spec.ts
  test/admin/e2e/1/e2e.spec.ts
  test/admin/seed.ts
  test/fields-relationship/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/collections/Text/index.ts
  test/fields/payload-types.ts
  test/fields/seed.ts
  test/helpers.ts
  test/helpers/e2e/openDocControls.ts
  test/localization/e2e.spec.ts
Labels: v3, created-by: Payload team

#8175 fix(templates): website media staticDir to public folder
  templates/website/src/collections/Media.ts
Labels: v3, created-by: Contributor

#8166 feat: passes client field config to server components
  docs/admin/fields.mdx
  packages/payload/src/admin/fields/Array.ts
  packages/payload/src/admin/fields/Blocks.ts
  packages/payload/src/admin/fields/Checkbox.ts
  packages/payload/src/admin/fields/Code.ts
  packages/payload/src/admin/fields/Collapsible.ts
  packages/payload/src/admin/fields/Date.ts
  packages/payload/src/admin/fields/Email.ts
  packages/payload/src/admin/fields/Group.ts
  packages/payload/src/admin/fields/JSON.ts
  packages/payload/src/admin/fields/Number.ts
  packages/payload/src/admin/fields/Point.ts
  packages/payload/src/admin/fields/Radio.ts
  packages/payload/src/admin/fields/Relationship.ts
  packages/payload/src/admin/fields/RichText.ts
  packages/payload/src/admin/fields/Row.ts
  packages/payload/src/admin/fields/Select.ts
  packages/payload/src/admin/fields/Tabs.ts
  packages/payload/src/admin/fields/Text.ts
  packages/payload/src/admin/fields/Textarea.ts
  packages/payload/src/admin/fields/Upload.ts
  packages/payload/src/admin/forms/Description.ts
  packages/payload/src/admin/forms/Error.ts
  packages/payload/src/admin/forms/Field.ts
  packages/payload/src/admin/forms/Label.ts
  packages/payload/src/admin/types.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/fields/Password/types.ts
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
  test/_community/collections/Posts/MyClientComponent.tsx
  test/_community/collections/Posts/MyClientField.tsx
  test/_community/collections/Posts/MyServerComponent.tsx
  test/_community/collections/Posts/MyServerField.tsx
  test/_community/collections/Posts/index.ts
  test/databaseAdapter.ts
  test/helpers.ts
  test/helpers/e2e/openDocControls.ts
  test/localization/e2e.spec.ts
Labels: v3, created-by: Payload team

#8171 fix(ui): properly retrieves singular labels for array field rows
  packages/ui/src/fields/Array/index.tsx
  test/fields/collections/Array/e2e.spec.ts
Labels: v3, created-by: Contributor

#8182 test: uploads return correct content type headers
  packages/next/src/routes/rest/files/checkFileAccess.ts
  test/uploads/int.spec.ts
Labels: v3, created-by: Contributor

#8188 fix: requires client field prop in server field components
  packages/payload/src/admin/forms/Description.ts
  packages/payload/src/admin/forms/Error.ts
  packages/payload/src/admin/forms/Label.ts
Labels: v3, created-by: Payload team

#8190 fix(ui): properly extracts label from field in FieldLabel component
  packages/payload/src/admin/forms/Label.ts
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-slate/src/field/RichText.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/fields/Code/index.tsx
  packages/ui/src/fields/DateTime/index.tsx
  packages/ui/src/fields/Email/index.tsx
  packages/ui/src/fields/FieldLabel/index.tsx
  packages/ui/src/fields/JSON/index.tsx
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/Point/index.tsx
  packages/ui/src/fields/RadioGroup/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Select/Input.tsx
  packages/ui/src/fields/Select/index.tsx
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/fields/Text/types.ts
  packages/ui/src/fields/Textarea/index.tsx
  packages/ui/src/fields/Textarea/types.ts
  packages/ui/src/fields/Upload/Input.tsx
  packages/ui/src/fields/Upload/index.tsx
  test/fields/collections/Email/CustomLabel.tsx
Labels: v3, created-by: Payload team

#8194 fix(ui)!: bulk selection and useSelection hook losing types of the IDs its returning
  packages/ui/src/elements/SelectRow/index.tsx
  packages/ui/src/fields/Checkbox/Input.tsx
  packages/ui/src/fields/Checkbox/index.scss
  packages/ui/src/fields/Upload/Input.tsx
  packages/ui/src/providers/Selection/index.tsx
Labels: v3, created-by: Contributor

#8200 chore: prevent leave without saving from appearing when not needed
  examples/multi-tenant-single-domain/src/fields/TenantField/components/Field.client.tsx
Labels: v3, created-by: Contributor

#8176 fix(richtext-lexical): unnecessary `isEnabled` computations on toolbar items
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx
Labels: v3

#8160 fix(db-postgres): preserve parent createdAt when creating a new version
  packages/drizzle/src/createVersion.ts
  test/versions/int.spec.ts
Labels: v3

#8202 perf: upgrade jsonwebtoken from 9.0.1 to 9.0.2
  packages/payload/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#8204 perf: upgrade ajv, and upgrade typescript to 5.6.2 in monorepo
  package.json
  packages/create-payload-app/package.json
  packages/eslint-config/package.json
  packages/eslint-plugin/package.json
  packages/graphql/package.json
  packages/payload/package.json
  packages/payload/src/fields/hooks/afterChange/promise.ts
  packages/payload/src/types/index.ts
  packages/plugin-sentry/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/translations/package.json
  packages/ui/package.json
  packages/ui/src/fields/Upload/Input.tsx
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/ecommerce/package.json
  templates/vercel-postgres/package.json
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/payload.config.ts
  test/package.json
Labels: v3, created-by: Payload team

#8211 fix(ui): field type being overridden when providing a Cell component
  packages/ui/src/elements/WhereBuilder/reduceClientFields.tsx
Labels: v3, created-by: Contributor

#8212 fix(richtext-lexical): default Cell not being a link when used as the primary column in lists
  packages/richtext-lexical/src/cell/index.tsx
Labels: v3, created-by: Contributor

#8213 fix: error when viewing versions if plural label is set as a function
  packages/next/src/views/Versions/index.tsx
Labels: v3, created-by: Contributor

#8206 fix(plugin-seo): removes duplicative json translations
  packages/plugin-seo/src/translations/en.json
  packages/plugin-seo/src/translations/en.ts
  packages/plugin-seo/src/translations/es.json
  packages/plugin-seo/src/translations/es.ts
  packages/plugin-seo/src/translations/fa.json
  packages/plugin-seo/src/translations/fa.ts
  packages/plugin-seo/src/translations/fr.json
  packages/plugin-seo/src/translations/fr.ts
  packages/plugin-seo/src/translations/index.ts
  packages/plugin-seo/src/translations/it.json
  packages/plugin-seo/src/translations/it.ts
  packages/plugin-seo/src/translations/nb.ts
  packages/plugin-seo/src/translations/pl.json
  packages/plugin-seo/src/translations/pl.ts
  packages/plugin-seo/src/translations/ru.json
  packages/plugin-seo/src/translations/ru.ts
  packages/plugin-seo/src/translations/uk.json
  packages/plugin-seo/src/translations/uk.ts
Labels: v3, created-by: Payload team

#8220 fix: duplicating localized nested arrays
  docs/hooks/fields.mdx
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/payload/src/collections/operations/duplicate.ts
  packages/payload/src/fields/baseFields/baseBeforeDuplicateArrays.ts
  packages/payload/src/fields/baseFields/baseIDField.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/hooks/beforeChange/index.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/hooks/beforeChange/traverseFields.ts
  packages/payload/src/fields/hooks/beforeDuplicate/index.ts
  packages/payload/src/fields/hooks/beforeDuplicate/promise.ts
  packages/payload/src/fields/hooks/beforeDuplicate/runHook.ts
  packages/payload/src/fields/hooks/beforeDuplicate/traverseFields.ts
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/index.ts
  test/localization/config.ts
  test/localization/int.spec.ts
Labels: v3, created-by: Payload team

#8195 perf: remove find-up dependency, upgrade file-type dependency
  jest.config.js
  packages/next/package.json
  packages/payload/package.json
  packages/payload/src/bin/loadEnv.ts
  packages/payload/src/config/find.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/dependencies/getDependencies.ts
  packages/payload/src/utilities/findUp.ts
  packages/payload/src/utilities/telemetry/index.ts
  pnpm-lock.yaml
  test/package.json
Labels: v3, created-by: Payload team

#8226 ci: release commenter
  .github/actions/release-commenter/.eslintrc.js
  .github/actions/release-commenter/README.md
  .github/actions/release-commenter/action.yml
  .github/actions/release-commenter/dist/index.js
  .github/actions/release-commenter/jest.config.js
  .github/actions/release-commenter/package.json
  .github/actions/release-commenter/pnpm-lock.yaml
  .github/actions/release-commenter/src/__snapshots__/index.test.ts.snap
  .github/actions/release-commenter/src/index.test.ts
  .github/actions/release-commenter/src/index.ts
  .github/actions/release-commenter/tsconfig.json
  .github/actions/setup/action.yml
  .github/pnpm-lock.yaml
  .github/pnpm-workspace.yaml
  .gitignore
Labels: v3, created-by: Payload team

#8234 feat(cpa): add node engines
  packages/create-payload-app/package.json
Labels: v3, created-by: Payload team

#7647 feat: add new option for admin.components.header
  docs/admin/components.mdx
  packages/next/src/templates/Default/index.scss
  packages/next/src/templates/Default/index.tsx
  packages/payload/src/bin/generateImportMap/iterateConfig.ts
  packages/payload/src/config/types.ts
  test/admin/components/CustomHeader/index.tsx
  test/admin/config.ts
  test/admin/e2e/1/e2e.spec.ts
Labels: v3, created-by: Payload team

#8236 fix: duplication with localized arrays in unnamed tabs
  packages/payload/src/fields/hooks/beforeDuplicate/promise.ts
  test/localization/config.ts
  test/localization/e2e.spec.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
Labels: v3, created-by: Payload team

#8235 chore: gitignore test/databaseAdapter
  .gitignore
  test/databaseAdapter.ts
  test/generateDatabaseAdapter.ts
  test/generateTypes.ts
  test/graphql-schema-gen/schema.graphql
  test/initDevAndTest.ts
  test/jest.setup.js
Labels: v3, created-by: Contributor

#8230 fix(drizzle)!: localized fields uniqueness per locale
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  test/localization/config.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
Labels: v3

#8238 fix(plugin-seo): threads entity slug and document config through generation fn args
  docs/plugins/seo.mdx
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/fields/Preview/PreviewComponent.tsx
  packages/plugin-seo/src/index.tsx
  packages/plugin-seo/src/types.ts
  packages/ui/src/providers/DocumentInfo/types.ts
Labels: v3, created-by: Payload team

#8242 fix(ui): nav button height being stretched and navWrapper border on RTL
  packages/next/src/elements/Nav/NavWrapper/index.scss
  packages/next/src/elements/Nav/index.scss
  packages/next/src/templates/Default/index.scss
  packages/next/src/templates/Default/index.tsx
Labels: v3, created-by: Contributor

#8245 fix(ui): draft docs are now correctly provided in preview URL
  packages/ui/src/elements/PreviewButton/usePreviewURL.tsx
Labels: v3, created-by: Contributor

#8246 fix(ui): field alignment when labels overflow inside rows
  packages/ui/src/fields/Row/index.scss
Labels: v3, created-by: Contributor

#8248 fix(ui): pass label as prop through to the textarea input
  packages/ui/src/fields/Textarea/index.tsx
Labels: v3, created-by: Contributor

#8243 fix: properly infers field validation args
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/plugin-cloud-storage/src/admin/fields/getFields.ts
  packages/plugin-cloud-storage/src/fields/getFields.ts
  packages/plugin-redirects/src/index.ts
  packages/ui/src/forms/buildStateFromSchema/addFieldStatePromise.ts
Labels: v3, created-by: Payload team

#8260 fix(ui): filtering in any collection crush the app after navigating to another colleciton
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
Labels: v3

#8240 fix(drizzle): polymorphic querying using in operator of different ID types
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  test/relationships/int.spec.ts
Labels: v3

#8264 fix(ui): mobile menu button sizing
  packages/next/src/elements/Nav/index.scss
Labels: v3, created-by: Contributor

#8263 fix: strongly types field validation args
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/validations.ts
  packages/payload/src/index.ts
  test/fields/collections/Number/index.ts
Labels: v3, created-by: Payload team

#8209 fix(ui): codeBlock adjusts its height to its content dynamically. Scrolling over the container is not prevented.
  packages/ui/src/elements/CodeEditor/CodeEditor.tsx
  packages/ui/src/elements/CodeEditor/index.tsx
  test/fields/collections/Lexical/blocks.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Lexical/generateLexicalRichText.ts
  test/fields/collections/Lexical/index.ts
Labels: v3

#8268 fix(templates): optional chaining bug
  templates/website/src/fields/slug/SlugComponent.tsx
Labels: v3

#8269 chore: cleans up locked-documents
  packages/next/src/views/Dashboard/Default/index.tsx
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/deleteByID.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/collections/operations/updateByID.ts
  packages/payload/src/globals/operations/findOne.ts
  packages/payload/src/globals/operations/update.ts
  packages/payload/src/lockedDocuments/lockedDocumentsCollection.ts
  packages/payload/src/utilities/checkDocumentLockStatus.ts
  packages/ui/src/elements/SelectRow/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/Selection/index.tsx
  packages/ui/src/utilities/buildFormState.ts
  test/_community/payload-types.ts
  test/locked-documents/e2e.spec.ts
  test/locked-documents/int.spec.ts
  test/locked-documents/payload-types.ts
Labels: v3, created-by: Contributor

#8272 fix(richtext-slate): fix issue with richText field cell not being a link when used as a useAsTitle
  packages/richtext-slate/src/cell/index.tsx
Labels: v3, created-by: Contributor

#8271 feat(plugin-form-builder): new wildcards {{*}} and {{*:table}} are now supported in email bodies and emails fall back to a global configuration value in addition to base email configuration
  docs/plugins/form-builder.mdx
  packages/plugin-form-builder/src/collections/FormSubmissions/hooks/sendEmail.ts
  packages/plugin-form-builder/src/collections/Forms/index.ts
  packages/plugin-form-builder/src/types.ts
  packages/plugin-form-builder/src/utilities/keyValuePairToHtmlTable.ts
  packages/plugin-form-builder/src/utilities/replaceDoubleCurlys.ts
  packages/plugin-form-builder/src/utilities/slate/serializeSlate.ts
  test/plugin-form-builder/config.ts
  test/plugin-form-builder/int.spec.ts
  test/plugin-form-builder/payload-types.ts
  test/plugin-form-builder/seed/index.ts
Labels: v3, created-by: Contributor

#8282 fix: findByID adjust type to null if disableErrors: true is passed
  docs/local-api/overview.mdx
  packages/payload/src/collections/operations/local/findByID.ts
  packages/payload/src/index.ts
  test/collections-rest/int.spec.ts
Labels: v3

#8296 feat(ui): useTableColumns add abillity to reset columns state
  packages/ui/src/elements/TableColumns/index.tsx
  test/admin/collections/Posts.ts
  test/admin/components/ResetColumns/index.tsx
  test/admin/payload-types.ts
Labels: v3

#8301 chore: add best practices for authenticating with cookies cross domains in documentation
  docs/authentication/cookies.mdx
Labels: v3, created-by: Contributor

#8293 fix: only add snapshot to versions query when localization is enabled
  packages/next/src/views/Version/Default/index.tsx
  packages/next/src/views/Version/SelectComparison/index.tsx
  packages/next/src/views/Version/SelectComparison/types.ts
  packages/next/src/views/Versions/index.tsx
  test/admin-root/e2e.spec.ts
  test/admin-root/globals/Menu/index.ts
Labels: v3, created-by: Payload team

#8292 feat(ui): threads collectionSlugs through useListDrawer
  packages/ui/src/elements/ListDrawer/index.tsx
  packages/ui/src/elements/ListDrawer/types.ts
Labels: v3

#8309 feat(ui): hides lock icon when locked by current user
  packages/next/src/views/Dashboard/Default/index.tsx
  packages/next/src/views/List/Default/index.tsx
  packages/ui/src/elements/SelectRow/index.tsx
  packages/ui/src/providers/Selection/index.tsx
  test/locked-documents/e2e.spec.ts
Labels: v3, created-by: Contributor

#8313 feat: join field sanitization
  docs/fields/join.mdx
  packages/payload/src/errors/InvalidFieldJoin.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/sanitizeJoinField.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/utilities/traverseFields.ts
  test/joins/collections/Categories.ts
  test/joins/payload-types.ts
Labels: created-by: Contributor

#8294 feat: adds `overrideLock` flag to `update` & `delete` operations
  docs/admin/locked-documents.mdx
  docs/local-api/overview.mdx
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/deleteByID.ts
  packages/payload/src/collections/operations/local/delete.ts
  packages/payload/src/collections/operations/local/update.ts
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/collections/operations/updateByID.ts
  packages/payload/src/errors/Locked.ts
  packages/payload/src/errors/index.ts
  packages/payload/src/globals/operations/local/update.ts
  packages/payload/src/globals/operations/update.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/checkDocumentLockStatus.ts
  test/locked-documents/int.spec.ts
Labels: v3, created-by: Contributor

#8315 perf: optimizes admin ui loading by using react cache to memoize req / auth
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initReq.ts
Labels: v3, created-by: Payload team

#8321 chore: add warning in documentation about custom endpoints and authentication
  docs/rest-api/overview.mdx
Labels: v3, created-by: Contributor

#8320 chore: fix lingering jest and next-server processes in monorepo
  test/dev.ts
  test/helpers/stopMemoryDB.ts
  test/jest.config.js
Labels: v3, created-by: Payload team

#8324 chore: use updatedAt instead of editedAt for locked documents
  packages/next/src/elements/DocumentLocked/index.tsx
  packages/next/src/views/Edit/Default/index.tsx
  packages/payload/src/lockedDocuments/lockedDocumentsCollection.ts
  packages/payload/src/utilities/checkDocumentLockStatus.ts
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/utilities/buildFormState.ts
  test/locked-documents/e2e.spec.ts
  test/locked-documents/int.spec.ts
  test/locked-documents/payload-types.ts
Labels: v3, created-by: Contributor

#8330 fix(ui): adjust list view table alignment
  packages/next/src/views/List/Default/index.scss
  packages/ui/src/elements/Table/index.scss
Labels: v3, created-by: Payload team

#8331 fix(drizzle): nested arrays with localized items and versions
  packages/drizzle/src/upsertRow/insertArrays.ts
  test/fields/collections/Array/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v3

#8316 fix(drizzle): support equals polymorphic querying with object notation
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  packages/drizzle/src/utilities/getCollectionIdType.ts
  packages/drizzle/src/utilities/isPolymorphicRelationship.ts
  test/_community/payload-types.ts
  test/relationships/int.spec.ts
Labels: v3

#8332 chore(templates): remove now unnecessary ts-ignore from lexical serializer
  templates/website/src/components/RichText/serialize.tsx
Labels: v3, created-by: Payload team

#8323 feat!: upgrade next, react and react-dom, move react/next dependency checker from payload to next package
  examples/custom-components/package.json
  next-env.d.ts
  package.json
  packages/live-preview-react/package.json
  packages/next/package.json
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/views/Document/getDocumentData.tsx
  packages/next/src/views/Versions/buildColumns.tsx
  packages/payload/package.json
  packages/payload/src/checkPayloadDependencies.ts
  packages/payload/src/index.ts
  packages/payload/src/versions/saveVersion.ts
  packages/plugin-form-builder/package.json
  packages/plugin-redirects/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-seo/package.json
  packages/plugin-stripe/package.json
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/index.ts
  packages/richtext-slate/package.json
  packages/translations/package.json
  packages/ui/package.json
  packages/ui/src/elements/Table/DefaultCell/fields/index.tsx
  packages/ui/src/fields/index.tsx
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/vercel-postgres/package.json
  templates/website/next-env.d.ts
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  test/admin-root/e2e.spec.ts
  test/helpers.ts
  test/helpers/NextRESTClient.ts
  test/helpers/e2e/reorderColumns.ts
  test/locked-documents/e2e.spec.ts
  test/package.json
Labels: v3, created-by: Payload team

#8333 chore: add re-usable run against prod command
  package.json
Labels: v3, created-by: Payload team

#8338 fix(plugin-form-builder)!: emails array field has read access by authenticated users only by default now
  docs/plugins/form-builder.mdx
  packages/plugin-form-builder/src/collections/Forms/index.ts
Labels: v3, created-by: Contributor

#8339 fix(ui): client side error when passing labels as functions for custom view tabs
  packages/ui/src/providers/Config/createClientConfig/collections.tsx
Labels: v3, created-by: Contributor

#8336 fix: treat empty strings as null / undefined for `exists` queries
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
Labels: created-by: Payload team

#8337 fix(db-mongodb): treat empty strings as null / undefined for exists queries
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
Labels: v3, created-by: Contributor

#8345 chore(cpa): prefer pnpm if exists
  packages/create-payload-app/src/lib/get-package-manager.ts
  packages/create-payload-app/src/main.ts
Labels: v3, created-by: Payload team

#8342 fix(ui): hide dot menu in read-only mode for locked documents
  packages/ui/src/elements/DocumentControls/index.tsx
  test/locked-documents/e2e.spec.ts
Labels: v3, created-by: Contributor

#8177 feat(richtext-lexical)!: dropdown menu disabled status
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarButton/index.scss
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.scss
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.tsx
  packages/richtext-lexical/src/features/toolbars/types.ts
Labels: v3, BREAKING

#8341 fix(ui): inconsistent arrow dropdown on buttons, popover missing caret
  packages/next/src/views/Version/Restore/index.tsx
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Popup/PopupTrigger/index.scss
  packages/ui/src/elements/Popup/PopupTrigger/index.tsx
  packages/ui/src/elements/Popup/index.scss
  packages/ui/src/elements/Popup/index.tsx
Labels: v3, created-by: Payload team

#8359 fix: cannot use join on relationships in unnamed fields
  packages/payload/src/fields/config/sanitizeJoinField.ts
Labels: v3, created-by: Contributor

#8355 fix(drizzle): array / relationship / select hasMany inside of localized groups / tabs
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  test/fields/collections/Group/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v3

#8369 fix(drizzle): sanitize query value uuid / number id NaN
  packages/drizzle/src/queries/parseParams.ts
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  test/collections-rest/int.spec.ts
Labels: v3

#8360 fix(next): set the user data after first user registration
  packages/next/src/views/CreateFirstUser/index.client.tsx
Labels: v3

#8340 fix: optional sortOptions type for SingleRelationshipFieldClient
  packages/payload/src/fields/config/types.ts
Labels: v3

#8368 fix(richtext-lexical): table dropdown menu dark mode color
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.scss
Labels: v3

#8378 fix(richtext-lexical): regression in lexical blocks
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/ui/src/providers/DocumentInfo/types.ts
Labels: v3

#8376 fix(db-mongodb): db.find default limit to 0
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  test/joins/int.spec.ts
Labels: v3, created-by: Contributor

#8381 fix: safely access user in auth operations
  packages/payload/src/auth/operations/login.ts
  packages/payload/src/auth/operations/me.ts
  packages/payload/src/auth/operations/refresh.ts
Labels: v3, created-by: Payload team

#8391 feat: templates update
  scripts/generate-template-variations.ts
  templates/with-vercel-postgres/README.md
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/payload.config.ts
Labels: v3, created-by: Payload team

#8394 fix(templates): proper migration file import source for vercel-postgres
  scripts/generate-template-variations.ts
  templates/with-postgres/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/initial.ts
Labels: v3, created-by: Payload team

#8393 fix(db-vercel-postgres): include needed pg dependency
  packages/db-vercel-postgres/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#8389 feat!: improve afterError hook to accept array of functions, change to object args
  docs/hooks/collections.mdx
  docs/hooks/overview.mdx
  packages/next/src/routes/graphql/handler.ts
  packages/next/src/routes/rest/routeError.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/config/types.ts
  packages/payload/src/index.ts
  packages/plugin-sentry/src/plugin.ts
  test/_community/payload-types.ts
  test/collections-rest/config.ts
  test/collections-rest/int.spec.ts
  test/hooks/config.ts
Labels: v3, created-by: Payload team

#8382 fix(ui): published, draft and changed labels should now be correctly displayed
  packages/payload/src/versions/types.ts
  packages/ui/src/elements/PublishButton/index.tsx
  packages/ui/src/elements/Status/index.tsx
  test/versions/e2e.spec.ts
Labels: v3, created-by: Contributor

#8343 feat: adds document locking to `live-preview` view
  packages/next/src/views/Edit/Default/index.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/utilities/handleBackToDashboard.tsx
  packages/ui/src/utilities/handleGoBack.tsx
  packages/ui/src/utilities/handleTakeOver.tsx
  test/locked-documents/e2e.spec.ts
Labels: v3, created-by: Contributor

#8374 fix: client function error on forgot password view
  packages/next/src/views/ForgotPassword/index.tsx
Labels: v3, created-by: Contributor

#8397 feat: add upsert to database interface and adapters
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/updateOne.ts
  packages/db-mongodb/src/upsert.ts
  packages/db-postgres/src/index.ts
  packages/db-sqlite/src/index.ts
  packages/db-vercel-postgres/src/index.ts
  packages/payload/src/database/types.ts
  packages/payload/src/index.ts
  packages/payload/src/preferences/operations/update.ts
  test/auth/int.spec.ts
Labels: v3, created-by: Payload team

#8375 fix(drizzle): make migrate up and down args take full payload request instead of partial
  packages/db-sqlite/src/types.ts
  packages/drizzle/src/postgres/types.ts
Labels: v3, created-by: Contributor

#8310 fix(plugin-seo): titles being displayed twice
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/fields/Preview/PreviewComponent.tsx
  packages/plugin-seo/src/index.tsx
  test/plugin-seo/collections/PagesWithImportedFields.ts
Labels: v3, created-by: Contributor

#8408 chore(deps): bump express
  packages/payload/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#8409 fix: make field property of FieldLabel optional and partial
  packages/payload/src/admin/forms/Label.ts
Labels: v3, created-by: Payload team

#8407 fix(db-mongodb): add req to migration templates for transactions
  docs/database/migrations.mdx
  docs/database/transactions.mdx
  packages/db-mongodb/src/createMigration.ts
  packages/db-mongodb/src/types.ts
Labels: v3, created-by: Payload team

#8196 feat(drizzle): allow to customize the drizzle schema with before / after init hooks
  docs/database/postgres.mdx
  docs/database/sqlite.mdx
  packages/db-postgres/src/index.ts
  packages/db-postgres/src/types.ts
  packages/db-sqlite/src/index.ts
  packages/db-sqlite/src/init.ts
  packages/db-sqlite/src/types.ts
  packages/db-vercel-postgres/src/index.ts
  packages/db-vercel-postgres/src/types.ts
  packages/drizzle/src/index.ts
  packages/drizzle/src/postgres/init.ts
  packages/drizzle/src/postgres/types.ts
  packages/drizzle/src/utilities/executeSchemaHooks.ts
  packages/drizzle/src/utilities/extendDrizzleTable.ts
  test/_community/payload-types.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: v3

#8417 fix(ui): versions in documentInfo and status component reverse latest true changes
  packages/ui/src/elements/PublishButton/index.tsx
  packages/ui/src/elements/Status/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
Labels: v3, created-by: Payload team

#8420 chore: add join field image to docs
  docs/fields/join.mdx
Labels: v3, created-by: Payload team

#8421 fix(ui): align to the top fields inside row field
  packages/ui/src/fields/Row/index.scss
Labels: v3, created-by: Payload team

#8425 fix(ui): number field not being able to clear out the field's value
  packages/ui/src/fields/Number/index.tsx
  test/fields/collections/Number/e2e.spec.ts
Labels: v3, created-by: Payload team

#8434 fix(ui): autosave and preventLeaveWithoutSaving interfering with fetching form-state reliably
  packages/next/src/views/Edit/Default/index.tsx
  packages/ui/src/elements/Autosave/index.tsx
Labels: v3, created-by: Payload team

#8431 fix(richtext-lexical): add max-width to tables (temporary fix for overflow).
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.scss
Labels: v3

#8435 fix(db-mongodb): docs duplicated in list view with drafts
  packages/db-mongodb/src/createVersion.ts
Labels: v3, created-by: Payload team

#8398 feat(payload, ui): add allowEdit config to the admin of the relationship field
  docs/fields/relationship.mdx
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/ReactSelect/types.ts
  packages/ui/src/fields/Relationship/findOptionsByValue.ts
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Relationship/select-components/MultiValueLabel/index.tsx
  packages/ui/src/fields/Relationship/select-components/SingleValue/index.tsx
  packages/ui/src/fields/Relationship/types.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/collections/Relationship/index.ts
  test/fields/payload-types.ts
Labels: v3

#8438 chore: export toast from react toastify in payload
  packages/payload/src/exports/components/elements.ts
Labels: created-by: Payload team

#8437 fix(richtext-lexical): match the indentation spacing of paragraphs and lists
  packages/richtext-lexical/src/lexical/theme/EditorTheme.scss
Labels: v3

#8454 feat(templates): add search functionality to the website template
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/Header/Nav/index.tsx
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/next/preview/route.ts
  templates/website/src/app/(frontend)/search/page.tsx
  templates/website/src/app/(payload)/admin/importMap.js
  templates/website/src/collections/Pages/index.ts
  templates/website/src/collections/Posts/index.ts
  templates/website/src/components/PayloadRedirects/index.tsx
  templates/website/src/endpoints/seed/index.ts
  templates/website/src/fields/slug/SlugComponent.tsx
  templates/website/src/payload-types.ts
  templates/website/src/payload.config.ts
  templates/website/src/search/Component.tsx
  templates/website/src/search/beforeSync.ts
  templates/website/src/search/fieldOverrides.ts
  templates/website/src/utilities/generatePreviewPath.ts
  templates/website/src/utilities/useDebounce.ts
Labels: v3, created-by: Payload team

#8415 fix: properly filters out `number` field values with the `exists` operator filter
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
  test/fields/int.spec.ts
Labels: created-by: Payload team

#8444 feat(richtext-lexical)!: upgrade lexical from 0.17.0 to 0.18.0, make tables more reliable
  package.json
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.tsx
  packages/richtext-lexical/src/features/horizontalRule/client/component/index.tsx
  packages/richtext-lexical/src/features/relationship/client/components/RelationshipComponent.tsx
  packages/richtext-lexical/src/features/upload/client/component/index.tsx
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/theme/EditorTheme.tsx
  packages/ui/src/providers/ScrollInfo/index.tsx
  pnpm-lock.yaml
  templates/website/package.json
  test/package.json
Labels: v3

#8467 chore: add workaround for unsettled top-level await script failures
  test/dev.ts
  test/safelyRunScript.ts
Labels: v3, created-by: Payload team

#8471 chore: fix build by adding missing translation keys
  packages/translations/src/languages/da.ts
Labels: v3, created-by: Payload team

#8474 fix(ui): locales with RTL enabled not applying for localised textarea fields
  packages/ui/src/fields/Textarea/index.tsx
Labels: v3, created-by: Payload team

#8416 fix(db-mongodb): properly filters out `number` field values with the `exists` operator filter
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
  test/fields/int.spec.ts
Labels: v3, created-by: Payload team

#8448 fix: reset password link extra slash and thread admin.routes.reset property
  packages/next/src/views/Root/getViewFromConfig.ts
  packages/next/src/views/Root/meta.ts
  packages/payload/src/auth/operations/forgotPassword.ts
Labels: v3, created-by: Payload team

#8486 fix: draft status access control checks
  packages/next/src/views/Document/getDocumentPermissions.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
Labels: v3, created-by: Payload team

#8487 fix(db-mongodb): duplicate versions with parent string ids
  packages/db-mongodb/src/createVersion.ts
Labels: v3, created-by: Payload team

#8419 fix(db-*): make db.begintransactions required
  packages/db-mongodb/src/index.ts
  packages/db-postgres/src/index.ts
  packages/db-sqlite/src/index.ts
  packages/db-vercel-postgres/src/index.ts
  packages/payload/src/database/defaultBeginTransaction.ts
  packages/payload/src/database/types.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/initTransaction.ts
Labels: v3, created-by: Payload team

#8379 feat: join field on upload fields
  docs/fields/join.mdx
  docs/fields/upload.mdx
  packages/payload/src/fields/config/sanitizeJoinField.ts
  packages/ui/src/elements/Table/TableCellProvider/index.tsx
  packages/ui/src/fields/Upload/Input.tsx
  test/joins/.gitignore
  test/joins/collections/Posts.ts
  test/joins/collections/Uploads.ts
  test/joins/config.ts
  test/joins/e2e.spec.ts
  test/joins/image.png
  test/joins/int.spec.ts
  test/joins/payload-types.ts
  test/joins/seed.ts
  test/joins/shared.ts
Labels: v3, created-by: Contributor
