Repository payloadcms/payload, pull requests merged in 2024-07, with the labels that each got.

#6995 feat(ui): export iterateFields function
  packages/ui/src/forms/buildStateFromSchema/index.tsx
Labels: created-by: Payload team

#6999 chore: threads customActions through to FileDetails component
  packages/ui/src/elements/Upload/index.tsx
Labels: created-by: Contributor

#6997 chore: add user type argument to generate email html and subject types
  packages/payload/src/auth/types.ts
Labels: created-by: Contributor

#7001 fix: translation fallback language returning the label and not the language key
  packages/translations/src/utilities/getTranslation.ts
Labels: created-by: Contributor

#7003 fix(ui): content alignment in modal
  packages/ui/src/elements/DeleteDocument/index.scss
  packages/ui/src/elements/DeleteMany/index.scss
Labels: created-by: Contributor

#6996 feat(plugin-seo): export fields from plugin seo so that they can be imported freely in a collection fields config
  docs/plugins/seo.mdx
  packages/plugin-seo/package.json
  packages/plugin-seo/src/exports/fields.ts
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaDescription/index.ts
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/index.ts
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/index.ts
  packages/plugin-seo/src/fields/Overview/OverviewComponent.tsx
  packages/plugin-seo/src/fields/Overview/index.tsx
  packages/plugin-seo/src/fields/Preview/PreviewComponent.tsx
  packages/plugin-seo/src/fields/Preview/index.tsx
  packages/plugin-seo/src/index.tsx
  test/plugin-seo/collections/PagesWithImportedFields.ts
  test/plugin-seo/config.ts
  test/plugin-seo/payload-types.ts
  test/plugin-seo/shared.ts
Labels: created-by: Contributor

#7009 feat(richtext-lexical)!: upgrade lexical from 0.16.0 to 0.16.1
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/link/plugins/autoLink/index.tsx
  pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#6647 feat(ui): allows filtering on group and tab fields from list controls
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/FieldSelect/index.tsx
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/elements/WhereBuilder/reduceFieldMap.tsx
  packages/ui/src/elements/WhereBuilder/types.ts
  test/admin/e2e/2/e2e.spec.ts
Labels: created-by: Payload team

#7002 docs: rewrites field admin docs to 3.0
  docs/admin/components.mdx
  docs/admin/fields.mdx
  docs/admin/hooks.mdx
  docs/admin/overview.mdx
  docs/admin/views.mdx
  docs/fields/overview.mdx
  docs/fields/text.mdx
Labels: created-by: Payload team

#7012 fix: ensures req has headers, passes it through in view rendering
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/views/List/index.tsx
  packages/next/src/views/Version/index.tsx
  packages/next/src/views/Versions/index.tsx
Labels: created-by: Contributor

#7010 feat(richtext-lexical): add EXPERIMENTAL_TableFeature, allow Client Features to register providers
  docs/lexical/building-custom-features.mdx
  docs/lexical/overview.mdx
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/exports/client/index.ts
  packages/richtext-lexical/src/features/experimental_table/feature.client.ts
  packages/richtext-lexical/src/features/experimental_table/feature.server.ts
  packages/richtext-lexical/src/features/experimental_table/plugins/TableActionMenuPlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/plugins/TableActionMenuPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/plugins/TableCellResizerPlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/plugins/TablePlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/plugins/TablePlugin/index.tsx
  packages/richtext-lexical/src/features/toolbars/fixed/Toolbar/index.scss
  packages/richtext-lexical/src/features/typesClient.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/lexical/config/client/sanitize.ts
  packages/richtext-lexical/src/lexical/theme/EditorTheme.scss
  packages/richtext-lexical/src/lexical/ui/icons/Meatballs/index.tsx
  packages/richtext-lexical/src/lexical/ui/icons/Table/index.tsx
  pnpm-lock.yaml
  test/fields/collections/Lexical/index.ts
Labels: created-by: Payload team

#7023 docs: root-level routes require directory rename
  docs/admin/overview.mdx
  docs/fields/text.mdx
Labels: created-by: Payload team

#7027 chore: clean up packages
  package.json
  packages/create-payload-app/package.json
  packages/create-payload-app/src/lib/create-project.spec.ts
  packages/eslint-config-payload/eslint-config/index.js
  packages/eslint-config-payload/package.json
  packages/eslint-plugin-payload/package.json
  packages/payload/package.json
  packages/payload/src/uploads/generateFileData.ts
  packages/translations/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/with-payload-cloud/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  test/package.json
Labels: created-by: Payload team

#7040 docs: fix typo in storage-adapters.mdx
  docs/upload/storage-adapters.mdx
Labels: created-by: Payload team

#7042 fix(richtext-lexical): avoid conflicts between internal component/schema map paths and field names
  packages/richtext-lexical/src/cell/index.tsx
  packages/richtext-lexical/src/features/blocks/component/index.tsx
  packages/richtext-lexical/src/features/createFeaturePropComponent.tsx
  packages/richtext-lexical/src/field/index.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/DrawerContent.tsx
  packages/richtext-lexical/src/utilities/generateComponentMap.tsx
  packages/richtext-lexical/src/utilities/generateSchemaMap.ts
Labels: created-by: Payload team

#7043 chore: upgrade @lexical/eslint-plugin and @types/uuid
  packages/payload/package.json
  packages/plugin-stripe/package.json
  packages/richtext-lexical/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#7045 feat: avoid unnecessary config await in getPayloadHMR
  packages/next/src/utilities/getPayloadHMR.ts
Labels: created-by: Payload team

#7044 feat(ui): support nested tabs, groups, collapsibles and rows in where filters in list view
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/elements/WhereBuilder/reduceFieldMap.tsx
  test/admin/e2e/2/e2e.spec.ts
Labels: created-by: Contributor

#7026 feat!: support latest Next.js versions
  package.json
  packages/next/package.json
  packages/next/src/views/Document/index.tsx
  packages/payload/src/utilities/isReactComponent.ts
  packages/ui/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/with-payload-cloud/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
Labels: created-by: Payload team

#7011 feat!: updated admin panel color palette
  examples/auth/next-app/app/_css/colors.scss
  examples/auth/next-pages/src/css/colors.scss
  examples/auth/payload/src/app/(app)/_css/colors.scss
  packages/next/src/scss/colors.scss
  packages/richtext-lexical/src/scss/colors.scss
  packages/richtext-slate/src/scss/colors.scss
  packages/ui/src/providers/ToastContainer/icons/Error.tsx
  packages/ui/src/providers/ToastContainer/icons/Info.tsx
  packages/ui/src/providers/ToastContainer/icons/Success.tsx
  packages/ui/src/providers/ToastContainer/icons/Warning.tsx
  packages/ui/src/providers/ToastContainer/index.tsx
  packages/ui/src/scss/app.scss
  packages/ui/src/scss/colors.scss
  packages/ui/src/scss/toasts.scss
  templates/ecommerce/src/app/_css/colors.scss
  test/live-preview/app/live-preview/_css/colors.scss
Labels: created-by: Payload team

#7061 fix(plugin-redirects): make fields optional type in overrides
  packages/plugin-redirects/src/types.ts
Labels: created-by: Contributor

#7062 fix(plugin-form-builder): make fields optional type in overrides
  packages/plugin-form-builder/src/types.ts
Labels: created-by: Contributor

#6925 fix: graphql query concurrency issues
  packages/db-mongodb/src/count.ts
  packages/db-mongodb/src/create.ts
  packages/db-mongodb/src/createGlobal.ts
  packages/db-mongodb/src/createGlobalVersion.ts
  packages/db-mongodb/src/createVersion.ts
  packages/db-mongodb/src/deleteMany.ts
  packages/db-mongodb/src/deleteOne.ts
  packages/db-mongodb/src/deleteVersions.ts
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobal.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findOne.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/queryDrafts.ts
  packages/db-mongodb/src/transactions/commitTransaction.ts
  packages/db-mongodb/src/transactions/rollbackTransaction.ts
  packages/db-mongodb/src/updateGlobal.ts
  packages/db-mongodb/src/updateGlobalVersion.ts
  packages/db-mongodb/src/updateOne.ts
  packages/db-mongodb/src/updateVersion.ts
  packages/db-mongodb/src/withSession.ts
  packages/db-postgres/src/count.ts
  packages/db-postgres/src/create.ts
  packages/db-postgres/src/createGlobal.ts
  packages/db-postgres/src/createGlobalVersion.ts
  packages/db-postgres/src/createVersion.ts
  packages/db-postgres/src/deleteMany.ts
  packages/db-postgres/src/deleteOne.ts
  packages/db-postgres/src/deleteVersions.ts
  packages/db-postgres/src/find/findMany.ts
  packages/db-postgres/src/predefinedMigrations/v2-v3/index.ts
  packages/db-postgres/src/queryDrafts.ts
  packages/db-postgres/src/transactions/commitTransaction.ts
  packages/db-postgres/src/transactions/rollbackTransaction.ts
  packages/db-postgres/src/update.ts
  packages/db-postgres/src/updateGlobal.ts
  packages/db-postgres/src/updateGlobalVersion.ts
  packages/db-postgres/src/updateVersion.ts
  packages/graphql/src/resolvers/collections/find.ts
  packages/payload/src/collections/dataloader.ts
  packages/payload/src/database/types.ts
  packages/payload/src/types/index.ts
  packages/payload/src/utilities/initTransaction.ts
  packages/payload/src/utilities/isolateObjectProperty.ts
  packages/payload/src/utilities/killTransaction.ts
  packages/richtext-lexical/src/features/link/plugins/autoLink/index.tsx
  packages/ui/src/elements/WhereBuilder/reduceFieldMap.tsx
  test/dataloader/config.ts
  test/dataloader/int.spec.ts
Labels: created-by: Contributor

#7065 docs: rewrites fields overview doc
  docs/admin/components.mdx
  docs/admin/fields.mdx
  docs/admin/overview.mdx
  docs/admin/views.mdx
  docs/fields/overview.mdx
Labels: created-by: Payload team

#7068 docs: cleans up live preview overview
  docs/live-preview/client.mdx
  docs/live-preview/overview.mdx
Labels: created-by: Payload team

#7070 fix!: exports getSiblingData, getDataByPath, and reduceFieldsToValues from payload
  docs/admin/hooks.mdx
  packages/next/src/views/Document/getDocumentData.tsx
  packages/next/src/views/LivePreview/Preview/index.tsx
  packages/payload/src/exports/shared.ts
  packages/payload/src/utilities/getDataByPath.ts
  packages/payload/src/utilities/getSiblingData.ts
  packages/payload/src/utilities/reduceFieldsToValues.ts
  packages/payload/src/utilities/unflatten.ts
  packages/richtext-lexical/src/features/blocks/component/FormSavePlugin.tsx
  packages/richtext-slate/src/field/elements/link/Button/index.tsx
  packages/richtext-slate/src/field/elements/link/Element/index.tsx
  packages/ui/package.json
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/utilities/buildFormState.ts
  packages/ui/src/utilities/reduceFieldsToValuesWithValidation.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#7072 feat(richtext-lexical): remove unused json-schema dependency
  packages/payload/package.json
  packages/richtext-lexical/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#7074 fix(ui): tooltips for fields rendered outside RenderFields not positioned correctly
  packages/ui/src/forms/RenderFields/index.scss
Labels: created-by: Payload team

#6966 feat: replace qs with qs-esm
  docs/queries/overview.mdx
  package.json
  packages/next/package.json
  packages/next/src/utilities/createPayloadRequest.ts
  packages/next/src/utilities/initPage/handleAuthRedirect.ts
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/meta.ts
  packages/next/src/views/Version/SelectComparison/index.tsx
  packages/richtext-lexical/bundle.js
  packages/richtext-lexical/package.json
  packages/ui/bundle.js
  packages/ui/package.json
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/elements/SortComplex/index.tsx
  packages/ui/src/elements/Table/RelationshipProvider/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/hooks/usePayloadAPI.ts
  packages/ui/src/providers/Auth/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/ListQuery/index.tsx
  packages/ui/src/providers/SearchParams/index.tsx
  packages/ui/src/providers/Selection/index.tsx
  packages/ui/src/utilities/api.ts
  pnpm-lock.yaml
  test/admin/e2e/2/e2e.spec.ts
  test/buildConfigWithDefaults.ts
  test/helpers/NextRESTClient.ts
  test/helpers/rest.ts
  test/live-preview/app/live-preview/_components/CollectionArchive/PopulateByCollection/index.tsx
  test/package.json
Labels: created-by: Payload team

#7088 chore(templates): update website template's seed script with content
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/app/blocks/Banner/index.tsx
  templates/website/src/app/blocks/Content/index.tsx
  templates/website/src/app/blocks/Form/index.tsx
  templates/website/src/app/blocks/RelatedPosts/index.tsx
  templates/website/src/app/components/Card/index.tsx
  templates/website/src/app/utilities/generateMeta.ts
  templates/website/src/payload.config.ts
  templates/website/src/payload/components/BeforeLogin/index.scss
  templates/website/src/payload/components/BeforeLogin/index.tsx
  templates/website/src/payload/seed/contact-form.ts
  templates/website/src/payload/seed/contact-page.ts
  templates/website/src/payload/seed/home.ts
  templates/website/src/payload/seed/index.ts
  templates/website/src/payload/seed/post-1.ts
  templates/website/src/payload/seed/post-2.ts
  templates/website/src/payload/seed/post-3.ts
Labels: created-by: Contributor

#7090 docs: improves configuration docs
  docs/access-control/collections.mdx
  docs/admin/environment-vars.mdx
  docs/admin/fields.mdx
  docs/admin/overview.mdx
  docs/authentication/api-keys.mdx
  docs/authentication/operations.mdx
  docs/authentication/overview.mdx
  docs/cloud/configuration.mdx
  docs/cloud/projects.mdx
  docs/configuration/collections.mdx
  docs/configuration/environment-vars.mdx
  docs/configuration/globals.mdx
  docs/configuration/i18n.mdx
  docs/configuration/overview.mdx
  docs/fields/array.mdx
  docs/fields/blocks.mdx
  docs/fields/checkbox.mdx
  docs/fields/code.mdx
  docs/fields/collapsible.mdx
  docs/fields/date.mdx
  docs/fields/email.mdx
  docs/fields/group.mdx
  docs/fields/json.mdx
  docs/fields/number.mdx
  docs/fields/point.mdx
  docs/fields/radio.mdx
  docs/fields/relationship.mdx
  docs/fields/rich-text.mdx
  docs/fields/row.mdx
  docs/fields/select.mdx
  docs/fields/tabs.mdx
  docs/fields/text.mdx
  docs/fields/textarea.mdx
  docs/fields/ui.mdx
  docs/fields/upload.mdx
  docs/live-preview/server.mdx
  docs/rich-text/slate.mdx
  docs/upload/overview.mdx
Labels: created-by: Payload team

#7089 chore: revert changed localization test suite
  packages/payload/src/admin/components/utilities/Locale/index.tsx
  test/localization/config.ts
Labels: created-by: Payload team

#7079 feat(cpa): add website template to CPA
  packages/create-payload-app/src/lib/templates.ts
  packages/create-payload-app/src/lib/write-env-file.ts
Labels: created-by: Contributor

#7094 chore: update all plugin docs installation and import steps
  docs/plugins/form-builder.mdx
  docs/plugins/nested-docs.mdx
  docs/plugins/redirects.mdx
  docs/plugins/search.mdx
  docs/plugins/sentry.mdx
  docs/plugins/seo.mdx
  docs/plugins/stripe.mdx
Labels: created-by: Contributor

#7095 feat(plugin-search)!: make search collection fields override into a function that provides defaultFields inline with other plugins
  docs/plugins/search.mdx
  packages/plugin-search/src/Search/index.ts
  packages/plugin-search/src/types.ts
  test/plugin-search/config.ts
Labels: created-by: Contributor

#7097 fix(richtext-lexical): export types as type-only exports
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/nodeTypes.ts
Labels: created-by: Payload team

#7063 feat: adds ability to upload files from a remote url
  docs/upload/overview.mdx
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/getBaseFields.ts
  packages/payload/src/uploads/types.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/Dropzone/index.tsx
  packages/ui/src/elements/Upload/index.scss
  packages/ui/src/elements/Upload/index.tsx
  templates/website/src/payload.config.ts
  test/fields/collections/Upload/e2e.spec.ts
  test/fields/collections/Upload/index.ts
Labels: created-by: Contributor

#7105 docs: cleans up configuration
  docs/configuration/collections.mdx
  docs/configuration/globals.mdx
  docs/configuration/overview.mdx
Labels: created-by: Payload team

#7098 chore(templates): update website template to use transactions for seeding
  templates/website/.env.example
  templates/website/next.config.js
  templates/website/src/app/components/Blocks/index.tsx
  templates/website/src/app/components/Media/Image/index.tsx
  templates/website/src/app/providers/HeaderTheme/index.tsx
  templates/website/src/payload/endpoints/seed.ts
  templates/website/src/payload/seed/index.ts
  templates/website/src/payload/seed/post-3.ts
Labels: created-by: Contributor

#7112 chore: eslint ignore templates
  eslint.config.js
  templates/website/.eslintrc.cjs
Labels: created-by: Contributor

#7111 chore: example of multi tenant using a single domain
  examples/multi-tenant-single-domain/.env.example
  examples/multi-tenant-single-domain/.eslintrc.cjs
  examples/multi-tenant-single-domain/.gitignore
  examples/multi-tenant-single-domain/.swcrc
  examples/multi-tenant-single-domain/README.md
  examples/multi-tenant-single-domain/next-env.d.ts
  examples/multi-tenant-single-domain/package.json
  examples/multi-tenant-single-domain/scripts/seed.ts
  examples/multi-tenant-single-domain/src/app/(app)/[tenant]/[...slug]/page.tsx
  examples/multi-tenant-single-domain/src/app/(app)/[tenant]/login/page.tsx
  examples/multi-tenant-single-domain/src/app/(app)/[tenant]/page.tsx
  examples/multi-tenant-single-domain/src/app/(app)/index.scss
  examples/multi-tenant-single-domain/src/app/(app)/layout.tsx
  examples/multi-tenant-single-domain/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  examples/multi-tenant-single-domain/src/app/(payload)/admin/[[...segments]]/page.tsx
  examples/multi-tenant-single-domain/src/app/(payload)/api/[...slug]/route.ts
  examples/multi-tenant-single-domain/src/app/(payload)/api/graphql-playground/route.ts
  examples/multi-tenant-single-domain/src/app/(payload)/api/graphql/route.ts
  examples/multi-tenant-single-domain/src/app/(payload)/custom.scss
  examples/multi-tenant-single-domain/src/app/(payload)/layout.tsx
  examples/multi-tenant-single-domain/src/app/components/Login/client.page.tsx
  examples/multi-tenant-single-domain/src/app/components/Login/index.scss
  examples/multi-tenant-single-domain/src/app/components/RenderPage/index.tsx
  examples/multi-tenant-single-domain/src/cms/access/isSuperAdmin.ts
  examples/multi-tenant-single-domain/src/cms/collections/Pages/access/byTenant.ts
  examples/multi-tenant-single-domain/src/cms/collections/Pages/access/externalReadAccess.ts
  examples/multi-tenant-single-domain/src/cms/collections/Pages/hooks/ensureUniqueSlug.ts
  examples/multi-tenant-single-domain/src/cms/collections/Pages/index.ts
  examples/multi-tenant-single-domain/src/cms/collections/Tenants/access/read.ts
  examples/multi-tenant-single-domain/src/cms/collections/Tenants/index.ts
  examples/multi-tenant-single-domain/src/cms/collections/Users/access/isAccessingSelf.ts
  examples/multi-tenant-single-domain/src/cms/collections/Users/access/isSuperAdminOrSelf.ts
  examples/multi-tenant-single-domain/src/cms/collections/Users/endpoints/externalUsersLogin.ts
  examples/multi-tenant-single-domain/src/cms/collections/Users/hooks/ensureUniqueUsername.ts
  examples/multi-tenant-single-domain/src/cms/collections/Users/index.ts
  examples/multi-tenant-single-domain/src/cms/components/TenantSelector/index.client.tsx
  examples/multi-tenant-single-domain/src/cms/components/TenantSelector/index.scss
  examples/multi-tenant-single-domain/src/cms/components/TenantSelector/index.tsx
  examples/multi-tenant-single-domain/src/cms/fields/TenantField/access/update.ts
  examples/multi-tenant-single-domain/src/cms/fields/TenantField/components/Field.tsx
  examples/multi-tenant-single-domain/src/cms/fields/TenantField/hooks/autofillTenant.ts
  examples/multi-tenant-single-domain/src/cms/fields/TenantField/index.ts
  examples/multi-tenant-single-domain/src/cms/mocks/emptyObject.js
  examples/multi-tenant-single-domain/src/cms/utilities/getTenantAccessIDs.ts
  examples/multi-tenant-single-domain/src/cms/utilities/isPayloadAdminPanel.ts
  examples/multi-tenant-single-domain/src/cms/utilities/parseCookies.ts
  examples/multi-tenant-single-domain/src/payload-types.ts
  examples/multi-tenant-single-domain/src/payload.config.ts
  examples/multi-tenant-single-domain/tsconfig.json
  examples/multi-tenant-single-domain/yarn.lock
Labels: created-by: Contributor

#7106 feat!: upgrade minimum react, react-dom, @types/react and @types/react-dom versions to match exactly what Next.js is using, various dependency cleanup
  jest.config.js
  package.json
  packages/db-postgres/package.json
  packages/live-preview-react/package.json
  packages/next/bundleScss.js
  packages/next/package.json
  packages/next/src/esbuildEntry.ts
  packages/next/webpack.config.js
  packages/payload/package.json
  packages/plugin-form-builder/package.json
  packages/plugin-redirects/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-seo/package.json
  packages/plugin-stripe/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/translations/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  scripts/delete-recursively.js
  templates/_template/package.json
  templates/blank-3.0/package.json
  templates/blank/package.json
  templates/website/pnpm-lock.yaml
  templates/with-payload-cloud/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  test/package.json
  test/runE2E.ts
Labels: created-by: Payload team

#7116 chore: lint templates
  package.json
  templates/website/.eslintrc.cjs
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(frontend)/layout.tsx
  templates/website/src/app/components/LivePreviewListener/index.tsx
  templates/website/src/app/components/Media/ImageMedia/index.tsx
  templates/website/src/app/components/Media/VideoMedia/index.tsx
  templates/website/src/app/components/Media/index.tsx
  templates/website/src/app/components/RichText/nodeFormat.tsx
  templates/website/src/app/cssVariables.js
  templates/website/src/app/next/exit-preview/GET.ts
  templates/website/src/app/next/exit-preview/route.ts
  templates/website/src/app/next/preview/route.ts
  templates/website/src/app/utilities/generateMeta.ts
Labels: created-by: Contributor

#7118 fix(templates): website template gitignore issue for case sensitivity
  package.json
  templates/website/.gitignore
  templates/website/pnpm-lock.yaml
Labels: created-by: Contributor

#7120 fix(ui): ctrl+s not triggering a save if autosave is enabled
  packages/ui/src/elements/PublishButton/index.tsx
Labels: created-by: Contributor

#7122 docs: improves queries docs
  docs/configuration/collections.mdx
  docs/configuration/globals.mdx
  docs/configuration/overview.mdx
  docs/fields/relationship.mdx
  docs/fields/upload.mdx
  docs/getting-started/concepts.mdx
  docs/live-preview/client.mdx
  docs/local-api/overview.mdx
  docs/queries/depth.mdx
  docs/queries/overview.mdx
  docs/queries/pagination.mdx
  docs/queries/sort.mdx
  docs/rest-api/overview.mdx
Labels: created-by: Payload team

#7087 feat: adds ability to upload files from a remote url
  packages/payload/src/admin/components/elements/Dropzone/index.tsx
  packages/payload/src/admin/components/elements/EditUpload/index.tsx
  packages/payload/src/admin/components/utilities/UploadEdits/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/Upload/index.scss
  packages/payload/src/admin/components/views/collections/Edit/Upload/index.tsx
  packages/payload/src/translations/ar.json
  packages/payload/src/translations/az.json
  packages/payload/src/translations/bg.json
  packages/payload/src/translations/cs.json
  packages/payload/src/translations/de.json
  packages/payload/src/translations/en.json
  packages/payload/src/translations/es.json
  packages/payload/src/translations/fa.json
  packages/payload/src/translations/fr.json
  packages/payload/src/translations/hr.json
  packages/payload/src/translations/hu.json
  packages/payload/src/translations/it.json
  packages/payload/src/translations/ja.json
  packages/payload/src/translations/ko.json
  packages/payload/src/translations/my.json
  packages/payload/src/translations/nb.json
  packages/payload/src/translations/nl.json
  packages/payload/src/translations/pl.json
  packages/payload/src/translations/pt.json
  packages/payload/src/translations/ro.json
  packages/payload/src/translations/rs-latin.json
  packages/payload/src/translations/rs.json
  packages/payload/src/translations/ru.json
  packages/payload/src/translations/sv.json
  packages/payload/src/translations/th.json
  packages/payload/src/translations/tr.json
  packages/payload/src/translations/translation-schema.json
  packages/payload/src/translations/ua.json
  packages/payload/src/translations/vi.json
  packages/payload/src/translations/zh-tw.json
  packages/payload/src/translations/zh.json
  packages/payload/src/uploads/generateFileData.ts
  test/fields/e2e.spec.ts
Labels: created-by: Payload team

#6661 feat(ui): updates version status UI to be more informative
  packages/next/src/views/Version/Default/SetStepNav.tsx
  packages/next/src/views/Version/Default/index.tsx
  packages/next/src/views/Version/Default/types.ts
  packages/next/src/views/Version/SelectComparison/index.tsx
  packages/next/src/views/Version/SelectComparison/types.ts
  packages/next/src/views/Version/index.tsx
  packages/next/src/views/Version/shared.ts
  packages/next/src/views/Versions/buildColumns.tsx
  packages/next/src/views/Versions/cells/AutosaveCell/index.tsx
  packages/next/src/views/Versions/getLatestVersion.ts
  packages/next/src/views/Versions/index.tsx
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
Labels: created-by: Payload team

#7132 feat(richtext-lexical): lexical type improvements
  packages/richtext-lexical/src/features/blocks/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/nodeTypes.ts
Labels: created-by: Payload team

#7129 feat: suppress email adapter warning on build
  packages/payload/src/index.ts
Labels: created-by: Payload team

#7133 docs: improves hooks docs
  docs/access-control/fields.mdx
  docs/access-control/globals.mdx
  docs/admin/views.mdx
  docs/configuration/collections.mdx
  docs/configuration/globals.mdx
  docs/fields/overview.mdx
  docs/getting-started/concepts.mdx
  docs/getting-started/installation.mdx
  docs/getting-started/what-is-payload.mdx
  docs/hooks/collections.mdx
  docs/hooks/context.mdx
  docs/hooks/fields.mdx
  docs/hooks/globals.mdx
  docs/hooks/overview.mdx
  docs/live-preview/client.mdx
  docs/live-preview/overview.mdx
  docs/live-preview/server.mdx
  docs/queries/depth.mdx
  docs/queries/sort.mdx
Labels: created-by: Payload team

#7130 feat: validate field names for reserved names
  docs/fields/overview.mdx
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/errors/ReservedFieldName.ts
  packages/payload/src/errors/index.ts
  packages/payload/src/fields/config/sanitize.spec.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/globals/config/sanitize.ts
Labels: created-by: Contributor

#7135 chore(templates): improve website template lexical types
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/app/blocks/Code/index.tsx
  templates/website/src/app/components/RichText/index.tsx
  templates/website/src/app/components/RichText/nodeFormat.tsx
  templates/website/src/app/components/RichText/serialize.tsx
Labels: created-by: Payload team

#7147 chore(docs): minor change to uploads overview
  docs/upload/overview.mdx
Labels: created-by: Payload team

#7148 fix: custom tabs not working in globals
  packages/next/src/views/Document/getViewsFromConfig.tsx
  test/admin/components/CustomTabComponent/client.tsx
  test/admin/e2e/1/e2e.spec.ts
Labels: created-by: Contributor

#7152 chore(eslint): add missing recommended config for eslint-plugin-react-hooks
  packages/eslint-config/configs/react/index.mjs
Labels: created-by: Payload team

#7154 docs: improves access control docs
  docs/access-control/collections.mdx
  docs/access-control/fields.mdx
  docs/access-control/globals.mdx
  docs/access-control/overview.mdx
  docs/admin/overview.mdx
  docs/authentication/api-keys.mdx
  docs/authentication/http-only-cookies.mdx
  docs/authentication/jwt.mdx
  docs/authentication/operations.mdx
  docs/authentication/token-data.mdx
  docs/configuration/collections.mdx
  docs/configuration/environment-vars.mdx
  docs/configuration/globals.mdx
  docs/fields/array.mdx
  docs/fields/blocks.mdx
  docs/fields/checkbox.mdx
  docs/fields/code.mdx
  docs/fields/date.mdx
  docs/fields/email.mdx
  docs/fields/group.mdx
  docs/fields/json.mdx
  docs/fields/number.mdx
  docs/fields/overview.mdx
  docs/fields/point.mdx
  docs/fields/radio.mdx
  docs/fields/relationship.mdx
  docs/fields/rich-text.mdx
  docs/fields/select.mdx
  docs/fields/text.mdx
  docs/fields/textarea.mdx
  docs/fields/upload.mdx
  docs/getting-started/concepts.mdx
  docs/hooks/collections.mdx
  docs/hooks/context.mdx
  docs/hooks/fields.mdx
  docs/hooks/globals.mdx
  docs/hooks/overview.mdx
  docs/local-api/overview.mdx
  docs/plugins/stripe.mdx
  docs/rest-api/overview.mdx
  docs/typescript/generating-types.mdx
  docs/typescript/overview.mdx
  docs/upload/storage-adapters.mdx
  docs/versions/drafts.mdx
  docs/versions/overview.mdx
Labels: created-by: Payload team

#7153 fix(richtext-*): migration and field recursion issues
  packages/richtext-lexical/src/utilities/migrateSlateToLexical/migrateDocumentFieldsRecursively.ts
  packages/richtext-lexical/src/utilities/upgradeLexicalData/upgradeDocumentFieldsRecursively.ts
  packages/richtext-slate/src/data/recurseNestedFields.ts
Labels: created-by: Payload team

#7155 fix(richtext-lexical): newly created upload nodes with extra fields do not display fields when opening extra fields drawer
  packages/richtext-lexical/src/features/experimental_table/plugins/TablePlugin/index.tsx
  packages/richtext-lexical/src/features/link/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/Drawer.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/DrawerContent.tsx
Labels: created-by: Payload team

#7156 chore(richtext-lexical): add e2e test which reproduces #7128
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#7157 feat(next): strongly type getNextRequestI18n
  packages/next/src/utilities/getNextRequestI18n.ts
  packages/next/src/views/NotFound/meta.ts
  packages/next/src/views/Root/index.tsx
Labels: created-by: Payload team

#7160 docs: root hooks
  docs/access-control/overview.mdx
  docs/admin/overview.mdx
  docs/configuration/overview.mdx
  docs/getting-started/concepts.mdx
  docs/getting-started/installation.mdx
  docs/hooks/overview.mdx
Labels: created-by: Payload team

#7159 chore: run esbuild scripts in sync, hopefully fixing publishing issues
  packages/db-postgres/bundle.js
  packages/next/bundleScss.js
  packages/payload/bundle.js
  packages/richtext-lexical/bundle.js
  packages/ui/bundle.js
Labels: created-by: Payload team

#7165 chore(examples): updates to multi tenant single domain example
  examples/multi-tenant-single-domain/scripts/seed.ts
  examples/multi-tenant-single-domain/src/cms/collections/Users/access/read.ts
  examples/multi-tenant-single-domain/src/cms/collections/Users/index.ts
Labels: created-by: Contributor

#7170 chore(richtext-lexical): adjust error message when loading the editor on unmigrated data
  packages/richtext-lexical/src/lexical/LexicalProvider.tsx
Labels: created-by: Payload team

#7168 docs: moves collection and global admin options to admin docs
  docs/access-control/collections.mdx
  docs/admin/collections.mdx
  docs/admin/components.mdx
  docs/admin/customizing-css.mdx
  docs/admin/fields.mdx
  docs/admin/globals.mdx
  docs/admin/hooks.mdx
  docs/admin/overview.mdx
  docs/admin/preferences.mdx
  docs/admin/views.mdx
  docs/configuration/collections.mdx
  docs/configuration/globals.mdx
Labels: created-by: Payload team

#7099 chore: allows mongoose strict to be configured
  .vscode/settings.json
  docs/database/mongodb.mdx
  packages/db-mongodb/package.json
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/init.ts
  packages/db-mongodb/src/models/buildCollectionSchema.ts
  packages/db-mongodb/src/models/buildGlobalModel.ts
  packages/db-mongodb/src/models/buildSchema.ts
  packages/db-mongodb/src/updateGlobal.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/fields/hooks/beforeValidate/traverseFields.ts
  pnpm-lock.yaml
  test/auth/config.ts
  test/auth/int.spec.ts
  test/collections-graphql/media/test-image.jpg
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
  test/fields/int.spec.ts
  test/plugin-search/int.spec.ts
  test/plugin-stripe/webhooks/subscriptionCreatedOrUpdated.ts
  test/relationships/int.spec.ts
  test/uploads/focal-only/focal-1-400x300.png
  test/uploads/focal-only/focal-1-600x300.png
  test/uploads/focal-only/focal-1-900x300.png
  test/uploads/focal-only/focal-1.png
  test/uploads/focal-only/focal-400x300.png
  test/uploads/focal-only/focal-600x300.png
  test/uploads/focal-only/focal-900x300.png
  test/uploads/focal-only/focal.png
Labels: created-by: Payload team

#7178 fix: localised relationship fields
  packages/next/src/utilities/createPayloadRequest.ts
  test/localization/e2e.spec.ts
Labels: created-by: Contributor

#7180 fix: version comparison view showing empty localized fields
  packages/next/src/views/Version/Default/index.tsx
Labels: created-by: Payload team

#7181 fix(ui): date field background color specificity
  packages/ui/src/elements/DatePicker/index.scss
Labels: created-by: Payload team

#7184 fix: webpack error if dbName or enumName is set
  packages/payload/src/fields/config/client.ts
Labels: created-by: Payload team

#7185 fix(richtext-lexical): slash menu keyboard navigation not triggering auto-scroll
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/LexicalMenu.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/index.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/types.ts
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/index.tsx
Labels: created-by: Payload team

#7139 chore(templates): clean up templates dependencies
  templates/_template/package.json
  templates/blank/package.json
  templates/website/.gitignore
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/app/blocks/RelatedPosts/index.tsx
  templates/website/src/payload-types.ts
  templates/website/src/payload.config.ts
  templates/website/src/payload/collections/Categories.ts
  templates/website/src/payload/collections/Media.ts
  templates/website/src/payload/collections/Pages/index.ts
  templates/website/src/payload/collections/Posts/hooks/populateAuthors.ts
  templates/website/src/payload/collections/Posts/index.ts
  templates/website/src/payload/components/BeforeDashboard/SeedButton/index.tsx
  templates/website/src/payload/components/BeforeDashboard/index.tsx
  templates/website/src/payload/endpoints/seed.ts
  templates/website/src/payload/seed/contact-page.ts
  templates/website/src/payload/seed/home-static.ts
  templates/website/src/payload/seed/home.ts
  templates/website/src/payload/seed/index.ts
  templates/website/src/payload/seed/post-1.ts
  templates/website/src/payload/seed/post-2.ts
  templates/website/src/payload/seed/post-3.ts
  templates/website/tsconfig.json
  templates/with-payload-cloud/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
Labels: created-by: Payload team

#7195 docs: improves authentication docs
  CONTRIBUTING.md
  docs/access-control/collections.mdx
  docs/admin/fields.mdx
  docs/admin/overview.mdx
  docs/authentication/config.mdx
  docs/authentication/cookies.mdx
  docs/authentication/custom-strategies.mdx
  docs/authentication/email.mdx
  docs/authentication/jwt.mdx
  docs/authentication/operations.mdx
  docs/authentication/overview.mdx
  docs/cloud/projects.mdx
  docs/configuration/collections.mdx
  docs/email/overview.mdx
  docs/fields/array.mdx
  docs/fields/blocks.mdx
  docs/fields/checkbox.mdx
  docs/fields/code.mdx
  docs/fields/date.mdx
  docs/fields/email.mdx
  docs/fields/group.mdx
  docs/fields/json.mdx
  docs/fields/number.mdx
  docs/fields/point.mdx
  docs/fields/radio.mdx
  docs/fields/relationship.mdx
  docs/fields/rich-text.mdx
  docs/fields/select.mdx
  docs/fields/text.mdx
  docs/fields/textarea.mdx
  docs/fields/upload.mdx
  docs/getting-started/concepts.mdx
  docs/hooks/collections.mdx
  docs/hooks/fields.mdx
  docs/hooks/globals.mdx
  docs/hooks/overview.mdx
  docs/production/deployment.mdx
  docs/production/preventing-abuse.mdx
  docs/typescript/generating-types.mdx
  examples/auth/payload/README.md
  examples/draft-preview/payload/README.md
Labels: created-by: Payload team

#7169 fix(ui): search queries remain between navigation
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/elements/SearchFilter/index.tsx
  test/admin/e2e/2/e2e.spec.ts
Labels: created-by: Contributor

#7182 fix: maxListenersExceeded warning due to atomically, which is a peerdep of conf
  packages/next/src/utilities/getPayloadHMR.ts
  packages/payload/bundle.js
  packages/payload/package.json
  packages/payload/src/utilities/telemetry/conf/envPaths.ts
  packages/payload/src/utilities/telemetry/conf/index.ts
  packages/payload/src/utilities/telemetry/index.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#7198 fix(templates): bad import in website seed script
  templates/website/src/payload/seed/index.ts
Labels: created-by: Contributor

#7213 fix: cherry picks lockUntil fix from #6052
  packages/payload/src/auth/isLocked.ts
  packages/payload/src/auth/operations/login.ts
  test/auth/int.spec.ts
Labels: created-by: Contributor

#7217 fix: exports fallback hook types to ensure backwards compatibility
  packages/payload/src/exports/types.ts
Labels: created-by: Payload team

#7215 chore: use href for locale switching, warns user before leaving
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/elements/Localizer/index.tsx
  test/helpers.ts
Labels: created-by: Contributor

#7117 fix(ui): uploading from drawer & focal point positioning
  docs/migration-guide/overview.mdx
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/Edit/Default/index.tsx
  packages/payload/src/uploads/cropImage.ts
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/imageResizer.ts
  packages/payload/src/uploads/types.ts
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/elements/EditUpload/index.tsx
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/FormQueryParams/index.tsx
  packages/ui/src/providers/FormQueryParams/types.ts
  packages/ui/src/providers/UploadEdits/index.tsx
  packages/ui/src/utilities/buildFormState.ts
  test/fields/collections/Upload/e2e.spec.ts
  test/uploads/e2e.spec.ts
  test/uploads/horizontal-squares.jpg
Labels: created-by: Contributor

#7218 chore: ensure fs operations in bundle scripts finish in sync
  packages/next/bundleScss.js
  packages/richtext-lexical/bundle.js
  packages/ui/bundle.js
  scripts/delete-recursively.js
Labels: created-by: Payload team

#7219 chore(templates): add react cache to queryPostBySlug in website template
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
Labels: created-by: Contributor

#7237 chore(docs): update rest API handler to async
  docs/rest-api/overview.mdx
Labels: created-by: Contributor

#7232 fix: api errors not populating in prod
  packages/next/src/routes/rest/routeError.ts
  packages/payload/src/errors/APIError.ts
  packages/payload/src/errors/ValidationError.ts
  packages/payload/src/errors/index.ts
  packages/payload/src/index.ts
Labels: created-by: Payload team

#7235 feat: update reserved fields name check to be more comprehensive and only check top level fields
  packages/payload/src/collections/config/reservedFieldNames.spec.ts
  packages/payload/src/collections/config/reservedFieldNames.ts
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/fields/config/sanitize.spec.ts
  packages/payload/src/fields/config/sanitize.ts
Labels: created-by: Contributor

#7231 chore(translations, ui): updates `addImage` translation to `addFile` translation
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/Upload/index.tsx
  test/fields/collections/Upload/e2e.spec.ts
Labels: created-by: Contributor

#7244 fix: uploads from drawer and focal point positioning
  packages/payload/src/admin/components/elements/EditUpload/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/Upload/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/types.ts
  packages/payload/src/translations/ar.json
  packages/payload/src/translations/az.json
  packages/payload/src/translations/bg.json
  packages/payload/src/translations/cs.json
  packages/payload/src/translations/de.json
  packages/payload/src/translations/en.json
  packages/payload/src/translations/es.json
  packages/payload/src/translations/fa.json
  packages/payload/src/translations/fr.json
  packages/payload/src/translations/hr.json
  packages/payload/src/translations/hu.json
  packages/payload/src/translations/it.json
  packages/payload/src/translations/ja.json
  packages/payload/src/translations/ko.json
  packages/payload/src/translations/my.json
  packages/payload/src/translations/nb.json
  packages/payload/src/translations/nl.json
  packages/payload/src/translations/pl.json
  packages/payload/src/translations/pt.json
  packages/payload/src/translations/ro.json
  packages/payload/src/translations/rs-latin.json
  packages/payload/src/translations/rs.json
  packages/payload/src/translations/ru.json
  packages/payload/src/translations/sv.json
  packages/payload/src/translations/th.json
  packages/payload/src/translations/tr.json
  packages/payload/src/translations/translation-schema.json
  packages/payload/src/translations/ua.json
  packages/payload/src/translations/vi.json
  packages/payload/src/translations/zh-tw.json
  packages/payload/src/translations/zh.json
  packages/payload/src/uploads/cropImage.ts
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/imageResizer.ts
  packages/payload/src/uploads/types.ts
  test/fields/e2e.spec.ts
  test/uploads/e2e.spec.ts
  test/uploads/horizontal-squares.jpg
Labels: created-by: Payload team

#7224 feat!: new server-only, faster and immediate autoLogin
  docs/admin/overview.mdx
  docs/authentication/overview.mdx
  docs/configuration/overview.mdx
  packages/next/src/views/Login/LoginForm/index.tsx
  packages/next/src/views/Login/index.tsx
  packages/payload/src/auth/strategies/jwt.ts
  packages/payload/src/config/client.ts
  packages/payload/src/config/types.ts
  packages/ui/src/providers/Auth/index.tsx
  test/_community/e2e.spec.ts
  test/_community/payload-types.ts
  test/access-control/e2e.spec.ts
  test/admin/e2e/1/e2e.spec.ts
  test/admin/e2e/2/e2e.spec.ts
  test/admin/payload-types.ts
  test/auth/e2e.spec.ts
  test/buildConfigWithDefaults.ts
  test/field-error-states/e2e.spec.ts
  test/fields-relationship/e2e.spec.ts
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Date/e2e.spec.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/collections/Number/e2e.spec.ts
  test/fields/collections/Point/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/collections/RichText/e2e.spec.ts
  test/fields/collections/Tabs/e2e.spec.ts
  test/fields/collections/Text/e2e.spec.ts
  test/fields/collections/Upload/e2e.spec.ts
  test/fields/e2e.spec.ts
  test/fields/payload-types.ts
  test/helpers.ts
  test/helpers/NextRESTClient.ts
  test/i18n/e2e.spec.ts
  test/live-preview/e2e.spec.ts
  test/localization/e2e.spec.ts
  test/package.json
  test/plugin-cloud-storage/e2e.spec.ts
  test/plugin-form-builder/e2e.spec.ts
  test/plugin-nested-docs/e2e.spec.ts
  test/plugin-seo/e2e.spec.ts
  test/uploads/e2e.spec.ts
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#7268 chore: add custom ID warning about forbidden characters
  docs/fields/overview.mdx
Labels: created-by: Contributor

#7277 fix(payload): resizes images first before applying focal point
  packages/payload/src/uploads/imageResizer.ts
Labels: created-by: Contributor

#7278 fix: resizes images first before applying focal point
  packages/payload/src/uploads/imageResizer.ts
Labels: created-by: Payload team

#7197 chore: windows compatible file path handling ui bundle script
  packages/ui/bundle.js
Labels: created-by: Contributor

#6257 chore: index version status v3
  packages/payload/src/versions/baseFields.ts
Labels: created-by: Payload team

#7226 feat: remove joi schema validation
  packages/payload/bundle.js
  packages/payload/package.json
  packages/payload/src/collections/config/schema.ts
  packages/payload/src/config/schema.ts
  packages/payload/src/config/shared/adminViewSchema.ts
  packages/payload/src/config/shared/componentSchema.ts
  packages/payload/src/config/shared/openGraphSchema.ts
  packages/payload/src/config/validate.ts
  packages/payload/src/fields/config/schema.ts
  packages/payload/src/globals/config/schema.ts
  packages/payload/src/index.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#7245 fix(ui): not updating permissions when locale changes
  packages/ui/src/providers/DocumentInfo/index.tsx
Labels: created-by: Contributor

#7283 chore: ensure the correct next & react versions are installed in templates and core
  packages/payload/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank-3.0/package.json
  templates/blank/package.json
  templates/vercel-postgres/package.json
  templates/vercel-postgres/pnpm-lock.yaml
  templates/vercel-postgres/src/collections/Media.ts
  templates/vercel-postgres/src/collections/Users.ts
  templates/vercel-postgres/src/payload.config.ts
  templates/with-payload-cloud/package.json
  templates/with-payload-cloud/pnpm-lock.yaml
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
Labels: created-by: Payload team

#7291 feat: upgrade pino and pino-pretty, clean up hacky esm imports
  packages/payload/package.json
  packages/payload/src/bin/generateTypes.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/logger.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#7292 fix: search plugin localized fields
  packages/plugin-search/src/Search/hooks/syncWithSearch.ts
  packages/plugin-search/src/index.ts
  test/plugin-search/collections/Posts.ts
  test/plugin-search/config.ts
  test/plugin-search/int.spec.ts
  test/plugin-search/payload-types.ts
Labels: created-by: Contributor

#6923 fix(db-mongodb): removes precedence of regular chars over international chars in sort
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/queryDrafts.ts
  test/localization/config.ts
  test/localization/int.spec.ts
  test/localization/shared.ts
Labels: created-by: Payload team

#7297 fix(cpa): check cmd exists after first checking flag and lock file
  packages/create-payload-app/src/lib/get-package-manager.ts
Labels: created-by: Payload team

#7202 docs: cleanup to individual field docs
  docs/fields/array.mdx
  docs/fields/blocks.mdx
  docs/fields/checkbox.mdx
  docs/fields/code.mdx
  docs/fields/collapsible.mdx
  docs/fields/date.mdx
  docs/fields/email.mdx
  docs/fields/group.mdx
  docs/fields/json.mdx
  docs/fields/number.mdx
  docs/fields/point.mdx
  docs/fields/radio.mdx
  docs/fields/relationship.mdx
  docs/fields/rich-text.mdx
  docs/fields/row.mdx
  docs/fields/select.mdx
  docs/fields/tabs.mdx
  docs/fields/text.mdx
  docs/fields/textarea.mdx
  docs/fields/ui.mdx
  docs/fields/upload.mdx
  docs/getting-started/installation.mdx
  docs/getting-started/what-is-payload.mdx
Labels: created-by: Payload team

#7294 fix(db-mongodb): removes precedence of regular chars over international chars in sort
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/queryDrafts.ts
  test/localization/config.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
  test/localization/shared.ts
Labels: created-by: Contributor

#7314 fix: first version doc throws error
  packages/next/src/views/Version/index.tsx
Labels: created-by: Payload team

#7309 fix(ui): where query selectors for checkboxes are now translated
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
Labels: created-by: Contributor

#7316 fix(plugin-stripe): properly types async webhooks
  packages/plugin-stripe/src/types.ts
Labels: created-by: Payload team

#7317 fix(plugin-stripe): properly types async webhooks
  packages/eslint-config/index.mjs
  packages/plugin-stripe/src/types.ts
  test/plugin-stripe/webhooks/syncPriceJSON.ts
Labels: created-by: Payload team

#7322 fix(ui): email field now correctly renders autocomplete attribute
  packages/ui/src/providers/ComponentMap/buildComponentMap/fields.tsx
  test/fields/collections/Email/AfterInput.tsx
  test/fields/collections/Email/BeforeInput.tsx
  test/fields/collections/Email/CustomError.tsx
  test/fields/collections/Email/CustomLabel.tsx
  test/fields/collections/Email/e2e.spec.ts
  test/fields/collections/Email/index.ts
  test/fields/collections/Email/shared.ts
  test/fields/config.ts
  test/fields/payload-types.ts
  test/fields/seed.ts
  test/fields/slugs.ts
Labels: created-by: Contributor

#7311 fix: misc issues with loginWithUsername
  packages/graphql/src/schema/initCollections.ts
  packages/next/src/routes/rest/auth/login.ts
  packages/next/src/routes/rest/auth/unlock.ts
  packages/next/src/views/CreateFirstUser/index.client.tsx
  packages/next/src/views/CreateFirstUser/index.tsx
  packages/next/src/views/Edit/Default/Auth/index.tsx
  packages/next/src/views/Edit/Default/Auth/types.ts
  packages/next/src/views/Edit/Default/index.tsx
  packages/next/src/views/Login/LoginField/index.tsx
  packages/payload/src/auth/baseFields/email.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  packages/ui/src/elements/DocumentFields/index.tsx
  packages/ui/src/utilities/buildFormState.ts
Labels: created-by: Payload team

#7325 fix: allow autosave relationship drawers to function properly
  packages/payload/src/admin/components/elements/Autosave/index.tsx
  packages/payload/src/admin/components/elements/Autosave/types.ts
  packages/payload/src/admin/components/elements/DocumentControls/index.tsx
  packages/payload/src/admin/components/views/collections/Edit/Default/index.tsx
Labels: created-by: Payload team

#7328 feat: adds @payloadcms/live-preview-vue to release pipeline
  package.json
  packages/live-preview-react/package.json
  packages/live-preview-vue/package.json
  scripts/lib/publishList.ts
  tsconfig.json
Labels: created-by: Payload team

#7326 fix: some email adapters not working if they're promises due to config sanitisation
  packages/payload/src/config/sanitize.ts
Labels: created-by: Contributor

#7340 chore(live-preview): ensures dev points to src
  packages/live-preview-react/package.json
  packages/live-preview-vue/package.json
  packages/live-preview/package.json
  test/live-preview/next-app/tsconfig.json
Labels: created-by: Payload team

#7337 fix: fetches and sets permissions before setting user
  packages/payload/src/admin/components/utilities/Auth/index.tsx
  packages/payload/src/admin/components/utilities/Auth/types.ts
  packages/payload/src/admin/components/views/Logout/index.tsx
Labels: created-by: Payload team

#7338 feat: add jsonParse flag to mongooseAdapter that preserves existing, untracked MongoDB data types
  docs/database/mongodb.mdx
  packages/db-mongodb/src/create.ts
  packages/db-mongodb/src/createGlobal.ts
  packages/db-mongodb/src/createGlobalVersion.ts
  packages/db-mongodb/src/createVersion.ts
  packages/db-mongodb/src/deleteOne.ts
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobal.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findOne.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/queryDrafts.ts
  packages/db-mongodb/src/updateGlobal.ts
  packages/db-mongodb/src/updateGlobalVersion.ts
  packages/db-mongodb/src/updateOne.ts
  packages/db-mongodb/src/updateVersion.ts
  packages/db-mongodb/src/utilities/sanitizeInternalFields.ts
  packages/payload/src/fields/hooks/beforeChange/cloneDataFromOriginalDoc.ts
  packages/payload/src/fields/validations.ts
  test/collections-graphql/media/test-image-1.jpg
  test/collections-graphql/media/test-image-2.jpg
  test/collections-graphql/media/test-image-3.jpg
  test/database/config.ts
  test/database/int.spec.ts
  test/uploads/focal-only/focal-2-400x300.png
  test/uploads/focal-only/focal-2-600x300.png
  test/uploads/focal-only/focal-2-900x300.png
  test/uploads/focal-only/focal-2.png
  test/uploads/focal-only/focal-3-400x300.png
  test/uploads/focal-only/focal-3-600x300.png
  test/uploads/focal-only/focal-3-900x300.png
  test/uploads/focal-only/focal-3.png
  test/uploads/focal-only/focal-4-400x300.png
  test/uploads/focal-only/focal-4-600x300.png
  test/uploads/focal-only/focal-4-900x300.png
  test/uploads/focal-only/focal-4.png
  test/uploads/focal-only/focal-5-400x300.png
  test/uploads/focal-only/focal-5-600x300.png
  test/uploads/focal-only/focal-5-900x300.png
  test/uploads/focal-only/focal-5.png
  test/uploads/focal-only/focal-6-400x300.png
  test/uploads/focal-only/focal-6-600x300.png
  test/uploads/focal-only/focal-6-900x300.png
  test/uploads/focal-only/focal-6.png
  test/uploads/focal-only/focal-7-400x300.png
  test/uploads/focal-only/focal-7-600x300.png
  test/uploads/focal-only/focal-7-900x300.png
  test/uploads/focal-only/focal-7.png
Labels: created-by: Payload team

#7293 feat(payload): allows metadata to be appended to the file of the output media
  docs/upload/overview.mdx
  packages/payload/src/collections/config/client.ts
  packages/payload/src/uploads/cropImage.ts
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/imageResizer.ts
  packages/payload/src/uploads/optionallyAppendMetadata.ts
  packages/payload/src/uploads/types.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/shared.ts
Labels: created-by: Contributor

#7295 feat(payload): allows metadata to be appended to the file of the output media
  docs/upload/overview.mdx
  packages/payload/src/collections/config/schema.ts
  packages/payload/src/uploads/cropImage.ts
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/imageResizer.ts
  packages/payload/src/uploads/optionallyAppendMetadata.ts
  packages/payload/src/uploads/types.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#7344 fix: relaxes equality check for relationship options in filter
  packages/payload/src/admin/components/elements/WhereBuilder/Condition/Relationship/index.tsx
Labels: created-by: Payload team

#7343 fix: relaxes equality check for relationship options in filter
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
Labels: created-by: Contributor

#7345 fix: attempts to use query.locale when present in createLocalReq
  packages/next/src/utilities/initPage/index.ts
  packages/payload/src/utilities/createLocalReq.ts
Labels: created-by: Contributor

#7348 fix(ui): hide 'Create new' button entirely if user has no access to create a media item
  packages/eslint-config/configs/react/index.mjs
  packages/ui/src/fields/Upload/Input.tsx
  packages/ui/src/fields/Upload/index.tsx
Labels: created-by: Contributor

#7359 fix(db-mongodb): adds new optional `collation` feature flag behind mongodb collation option
  docs/database/mongodb.mdx
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/queryDrafts.ts
  test/buildConfigWithDefaults.ts
Labels: created-by: Payload team

#7361 fix(db-mongodb): adds new optional collation feature flag behind mongodb collation option
  docs/database/mongodb.mdx
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/queryDrafts.ts
  test/buildConfigWithDefaults.ts
Labels: v3, created-by: Contributor

#5241 fix: supports null values in query strings
  packages/payload/src/admin/components/forms/field-types/Relationship/index.tsx
  packages/payload/src/express/middleware/index.ts
Labels: created-by: Payload team

#7364 fix(payload): properly handles `0` value number fields in list view
  packages/payload/src/admin/components/views/collections/List/Cell/index.tsx
  packages/payload/src/admin/components/views/collections/List/Cell/types.ts
Labels: created-by: Payload team

#7347 fix: filterOptions for upload fields
  packages/payload/src/fields/config/types.ts
  packages/ui/src/forms/buildStateFromSchema/addFieldStatePromise.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
Labels: created-by: Payload team

#7383 fix(db-postgres): properly reference drizzle createTableName function
  packages/db-postgres/src/init.ts
Labels: v3, created-by: Payload team

#7367 feat(cpa): support next.config.ts
  packages/create-payload-app/package.json
  packages/create-payload-app/src/lib/init-next.ts
  packages/create-payload-app/src/lib/wrap-next-config.spec.ts
  packages/create-payload-app/src/lib/wrap-next-config.ts
  packages/create-payload-app/src/types.ts
  pnpm-lock.yaml
  test/create-payload-app/int.spec.ts
Labels: v3, created-by: Payload team

#7384 feat(templates): add live preview breakpoints for mobile, tablet and desktop to website template
  templates/website/src/payload.config.ts
Labels: v3, created-by: Contributor

#7385 fix: preserves objectids in deepCopyObject
  packages/payload/src/utilities/deepCopyObject.ts
Labels: created-by: Payload team

#7387 fix(ui): spacing in row fields by using gap instead of inner margins
  packages/plugin-form-builder/src/collections/Forms/index.ts
  packages/ui/src/fields/Row/index.scss
Labels: v3, created-by: Contributor

#7388 feat: adds keepAfterRead to plugin-relationship-objectid
  packages/plugin-relationship-object-ids/README.md
  packages/plugin-relationship-object-ids/src/hooks/afterRead.ts
  packages/plugin-relationship-object-ids/src/index.ts
Labels: v3, created-by: Payload team

#7390 fix(ui): handle `abort()` call signal error
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/hooks/usePayloadAPI.ts
  packages/ui/src/providers/DocumentInfo/index.tsx
Labels: v3, created-by: Contributor

#7362 chore(ui)!: update the names of internal components so that they respect eslint rules
  packages/eslint-config/configs/react/index.mjs
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/fields/Checkbox/index.tsx
  packages/ui/src/fields/Code/index.tsx
  packages/ui/src/fields/Collapsible/index.tsx
  packages/ui/src/fields/DateTime/index.tsx
  packages/ui/src/fields/Email/index.tsx
  packages/ui/src/fields/Group/index.tsx
  packages/ui/src/fields/Hidden/index.tsx
  packages/ui/src/fields/JSON/index.tsx
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/Password/index.tsx
  packages/ui/src/fields/Point/index.tsx
  packages/ui/src/fields/RadioGroup/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Row/index.tsx
  packages/ui/src/fields/Select/index.tsx
  packages/ui/src/fields/Tabs/index.tsx
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/fields/Textarea/index.tsx
  packages/ui/src/fields/Upload/index.tsx
Labels: v3, created-by: Contributor

#7391 chore(cpa): replaces missing type assertion
  packages/create-payload-app/src/lib/wrap-next-config.ts
Labels: v3, created-by: Payload team

#7392 fix(docs): update import path for validation functions for fields
  docs/fields/overview.mdx
  docs/fields/relationship.mdx
  docs/fields/upload.mdx
Labels: v3, created-by: Contributor

#7393 fix(payload): retained date milliseconds
  packages/payload/src/admin/components/elements/DatePicker/DatePicker.tsx
Labels: created-by: Payload team

#7397 fix(ui): stacking drawers
  packages/ui/src/elements/Drawer/index.scss
  packages/ui/src/elements/Drawer/index.tsx
  test/admin/e2e/1/e2e.spec.ts
  test/admin/seed.ts
  test/fields/collections/Tabs/e2e.spec.ts
  test/helpers.ts
  test/helpers/e2e/navigateToDoc.ts
  test/helpers/e2e/navigateToFirstCellLink.ts
  test/live-preview/e2e.spec.ts
  test/live-preview/helpers.ts
  tsconfig.json
Labels: v3, created-by: Payload team

#7399 fix: merges headers safely in nextjs route handlers
  packages/next/src/routes/graphql/handler.ts
  packages/next/src/routes/rest/index.ts
  packages/next/src/utilities/mergeHeaders.ts
Labels: v3, created-by: Payload team

#7403 fix(db-postgres): migration template type error
  packages/db-postgres/src/createMigration.ts
  packages/db-postgres/src/getMigrationTemplate.ts
  packages/db-postgres/src/types.ts
Labels: v3, created-by: Contributor

#7404 fix(db-sqlite): migration template errors
  .github/workflows/pr-title.yml
  packages/db-sqlite/src/createMigration.ts
  packages/db-sqlite/src/defaultSnapshot.ts
  packages/db-sqlite/src/getMigrationTemplate.ts
  packages/db-sqlite/src/types.ts
  test/_community/migrations/20240513_181104_test.js
  test/_community/migrations/20240513_181104_test.json
Labels: v3, created-by: Contributor

#7411 chore: extends buildConfigWithDefaults to accept options arg
  test/buildConfigWithDefaults.ts
Labels: v3, created-by: Contributor

#7394 fix: types for the 'validate' property across fields so internal validation functions can be reused
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
Labels: v3, created-by: Contributor

#7412 fix(next): infinite loop when logging into root admin
  packages/next/src/utilities/initPage/handleAdminPage.ts
  packages/next/src/utilities/initPage/handleAuthRedirect.ts
  packages/next/src/utilities/initPage/shared.ts
  test/access-control/e2e.spec.ts
  test/admin-root/app/favicon.ico
  test/admin-root/config.ts
  test/admin-root/e2e.spec.ts
  test/admin/e2e/1/e2e.spec.ts
  test/admin/e2e/2/e2e.spec.ts
  test/auth/e2e.spec.ts
  test/helpers.ts
  tsconfig.json
Labels: v3, created-by: Payload team

#7243 fix: page param not getting reset when applying filters
  packages/ui/src/elements/SortColumn/index.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/providers/ListQuery/index.tsx
  test/admin/e2e/2/e2e.spec.ts
Labels: v3, created-by: Payload team

#7395 feat(db-*, payload): better transactions
  packages/db-postgres/src/types.ts
  packages/db-sqlite/src/types.ts
  packages/drizzle/src/transactions/beginTransaction.ts
  packages/payload/src/auth/getAccessResults.ts
  packages/payload/src/auth/operations/access.ts
  packages/payload/src/collections/operations/count.ts
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/deleteByID.ts
  packages/payload/src/collections/operations/docAccess.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/collections/operations/findVersionByID.ts
  packages/payload/src/collections/operations/findVersions.ts
  packages/payload/src/collections/operations/restoreVersion.ts
  packages/payload/src/collections/operations/updateByID.ts
  packages/payload/src/globals/operations/findOne.ts
  packages/payload/src/globals/operations/findVersionByID.ts
  packages/payload/src/globals/operations/findVersions.ts
  packages/payload/src/utilities/killTransaction.ts
  test/hooks/collections/Hook/index.ts
Labels: v3, created-by: Contributor

#7421 chore: fix generic usage
  packages/payload/src/uploads/mimeTypeValidator.spec.ts
  packages/richtext-lexical/src/field/features/types.ts
  packages/richtext-lexical/src/validate/validateNodes.ts
Labels: created-by: Payload team

#7414 chore: duplicates prev value PRs from v2
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/validate/validateNodes.ts
  test/field-error-states/collections/PrevValue/index.ts
  test/field-error-states/collections/PrevValueRelation/index.ts
  test/field-error-states/collections/ValidateDraftsOff/index.ts
  test/field-error-states/collections/ValidateDraftsOn/index.ts
  test/field-error-states/collections/ValidateDraftsOnAutosave/index.ts
  test/field-error-states/config.ts
  test/field-error-states/e2e.spec.ts
  test/field-error-states/globals/ValidateDraftsOn/index.ts
  test/field-error-states/payload-types.ts
  test/field-error-states/shared.ts
Labels: v3, created-by: Contributor

#7418 fix: hide force unlock button if the user has no permissions to interact with it
  packages/next/src/views/Edit/Default/Auth/index.tsx
Labels: v3, created-by: Contributor

#7433 fix: formats locales for version comparison view
  packages/next/src/views/Version/Default/index.tsx
  packages/next/src/views/Version/index.tsx
Labels: v3, created-by: Payload team
