Repository payloadcms/payload, pull requests merged in 2024-12, with the labels that each got.

#9641 feat(examples): add custom server example [skip-lint]
  examples/custom-server/.gitignore
  examples/custom-server/README.md
  examples/custom-server/next-env.d.ts
  examples/custom-server/next.config.ts
  examples/custom-server/nodemon.json
  examples/custom-server/package.json
  examples/custom-server/src/app/(app)/b/page.tsx
  examples/custom-server/src/app/(app)/layout.tsx
  examples/custom-server/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  examples/custom-server/src/app/(payload)/admin/[[...segments]]/page.tsx
  examples/custom-server/src/app/(payload)/admin/importMap.js
  examples/custom-server/src/app/(payload)/api/[...slug]/route.ts
  examples/custom-server/src/app/(payload)/api/graphql-playground/route.ts
  examples/custom-server/src/app/(payload)/api/graphql/route.ts
  examples/custom-server/src/app/(payload)/custom.scss
  examples/custom-server/src/app/(payload)/layout.tsx
  examples/custom-server/src/collections/Media.ts
  examples/custom-server/src/collections/Users.ts
  examples/custom-server/src/payload-types.ts
  examples/custom-server/src/payload.config.ts
  examples/custom-server/src/server.ts
  examples/custom-server/tsconfig.json
  examples/custom-server/tsconfig.server.json
Labels: created-by: Payload team

#9642 docs: add upgrade from previous beta section to migration guide
  docs/migration-guide/overview.mdx
Labels: created-by: Payload team

#9644 fix: ensure job errors are saved in payload
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/index.ts
Labels: created-by: Payload team

#9647 feat(ui): export TabsProvider and TabComponent
  packages/ui/src/exports/client/index.ts
Labels: created-by: Payload team

#9649 fix: prevent workflow destructuring errors for failing tasks
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
Labels: created-by: Payload team

#9650 feat(ui): export CodeEditor
  packages/ui/src/exports/client/index.ts
Labels: created-by: Payload team

#9651 fix: job task output data was not fetched and restored, if task failed previously
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
  packages/payload/src/queues/utilities/getJobTaskStatus.ts
Labels: created-by: Payload team

#9653 fix(ui): upgrade react-select, fixes type issues with select input
  examples/form-builder/next-app/package.json
  examples/form-builder/next-pages/package.json
  packages/ui/package.json
  packages/ui/src/elements/ReactSelect/Input/index.tsx
  packages/ui/src/elements/ReactSelect/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  pnpm-lock.yaml
Labels: created-by: Payload team

#9652 ci: add back CI-level automatic retrying for failing int and e2e tests
  .github/workflows/main.yml
Labels: created-by: Payload team

#9654 feat(ui): upgrade react-datepicker dependency from 6.2.0 to 7.5.0
  packages/payload/package.json
  packages/payload/src/admin/elements/DatePicker.ts
  packages/ui/package.json
  packages/ui/src/elements/DatePicker/DatePicker.tsx
  pnpm-lock.yaml
Labels: created-by: Payload team

#9655 chore: upgrade all react and next-related packages
  package.json
  packages/next/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-website/package.json
  test/package.json
Labels: created-by: Payload team

#9658 chore: upgrade all dependencies used to build payload (swc, esbuild, react compiler, babel)
  .github/actions/release-commenter/package.json
  package.json
  packages/db-postgres/package.json
  packages/db-vercel-postgres/package.json
  packages/next/package.json
  packages/payload/package.json
  packages/richtext-lexical/package.json
  packages/translations/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#9666 fix(ui): upgrade sonner from 1.5.0 to 1.7.0
  packages/next/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#9032 fix: latest: true version disappear on parallel writes
  packages/db-mongodb/src/createVersion.ts
  packages/drizzle/src/createVersion.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#9674 feat(ui): adds `beforeInput` & `afterInput` props for `arrays`, `blocks`, `collapsible`, `group`, `radio`, & `relationship` fields.
  packages/payload/src/fields/config/types.ts
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/fields/Collapsible/index.tsx
  packages/ui/src/fields/Group/index.tsx
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/RadioGroup/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  test/admin/collections/CustomFields/index.ts
Labels: created-by: Payload team

#9677 ci: allow more commit types in release notes
  .github/workflows/pr-title.yml
  scripts/utils/generateReleaseNotes.ts
Labels: created-by: Payload team

#9605 fix: ensure jobs do not retry indefinitely by default, fix undefined values in error messages
  docs/jobs-queue/tasks.mdx
  docs/jobs-queue/workflows.mdx
  packages/payload/src/queues/config/types/taskTypes.ts
  packages/payload/src/queues/config/types/workflowJSONTypes.ts
  packages/payload/src/queues/config/types/workflowTypes.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/handleWorkflowError.ts
  test/live-preview/payload-types.ts
  test/queues/config.ts
  test/queues/int.spec.ts
  test/queues/payload-types.ts
Labels: created-by: Payload team

#9679 fix: throw proper error if import handler paths are not able to be imported, improve import handler path docs
  docs/jobs-queue/tasks.mdx
  docs/jobs-queue/workflows.mdx
  packages/payload/src/queues/config/types/taskTypes.ts
  packages/payload/src/queues/config/types/workflowTypes.ts
  packages/payload/src/queues/operations/runJobs/runJob/importHandlerPath.ts
Labels: created-by: Payload team

#9671 chore(scripts): fix generate template variations script
  .github/workflows/post-release.yml
  scripts/generate-template-variations.ts
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/collections/Pages/index.ts
  templates/website/src/payload-types.ts
  templates/with-vercel-website/src/app/(frontend)/[slug]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/next/preview/route.ts
  templates/with-vercel-website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/with-vercel-website/src/app/(payload)/admin/importMap.js
  templates/with-vercel-website/src/collections/Pages/index.ts
  templates/with-vercel-website/src/heros/MediumImpact/index.tsx
  templates/with-vercel-website/src/heros/PostHero/index.tsx
  templates/with-vercel-website/src/payload-types.ts
  templates/with-vercel-website/tailwind.config.mjs
Labels: created-by: Payload team

#9579 feat: disableLocalStrategy with auth fields still enabled
  packages/graphql/src/schema/initCollections.ts
  packages/payload/src/auth/getAuthFields.ts
  packages/payload/src/auth/operations/forgotPassword.ts
  packages/payload/src/auth/operations/login.ts
  packages/payload/src/auth/operations/registerFirstUser.ts
  packages/payload/src/auth/operations/resetPassword.ts
  packages/payload/src/auth/operations/unlock.ts
  packages/payload/src/auth/operations/verifyEmail.ts
  packages/payload/src/auth/types.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  packages/ui/src/views/Edit/Auth/types.ts
  test/auth/config.ts
  test/auth/e2e.spec.ts
  test/auth/int.spec.ts
  test/auth/payload-types.ts
  test/auth/shared.ts
Labels: created-by: Payload team

#9682 fix(ui): data disappearing when form state updates in globals
  packages/ui/src/views/Edit/index.tsx
Labels: created-by: Payload team

#9673 fix: copy data from locale transaction error
  packages/ui/src/utilities/copyDataFromLocale.ts
Labels: created-by: Payload team

#9700 chore: change deprecation warning for getPayloadHMR to warning
  packages/next/src/utilities/getPayloadHMR.ts
Labels: created-by: Payload team

#9702 fix(templates): website remove maxDepth from references in link field
  templates/website/src/Header/Component.client.tsx
  templates/website/src/fields/link.ts
Labels: created-by: Payload team

#9705 fix(ui): copy to locale incorrect label when locale label is defined as object
  packages/ui/src/elements/CopyLocaleData/index.tsx
Labels: created-by: Payload team

#9706 chore(templates): add initial migrations for vercel with website template
  templates/website/.env.example
  templates/with-vercel-website/.env.example
  templates/with-vercel-website/src/migrations/20241203_183323_initial.json
  templates/with-vercel-website/src/migrations/20241203_183323_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: created-by: Payload team

#9707 feat(ui): adds before & after inputs to join field
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/fields/Join/index.tsx
  test/joins/collections/Categories.ts
  test/joins/components/AfterInput.tsx
  test/joins/components/BeforeInput.tsx
Labels: created-by: Payload team

#9709 fix: error after view is left idle on edit views
  packages/next/src/views/LivePreview/index.client.tsx
  packages/ui/src/views/Edit/index.tsx
Labels: created-by: Payload team

#9703 fix: join field shows loading when creating a document
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/fields/Join/index.tsx
  test/joins/collections/Categories.ts
  test/joins/components/AfterInput.tsx
  test/joins/components/BeforeInput.tsx
  test/joins/components/CustomDescription/index.tsx
  test/joins/config.ts
  test/joins/e2e.spec.ts
Labels: created-by: Payload team

#9716 feat(templates): add new favicons and og images to website template
  templates/website/public/favicon.ico
  templates/website/public/favicon.svg
  templates/website/public/website-template-OG.webp
  templates/website/src/collections/Media.ts
  templates/website/src/payload-types.ts
  templates/website/src/utilities/generateMeta.ts
  templates/with-vercel-website/public/favicon.ico
  templates/with-vercel-website/public/favicon.svg
  templates/with-vercel-website/public/website-template-OG.webp
  templates/with-vercel-website/src/collections/Media.ts
  templates/with-vercel-website/src/payload-types.ts
  templates/with-vercel-website/src/utilities/generateMeta.ts
Labels: created-by: Payload team

#9727 feat(templates): add sitemap support to website template
  templates/website/.gitignore
  templates/website/.npmrc
  templates/website/next-sitemap.config.cjs
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(frontend)/(sitemaps)/pages-sitemap.xml/route.ts
  templates/website/src/app/(frontend)/(sitemaps)/posts-sitemap.xml/route.ts
  templates/website/src/app/(frontend)/search/page.tsx
  templates/website/src/collections/Pages/hooks/revalidatePage.ts
  templates/website/src/collections/Pages/index.ts
  templates/website/src/collections/Posts/hooks/revalidatePost.ts
  templates/website/src/collections/Posts/index.ts
  templates/website/tsconfig.json
  templates/with-vercel-website/.env.example
  templates/with-vercel-website/.gitignore
  templates/with-vercel-website/.npmrc
  templates/with-vercel-website/next-sitemap.config.cjs
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/Header/Component.client.tsx
  templates/with-vercel-website/src/app/(frontend)/(sitemaps)/pages-sitemap.xml/route.ts
  templates/with-vercel-website/src/app/(frontend)/(sitemaps)/posts-sitemap.xml/route.ts
  templates/with-vercel-website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/search/page.tsx
  templates/with-vercel-website/src/collections/Pages/hooks/revalidatePage.ts
  templates/with-vercel-website/src/collections/Pages/index.ts
  templates/with-vercel-website/src/collections/Posts/hooks/revalidatePost.ts
  templates/with-vercel-website/src/collections/Posts/index.ts
  templates/with-vercel-website/src/fields/link.ts
  templates/with-vercel-website/tsconfig.json
Labels: created-by: Payload team

#9680 fix: hidden and disabled fields cause incorrect field paths
  docs/admin/fields.mdx
  packages/next/src/views/Version/RenderFieldsToDiff/index.tsx
  packages/payload/src/collections/config/client.ts
  packages/payload/src/exports/shared.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/fieldSchemaToJSON.ts
  packages/ui/src/elements/FieldSelect/index.tsx
  packages/ui/src/elements/Table/DefaultCell/index.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/elements/WhereBuilder/reduceClientFields.tsx
  packages/ui/src/forms/RenderFields/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/utilities/buildTableState.ts
  packages/ui/src/utilities/formatFields.ts
  packages/ui/src/utilities/renderTable.tsx
  test/admin/payload-types.ts
  test/fields/collections/Text/e2e.spec.ts
  test/fields/collections/Text/index.ts
  test/fields/components/CustomField.tsx
  test/fields/e2e.spec.ts
  test/fields/payload-types.ts
  test/helpers/e2e/toggleColumn.ts
  tsconfig.json
Labels: created-by: Payload team

#9730 fix(templates): vercel migrations
  templates/with-vercel-website/src/migrations/20241204_024245_initial.json
  templates/with-vercel-website/src/migrations/20241204_024245_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: created-by: Payload team

#9733 ci: template bump workflow
  .github/workflows/post-release-templates.yml
  scripts/generate-template-variations.ts
Labels: created-by: Payload team

#9406 fix(richtext-lexical): ensure hooks from sub-fields receive document data and doc props, and not node data and doc props
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/index.ts
Labels: created-by: Payload team

#9710 feat: adds configurable `expiration` prop for password reset tokens
  docs/authentication/email.mdx
  packages/payload/src/auth/operations/forgotPassword.ts
  packages/payload/src/auth/types.ts
Labels: created-by: Payload team, prioritized

#9738 docs: add output standalone in docker deployment section
  docs/production/deployment.mdx
Labels: created-by: Payload team

#9739 chore: adds jsdocs for `auth.forgotPassword.expiration` prop
  packages/payload/src/auth/types.ts
Labels: created-by: Payload team

#9607 fix(db-postgres): handle `select` query on select fields
  packages/drizzle/src/find/traverseFields.ts
  test/select/collections/LocalizedPosts/index.ts
  test/select/collections/Posts/index.ts
  test/select/int.spec.ts
  test/select/payload-types.ts
Labels: created-by: Payload team

#9742 fix(ui): only render header dom node if needed
  packages/ui/src/fields/Group/index.tsx
Labels: created-by: Payload team

#9746 feat(live-preview): supports relative urls for dynamic preview deployments
  docs/live-preview/overview.mdx
  packages/next/src/views/LivePreview/index.tsx
  test/live-preview/app/live-preview/(pages)/[slug]/page.tsx
  test/live-preview/app/live-preview/_api/getDoc.ts
  test/live-preview/app/live-preview/_api/getDocs.ts
  test/live-preview/app/live-preview/_components/Footer/index.tsx
  test/live-preview/app/live-preview/_components/Link/index.tsx
  test/live-preview/prod/app/live-preview/(pages)/[slug]/page.tsx
  test/live-preview/prod/app/live-preview/_api/getDoc.ts
  test/live-preview/prod/app/live-preview/_api/getDocs.ts
  test/live-preview/prod/app/live-preview/_components/Footer/index.tsx
  test/live-preview/prod/app/live-preview/_components/Link/index.tsx
  test/live-preview/seed/posts-page.ts
  test/live-preview/utilities/formatLivePreviewURL.ts
Labels: created-by: Payload team

#9745 ci: ensure clean all script does not error after retrying step, by installing globby and chalk globally
  .github/workflows/main.yml
Labels: created-by: Payload team

#9748 templates: improve speed of seed script
  templates/website/src/Footer/hooks/revalidateFooter.ts
  templates/website/src/Header/hooks/revalidateHeader.ts
  templates/website/src/app/(frontend)/next/seed/route.ts
  templates/website/src/collections/Pages/hooks/revalidatePage.ts
  templates/website/src/collections/Posts/hooks/revalidatePost.ts
  templates/website/src/endpoints/seed/index.ts
  templates/website/src/endpoints/seedHandler.ts
Labels: created-by: Payload team

#9371 fix: `getPayload` generate import map only in Next.js
  packages/payload/src/index.ts
Labels: created-by: Payload team

#9754 chore(richtext-lexical): remove outdated custom block component examples
  test/fields/collections/Lexical/InlineFieldsDisplayComponent.tsx
  test/fields/collections/Lexical/LabelComponent.tsx
Labels: created-by: Payload team

#9755 feat(next): supports relative preview URLs
  docs/admin/collections.mdx
  docs/live-preview/overview.mdx
  packages/next/src/routes/rest/collections/preview.ts
  test/live-preview/collections/Pages.ts
  test/live-preview/collections/Posts.ts
  test/live-preview/collections/SSR.ts
  test/live-preview/collections/SSRAutosave.ts
  test/versions/collections/Autosave.ts
  test/versions/collections/CustomIDs.ts
  test/versions/collections/Drafts.ts
  test/versions/collections/DraftsWithMax.ts
  test/versions/collections/Versions.ts
  test/versions/globals/Autosave.ts
  test/versions/globals/DraftWithMax.ts
Labels: created-by: Payload team

#9759 feat: allow to define global label as function
  packages/payload/src/globals/config/client.ts
  packages/payload/src/globals/config/types.ts
  packages/ui/src/utilities/groupNavItems.ts
Labels: created-by: Payload team

#9758 templates: fixes the seeding for the website template when using postgres
  templates/website/src/endpoints/seed/index.ts
Labels: created-by: Payload team

#9728 chore(ui): expose onInputChange from react-select in SelectInput component
  packages/ui/src/fields/Select/Input.tsx
Labels: created-by: Payload team

#9761 templates: add next sitemap robots disallow config for /admin
  templates/website/next-sitemap.config.cjs
Labels: created-by: Payload team

#9747 fix(db-mongodb): bump `mongoose` to `8.8.3`
  packages/db-mongodb/package.json
  pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#9751 fix: `defaultPopulate` and `populate` with nested to arrays/blocks properties
  packages/payload/src/fields/hooks/afterRead/promise.ts
  test/select/collections/Pages/index.ts
  test/select/int.spec.ts
  test/select/payload-types.ts
Labels: created-by: Payload team

#9778 docs: adds missing "to" in jobs-queue/overview
  docs/jobs-queue/overview.mdx
Labels: created-by: Payload team

#9750 fix(ui): disable doc submenu when parent button is disabled
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Popup/PopupTrigger/index.scss
  packages/ui/src/elements/Popup/PopupTrigger/index.tsx
Labels: created-by: Contributor

#9779 templates: improvements to seed speed on website template and updated hero and collapsible fields
  templates/website/src/Footer/RowLabel.tsx
  templates/website/src/Footer/config.ts
  templates/website/src/Header/RowLabel.tsx
  templates/website/src/Header/config.ts
  templates/website/src/app/(payload)/admin/importMap.js
  templates/website/src/blocks/Content/config.ts
  templates/website/src/blocks/RelatedPosts/Component.tsx
  templates/website/src/collections/Pages/index.ts
  templates/website/src/components/RichText/index.tsx
  templates/website/src/endpoints/seed/index.ts
  templates/website/src/fields/linkGroup.ts
  templates/website/src/heros/HighImpact/index.tsx
  templates/website/tailwind.config.mjs
Labels: created-by: Payload team

#9766 fix(ui): join field ignoring defaultSort and defaultLimit
  packages/payload/src/admin/functions/index.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/providers/ListQuery/index.tsx
  test/joins/e2e.spec.ts
Labels: created-by: Payload team, prioritized

#9780 templates: bump for v3.4.0
  templates/with-postgres/src/migrations/20241205_211431_initial.json
  templates/with-postgres/src/migrations/20241205_211431_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20241205_211405_initial.json
  templates/with-vercel-postgres/src/migrations/20241205_211405_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/src/Footer/RowLabel.tsx
  templates/with-vercel-website/src/Footer/config.ts
  templates/with-vercel-website/src/Header/RowLabel.tsx
  templates/with-vercel-website/src/Header/config.ts
  templates/with-vercel-website/src/app/(payload)/admin/importMap.js
  templates/with-vercel-website/src/blocks/Content/config.ts
  templates/with-vercel-website/src/blocks/RelatedPosts/Component.tsx
  templates/with-vercel-website/src/collections/Pages/index.ts
  templates/with-vercel-website/src/components/RichText/index.tsx
  templates/with-vercel-website/src/endpoints/seed/index.ts
  templates/with-vercel-website/src/fields/linkGroup.ts
  templates/with-vercel-website/src/heros/HighImpact/index.tsx
  templates/with-vercel-website/src/migrations/20241205_211421_initial.json
  templates/with-vercel-website/src/migrations/20241205_211421_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
  templates/with-vercel-website/tailwind.config.mjs
Labels: area: templates, created-by: Payload team

#9764 docs(plugin-search): add info on collection reindexing
  docs/admin/components.mdx
  docs/plugins/search.mdx
Labels: created-by: Contributor

#9781 ci: only run tests when needed via needs_tests filter
  .github/workflows/main.yml
Labels: created-by: Payload team

#9784 ci: main workflow improvements
  .github/actions/setup/action.yml
  .github/workflows/main.yml
Labels: created-by: Payload team

#9786 ci: explicitly use ubuntu-24.04 instead of latest to ensure compat
  .github/workflows/label-on-change.yml
  .github/workflows/lock-issues.yml
  .github/workflows/main.yml
  .github/workflows/post-release-templates.yml
  .github/workflows/post-release.yml
  .github/workflows/pr-title.yml
  .github/workflows/release-canary.yml
  .github/workflows/stale.yml
  .github/workflows/triage.yml
Labels: created-by: Payload team

#8709 feat(i18n): add Slovenian (sl) translation
  packages/payload/src/translations/index.ts
  packages/payload/src/translations/sl.json
Labels: v2, keep

#9795 chore(translations): improved serbian translations for the lexical editor
  packages/richtext-lexical/src/features/align/server/i18n.ts
  packages/richtext-lexical/src/features/blockquote/server/i18n.ts
  packages/richtext-lexical/src/features/blocks/server/i18n.ts
  packages/richtext-lexical/src/features/heading/server/i18n.ts
  packages/richtext-lexical/src/features/horizontalRule/server/i18n.ts
  packages/richtext-lexical/src/features/indent/server/i18n.ts
  packages/richtext-lexical/src/features/link/server/i18n.ts
  packages/richtext-lexical/src/features/lists/checklist/server/i18n.ts
  packages/richtext-lexical/src/features/lists/orderedList/server/i18n.ts
  packages/richtext-lexical/src/features/lists/unorderedList/server/i18n.ts
  packages/richtext-lexical/src/features/paragraph/server/i18n.ts
  packages/richtext-lexical/src/features/relationship/server/i18n.ts
  packages/richtext-lexical/src/features/upload/server/i18n.ts
  packages/richtext-lexical/src/i18n.ts
Labels: created-by: Contributor

#6864 Fix typo in concepts
  docs/getting-started/concepts.mdx
Labels: stale, v2

#8110 fix(plugin-form-builder): use escapeHTML on submission data in serializeLexical
  packages/plugin-form-builder/src/utilities/lexical/converters/link.ts
  packages/plugin-form-builder/src/utilities/lexical/converters/text.ts
Labels: stale, v2, keep

#9800 fix(ui): collapsed array state on input change
  packages/ui/src/elements/TableColumns/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  test/fields/collections/Array/e2e.spec.ts
Labels: created-by: Payload team

#9777 feat: export `sanitizeSelectParam`, `sanitizePopulateParam`, `senitizeJoinParams` utils
  packages/next/src/routes/rest/collections/create.ts
  packages/next/src/routes/rest/collections/delete.ts
  packages/next/src/routes/rest/collections/deleteByID.ts
  packages/next/src/routes/rest/collections/duplicate.ts
  packages/next/src/routes/rest/collections/find.ts
  packages/next/src/routes/rest/collections/findByID.ts
  packages/next/src/routes/rest/collections/findVersionByID.ts
  packages/next/src/routes/rest/collections/findVersions.ts
  packages/next/src/routes/rest/collections/restoreVersion.ts
  packages/next/src/routes/rest/collections/update.ts
  packages/next/src/routes/rest/collections/updateByID.ts
  packages/next/src/routes/rest/globals/findOne.ts
  packages/next/src/routes/rest/globals/findVersionByID.ts
  packages/next/src/routes/rest/globals/findVersions.ts
  packages/next/src/routes/rest/globals/restoreVersion.ts
  packages/next/src/routes/rest/globals/update.ts
  packages/next/src/routes/rest/utilities/sanitizePopulate.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/sanitizeJoinParams.ts
  packages/payload/src/utilities/sanitizePopulateParam.ts
  packages/payload/src/utilities/sanitizeSelectParam.ts
  test/_community/payload-types.ts
Labels: created-by: Payload team

#9802 ci: add nightly stale cron
  .github/workflows/stale.yml
Labels: created-by: Payload team

#9757 chore(cpa): updates `.env.example` env vars along side `.env` vars based on selected DB
  packages/create-payload-app/src/lib/manage-env-files.ts
  packages/create-payload-app/src/lib/write-env-file.ts
  packages/create-payload-app/src/main.ts
Labels: created-by: Payload team

#9804 templates: bump for v3.5.0
  templates/blank/pnpm-lock.yaml
  templates/website/pnpm-lock.yaml
  templates/with-postgres/src/migrations/20241206_203050_initial.json
  templates/with-postgres/src/migrations/20241206_203050_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20241206_203025_initial.json
  templates/with-vercel-postgres/src/migrations/20241206_203025_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/src/migrations/20241206_203040_initial.json
  templates/with-vercel-website/src/migrations/20241206_203040_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#9803 ci: add types testing with `tstyche`
  .github/workflows/main.yml
  package.json
  pnpm-lock.yaml
  test/types/.gitignore
  test/types/config.ts
  test/types/eslint.config.js
  test/types/payload-types.ts
  test/types/tsconfig.eslint.json
  test/types/tsconfig.json
  test/types/types.spec.ts
  tstyche.config.json
Labels: created-by: Payload team

#9815 refactor(richtext-lexical): export JSXConverter type
  packages/richtext-lexical/src/exports/react/index.ts
Labels: created-by: Payload team

#9823 chore(deps): upgrade dataloader dependency from 2.2.2 to 2.2.3
  packages/payload/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#9824 fix(richtext-*): field errors and descriptions were not displayed
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-slate/src/field/RichText.tsx
Labels: created-by: Payload team

#9808 templates: website template added changes for seed script, relative live preview URLs and fixed endpoint status code
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(frontend)/next/seed/route.ts
  templates/website/src/collections/Pages/index.ts
  templates/website/src/collections/Posts/index.ts
  templates/website/src/endpoints/seed/index.ts
  templates/with-vercel-website/src/app/(frontend)/next/seed/route.ts
  templates/with-vercel-website/src/collections/Pages/index.ts
  templates/with-vercel-website/src/collections/Posts/index.ts
  templates/with-vercel-website/src/endpoints/seed/index.ts
  templates/with-vercel-website/src/endpoints/seedHandler.ts
Labels: created-by: Payload team

#9793 fix(richtext-lexical): lexical-html export
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/lexical-proxy/@lexical-html.ts
  pnpm-lock.yaml
Labels: created-by: Contributor

#9832 test: properly mock nodemailer verify in unit test
  packages/payload-cloud/src/plugin.spec.ts
Labels: created-by: Payload team

#9825 ci: add missing tests to all-green dependency array
  .github/workflows/main.yml
Labels: created-by: Payload team

#9843 fix(templates): website infinite reload bug with 404s in production mode
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/layout.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/components/PayloadRedirects/index.tsx
Labels: created-by: Payload team

#9844 templates: bump for v3.5.0
  templates/website/pnpm-lock.yaml
  templates/with-postgres/src/migrations/20241210_000627_initial.json
  templates/with-postgres/src/migrations/20241210_000627_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20241210_000603_initial.json
  templates/with-vercel-postgres/src/migrations/20241210_000603_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/src/app/(frontend)/[slug]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/layout.tsx
  templates/with-vercel-website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/with-vercel-website/src/collections/Pages/index.ts
  templates/with-vercel-website/src/collections/Posts/index.ts
  templates/with-vercel-website/src/components/PayloadRedirects/index.tsx
  templates/with-vercel-website/src/migrations/20241210_000617_initial.json
  templates/with-vercel-website/src/migrations/20241210_000617_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
  templates/with-vercel-website/src/utilities/generatePreviewPath.ts
Labels: area: templates, created-by: Payload team

#9845 docs: fix typo
  docs/database/migrations.mdx
Labels: created-by: Payload team

#9847 docs: add missing types, prefer pnpm, fix various typos, discourage using payload from import
  docs/cloud/projects.mdx
  docs/getting-started/installation.mdx
  docs/graphql/graphql-schema.mdx
  docs/hooks/context.mdx
  docs/hooks/overview.mdx
  docs/plugins/build-your-own.mdx
  docs/plugins/form-builder.mdx
  docs/plugins/nested-docs.mdx
  docs/plugins/redirects.mdx
  docs/plugins/search.mdx
  docs/plugins/sentry.mdx
  docs/plugins/seo.mdx
  docs/plugins/stripe.mdx
  docs/queries/depth.mdx
  docs/queries/overview.mdx
  docs/queries/select.mdx
  docs/queries/sort.mdx
  docs/typescript/generating-types.mdx
Labels: created-by: Payload team

#9848 docs: properly capitalize SQLite and Next.js
  docs/getting-started/installation.mdx
  docs/local-api/overview.mdx
  docs/migration-guide/overview.mdx
Labels: created-by: Payload team

#9841 chore: better default for useAsTitle with custom auth collections
  packages/payload/src/collections/config/sanitize.ts
  test/login-with-username/config.ts
  test/login-with-username/payload-types.ts
Labels: created-by: Payload team

#9842 fix(ui): prevents unwanted data overrides when bulk editing
  packages/ui/src/elements/EditMany/index.tsx
  packages/ui/src/elements/FieldSelect/index.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/types.ts
  test/admin/collections/Posts.ts
  test/admin/e2e/3/e2e.spec.ts
  test/admin/payload-types.ts
Labels: created-by: Payload team

#9846 fix(ui): refreshes column state during hmr and respects admin.disableListColumn despite preferences
  packages/next/src/views/List/index.tsx
  packages/payload/src/exports/shared.ts
  packages/payload/src/utilities/flattenTopLevelFields.ts
  packages/ui/src/elements/ListControls/getTextFieldsToBeSearched.ts
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/elements/TableColumns/filterFields.tsx
  packages/ui/src/elements/TableColumns/getInitialColumns.ts
  packages/ui/src/elements/TableColumns/index.tsx
  packages/ui/src/hooks/useUseAsTitle.ts
  packages/ui/src/utilities/buildTableState.ts
  packages/ui/src/utilities/flattenFieldMap.ts
  packages/ui/src/utilities/renderTable.tsx
  test/admin/e2e/2/e2e.spec.ts
  test/fields/collections/Text/e2e.spec.ts
  test/fields/collections/Text/index.ts
  test/helpers/e2e/toggleColumn.ts
  test/helpers/e2e/upsertPrefs.ts
  test/helpers/rest.ts
  test/helpers/sdk/endpoint.ts
Labels: created-by: Payload team

#9874 fix(ui): ensures admin.disableListFilter is disabled despite url search params
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/reduceClientFields.tsx
  packages/ui/src/providers/ListQuery/index.tsx
  test/admin/e2e/2/e2e.spec.ts
  test/fields-relationship/e2e.spec.ts
  test/fields/collections/Email/e2e.spec.ts
  test/fields/collections/Number/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/collections/Text/e2e.spec.ts
  test/helpers/e2e/openListColumns.ts
  test/helpers/e2e/openListFilters.ts
  test/helpers/e2e/toggleColumn.ts
Labels: created-by: Payload team

#9875 feat: add payload.jobs.runByID
  docs/jobs-queue/queues.mdx
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  test/queues/int.spec.ts
Labels: created-by: Payload team

#9877 feat: allow `where` in payload.jobs.run
  docs/jobs-queue/queues.mdx
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  test/queues/int.spec.ts
Labels: created-by: Payload team

#9878 fix(next): next.js 15.1.0 compatibility by not importing isRedirectError from next/dist
  packages/next/src/views/Document/index.tsx
Labels: created-by: Payload team

#9866 feat: consolidates create and duplicate operations
  docs/local-api/overview.mdx
  packages/graphql/src/resolvers/collections/create.ts
  packages/graphql/src/resolvers/collections/duplicate.ts
  packages/graphql/src/schema/initCollections.ts
  packages/next/src/routes/rest/collections/duplicate.ts
  packages/payload/src/collections/operations/create.ts
  packages/payload/src/collections/operations/duplicate.ts
  packages/payload/src/collections/operations/local/create.ts
  packages/payload/src/collections/operations/local/duplicate.ts
  packages/payload/src/duplicateDocument/index.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/uploads/generateFileData.ts
Labels: created-by: Payload team

#9871 fix: forgotPassword set expiration time
  packages/payload/src/auth/operations/forgotPassword.ts
  test/access-control/int.spec.ts
  test/auth/config.ts
  test/auth/int.spec.ts
Labels: created-by: Payload team

#9867 feat(next): adds `suppressHydrationWarning` property to payload config admin options
  docs/admin/overview.mdx
  packages/next/src/layouts/Root/index.tsx
  packages/payload/src/config/types.ts
Labels: created-by: Payload team

#9892 fix: ensures autosave only runs sequentially
  packages/ui/src/elements/Autosave/index.tsx
Labels: created-by: Payload team

#9868 fix(next): thread default ServerProps to view actions and other components that were missing
  packages/next/src/templates/Default/index.tsx
  packages/next/src/views/Document/renderDocumentSlots.tsx
  packages/payload/src/config/types.ts
Labels: created-by: Contributor

#9849 feat: expose `session` / `db` in migrations to use the active transaction with the database directly
  docs/database/migrations.mdx
  docs/database/transactions.mdx
  packages/db-mongodb/src/createMigration.ts
  packages/db-mongodb/src/types.ts
  packages/db-postgres/src/exports/migration-utils.ts
  packages/db-postgres/src/index.ts
  packages/db-sqlite/src/createMigration.ts
  packages/db-sqlite/src/getMigrationTemplate.ts
  packages/db-sqlite/src/index.ts
  packages/db-sqlite/src/requireDrizzleKit.ts
  packages/db-sqlite/src/types.ts
  packages/db-vercel-postgres/src/exports/migration-utils.ts
  packages/db-vercel-postgres/src/index.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/fetchAndResave/index.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/fetchAndResave/traverseFields.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/groupUpSQLStatements.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/index.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/migrateRelationships.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/traverseFields.ts
  packages/db-vercel-postgres/src/predefinedMigrations/v2-v3/types.ts
  packages/drizzle/src/exports/postgres.ts
  packages/drizzle/src/index.ts
  packages/drizzle/src/migrateDown.ts
  packages/drizzle/src/migrateFresh.ts
  packages/drizzle/src/migrateRefresh.ts
  packages/drizzle/src/migrateReset.ts
  packages/drizzle/src/postgres/createMigration.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/fetchAndResave/index.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/fetchAndResave/traverseFields.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/groupUpSQLStatements.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/index.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/migrateRelationships.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/traverseFields.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/types.ts
  packages/drizzle/src/postgres/requireDrizzleKit.ts
  packages/drizzle/src/postgres/types.ts
  packages/drizzle/src/types.ts
  packages/drizzle/src/utilities/buildCreateMigration.ts
  packages/drizzle/src/utilities/getMigrationTemplate.ts
  packages/payload/src/database/migrations/migrate.ts
  packages/payload/src/database/migrations/migrateDown.ts
  packages/payload/src/database/migrations/migrateRefresh.ts
  packages/payload/src/database/migrations/migrateReset.ts
  packages/payload/src/database/types.ts
Labels: created-by: Payload team

#9896 refactor(richtext-lexical): export useBlockComponentContext and useInlineBlockComponentContext
  packages/richtext-lexical/src/exports/client/index.ts
Labels: created-by: Payload team

#9898 fix: cannot pass function to client error when defining server-only props in custom field components
  packages/payload/src/fields/config/client.ts
  test/fields/collections/Array/index.ts
Labels: created-by: Payload team

#9900 templates: bump for v3.6.0
  templates/with-postgres/src/migrations/20241211_181852_initial.json
  templates/with-postgres/src/migrations/20241211_181852_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20241211_181826_initial.json
  templates/with-vercel-postgres/src/migrations/20241211_181826_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/src/migrations/20241211_181841_initial.json
  templates/with-vercel-website/src/migrations/20241211_181841_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#9897 feat: allows excluding entities from the nav sidebar / dashboard without disabling its routes
  docs/admin/collections.mdx
  docs/admin/globals.mdx
  packages/payload/src/collections/config/types.ts
  packages/payload/src/globals/config/types.ts
  packages/ui/src/utilities/groupNavItems.ts
  test/admin/collections/NotInView.ts
  test/admin/config.ts
  test/admin/e2e/1/e2e.spec.ts
  test/admin/globals/NotInView.ts
  test/admin/slugs.ts
Labels: created-by: Payload team

#9899 refactor(ui): export TableColumnsProvider, documentDrawerBaseClass and SelectMany
  packages/ui/src/elements/DocumentDrawer/DrawerHeader/index.tsx
  packages/ui/src/elements/DocumentDrawer/index.tsx
  packages/ui/src/exports/client/index.ts
Labels: created-by: Payload team

#9903 templates: bump nextjs version to 15.1
  templates/website/next-env.d.ts
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-vercel-website/package.json
Labels: created-by: Payload team

#9908 fix(translations): capitalized swedish 'collapseAll' translation
  packages/translations/src/languages/sv.ts
Labels: created-by: Contributor

#9910 templates: fix preview path protocol not being https in production environments
  templates/website/src/utilities/generatePreviewPath.ts
  templates/with-vercel-website/src/utilities/generatePreviewPath.ts
Labels: created-by: Payload team

#9907 refactor(ui): migrates away from React.forwardRef
  packages/next/src/views/LivePreview/IFrame/index.tsx
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Button/types.ts
  packages/ui/src/elements/EditUpload/index.tsx
  packages/ui/src/elements/Gutter/index.tsx
  packages/ui/src/forms/Submit/index.tsx
  packages/ui/src/utilities/getClientConfig.ts
Labels: created-by: Payload team

#9912 templates: change names of data variables to improve clarity between data and elements
  templates/website/src/Footer/Component.tsx
  templates/website/src/Header/Component.client.tsx
  templates/website/src/Header/Component.tsx
  templates/website/src/Header/Nav/index.tsx
  templates/with-vercel-website/src/Footer/Component.tsx
  templates/with-vercel-website/src/Header/Component.client.tsx
  templates/with-vercel-website/src/Header/Component.tsx
  templates/with-vercel-website/src/Header/Nav/index.tsx
Labels: created-by: Payload team

#9911 fix(ui): truncates richtext fields when displaying within a joins field
  packages/ui/src/elements/RelationshipTable/index.scss
Labels: created-by: Payload team

#9916 fix(db-postgres): `payload.db.upsert` inserts new rows instead of updating existing ones
  packages/drizzle/src/update.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#9920 feat(ui): allow customizing min height of code editor
  packages/ui/src/elements/CodeEditor/CodeEditor.tsx
  packages/ui/src/elements/CodeEditor/types.ts
Labels: created-by: Payload team

#9921 chore: export JobLog and importHandlerPath, add missing id type to JobLog
  packages/payload/src/index.ts
  packages/payload/src/queues/config/types/workflowTypes.ts
Labels: created-by: Payload team

#9926 docs: update Lexical to JSX documentation for RichText component
  docs/lexical/converters.mdx
  packages/richtext-lexical/src/exports/react/components/RichText/index.tsx
Labels: created-by: Payload team

#9872 feat: allow loading predefined migrations from proper exports
  packages/payload/src/database/migrations/getPredefinedMigration.ts
Labels: created-by: Payload team

#9931 chore(translations): improve password reset message
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
Labels: created-by: Payload team

#9942 chore: update what-is-payload.mdx
  docs/getting-started/what-is-payload.mdx
Labels: created-by: Contributor

#9936 templates: set up prettier, bump next to 15.1.0, bump eslint to v9, set up .vscode configs
  templates/_template/.eslintrc.cjs
  templates/_template/.vscode/extensions.json
  templates/_template/.vscode/launch.json
  templates/_template/.vscode/settings.json
  templates/_template/eslint.config.mjs
  templates/_template/package.json
  templates/blank/.eslintrc.cjs
  templates/blank/.vscode/extensions.json
  templates/blank/.vscode/launch.json
  templates/blank/.vscode/settings.json
  templates/blank/eslint.config.mjs
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/.eslintignore
  templates/website/.eslintrc.cjs
  templates/website/.vscode/extensions.json
  templates/website/.vscode/settings.json
  templates/website/eslint.config.mjs
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-payload-cloud/.eslintrc.cjs
  templates/with-payload-cloud/.vscode/extensions.json
  templates/with-payload-cloud/.vscode/launch.json
  templates/with-payload-cloud/.vscode/settings.json
  templates/with-payload-cloud/eslint.config.mjs
  templates/with-payload-cloud/package.json
  templates/with-postgres/.eslintrc.cjs
  templates/with-postgres/.vscode/extensions.json
  templates/with-postgres/.vscode/launch.json
  templates/with-postgres/.vscode/settings.json
  templates/with-postgres/eslint.config.mjs
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/.eslintrc.cjs
  templates/with-vercel-mongodb/.vscode/extensions.json
  templates/with-vercel-mongodb/.vscode/launch.json
  templates/with-vercel-mongodb/.vscode/settings.json
  templates/with-vercel-mongodb/eslint.config.mjs
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/.eslintrc.cjs
  templates/with-vercel-postgres/.vscode/extensions.json
  templates/with-vercel-postgres/.vscode/launch.json
  templates/with-vercel-postgres/.vscode/settings.json
  templates/with-vercel-postgres/eslint.config.mjs
  templates/with-vercel-postgres/package.json
  templates/with-vercel-website/.eslintignore
  templates/with-vercel-website/.eslintrc.cjs
  templates/with-vercel-website/.vscode/extensions.json
  templates/with-vercel-website/.vscode/settings.json
  templates/with-vercel-website/eslint.config.mjs
  templates/with-vercel-website/package.json
Labels: created-by: Payload team

#9943 templates: fix build by reducing strictness of eslint rules
  templates/_template/eslint.config.mjs
  templates/blank/eslint.config.mjs
  templates/blank/pnpm-lock.yaml
  templates/website/eslint.config.mjs
  templates/website/src/utilities/generatePreviewPath.ts
  templates/with-payload-cloud/eslint.config.mjs
  templates/with-postgres/eslint.config.mjs
  templates/with-vercel-mongodb/eslint.config.mjs
  templates/with-vercel-postgres/eslint.config.mjs
  templates/with-vercel-website/eslint.config.mjs
  templates/with-vercel-website/src/utilities/generatePreviewPath.ts
Labels: created-by: Payload team

#9929 docs: refactor and improve rich text docs
  docs/fields/rich-text.mdx
  docs/lexical/overview.mdx
  docs/rich-text/building-custom-features.mdx
  docs/rich-text/converters.mdx
  docs/rich-text/lexical.mdx
  docs/rich-text/migration.mdx
  docs/rich-text/overview.mdx
  docs/rich-text/slate.mdx
Labels: created-by: Payload team

#9945 docs: fix mdx error
  docs/admin/overview.mdx
Labels: created-by: Payload team

#9948 chore: use non-permanent / => /admin redirect so that the browser doesn't cache it for projects that don't redirect
  next.config.mjs
Labels: created-by: Payload team

#9946 fix: updates username validation to allow for all special character usage
  packages/payload/src/fields/validations.ts
Labels: created-by: Payload team

#9950 feat: add waitUntil property to payload.jobs.queue
  packages/payload/src/queues/localAPI.ts
Labels: created-by: Payload team

#9952 feat: expose `pagination: false` to REST / GraphQL
  packages/graphql/src/resolvers/collections/find.ts
  packages/graphql/src/resolvers/collections/findVersions.ts
  packages/graphql/src/resolvers/globals/findVersions.ts
  packages/graphql/src/schema/initCollections.ts
  packages/graphql/src/schema/initGlobals.ts
  packages/next/src/routes/rest/collections/find.ts
  packages/next/src/routes/rest/collections/findVersions.ts
  packages/next/src/routes/rest/globals/findVersions.ts
Labels: created-by: Payload team

#9934 chore(payload-cloud): improve error log of staticHandler
  packages/payload-cloud/src/staticHandler.ts
Labels: created-by: Payload team

#9957 test: mock nodemailer network calls
  packages/payload-cloud/src/email.spec.ts
  packages/payload-cloud/src/plugin.spec.ts
  pnpm-lock.yaml
  test/jest.setup.js
  test/package.json
Labels: created-by: Payload team

#9933 fix(ui): awaits form state before rendering conditional fields
  packages/payload/src/admin/forms/Form.ts
  packages/ui/src/fields/Array/ArrayRow.tsx
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/BlockRow.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/forms/Form/fieldReducer.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  packages/ui/src/forms/useField/index.tsx
  packages/ui/src/forms/withCondition/WatchCondition.tsx
  packages/ui/src/hooks/useThrottledValue.ts
  packages/ui/src/views/Edit/Auth/index.tsx
  test/fields/collections/ConditionalLogic/index.ts
  test/fields/e2e.spec.ts
Labels: created-by: Payload team

#9958 fix(plugin-nested-docs): publishing parent doc should not publish child doc
  packages/plugin-nested-docs/src/hooks/resaveChildren.ts
  test/plugin-nested-docs/e2e.spec.ts
Labels: created-by: Payload team

#9959 test: splits remaining field tests
  .github/workflows/main.yml
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Collapsible/e2e.spec.ts
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  test/fields/collections/ConditionalLogic/index.ts
  test/fields/collections/ConditionalLogic/shared.ts
  test/fields/collections/CustomID/e2e.spec.ts
  test/fields/collections/Indexed/e2e.spec.ts
  test/fields/collections/JSON/e2e.spec.ts
  test/fields/collections/Radio/e2e.spec.ts
  test/fields/collections/Row/e2e.spec.ts
  test/fields/collections/Select/e2e.spec.ts
  test/fields/collections/Tabs/e2e.spec.ts
  test/fields/collections/Tabs2/e2e.spec.ts
  test/fields/collections/UI/e2e.spec.ts
  test/fields/e2e.spec.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#9928 fix(ui): automatically subscribes custom fields to conditional logic
  packages/payload/src/queues/localAPI.ts
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-slate/src/field/RichText.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/forms/RenderFields/RenderField.tsx
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/forms/withCondition/WatchCondition.tsx
  packages/ui/src/forms/withCondition/index.tsx
  templates/_template/.vscode/settings.json
  templates/_template/package.json
  templates/blank/.vscode/settings.json
  templates/blank/package.json
  templates/website/.vscode/settings.json
  templates/website/package.json
  templates/with-payload-cloud/.vscode/settings.json
  templates/with-payload-cloud/package.json
  templates/with-postgres/.vscode/settings.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/.vscode/settings.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/.vscode/settings.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-website/.vscode/settings.json
  templates/with-vercel-website/package.json
  test/fields/collections/ConditionalLogic/CustomClientField.tsx
  test/fields/collections/ConditionalLogic/CustomFieldWithField.tsx
  test/fields/collections/ConditionalLogic/CustomFieldWithHOC.tsx
  test/fields/collections/ConditionalLogic/CustomServerField.tsx
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  test/fields/collections/ConditionalLogic/index.ts
  test/fields/collections/ConditionalLogic/shared.ts
  test/fields/components/CustomField.tsx
Labels: created-by: Payload team

#9963 fix: job collection was not added if job config only has workflows and no predefined tasks
  packages/payload/src/config/sanitize.ts
  packages/payload/src/queues/config/jobsCollection.ts
Labels: created-by: Payload team

#9966 templates: bump for v3.7.0
  templates/blank/pnpm-lock.yaml
  templates/website/pnpm-lock.yaml
  templates/with-postgres/src/migrations/20241213_192425_initial.json
  templates/with-postgres/src/migrations/20241213_192425_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20241213_192401_initial.json
  templates/with-vercel-postgres/src/migrations/20241213_192401_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/next-env.d.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/migrations/20241213_192414_initial.json
  templates/with-vercel-website/src/migrations/20241213_192414_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#9962 refactor(plugin-seo): strongly type collection and global slugs in plugin config
  packages/plugin-seo/src/types.ts
Labels: created-by: Payload team

#9955 feat(graphql): graphQL custom field complexity and validationRules
  docs/fields/join.mdx
  docs/fields/relationship.mdx
  docs/fields/upload.mdx
  docs/graphql/overview.mdx
  packages/graphql/src/index.ts
  packages/graphql/src/schema/buildObjectType.ts
  packages/payload/src/config/types.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/types.ts
  test/graphql/config.ts
  test/graphql/eslint.config.js
  test/graphql/int.spec.ts
  test/graphql/payload-types.ts
  test/graphql/schema.graphql
  test/graphql/tsconfig.eslint.json
  test/graphql/tsconfig.json
Labels: created-by: Payload team

#9969 templates: fixes formatting issue with authors and footer not being at the bottom in the website template
  templates/website/src/Footer/Component.tsx
  templates/website/src/app/(frontend)/globals.css
  templates/website/src/heros/PostHero/index.tsx
  templates/website/src/utilities/formatAuthors.ts
  templates/with-vercel-website/src/Footer/Component.tsx
  templates/with-vercel-website/src/app/(frontend)/globals.css
  templates/with-vercel-website/src/heros/PostHero/index.tsx
  templates/with-vercel-website/src/utilities/formatAuthors.ts
Labels: created-by: Payload team

#9968 ci: wait until version resolves in post-release-templates
  .github/workflows/post-release-templates.yml
  .github/workflows/wait-until-package-version.sh
Labels: created-by: Payload team

#9967 chore(deps): bumps react-select to v5.9.0 to surpress react 19 warnings
  examples/form-builder/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#9973 templates: conditionally render the live preview listener component
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/[slug]/page.tsx
  templates/with-vercel-website/src/app/(frontend)/posts/[slug]/page.tsx
Labels: created-by: Payload team

#9971 fix: edit join field not rendering
  .github/workflows/main.yml
  packages/ui/src/utilities/buildTableState.ts
  test/joins/e2e.spec.ts
  test/joins/payload-types.ts
Labels: created-by: Payload team

#9982 feat: join field admin.defaultColumns
  docs/fields/join.mdx
  packages/payload/src/admin/functions/index.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/RelationshipTable/index.tsx
  test/joins/collections/Categories.ts
  test/joins/e2e.spec.ts
Labels: created-by: Payload team

#9989 fix(db-sqlite): working point field CRUD and default value
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/db-sqlite/src/schema/withDefault.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#9672 fix: remove `localized` property from `RowField` and `CollapsibleField`
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
Labels: created-by: Payload team

#9987 refactor: deduplicate and abstract SQL schema building
  packages/db-postgres/src/index.ts
  packages/db-sqlite/src/index.ts
  packages/db-sqlite/src/init.ts
  packages/db-sqlite/src/schema/build.ts
  packages/db-sqlite/src/schema/buildDrizzleTable.ts
  packages/db-sqlite/src/schema/createIndex.ts
  packages/db-sqlite/src/schema/getIDColumn.ts
  packages/db-sqlite/src/schema/setColumnID.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/db-sqlite/src/schema/withDefault.ts
  packages/db-sqlite/src/types.ts
  packages/db-vercel-postgres/src/index.ts
  packages/drizzle/src/index.ts
  packages/drizzle/src/postgres/init.ts
  packages/drizzle/src/postgres/schema/build.ts
  packages/drizzle/src/postgres/schema/buildDrizzleTable.ts
  packages/drizzle/src/postgres/schema/createIndex.ts
  packages/drizzle/src/postgres/schema/idToUUID.ts
  packages/drizzle/src/postgres/schema/parentIDColumnMap.ts
  packages/drizzle/src/postgres/schema/setColumnID.ts
  packages/drizzle/src/postgres/schema/withDefault.ts
  packages/drizzle/src/schema/build.ts
  packages/drizzle/src/schema/buildDrizzleRelations.ts
  packages/drizzle/src/schema/buildRawSchema.ts
  packages/drizzle/src/schema/idToUUID.ts
  packages/drizzle/src/schema/traverseFields.ts
  packages/drizzle/src/schema/withDefault.ts
  packages/drizzle/src/types.ts
  packages/drizzle/src/utilities/executeSchemaHooks.ts
  packages/drizzle/src/utilities/validateExistingBlockIsIdentical.ts
Labels: created-by: Payload team

#9870 perf: reduce generated types for select by respecting `interfaceName`
  packages/payload/src/utilities/addSelectGenericsToGeneratedTypes.spec.ts
  packages/payload/src/utilities/addSelectGenericsToGeneretedTypes.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  test/auth/payload-types.ts
  test/fields/collections/Blocks/index.ts
  test/fields/payload-types.ts
  test/graphql-schema-gen/payload-types.ts
Labels: created-by: Payload team

#9937 feat: expose `req` to `defaultValue` function arguments
  docs/fields/overview.mdx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/getDefaultValue.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/types/index.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/index.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/iterateFields.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/promise.ts
  packages/ui/src/forms/fieldSchemasToFormState/index.tsx
  test/fields/collections/Text/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#9999 templates: add hero image field to posts instead of using the meta image for the hero as well
  templates/website/src/blocks/RenderBlocks.tsx
  templates/website/src/collections/Posts/index.ts
  templates/website/src/components/ui/card.tsx
  templates/website/src/components/ui/pagination.tsx
  templates/website/src/endpoints/seed/image-hero-1.ts
  templates/website/src/endpoints/seed/index.ts
  templates/website/src/endpoints/seed/post-1.ts
  templates/website/src/endpoints/seed/post-2.ts
  templates/website/src/endpoints/seed/post-3.ts
  templates/website/src/heros/PostHero/index.tsx
  templates/website/src/payload-types.ts
  templates/website/src/providers/Theme/types.ts
Labels: created-by: Payload team

#10001 templates: fix missing ts-ignore in seed script causing build errors
  templates/website/src/endpoints/seed/post-1.ts
  templates/website/src/endpoints/seed/post-2.ts
  templates/website/src/endpoints/seed/post-3.ts
  templates/with-vercel-website/src/endpoints/seed/post-1.ts
  templates/with-vercel-website/src/endpoints/seed/post-2.ts
  templates/with-vercel-website/src/endpoints/seed/post-3.ts
Labels: created-by: Payload team

#9972 docs: fix links in rich-text referencing old lexical sections
  docs/rich-text/building-custom-features.mdx
  docs/rich-text/overview.mdx
Labels: created-by: Contributor

#10003 fix(templates): adds priority to hero images
  templates/website/src/heros/HighImpact/index.tsx
  templates/website/src/heros/MediumImpact/index.tsx
  templates/website/src/heros/PostHero/index.tsx
  templates/with-vercel-website/src/heros/HighImpact/index.tsx
  templates/with-vercel-website/src/heros/MediumImpact/index.tsx
  templates/with-vercel-website/src/heros/PostHero/index.tsx
Labels: created-by: Payload team

#10005 feat(storage-vercel-blob): allow fallback to disk if token not set
  packages/storage-vercel-blob/src/index.ts
  test/storage-vercel-blob/collections/Media.ts
Labels: created-by: Payload team

#10002 fix(ui): does not render row labels until form state returns
  packages/ui/src/fields/Array/ArrayRow.tsx
  packages/ui/src/fields/Blocks/BlockRow.tsx
  packages/ui/src/forms/RowLabel/Context/index.tsx
  test/fields/collections/Array/LabelComponent.tsx
  test/fields/collections/Array/e2e.spec.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#9771 feat(db-vercel-postgres): allow to use a local database using `pg` instead of `@vercel/postgres`
  docs/database/postgres.mdx
  packages/db-vercel-postgres/src/connect.ts
  packages/db-vercel-postgres/src/index.ts
  packages/db-vercel-postgres/src/types.ts
Labels: created-by: Payload team
