Repository payloadcms/payload, pull requests merged in 2024-05, with the labels that each got.

#3804 docs: slate linebreak serialization in 'Generating HTML' example
  docs/rich-text/slate.mdx
Labels: plugin: richtext-slate

#6466 fix: isHotkey webpack error
  packages/richtext-slate/package.json
  packages/richtext-slate/src/field/RichText.tsx
  pnpm-lock.yaml
Labels: created-by: Payload team

#6467 feat(richtext-lexical): various UX and performance improvements
  packages/email-nodemailer/README.md
  packages/email-resend/README.md
  packages/richtext-lexical/src/field/features/link/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/handles/AddBlockHandlePlugin/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/handles/DraggableBlockPlugin/index.scss
  packages/richtext-lexical/src/field/lexical/plugins/handles/DraggableBlockPlugin/index.tsx
  packages/richtext-lexical/src/field/lexical/plugins/handles/DraggableBlockPlugin/setTargetLine.ts
  packages/richtext-lexical/src/field/lexical/ui/ContentEditable.scss
  packages/ui/src/elements/Tooltip/index.scss
Labels: created-by: Payload team

#6476 fix: adds host to initPage req creation
  packages/next/src/utilities/initPage/index.ts
Labels: created-by: Contributor

#6471 feat(ui): split up Select component into Select and SelectInput
  packages/ui/src/fields/Checkbox/Input.tsx
  packages/ui/src/fields/Checkbox/index.tsx
  packages/ui/src/fields/Select/Input.tsx
  packages/ui/src/fields/Select/index.tsx
Labels: created-by: Payload team

#6478 fix(ui): where builder issues
  packages/ui/src/elements/RenderCustomClientComponent/index.tsx
  packages/ui/src/elements/RenderCustomComponent/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  test/fields/collections/Text/e2e.spec.ts
Labels: created-by: Contributor

#6480 chore: website template updates
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/globals.css
  templates/website/src/app/(frontend)/not-found.tsx
  templates/website/src/app/(frontend)/page.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.client.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/page.tsx
  templates/website/src/app/(frontend)/posts/page/[pageNumber]/page.tsx
  templates/website/src/app/blocks/Form/Email/index.tsx
  templates/website/src/app/blocks/Form/index.tsx
  templates/website/src/app/components/Card/index.tsx
  templates/website/src/app/components/Header/Nav/index.tsx
  templates/website/src/app/utilities/useClickableCard.ts
  templates/website/src/payload/seed/home.ts
Labels: created-by: Contributor

#6488 chore(templates): remove blank v2 template
  templates/blank/.env.example
  templates/blank/.gitignore
  templates/blank/Dockerfile
  templates/blank/README.md
  templates/blank/docker-compose.yml
  templates/blank/nodemon.json
  templates/blank/package.json
  templates/blank/src/collections/Users.ts
  templates/blank/src/payload.config.ts
  templates/blank/src/server.ts
  templates/blank/tsconfig.json
  templates/blank/yarn.lock
Labels: created-by: Payload team

#6489 fix(richtext-lexical): localized sub-fields were omitted from the API output
  packages/richtext-lexical/src/field/features/blocks/populationPromise.ts
  packages/richtext-lexical/src/field/features/link/populationPromise.ts
  packages/richtext-lexical/src/field/features/upload/populationPromise.ts
Labels: created-by: Payload team

#6491 chore: fix seed data validation in website template
  templates/website/src/payload.config.ts
Labels: created-by: Contributor

#6490 chore(cpa): adjust unit test template
  packages/create-payload-app/src/lib/create-project.spec.ts
Labels: created-by: Payload team

#6494 chore(templates): enable next lint on blank
  templates/blank-3.0/.eslintrc.cjs
  templates/blank-3.0/package.json
  templates/blank-3.0/pnpm-lock.yaml
  templates/blank-3.0/yarn.lock
Labels: created-by: Payload team

#6453 chore: db-example updates
  packages/db-example/README.md
  packages/db-example/src/connect.ts
  packages/db-example/src/count.ts
  packages/db-example/src/create.ts
  packages/db-example/src/createGlobal.ts
  packages/db-example/src/createGlobalVersion.ts
  packages/db-example/src/createMigration.ts
  packages/db-example/src/createVersion.ts
  packages/db-example/src/deleteMany.ts
  packages/db-example/src/deleteOne.ts
  packages/db-example/src/deleteVersions.ts
  packages/db-example/src/destroy.ts
  packages/db-example/src/errors/handleError.ts
  packages/db-example/src/find.ts
  packages/db-example/src/findGlobal.ts
  packages/db-example/src/findGlobalVersions.ts
  packages/db-example/src/findOne.ts
  packages/db-example/src/findVersions.ts
  packages/db-example/src/index.ts
  packages/db-example/src/init.ts
  packages/db-example/src/migrateFresh.ts
  packages/db-example/src/models/buildCollectionSchema.ts
  packages/db-example/src/models/buildGlobalModel.ts
  packages/db-example/src/models/buildSchema.ts
  packages/db-example/src/queries/buildAndOrConditions.ts
  packages/db-example/src/queries/buildQuery.ts
  packages/db-example/src/queries/buildSearchParams.ts
  packages/db-example/src/queries/buildSortParam.ts
  packages/db-example/src/queries/getLocalizedSortProperty.spec.ts
  packages/db-example/src/queries/getLocalizedSortProperty.ts
  packages/db-example/src/queries/mock.js
  packages/db-example/src/queries/operatorMap.ts
  packages/db-example/src/queries/parseParams.ts
  packages/db-example/src/queries/sanitizeQueryValue.ts
  packages/db-example/src/queryDrafts.ts
  packages/db-example/src/testCredentials.ts
  packages/db-example/src/transactions/beginTransaction.ts
  packages/db-example/src/transactions/commitTransaction.ts
  packages/db-example/src/transactions/rollbackTransaction.ts
  packages/db-example/src/types.ts
  packages/db-example/src/updateGlobal.ts
  packages/db-example/src/updateGlobalVersion.ts
  packages/db-example/src/updateOne.ts
  packages/db-example/src/updateVersion.ts
  packages/db-example/src/utilities/getDBName.ts
  packages/db-example/src/utilities/handleError.ts
  packages/db-example/src/utilities/sanitizeInternalFields.ts
  packages/db-example/src/withSession.ts
Labels: created-by: Payload team

#6495 chore: db-example
  packages/db-example/.eslintignore
  packages/db-example/.eslintrc.js
  packages/db-example/.gitignore
  packages/db-example/.prettierignore
  packages/db-example/.swcrc
  packages/db-example/README.md
  packages/db-example/package.json
  packages/db-example/src/connect.ts
  packages/db-example/src/count.ts
  packages/db-example/src/create.ts
  packages/db-example/src/createGlobal.ts
  packages/db-example/src/createGlobalVersion.ts
  packages/db-example/src/createVersion.ts
  packages/db-example/src/deleteMany.ts
  packages/db-example/src/deleteOne.ts
  packages/db-example/src/deleteVersions.ts
  packages/db-example/src/destroy.ts
  packages/db-example/src/errors/handleError.ts
  packages/db-example/src/find.ts
  packages/db-example/src/findGlobal.ts
  packages/db-example/src/findGlobalVersions.ts
  packages/db-example/src/findOne.ts
  packages/db-example/src/findVersions.ts
  packages/db-example/src/index.ts
  packages/db-example/src/init.ts
  packages/db-example/src/queryDrafts.ts
  packages/db-example/src/transactions/beginTransaction.ts
  packages/db-example/src/transactions/commitTransaction.ts
  packages/db-example/src/transactions/rollbackTransaction.ts
  packages/db-example/src/updateGlobal.ts
  packages/db-example/src/updateGlobalVersion.ts
  packages/db-example/src/updateOne.ts
  packages/db-example/src/updateVersion.ts
  packages/db-example/tsconfig.json
  pnpm-lock.yaml
Labels: created-by: Contributor

#6496 chore: add lexical as a direct dependency to the website template
  templates/website/package.json
  templates/website/pnpm-lock.yaml
Labels: created-by: Contributor

#6505 chore: swcrc syntax fix
  test/.swcrc
Labels: created-by: Contributor

#6508 chore: loader tests error on windows
  test/loader/load.js
  test/loader/startChildProcess.ts
Labels: created-by: Contributor

#6509 chore: gitignore static files uploads tests
  test/uploads/.gitignore
  test/uploads/config.ts
Labels: created-by: Contributor

#6510 chore: getPayloadHMR conditionally call db.connect
  packages/next/src/utilities/getPayloadHMR.ts
Labels: created-by: Contributor

#6512 chore: fix seed file path windows
  test/plugin-seo/seed/index.ts
Labels: created-by: Contributor

#6513 fix(next): unable to pass custom view client components
  packages/next/src/views/Root/index.tsx
Labels: created-by: Payload team

#6483 chore(ui): add ability to compile using react compiler
  packages/next/.swcrc
  packages/ui/.browserslistrc
  packages/ui/.swcrc
  packages/ui/babel.config.cjs
  packages/ui/package.json
  packages/ui/src/elements/ArrayAction/index.tsx
  packages/ui/src/elements/Banner/index.tsx
  packages/ui/src/elements/Card/index.tsx
  packages/ui/src/elements/CodeEditor/CodeEditor.tsx
  packages/ui/src/elements/CodeEditor/index.tsx
  packages/ui/src/elements/DatePicker/DatePicker.tsx
  packages/ui/src/elements/DatePicker/index.tsx
  packages/ui/src/elements/DraggableSortable/DraggableSortableItem/index.tsx
  packages/ui/src/elements/DraggableSortable/index.tsx
  packages/ui/src/elements/DraggableSortable/useDraggableSortable/index.tsx
  packages/ui/src/elements/Drawer/useDrawerSlug.tsx
  packages/ui/src/elements/Dropzone/index.tsx
  packages/ui/src/elements/ErrorPill/index.tsx
  packages/ui/src/elements/FieldSelect/index.tsx
  packages/ui/src/elements/FileDetails/FileMeta/index.tsx
  packages/ui/src/elements/FileDetails/index.tsx
  packages/ui/src/elements/IDLabel/index.tsx
  packages/ui/src/elements/Localizer/LocalizerLabel/index.tsx
  packages/ui/src/elements/Localizer/index.tsx
  packages/ui/src/elements/Pagination/ClickableArrow/index.tsx
  packages/ui/src/elements/Pagination/Page/index.tsx
  packages/ui/src/elements/Pagination/Separator/index.tsx
  packages/ui/src/elements/Popup/PopupTrigger/index.tsx
  packages/ui/src/elements/PreviewSizes/index.tsx
  packages/ui/src/elements/ReactSelect/ClearIndicator/index.tsx
  packages/ui/src/elements/ReactSelect/Control/index.tsx
  packages/ui/src/elements/ReactSelect/DropdownIndicator/index.tsx
  packages/ui/src/elements/ReactSelect/MultiValue/index.tsx
  packages/ui/src/elements/ReactSelect/MultiValueLabel/index.tsx
  packages/ui/src/elements/ReactSelect/MultiValueRemove/index.tsx
  packages/ui/src/elements/ReactSelect/SingleValue/index.tsx
  packages/ui/src/elements/ReactSelect/ValueContainer/index.tsx
  packages/ui/src/elements/RenderCustomClientComponent/index.tsx
  packages/ui/src/elements/SearchFilter/index.tsx
  packages/ui/src/elements/SortComplex/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Code/index.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/elements/TableColumns/filterFields.tsx
  packages/ui/src/elements/ThumbnailCard/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Date/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Number/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Select/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Text/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/elements/WhereBuilder/reduceFieldMap.tsx
  packages/ui/src/fields/Array/ArrayRow.tsx
  packages/ui/src/fields/Blocks/BlocksDrawer/BlockSearch/index.tsx
  packages/ui/src/fields/Blocks/SectionTitle/index.tsx
  pnpm-lock.yaml
Labels: created-by: Payload team

#6525 feat(richtext-lexical): update validation of custom URLs to include relative and anchor links
  packages/richtext-lexical/src/field/lexical/utils/url.ts
Labels: created-by: Contributor

#6524 feat(richtext-lexical): i18n support
  packages/next/src/views/Account/index.tsx
  packages/payload/src/admin/RichText.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/richtext-lexical/package.json
  packages/richtext-lexical/scripts/translateNewKeys.ts
  packages/richtext-lexical/src/field/features/horizontalRule/feature.client.tsx
  packages/richtext-lexical/src/field/features/horizontalRule/feature.server.ts
  packages/richtext-lexical/src/field/features/horizontalRule/i18n.ts
  packages/richtext-lexical/src/field/features/toolbars/types.ts
  packages/richtext-lexical/src/field/features/types.ts
  packages/richtext-lexical/src/field/lexical/config/server/sanitize.ts
  packages/richtext-lexical/src/field/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/types.ts
  packages/richtext-lexical/src/index.ts
  packages/translations/package.json
  packages/translations/scripts/translateNewKeys/index.ts
  packages/translations/scripts/translateNewKeys/run.ts
Labels: plugin: richtext-lexical, created-by: Payload team

#6193 feat(cpa): update existing payload installation
  packages/create-payload-app/src/lib/get-package-manager.ts
  packages/create-payload-app/src/lib/init-next.ts
  packages/create-payload-app/src/lib/install-packages.ts
  packages/create-payload-app/src/lib/update-payload-in-project.ts
  packages/create-payload-app/src/main.ts
  packages/create-payload-app/src/types.ts
Labels: created-by: Payload team

#6536 chore(templates): update dockerfile and docker-compose for blank template
  templates/blank-3.0/Dockerfile
  templates/blank-3.0/docker-compose.yml
Labels: created-by: Payload team

#6539 chore: adjust email-nodemailer workspace dep pattern
  packages/plugin-cloud/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#6541 ci: update app-build-with-packed job
  .github/workflows/main.yml
  scripts/pack-all-to-dest.ts
Labels: created-by: Payload team

#6497 feat(plugin-form-builder)!: update form builder plugin field overrides to use a function instead
  packages/plugin-form-builder/src/collections/FormSubmissions/index.ts
  packages/plugin-form-builder/src/collections/Forms/index.ts
  packages/plugin-form-builder/src/index.ts
  packages/plugin-form-builder/src/types.ts
  test/plugin-form-builder/config.ts
Labels: created-by: Contributor

#6542 feat(richtext-lexical): i18n
  packages/richtext-lexical/src/field/features/align/feature.client.tsx
  packages/richtext-lexical/src/field/features/align/feature.server.ts
  packages/richtext-lexical/src/field/features/align/i18n.ts
  packages/richtext-lexical/src/field/features/blockquote/feature.client.tsx
  packages/richtext-lexical/src/field/features/blockquote/feature.server.ts
  packages/richtext-lexical/src/field/features/blockquote/i18n.ts
  packages/richtext-lexical/src/field/features/blocks/feature.client.tsx
  packages/richtext-lexical/src/field/features/blocks/feature.server.ts
  packages/richtext-lexical/src/field/features/blocks/i18n.ts
  packages/richtext-lexical/src/field/features/heading/feature.client.tsx
  packages/richtext-lexical/src/field/features/heading/feature.server.ts
  packages/richtext-lexical/src/field/features/heading/i18n.ts
  packages/richtext-lexical/src/field/features/horizontalRule/feature.client.tsx
  packages/richtext-lexical/src/field/features/indent/feature.client.tsx
  packages/richtext-lexical/src/field/features/indent/feature.server.ts
  packages/richtext-lexical/src/field/features/indent/i18n.ts
  packages/richtext-lexical/src/field/features/link/feature.client.tsx
  packages/richtext-lexical/src/field/features/link/feature.server.ts
  packages/richtext-lexical/src/field/features/link/i18n.ts
  packages/richtext-lexical/src/field/features/lists/checklist/feature.client.tsx
  packages/richtext-lexical/src/field/features/lists/checklist/feature.server.ts
  packages/richtext-lexical/src/field/features/lists/checklist/i18n.ts
  packages/richtext-lexical/src/field/features/lists/orderedList/feature.client.tsx
  packages/richtext-lexical/src/field/features/lists/orderedList/feature.server.ts
  packages/richtext-lexical/src/field/features/lists/orderedList/i18n.ts
  packages/richtext-lexical/src/field/features/lists/shared/slashMenuListGroup.ts
  packages/richtext-lexical/src/field/features/lists/unorderedList/feature.client.tsx
  packages/richtext-lexical/src/field/features/lists/unorderedList/feature.server.ts
  packages/richtext-lexical/src/field/features/lists/unorderedList/i18n.ts
  packages/richtext-lexical/src/field/features/paragraph/feature.client.tsx
  packages/richtext-lexical/src/field/features/paragraph/feature.server.ts
  packages/richtext-lexical/src/field/features/paragraph/i18n.ts
  packages/richtext-lexical/src/field/features/relationship/feature.client.tsx
  packages/richtext-lexical/src/field/features/relationship/feature.server.ts
  packages/richtext-lexical/src/field/features/relationship/i18n.ts
  packages/richtext-lexical/src/field/features/shared/slashMenu/basicGroup.ts
  packages/richtext-lexical/src/field/features/upload/feature.client.tsx
  packages/richtext-lexical/src/field/features/upload/feature.server.ts
  packages/richtext-lexical/src/field/features/upload/i18n.ts
  packages/richtext-lexical/src/field/lexical/LexicalEditor.tsx
  packages/richtext-lexical/src/i18n.ts
  packages/richtext-lexical/src/index.ts
Labels: created-by: Payload team

#6543 feat(richtext-lexical): link markdown transformers
  packages/richtext-lexical/src/field/features/link/feature.client.tsx
  packages/richtext-lexical/src/field/features/link/feature.server.ts
  packages/richtext-lexical/src/field/features/link/markdownTransformer.ts
  pnpm-lock.yaml
  test/fields/collections/Lexical/index.ts
  test/fields/lexical.int.spec.ts
  test/fields/payload-types.ts
  test/package.json
Labels: created-by: Payload team

#6544 fix(richtext-lexical): various html converter fixes
  packages/richtext-lexical/src/field/features/converters/html/field/index.ts
  packages/richtext-lexical/src/field/features/link/feature.server.ts
  packages/richtext-lexical/src/field/features/lists/orderedList/feature.server.ts
Labels: created-by: Payload team

#6500 fix: multi value draggable/sortable pills
  packages/ui/src/elements/ReactSelect/MultiValue/index.tsx
  packages/ui/src/elements/ReactSelect/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
Labels: created-by: Contributor

#6556 docs: renames vercel visual editing to vercel content link
  docs/integrations/vercel-content-link.mdx
Labels: created-by: Payload team

#6561 fix: ensure relationship field pills respect isSortable property
  packages/ui/src/elements/ReactSelect/MultiValue/index.tsx
  packages/ui/src/providers/ComponentMap/buildComponentMap/fields.tsx
Labels: created-by: Contributor

#6475 docs: adds sentry to plugin docs
  docs/plugins/sentry.mdx
  packages/plugin-sentry/README.md
Labels: created-by: Payload team

#6564 chore: import vercel-postgres one-click template
  .eslintrc.cjs
  packages/create-payload-app/src/lib/templates.ts
  packages/live-preview-vue/.eslintrc.js
  templates/vercel-postgres/.env.example
  templates/vercel-postgres/.eslintignore
  templates/vercel-postgres/.eslintrc.json.bak
  templates/vercel-postgres/.gitignore
  templates/vercel-postgres/.prettierrc.json
  templates/vercel-postgres/.tool-versions
  templates/vercel-postgres/README.md
  templates/vercel-postgres/next.config.mjs
  templates/vercel-postgres/package.json
  templates/vercel-postgres/pnpm-lock.yaml
  templates/vercel-postgres/postcss.config.js
  templates/vercel-postgres/public/arrow.svg
  templates/vercel-postgres/public/blur.png
  templates/vercel-postgres/public/crosshair.svg
  templates/vercel-postgres/public/gradient.webp
  templates/vercel-postgres/public/next.svg
  templates/vercel-postgres/public/payload.svg
  templates/vercel-postgres/public/scanline-light.png
  templates/vercel-postgres/src/app/(app)/globals.scss
  templates/vercel-postgres/src/app/(app)/icon.svg
  templates/vercel-postgres/src/app/(app)/layout.tsx
  templates/vercel-postgres/src/app/(app)/page.tsx
  templates/vercel-postgres/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  templates/vercel-postgres/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/vercel-postgres/src/app/(payload)/api/[...slug]/route.ts
  templates/vercel-postgres/src/app/(payload)/api/graphql-playground/route.ts
  templates/vercel-postgres/src/app/(payload)/api/graphql/route.ts
  templates/vercel-postgres/src/app/(payload)/custom.scss
  templates/vercel-postgres/src/app/(payload)/layout.tsx
  templates/vercel-postgres/src/collections/Media.ts
  templates/vercel-postgres/src/collections/Users.ts
  templates/vercel-postgres/src/components/Background/index.tsx
  templates/vercel-postgres/src/components/Background/styles.module.scss
  templates/vercel-postgres/src/components/Links/index.tsx
  templates/vercel-postgres/src/components/Links/styles.module.scss
  templates/vercel-postgres/src/components/Logos/index.tsx
  templates/vercel-postgres/src/components/Logos/styles.module.scss
  templates/vercel-postgres/src/migrations/20240411_192848_initial.json
  templates/vercel-postgres/src/migrations/20240411_192848_initial.ts
  templates/vercel-postgres/src/migrations/20240412_190632_media.json
  templates/vercel-postgres/src/migrations/20240412_190632_media.ts
  templates/vercel-postgres/src/payload-types.ts
  templates/vercel-postgres/src/payload.config.ts
  templates/vercel-postgres/tailwind.config.ts
  templates/vercel-postgres/tsconfig.json
Labels: created-by: Payload team

#6557 fix: duplicate options appearing in relationship where builder
  next.config.mjs
  packages/payload/src/fields/validations.ts
  packages/ui/src/elements/ReactSelect/Input/index.tsx
  packages/ui/src/elements/ReactSelect/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/fields/Relationship/findOptionsByValue.ts
Labels: created-by: Contributor

#6568 chore(templates): consolidate initial vercel-postgres migration
  templates/vercel-postgres/src/migrations/20240412_190632_media.json
  templates/vercel-postgres/src/migrations/20240412_190632_media.ts
  templates/vercel-postgres/src/migrations/20240530_132905_initial.json
  templates/vercel-postgres/src/migrations/20240530_132905_initial.ts
Labels: created-by: Payload team

#6527 fix: adjusts sizing of remove/add buttons to be same size
  packages/payload/src/admin/components/icons/Plus/index.scss
  packages/payload/src/admin/components/icons/Plus/index.tsx
Labels: created-by: Contributor

#6566 fix(cpa): more package manager detection improvements
  packages/create-payload-app/src/lib/get-package-manager.ts
  templates/blank-3.0/pnpm-lock.yaml
Labels: created-by: Payload team

#6549 fix: adds new `userEmailAlreadyRegistered` translations
  packages/payload/src/auth/strategies/local/register.ts
  packages/payload/src/translations/ar.json
  packages/payload/src/translations/az.json
  packages/payload/src/translations/bg.json
  packages/payload/src/translations/cs.json
  packages/payload/src/translations/de.json
  packages/payload/src/translations/en.json
  packages/payload/src/translations/es.json
  packages/payload/src/translations/fa.json
  packages/payload/src/translations/fr.json
  packages/payload/src/translations/hr.json
  packages/payload/src/translations/hu.json
  packages/payload/src/translations/it.json
  packages/payload/src/translations/ja.json
  packages/payload/src/translations/ko.json
  packages/payload/src/translations/my.json
  packages/payload/src/translations/nb.json
  packages/payload/src/translations/nl.json
  packages/payload/src/translations/pl.json
  packages/payload/src/translations/pt.json
  packages/payload/src/translations/ro.json
  packages/payload/src/translations/rs-latin.json
  packages/payload/src/translations/rs.json
  packages/payload/src/translations/ru.json
  packages/payload/src/translations/sv.json
  packages/payload/src/translations/th.json
  packages/payload/src/translations/tr.json
  packages/payload/src/translations/translation-schema.json
  packages/payload/src/translations/ua.json
  packages/payload/src/translations/vi.json
  packages/payload/src/translations/zh-tw.json
  packages/payload/src/translations/zh.json
  test/collections-graphql/int.spec.ts
Labels: created-by: Contributor

#6550 fix(translations): adds new `userEmailAlreadyRegistered` translations
  packages/payload/src/auth/strategies/local/register.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  test/collections-graphql/int.spec.ts
Labels: created-by: Contributor

#6531 fix: ui field validation error with admin.disableListColumn property
  docs/fields/ui.mdx
  packages/payload/src/fields/config/schema.ts
  packages/payload/src/fields/config/types.ts
Labels: created-by: Contributor

#6529 fix(ui): adjusts sizing of remove/add buttons to be same size
  packages/ui/src/icons/Plus/index.scss
  packages/ui/src/icons/Plus/index.tsx
Labels: created-by: Contributor

#6560 feat(richtext-lexical)!: configurable fixed toolbar
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/exports/components.ts
  packages/richtext-lexical/src/field/features/toolbars/fixed/Toolbar/index.scss
  packages/richtext-lexical/src/field/features/toolbars/fixed/Toolbar/index.tsx
  packages/richtext-lexical/src/field/features/toolbars/fixed/feature.client.tsx
  packages/richtext-lexical/src/field/features/toolbars/fixed/feature.server.ts
  packages/richtext-lexical/src/field/features/toolbars/shared/ToolbarButton/index.tsx
  packages/richtext-lexical/src/field/features/toolbars/shared/ToolbarDropdown/index.tsx
  packages/richtext-lexical/src/field/features/toolbars/types.ts
  packages/richtext-lexical/src/field/lexical/EditorFocusProvider.tsx
  packages/richtext-lexical/src/field/lexical/LexicalEditor.tsx
  packages/richtext-lexical/src/field/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/field/lexical/config/client/EditorConfigProvider.tsx
  packages/richtext-lexical/src/field/lexical/ui/icons/Link/index.tsx
  packages/richtext-lexical/src/index.ts
  pnpm-lock.yaml
  test/fields/collections/Lexical/blocks.ts
Labels: created-by: Payload team

#6573 fix(richtext-*): fix client features were not loaded properly, improve performance of LexicalProvider, slate cell component was non-functional, support richtext adapter Cell RSCs
  packages/payload/src/admin/elements/Cell.ts
  packages/richtext-lexical/src/cell/index.tsx
  packages/richtext-lexical/src/field/features/createFeaturePropComponent.tsx
  packages/richtext-lexical/src/field/index.tsx
  packages/richtext-lexical/src/field/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/useLexicalFeature.tsx
  packages/richtext-slate/src/cell/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Textarea/index.tsx
  packages/ui/src/elements/Table/DefaultCell/index.tsx
  packages/ui/src/elements/Table/TableCellProvider/index.tsx
  packages/ui/src/elements/withMergedProps/index.tsx
  packages/ui/src/providers/ComponentMap/buildComponentMap/fields.tsx
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
Labels: created-by: Payload team

#6578 fix: critical getPredefinedMigration dependency error
  packages/payload/src/database/migrations/getPredefinedMigration.ts
  packages/payload/src/exports/database.ts
Labels: created-by: Payload team

#6575 fix(richtext-lexical): minor design improvements
  packages/richtext-lexical/src/field/features/toolbars/fixed/Toolbar/index.scss
  packages/richtext-lexical/src/field/lexical/ui/ContentEditable.scss
Labels: created-by: Payload team
