Repository payloadcms/payload, pull requests merged in 2024-08, with the labels that each got.

#7100 feat: adds restore as draft option to versions
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/graphql/src/resolvers/collections/restoreVersion.ts
  packages/graphql/src/resolvers/globals/restoreVersion.ts
  packages/graphql/src/schema/initCollections.ts
  packages/graphql/src/schema/initGlobals.ts
  packages/next/src/elements/DocumentHeader/Tabs/tabs/VersionsPill/index.tsx
  packages/next/src/routes/rest/collections/restoreVersion.ts
  packages/next/src/routes/rest/globals/restoreVersion.ts
  packages/next/src/views/Version/Default/index.tsx
  packages/next/src/views/Version/Restore/index.scss
  packages/next/src/views/Version/Restore/index.tsx
  packages/next/src/views/Version/Restore/types.ts
  packages/next/src/views/Versions/index.client.tsx
  packages/payload/src/collections/operations/restoreVersion.ts
  packages/payload/src/globals/operations/findVersions.ts
  packages/payload/src/globals/operations/restoreVersion.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  test/versions/e2e.spec.ts
  test/versions/int.spec.ts
Labels: v3, created-by: Payload team

#7459 fix(db-postgres): incorrect schema type on adapter
  packages/db-postgres/src/types.ts
Labels: v3, created-by: Contributor

#7467 fix: set active nav item
  packages/next/src/elements/Nav/index.client.tsx
Labels: v3, created-by: Payload team

#7470 feat(cpa): add sqlite
  packages/create-payload-app/src/lib/replacements.ts
  packages/create-payload-app/src/lib/select-db.ts
  packages/create-payload-app/src/types.ts
Labels: v3, created-by: Payload team

#7473 feat: adds upload's relationship thumbnail
  docs/fields/upload.mdx
  docs/upload/overview.mdx
  packages/payload/src/admin/elements/Cell.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/uploads/types.ts
  packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
  packages/ui/src/providers/ComponentMap/buildComponentMap/fields.tsx
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
  test/uploads/shared.ts
Labels: v3, created-by: Contributor

#7474 fix(ui): temporarily reverts custom component prop threading
  packages/payload/src/admin/forms/FieldDescription.ts
  packages/payload/src/admin/forms/Label.ts
  packages/ui/src/providers/ComponentMap/buildComponentMap/fields.tsx
  test/admin/e2e/1/e2e.spec.ts
Labels: v3, created-by: Payload team

#7490 fix: #7488, cant deploy SQLite to Vercel
  packages/next/src/withPayload.js
Labels: v3, created-by: Payload team

#7502 fix: error thrown in version view when localization is false
  packages/next/src/views/Version/Default/index.tsx
Labels: v3, created-by: Payload team

#7507 fix(cpa): adjust template file location detection
  packages/create-payload-app/src/lib/update-payload-in-project.ts
Labels: v3, created-by: Payload team

#7515 chore: improves plugin creation docs
  docs/plugins/build-your-own.mdx
  docs/plugins/form-builder.mdx
  docs/plugins/nested-docs.mdx
  docs/plugins/redirects.mdx
  docs/plugins/search.mdx
  docs/plugins/sentry.mdx
  docs/plugins/seo.mdx
  docs/plugins/stripe.mdx
Labels: v3, created-by: Contributor

#7514 fix(db-*): drizzle enums, bump drizzle-kit
  packages/db-postgres/package.json
  packages/db-postgres/src/createMigration.ts
  packages/db-postgres/src/defaultSnapshot.ts
  packages/db-postgres/src/predefinedMigrations/v2-v3/index.ts
  packages/db-postgres/src/requireDrizzleKit.ts
  packages/db-postgres/src/types.ts
  packages/db-sqlite/package.json
  packages/db-sqlite/src/createMigration.ts
  packages/db-sqlite/src/defaultSnapshot.ts
  packages/db-sqlite/src/requireDrizzleKit.ts
  packages/next/src/withPayload.js
  pnpm-lock.yaml
  test/dev.js
Labels: v3, created-by: Payload team

#7416 fix(ui): properly handles ID field component type based on `payload.db.defaultIDType`
  packages/payload/src/admin/RichText.ts
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/utilities/generateComponentMap.tsx
  packages/richtext-slate/src/generateComponentMap.tsx
  packages/ui/src/providers/ComponentMap/buildComponentMap/collections.tsx
  packages/ui/src/providers/ComponentMap/buildComponentMap/fields.tsx
  packages/ui/src/providers/ComponentMap/buildComponentMap/globals.tsx
  packages/ui/src/providers/ComponentMap/buildComponentMap/index.tsx
Labels: v3, created-by: Contributor

#7454 fix: prevents `hasMany` text going outside of input boundaries
  packages/payload/src/admin/components/elements/ReactSelect/ValueContainer/index.scss
  packages/payload/src/admin/components/forms/field-types/Text/index.scss
Labels: created-by: Payload team

#7455 fix(ui): prevents `hasMany` text going outside of input boundaries
  packages/db-sqlite/src/schema/createIndex.ts
  packages/next/src/views/Login/LoginField/index.tsx
  packages/ui/src/elements/ReactSelect/ValueContainer/index.scss
  packages/ui/src/fields/Text/index.scss
  test/hooks/collections/Hook/index.ts
Labels: v3, created-by: Contributor

#7521 feat(richtext-lexical)!: upgrade lexical from 0.16.1 to 0.17.0, add table feature converter
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/experimental_table/feature.client.ts
  packages/richtext-lexical/src/features/experimental_table/feature.server.ts
  packages/richtext-lexical/src/features/experimental_table/plugins/TableActionMenuPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/plugins/TableCellResizerPlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/plugins/TableHoverActionsPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/plugins/TablePlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/utils/debounce.ts
  packages/richtext-lexical/src/features/experimental_table/utils/useDebounce.ts
  packages/richtext-lexical/src/features/link/plugins/autoLink/index.tsx
  packages/richtext-lexical/src/features/migrations/slateToLexical/converter/index.ts
  packages/richtext-lexical/src/features/toolbars/fixed/Toolbar/index.scss
  packages/richtext-lexical/src/lexical/LexicalEditor.scss
  packages/richtext-lexical/src/lexical/LexicalEditor.tsx
  packages/richtext-lexical/src/lexical/ui/ContentEditable.tsx
  packages/richtext-lexical/src/populateGraphQL/defaultValue.ts
  pnpm-lock.yaml
  test/fields/payload-types.ts
  test/package.json
Labels: v3, created-by: Payload team

#7522 fix(richtext-lexical): various table and icon style issues
  packages/richtext-lexical/src/features/experimental_table/plugins/TableActionMenuPlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/plugins/TablePlugin/index.scss
  packages/richtext-lexical/src/lexical/ui/icons/Table/index.tsx
  packages/richtext-lexical/src/lexical/ui/icons/Upload/index.tsx
Labels: v3, created-by: Payload team

#7520 fix: email and username fields rendering in drawers
  .vscode/launch.json
  packages/next/src/elements/EmailAndUsername/index.tsx
  packages/next/src/views/CreateFirstUser/index.client.tsx
  packages/next/src/views/CreateFirstUser/index.scss
  packages/next/src/views/Edit/Default/Auth/index.tsx
  packages/payload/src/admin/fields/Array.ts
  packages/payload/src/admin/fields/Blocks.ts
  packages/payload/src/admin/fields/Checkbox.ts
  packages/payload/src/admin/fields/Code.ts
  packages/payload/src/admin/fields/Date.ts
  packages/payload/src/admin/fields/Email.ts
  packages/payload/src/admin/fields/JSON.ts
  packages/payload/src/admin/fields/Number.ts
  packages/payload/src/admin/fields/Point.ts
  packages/payload/src/admin/fields/Radio.ts
  packages/payload/src/admin/fields/Relationship.ts
  packages/payload/src/admin/fields/RichText.ts
  packages/payload/src/admin/fields/Select.ts
  packages/payload/src/admin/fields/Text.ts
  packages/payload/src/admin/fields/Textarea.ts
  packages/payload/src/admin/fields/Upload.ts
  packages/plugin-form-builder/src/collections/Forms/DynamicFieldSelector.tsx
  packages/richtext-slate/src/field/RichText.tsx
Labels: v3, created-by: Contributor

#7532 chore: fixes build error stemming from LoginField
  packages/next/src/views/Login/LoginField/index.tsx
Labels: v3, created-by: Contributor

#7466 fix: custom meta icons getting overwritten by default icon
  packages/next/src/utilities/meta.ts
  test/admin-root/e2e.spec.ts
  test/admin/e2e/1/e2e.spec.ts
Labels: v3, created-by: Payload team

#7535 fix: ensure pw confirmation when creating users in admin panel
  packages/next/src/views/Edit/Default/index.tsx
Labels: v3, created-by: Contributor

#7534 fix: scopes preferences queries and mutations by user
  packages/next/src/views/List/index.tsx
  packages/ui/src/utilities/buildFormState.ts
  test/auth/int.spec.ts
Labels: v3, created-by: Contributor

#7538 chore: turn off autocomplete for create first user form
  packages/next/src/elements/EmailAndUsername/index.tsx
  packages/next/src/views/CreateFirstUser/index.client.tsx
Labels: v3, created-by: Contributor

#7539 fix(richtext-lexical)!: html converters not respecting overrideAccess property when populating values, in local API
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/richtext-lexical/src/features/blockquote/feature.server.ts
  packages/richtext-lexical/src/features/converters/html/converter/converters/paragraph.ts
  packages/richtext-lexical/src/features/converters/html/converter/index.ts
  packages/richtext-lexical/src/features/converters/html/converter/types.ts
  packages/richtext-lexical/src/features/converters/html/feature.server.ts
  packages/richtext-lexical/src/features/converters/html/field/index.ts
  packages/richtext-lexical/src/features/experimental_table/feature.server.ts
  packages/richtext-lexical/src/features/heading/feature.server.ts
  packages/richtext-lexical/src/features/link/feature.server.ts
  packages/richtext-lexical/src/features/lists/htmlConverter.ts
  packages/richtext-lexical/src/features/upload/feature.server.ts
  packages/richtext-lexical/src/nodeTypes.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#7533 fix: enable `relationship` & `upload` field population in `versions`
  packages/payload/src/admin/components/views/Version/RenderFieldsToDiff/fields/Relationship/index.tsx
  packages/payload/src/admin/components/views/Version/Version.tsx
  packages/payload/src/admin/components/views/Versions/columns.tsx
  packages/payload/src/admin/components/views/Versions/index.tsx
  packages/payload/src/fields/hooks/afterRead/relationshipPopulationPromise.ts
  test/fields-relationship/collectionSlugs.ts
  test/fields-relationship/collections/VersionedRelationshipField/index.ts
  test/fields-relationship/config.ts
  test/fields-relationship/int.spec.ts
  test/fields-relationship/payload-types.ts
Labels: created-by: Payload team

#7542 chore: call refresh after the subscription is ready, fixes CI
  packages/live-preview-react/src/RefreshRouteOnSave.tsx
  test/live-preview/app/live-preview/_api/getDoc.ts
Labels: v3, created-by: Contributor

#7508 fix(next, payload): enable `relationship` & `upload` field population in `versions`
  .vscode/launch.json
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Relationship/index.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/index.tsx
  packages/payload/src/fields/hooks/afterRead/relationshipPopulationPromise.ts
  test/fields-relationship/collectionSlugs.ts
  test/fields-relationship/collections/VersionedRelationshipField/index.ts
  test/fields-relationship/config.ts
  test/fields-relationship/int.spec.ts
  test/fields-relationship/payload-types.ts
Labels: v3, created-by: Contributor

#7544 fix(ui): properly handles ID field component type based on `payload.db.defaultIDType`
  packages/next/src/views/List/index.tsx
  packages/ui/src/providers/Config/createClientConfig/collections.tsx
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
  packages/ui/src/providers/Config/createClientConfig/globals.tsx
  packages/ui/src/providers/Config/createClientConfig/index.tsx
Labels: created-by: Contributor

#7543 chore: removes default component imports from client config
  packages/next/src/elements/EmailAndUsername/index.tsx
  packages/next/src/views/Login/index.tsx
  packages/payload/src/admin/fields/Email.ts
  packages/payload/src/admin/forms/FieldDescription.ts
  packages/payload/src/bin/generateImportMap/parsePayloadComponent.ts
  packages/payload/src/collections/config/client.ts
  packages/payload/src/config/types.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/globals/config/client.ts
  packages/ui/src/elements/FieldSelect/index.tsx
  packages/ui/src/elements/StepNav/index.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/types.ts
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/fields/Checkbox/Input.tsx
  packages/ui/src/fields/Checkbox/index.tsx
  packages/ui/src/fields/Code/index.tsx
  packages/ui/src/fields/Collapsible/index.tsx
  packages/ui/src/fields/DateTime/index.tsx
  packages/ui/src/fields/Email/index.tsx
  packages/ui/src/fields/Group/index.tsx
  packages/ui/src/fields/Hidden/index.tsx
  packages/ui/src/fields/JSON/index.tsx
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/Password/index.tsx
  packages/ui/src/fields/Point/index.tsx
  packages/ui/src/fields/RadioGroup/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Select/index.tsx
  packages/ui/src/fields/Tabs/index.tsx
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/fields/Textarea/index.tsx
  packages/ui/src/fields/Upload/index.tsx
  packages/ui/src/forms/RenderFields/RenderField.tsx
  packages/ui/src/forms/RenderFields/index.tsx
  packages/ui/src/providers/Config/createClientConfig/collections.tsx
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
  packages/ui/src/providers/Config/createClientConfig/getComponent.ts
  packages/ui/src/providers/Config/createClientConfig/globals.tsx
  packages/ui/src/providers/Config/createClientConfig/index.tsx
  test/_community/payload-types.ts
  test/admin/payload-types.ts
  test/fields/config.ts
  test/fields/payload-types.ts
  tsconfig.json
Labels: created-by: Payload team

#7546 feat: client field types
  docs/migration-guide/overview.mdx
  packages/payload/src/admin/fields/Array.ts
  packages/payload/src/admin/fields/Blocks.ts
  packages/payload/src/admin/fields/Checkbox.ts
  packages/payload/src/admin/fields/Code.ts
  packages/payload/src/admin/fields/Collapsible.ts
  packages/payload/src/admin/fields/Date.ts
  packages/payload/src/admin/fields/Email.ts
  packages/payload/src/admin/fields/Group.ts
  packages/payload/src/admin/fields/Hidden.ts
  packages/payload/src/admin/fields/JSON.ts
  packages/payload/src/admin/fields/Number.ts
  packages/payload/src/admin/fields/Point.ts
  packages/payload/src/admin/fields/Radio.ts
  packages/payload/src/admin/fields/Relationship.ts
  packages/payload/src/admin/fields/RichText.ts
  packages/payload/src/admin/fields/Row.ts
  packages/payload/src/admin/fields/Select.ts
  packages/payload/src/admin/fields/Tabs.ts
  packages/payload/src/admin/fields/Text.ts
  packages/payload/src/admin/fields/Textarea.ts
  packages/payload/src/admin/fields/Upload.ts
  packages/payload/src/admin/types.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/fieldSchemaToJSON.ts
  packages/richtext-lexical/src/field/Field.tsx
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/fields/Array/ArrayRow.tsx
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/BlockRow.tsx
  packages/ui/src/fields/Blocks/BlocksDrawer/index.tsx
  packages/ui/src/fields/Blocks/RowActions.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/fields/Checkbox/index.tsx
  packages/ui/src/fields/Collapsible/index.tsx
  packages/ui/src/fields/ConfirmPassword/index.tsx
  packages/ui/src/fields/DateTime/index.tsx
  packages/ui/src/fields/Group/index.tsx
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/Password/types.ts
  packages/ui/src/fields/Row/index.tsx
  packages/ui/src/fields/Select/Input.tsx
  packages/ui/src/fields/Select/index.tsx
  packages/ui/src/fields/Text/types.ts
  packages/ui/src/fields/Textarea/index.tsx
  packages/ui/src/fields/Upload/index.tsx
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
  tsconfig.json
Labels: created-by: Payload team

#7541 feat!: bump next canary to 104 and update withPayload for new config
  package.json
  packages/live-preview-react/package.json
  packages/next/package.json
  packages/next/src/views/Document/index.tsx
  packages/next/src/withPayload.js
  packages/payload/package.json
  packages/plugin-form-builder/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-seo/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/ui/package.json
  packages/ui/src/providers/Params/index.tsx
  pnpm-lock.yaml
  test/access-control/e2e.spec.ts
  test/helpers.ts
  test/versions/e2e.spec.ts
Labels: v3, created-by: Contributor

#7547 fix(ui): fixes issue when filtering by checkbox value in a different language
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
Labels: v3, created-by: Contributor

#7559 feat: working lexical and richtext-slate, fix types, misc stuff, fields test suite is booting up
  packages/next/src/views/List/index.tsx
  packages/payload/src/admin/RichText.ts
  packages/payload/src/admin/elements/Cell.ts
  packages/payload/src/admin/fields/Blocks.ts
  packages/payload/src/admin/fields/RichText.ts
  packages/payload/src/admin/fields/Row.ts
  packages/payload/src/admin/fields/Tabs.ts
  packages/payload/src/admin/types.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/index.ts
  packages/richtext-lexical/src/cell/index.tsx
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/blocks/client/index.tsx
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
  packages/richtext-lexical/src/features/typesServer.ts
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-lexical/src/field/index.tsx
  packages/richtext-lexical/src/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/lexical/config/client/EditorConfigProvider.tsx
  packages/richtext-lexical/src/types.ts
  packages/richtext-lexical/src/utilities/generateComponentMap.tsx
  packages/richtext-slate/src/field/RichText.tsx
  packages/richtext-slate/src/field/elements/link/Button/index.tsx
  packages/richtext-slate/src/field/elements/link/Element/index.tsx
  packages/richtext-slate/src/field/elements/upload/Element/UploadDrawer/index.tsx
  packages/richtext-slate/src/field/elements/upload/Element/index.tsx
  packages/richtext-slate/src/field/index.tsx
  packages/richtext-slate/src/field/providers/ElementButtonProvider.tsx
  packages/richtext-slate/src/field/providers/ElementProvider.tsx
  packages/richtext-slate/src/field/types.ts
  packages/richtext-slate/src/generateComponentMap.tsx
  packages/richtext-slate/src/index.tsx
  packages/ui/src/providers/Config/createClientConfig/collections.tsx
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
  packages/ui/src/providers/Config/createClientConfig/globals.tsx
  packages/ui/src/providers/Config/createClientConfig/index.tsx
  test/fields/config.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#6558 fix: deprecated `inflight` package
  package.json
  packages/payload/package.json
  pnpm-lock.yaml
  test/fields/payload-types.ts
Labels: created-by: Payload team

#7545 chore!: adjusts auth hydration from server
  packages/next/src/elements/Nav/index.client.tsx
  packages/next/src/elements/Nav/index.scss
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/NotFound/index.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Relationship/index.tsx
  packages/next/src/views/Version/index.tsx
  packages/next/src/views/Versions/getLatestVersion.ts
  packages/next/src/views/Versions/index.tsx
  packages/ui/src/elements/HydrateAuthProvider/index.tsx
  packages/ui/src/elements/HydrateClientUser/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/providers/Auth/index.tsx
  packages/ui/src/providers/Root/index.tsx
  test/auth/e2e.spec.ts
  test/versions/e2e.spec.ts
Labels: v3, created-by: Contributor

#7566 fix(plugin-seo): issue with generating image from a function
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
Labels: v3, created-by: Contributor

#7540 fix(db-postgres): #7492 migrate snapshots
  packages/db-postgres/package.json
  packages/db-postgres/src/createMigration.ts
  packages/db-sqlite/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Contributor

#7568 chore(ui): update useField jsdoc comment to point to the right internal hook
  packages/ui/src/forms/useField/types.ts
Labels: v3, created-by: Contributor

#7563 feat(db-*): allows for running migrations in production automatically
  packages/db-mongodb/src/connect.ts
  packages/db-mongodb/src/index.ts
  packages/db-postgres/src/connect.ts
  packages/db-postgres/src/createMigration.ts
  packages/db-postgres/src/index.ts
  packages/db-postgres/src/types.ts
  packages/db-sqlite/src/connect.ts
  packages/db-sqlite/src/createMigration.ts
  packages/db-sqlite/src/index.ts
  packages/db-sqlite/src/types.ts
  packages/drizzle/src/migrate.ts
  packages/drizzle/src/migrateFresh.ts
  packages/drizzle/src/types.ts
  packages/payload/src/database/migrations/createMigration.ts
  packages/payload/src/database/migrations/migrate.ts
  packages/payload/src/database/migrations/readMigrationFiles.ts
  packages/payload/src/database/migrations/writeMigrationIndex.ts
  packages/payload/src/database/types.ts
  packages/payload/src/index.ts
Labels: v3, created-by: Payload team

#7565 fix: filtering by polymorphic `relationships` with `drafts` enabled
  packages/payload/src/database/getLocalizedPaths.ts
  test/fields-relationship/collections/VersionedRelationshipField/index.ts
  test/fields-relationship/e2e.spec.ts
Labels: created-by: Payload team

#7555 fix: empty path in error message
  packages/payload/src/database/getLocalizedPaths.ts
Labels: v3, created-by: Payload team

#7573 fix: filtering by non-poly `relationships` with `not_equals` operator
  packages/db-mongodb/src/queries/buildSearchParams.ts
  test/fields/collections/Relationship/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#7590 chore(db-*): remove unneeded drizzle import
  packages/drizzle/src/migrate.ts
Labels: v3, created-by: Payload team

#7595 feat: adds classnames to edit, list views
  packages/payload/src/admin/components/views/Global/Default.tsx
  packages/payload/src/admin/components/views/collections/Edit/Default.tsx
  packages/payload/src/admin/components/views/collections/List/Default.tsx
Labels: created-by: Payload team

#7587 fix: corrects local strategy user lookup when using loginWithUsername
  packages/payload/src/auth/strategies/local/register.ts
  test/login-with-username/int.spec.ts
Labels: v3, created-by: Contributor

#7596 feat: adds classnames to list, edit views
  packages/next/src/views/Edit/Default/index.tsx
  packages/next/src/views/List/Default/index.tsx
  test/_community/payload-types.ts
Labels: v3, created-by: Payload team

#7597 fix: add editDepth to account view so that it doesn't redirect from modals
  packages/next/src/views/Account/index.tsx
Labels: v3, created-by: Contributor

#7599 fix: set correct step nav path to Account on account page
  packages/next/src/views/Account/index.client.tsx
  packages/next/src/views/Account/index.tsx
Labels: v3, created-by: Contributor

#7537 chore: allow password to be mutated by hooks
  packages/payload/src/collections/operations/updateByID.ts
  test/_community/collections/Users/index.ts
  test/_community/config.ts
Labels: created-by: Payload team

#7591 fix(ui): apiKey field not being customisable and field access control not being updated with correct data
  packages/next/src/views/Edit/Default/Auth/APIKey.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
Labels: v3, created-by: Contributor

#7557 chore: adjusts admin UI styling
  packages/next/src/elements/DocumentHeader/Tabs/index.scss
  packages/next/src/elements/DocumentHeader/index.scss
  packages/next/src/elements/LeaveWithoutSaving/index.scss
  packages/next/src/elements/Nav/index.client.tsx
  packages/next/src/elements/Nav/index.scss
  packages/next/src/scss/app.scss
  packages/next/src/scss/type.scss
  packages/next/src/views/API/index.scss
  packages/next/src/views/List/Default/index.scss
  packages/richtext-lexical/src/features/blocks/component/index.scss
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/index.scss
  packages/richtext-lexical/src/scss/app.scss
  packages/richtext-lexical/src/scss/type.scss
  packages/richtext-slate/src/field/elements/link/LinkDrawer/index.scss
  packages/richtext-slate/src/scss/app.scss
  packages/richtext-slate/src/scss/type.scss
  packages/ui/src/elements/AppHeader/index.scss
  packages/ui/src/elements/Card/index.scss
  packages/ui/src/elements/Collapsible/index.scss
  packages/ui/src/elements/DeleteDocument/index.scss
  packages/ui/src/elements/DeleteMany/index.scss
  packages/ui/src/elements/DocumentControls/index.scss
  packages/ui/src/elements/DuplicateDocument/index.scss
  packages/ui/src/elements/EditMany/index.scss
  packages/ui/src/elements/GenerateConfirmation/index.scss
  packages/ui/src/elements/ListControls/index.scss
  packages/ui/src/elements/ListDrawer/index.scss
  packages/ui/src/elements/Localizer/LocalizerLabel/index.scss
  packages/ui/src/elements/Localizer/LocalizerLabel/index.tsx
  packages/ui/src/elements/PublishMany/index.scss
  packages/ui/src/elements/Status/index.scss
  packages/ui/src/elements/StayLoggedIn/index.scss
  packages/ui/src/elements/StepNav/index.scss
  packages/ui/src/elements/UnpublishMany/index.scss
  packages/ui/src/fields/Blocks/SectionTitle/index.scss
  packages/ui/src/fields/Blocks/index.scss
  packages/ui/src/scss/app.scss
  packages/ui/src/scss/type.scss
  packages/ui/src/scss/vars.scss
Labels: v3, created-by: Payload team

#7609 chore(db-sqlite): readme
  packages/db-sqlite/README.md
Labels: v3, created-by: Contributor

#7475 feat: indent migration sql
  packages/db-postgres/src/getMigrationTemplate.ts
  packages/db-sqlite/src/getMigrationTemplate.ts
Labels: v3, created-by: Payload team

#7625 feat(plugin-redirects): added new option for redirect type in the redirects collection
  packages/plugin-redirects/src/index.ts
  packages/plugin-redirects/src/redirectTypes.ts
  packages/plugin-redirects/src/types.ts
  test/plugin-redirects/config.ts
  test/plugin-redirects/int.spec.ts
  test/plugin-redirects/payload-types.ts
Labels: v3, created-by: Contributor

#7586 fix(ui): render singular label for `ArrayCell` when length is 1
  packages/ui/src/elements/Table/DefaultCell/fields/Array/index.tsx
Labels: v3, created-by: Contributor

#7570 fix(payload): filtering by polymorphic `relationships` with `drafts` enabled
  packages/payload/src/database/getLocalizedPaths.ts
  test/fields-relationship/collections/VersionedRelationshipField/index.ts
  test/fields-relationship/e2e.spec.ts
Labels: v3, created-by: Contributor

#7631 docs: adds prod migrations
  app/(payload)/admin/importMap.js
  docs/database/migrations.mdx
  docs/database/overview.mdx
Labels: v3, created-by: Payload team

#7456 fix: autoLogin not working if old, invalid token is present
  packages/payload/src/auth/strategies/jwt.ts
Labels: v3, created-by: Payload team

#7626 feat(plugin-form-builder): pass beforeChange params into beforeEmail hook and add types to it
  docs/plugins/form-builder.mdx
  packages/plugin-form-builder/src/collections/FormSubmissions/hooks/sendEmail.ts
  packages/plugin-form-builder/src/types.ts
  test/plugin-form-builder/config.ts
Labels: v3, created-by: Contributor

#7634 feat: add support for custom image size file names
  docs/upload/overview.mdx
  packages/payload/src/collections/config/client.ts
  packages/payload/src/uploads/imageResizer.ts
  packages/payload/src/uploads/types.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
  test/uploads/shared.ts
Labels: v3, created-by: Contributor

#7637 feat: add support for custom image size file names
  docs/upload/overview.mdx
  packages/payload/src/uploads/imageResizer.ts
  packages/payload/src/uploads/types.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#7639 fix: #7580 config deepmerge
  packages/payload/src/config/sanitize.ts
Labels: v3, created-by: Payload team

#7643 fix!: changes casing of admin views config to reflect types
  docs/admin/views.mdx
  packages/next/src/elements/DocumentHeader/Tabs/getCustomViews.ts
  packages/next/src/elements/DocumentHeader/Tabs/getViewConfig.ts
  packages/next/src/elements/DocumentHeader/Tabs/tabs/index.tsx
  packages/next/src/views/API/index.client.tsx
  packages/next/src/views/Document/getCustomViewByKey.tsx
  packages/next/src/views/Document/getCustomViewByRoute.tsx
  packages/next/src/views/Document/getViewsFromConfig.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/Edit/index.client.tsx
  packages/next/src/views/List/Default/index.tsx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/next/src/views/Version/Default/index.tsx
  packages/next/src/views/Versions/index.client.tsx
  packages/payload/src/admin/views/types.ts
  packages/payload/src/bin/generateImportMap/iterateCollections.ts
  packages/payload/src/bin/generateImportMap/iterateGlobals.ts
  packages/payload/src/collections/config/client.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/config/types.ts
  packages/payload/src/globals/config/client.ts
  packages/payload/src/globals/config/types.ts
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/elements/DocumentDrawer/types.ts
  packages/ui/src/elements/Drawer/types.ts
  packages/ui/src/elements/ListDrawer/DrawerContent.tsx
  packages/ui/src/elements/ListDrawer/types.ts
  packages/ui/src/providers/Config/createClientConfig/collections.tsx
  packages/ui/src/providers/Config/createClientConfig/globals.tsx
  packages/ui/src/utilities/buildFormState.ts
  test/admin/collections/CustomViews1.ts
  test/admin/collections/CustomViews2.ts
  test/admin/collections/Geo.ts
  test/admin/components/views/CustomEdit/index.tsx
  test/admin/components/views/CustomEditDefault/index.tsx
  test/admin/components/views/CustomVersions/index.tsx
  test/admin/globals/CustomViews1.ts
  test/admin/globals/CustomViews2.ts
  test/admin/globals/Global.ts
  test/live-preview/collections/Pages.ts
  test/live-preview/components/CollectionLivePreviewButton/index.tsx
  test/live-preview/components/GlobalLivePreviewButton/index.tsx
  test/live-preview/globals/Footer.ts
  test/versions/collections/Drafts.ts
  test/versions/collections/DraftsWithMax.ts
  test/versions/globals/Draft.ts
  test/versions/globals/DraftWithMax.ts
Labels: created-by: Payload team

#7635 fix(live-preview): encode query string url
  packages/live-preview/src/mergeData.ts
  test/live-preview/int.spec.ts
Labels: v3, created-by: Contributor

#7632 fix: update state of field if either `valid` status or `errorMessage` changes
  packages/payload/src/admin/components/forms/useField/index.tsx
Labels: created-by: Payload team

#7651 feat: filename compound index
  docs/upload/overview.mdx
  packages/db-mongodb/src/models/buildCollectionSchema.ts
  packages/db-postgres/src/init.ts
  packages/db-postgres/src/schema/build.ts
  packages/db-sqlite/src/init.ts
  packages/db-sqlite/src/schema/build.ts
  packages/payload/src/uploads/getBaseFields.ts
  packages/payload/src/uploads/types.ts
  scripts/pack-all-to-dest.ts
  test/uploads/config.ts
  test/uploads/payload-types.ts
Labels: v3, created-by: Payload team

#7657 docs: update docs with component path / client config changes
  docs/admin/fields.mdx
  docs/admin/hooks.mdx
  docs/admin/overview.mdx
  docs/local-api/overview.mdx
  docs/migration-guide/overview.mdx
Labels: v3, created-by: Payload team

#7658 docs: update ui field docs to use component paths
  docs/fields/ui.mdx
Labels: v3, created-by: Payload team

#7659 docs: move import map section from admin/overview to admin/components
  docs/admin/components.mdx
  docs/admin/overview.mdx
Labels: v3, created-by: Payload team

#7660 feat(richtext-lexical)!: move migration related features to /migrate subpath export in order to decrease module count when those are not used
  docs/lexical/migration.mdx
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/exports/server/migrate.ts
  packages/richtext-lexical/src/index.ts
  test/fields/collections/LexicalMigrate/index.ts
Labels: v3, created-by: Payload team

#7665 fix(richtext-lexical): inline blocks and tables not functioning correctly if they are used in more than one editor on the same page
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.tsx
  packages/richtext-lexical/src/features/upload/client/component/index.tsx
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: v3, created-by: Payload team

#7369 chore: upgrade to pnpm v9, regenerate lockfile
  .github/actions/setup/action.yml
  .github/workflows/main.yml
  .github/workflows/release-canary.yml
  .npmrc
  package.json
  packages/payload/src/fields/config/types.ts
  packages/plugin-cloud-storage/package.json
  packages/plugin-cloud/package.json
  packages/storage-s3/package.json
  packages/ui/src/elements/ReactSelect/Control/index.tsx
  packages/ui/src/elements/ReactSelect/MultiValue/index.tsx
  packages/ui/src/elements/ReactSelect/MultiValueLabel/index.tsx
  packages/ui/src/elements/ReactSelect/SingleValue/index.tsx
  packages/ui/src/elements/ReactSelect/ValueContainer/index.tsx
  packages/ui/src/fields/Relationship/select-components/MultiValueLabel/index.tsx
  packages/ui/src/fields/Relationship/select-components/SingleValue/index.tsx
  pnpm-lock.yaml
  test/helpers/initPayloadE2ENoConfig.ts
  test/helpers/initPayloadInt.ts
  test/package.json
  test/runInit.ts
  test/runInitSeparateProcess.ts
  tsconfig.json
Labels: v3, created-by: Payload team

#7670 fix(ui): ensure field components safely access field.admin property
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-lexical/src/field/index.tsx
  packages/richtext-slate/src/field/RichText.tsx
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/fields/Code/index.tsx
  packages/ui/src/fields/Collapsible/index.tsx
  packages/ui/src/fields/DateTime/index.tsx
  packages/ui/src/fields/Group/index.tsx
  packages/ui/src/fields/JSON/index.tsx
  packages/ui/src/fields/Point/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Row/index.tsx
  packages/ui/src/fields/Tabs/index.tsx
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/fields/Textarea/index.tsx
  packages/ui/src/fields/Upload/index.tsx
  tsconfig.json
Labels: v3, created-by: Payload team

#7672 chore: update docs for redirects plugin for new redirect type feature
  docs/plugins/redirects.mdx
Labels: v3, created-by: Contributor

#7574 fix: sidebar nav jumping around when loading page
  packages/next/src/elements/Nav/NavWrapper/index.scss
  packages/next/src/elements/Nav/NavWrapper/index.tsx
  packages/next/src/elements/Nav/index.scss
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/templates/Default/Wrapper/index.scss
  packages/next/src/templates/Default/Wrapper/index.tsx
  packages/ui/src/elements/Nav/context.tsx
  packages/ui/src/providers/Root/index.tsx
Labels: v3, created-by: Payload team

#7661 fix(next): properly closes `leave-without-saving` modal after navigating from `Leave anyway` button
  packages/next/src/elements/LeaveWithoutSaving/index.tsx
  packages/next/src/elements/LeaveWithoutSaving/usePreventLeave.tsx
  test/admin/e2e/1/e2e.spec.ts
Labels: v3, created-by: Contributor

#7674 chore: add command to run inside the importMap error
  packages/ui/src/providers/Config/createClientConfig/getComponent.ts
Labels: v3, created-by: Contributor

#7678 fix(ui): issue with checking for undefined json when autosave and validate is enabled
  packages/ui/src/elements/Autosave/index.tsx
Labels: v3, created-by: Contributor

#7681 fix: use tsx instead of swc as default bin script transpiler, as swc errors when it encounters 'next/cache'
  docs/admin/components.mdx
  docs/local-api/outside-nextjs.mdx
  packages/graphql/bin.js
  packages/graphql/package.json
  packages/payload/bin.js
  packages/payload/package.json
  packages/payload/src/bin/index.ts
  packages/payload/src/config/find.ts
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#7682 feat: allow passing `false` as PayloadComponent which signals that the component should not be rendered
  packages/payload/src/admin/types.ts
  packages/payload/src/auth/baseFields/apiKey.ts
  packages/payload/src/auth/baseFields/email.ts
  packages/payload/src/auth/baseFields/username.ts
  packages/payload/src/auth/baseFields/verification.ts
  packages/payload/src/bin/generateImportMap/parsePayloadComponent.ts
  packages/payload/src/config/types.ts
  packages/payload/src/versions/baseFields.ts
  packages/richtext-slate/src/field/elements/textAlign/index.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/providers/Config/RenderComponent.tsx
  packages/ui/src/providers/Config/createClientConfig/collections.tsx
  packages/ui/src/providers/Config/createClientConfig/getComponent.ts
  packages/ui/src/providers/Config/createClientConfig/getCreateMappedComponent.tsx
  packages/ui/src/providers/Config/createClientConfig/globals.tsx
Labels: v3, created-by: Payload team

#7690 chore(eslint): update relative import regex to handle more scenarios
  packages/eslint-plugin/customRules/no-relative-monorepo-imports.js
Labels: v3, created-by: Payload team

#7691 feat(eslint): no-imports-from-self rule
  eslint.config.js
  packages/eslint-plugin/customRules/no-imports-from-self.js
  packages/eslint-plugin/index.mjs
Labels: v3, created-by: Payload team

#7704 chore: fix issues running postgres in our dev test suites
  package.json
  pnpm-lock.yaml
  test/dev.ts
  test/package.json
Labels: v3, created-by: Payload team

#7706 fix: importMap windows paths
  packages/payload/src/bin/generateImportMap/index.ts
Labels: v3, created-by: Contributor

#7707 chore(ui): resolves self-referencing imports
  packages/payload/src/exports/shared.ts
  packages/ui/src/elements/Hamburger/index.tsx
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/elements/ReactSelect/DropdownIndicator/index.tsx
  packages/ui/src/elements/StepNav/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Date/index.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/fields/Password/index.tsx
  packages/ui/src/forms/RenderFields/RenderField.tsx
  packages/ui/src/graphics/Account/index.tsx
  packages/ui/src/providers/Actions/index.tsx
  packages/ui/src/utilities/reduceFieldsToValuesWithValidation.ts
Labels: v3, created-by: Payload team

#7713 chore: extends dropzone and upload field
  packages/ui/src/elements/Dropzone/index.tsx
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/exports/client/index.ts
Labels: v3, created-by: Contributor

#7720 chore: admin panel style updates
  packages/next/src/elements/DocumentHeader/index.scss
  packages/next/src/scss/toasts.scss
  packages/next/src/views/List/Default/index.scss
  packages/richtext-lexical/src/scss/toasts.scss
  packages/richtext-slate/src/scss/toasts.scss
  packages/ui/src/elements/IDLabel/index.scss
  packages/ui/src/elements/RenderTitle/index.scss
  packages/ui/src/icons/Chevron/index.tsx
  packages/ui/src/scss/toasts.scss
Labels: v3, created-by: Payload team

#7723 fix(ui): ensure that aborting Autosave always has a valid reason for the controller - fixes uncaught error
  packages/ui/src/elements/Autosave/index.tsx
Labels: v3, created-by: Contributor

#7721 fix: bin script error when running on linux
  packages/payload/bin.js
Labels: v3, created-by: Contributor

#7725 fix: type RelationshipFieldClient typed incorrectly
  packages/payload/src/fields/config/types.ts
Labels: v3, created-by: Payload team

#7726 fix: corrects logout icon styling
  packages/ui/src/icons/LogOut/index.tsx
Labels: v3, created-by: Payload team

#7727 fix: ensures user is accurate in useAuth
  packages/ui/src/providers/Auth/index.tsx
Labels: v3, created-by: Payload team

#7730 fix(ui): relationship cells in table from list drawer not shown
  packages/ui/src/elements/ListDrawer/DrawerContent.tsx
Labels: v3, created-by: Payload team

#7731 chore: update all templates
  package.json
  templates/_template/src/app/(payload)/admin/importMap.js
  templates/blank/src/app/(payload)/admin/importMap.js
  templates/website/package.json
  templates/website/src/app/(payload)/admin/importMap.js
  templates/with-payload-cloud/src/app/(payload)/admin/importMap.js
  templates/with-vercel-mongodb/src/app/(payload)/admin/importMap.js
  templates/with-vercel-postgres/src/app/(payload)/admin/importMap.js
Labels: v3, created-by: Payload team

#7729 fix: prevent vertical scrolling on tab fields
  packages/ui/src/fields/Tabs/index.scss
Labels: v3, created-by: Payload team

#7733 chore: fix dev:postgres command, disable dependency checker in core dev
  next.config.mjs
  package.json
  packages/payload/src/index.ts
  packages/richtext-lexical/src/index.ts
  test/helpers/initPayloadE2E.ts
  test/helpers/initPayloadE2ENoConfig.ts
  test/jest.setup.js
Labels: v3, created-by: Payload team

#7716 feat: custom view and document-level metadata
  packages/next/src/utilities/meta.ts
  packages/next/src/views/API/meta.ts
  packages/next/src/views/Document/getCustomViewByRoute.tsx
  packages/next/src/views/Document/getMetaBySegment.tsx
  packages/next/src/views/Document/getViewsFromConfig.tsx
  packages/next/src/views/Edit/meta.ts
  packages/next/src/views/LivePreview/meta.ts
  packages/next/src/views/Root/generateCustomViewMetadata.ts
  packages/next/src/views/Root/getCustomViewByRoute.ts
  packages/next/src/views/Root/getCustomViewByRoute.tsx
  packages/next/src/views/Root/getViewFromConfig.ts
  packages/next/src/views/Root/meta.ts
  packages/next/src/views/Version/meta.ts
  packages/next/src/views/Versions/meta.ts
  packages/payload/src/admin/types.ts
  packages/payload/src/admin/views/types.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/config/types.ts
  packages/payload/src/globals/config/types.ts
  test/admin/collections/CustomViews2.ts
  test/admin/components/CustomTabComponent/client.tsx
  test/admin/config.ts
  test/admin/e2e/1/e2e.spec.ts
  test/admin/shared.ts
  tsconfig.json
Labels: v3, created-by: Payload team

#7758 fix(richtext-lexical): richtext editor features overriding other editor features props if multiple editors in one document
  packages/richtext-lexical/src/utilities/createClientFeature.ts
  packages/richtext-lexical/src/utilities/createServerFeature.ts
Labels: v3, created-by: Payload team

#7761 fix(ui): tabs preferences not being saved
  packages/ui/src/providers/DocumentInfo/index.tsx
  test/fields/e2e.spec.ts
Labels: v3, created-by: Contributor

#7759 fix: migrate error on windows
  packages/payload/src/database/migrations/readMigrationFiles.ts
  test/database/int.spec.ts
Labels: v3, created-by: Contributor

#7765 fix: type generation for block fields with no blocks
  packages/payload/src/utilities/configToJSONSchema.spec.ts
  packages/payload/src/utilities/configToJSONSchema.ts
Labels: v3, created-by: Contributor

#7766 fix: postgres migrate args
  packages/db-postgres/src/index.ts
Labels: v3, created-by: Payload team

#7774 fix(ui): text clipping on document header title with Segoe UI font
  packages/next/src/elements/DocumentHeader/index.scss
Labels: v3, created-by: Payload team

#7775 fix(plugin-search): not being able to override labels
  packages/plugin-search/src/Search/index.ts
Labels: v3, created-by: Contributor

#7776 fix(ui): on Table component crashing when looking for className on admin
  packages/ui/src/elements/Table/DefaultCell/index.tsx
Labels: v3, created-by: Contributor

#7779 feat(ui): export Banner component
  packages/ui/src/elements/Banner/index.tsx
  packages/ui/src/exports/client/index.ts
Labels: v3, created-by: Payload team

#7777 feat: extends Button and extracts ListHeader components
  packages/next/src/views/List/Default/index.scss
  packages/next/src/views/List/Default/index.tsx
  packages/ui/src/elements/Button/index.scss
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Button/types.ts
  packages/ui/src/elements/ListHeader/index.scss
  packages/ui/src/elements/ListHeader/index.tsx
  packages/ui/src/elements/Popup/PopupButtonList/index.tsx
  packages/ui/src/elements/Popup/PopupTrigger/index.scss
  packages/ui/src/elements/Popup/PopupTrigger/index.tsx
  packages/ui/src/elements/Popup/index.tsx
  packages/ui/src/exports/client/index.ts
Labels: v3, created-by: Contributor

#7792 chore: corrects icon color styles
  packages/ui/src/elements/Button/index.scss
  packages/ui/src/elements/Button/index.tsx
Labels: v3, created-by: Contributor

#7791 fix(ui, richtext-lexical): corrects clickable areas on block headers
  packages/richtext-lexical/src/features/blocks/client/component/index.scss
  packages/ui/src/fields/Blocks/SectionTitle/index.scss
Labels: v3, created-by: Payload team

#7797 fix: no longer handle disabling node deprecation warnings within bin script shebangs, as it errored on some systems
  packages/graphql/bin.js
  packages/payload/bin.js
  templates/_template/package.json
  templates/blank/package.json
  templates/website/package.json
  templates/with-payload-cloud/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
Labels: v3, created-by: Payload team

#7801 fix(richtext-lexical): migrate scripts not working due to migration hooks running during migrate script
  docs/lexical/migration.mdx
  packages/drizzle/src/upsertRow/index.ts
  packages/payload/src/errors/ValidationError.ts
  packages/payload/src/fields/hooks/beforeChange/index.ts
  packages/richtext-lexical/src/features/migrations/lexicalPluginToLexical/converter/index.ts
  packages/richtext-lexical/src/features/migrations/lexicalPluginToLexical/feature.server.ts
  packages/richtext-lexical/src/features/migrations/slateToLexical/converter/index.ts
  packages/richtext-lexical/src/features/migrations/slateToLexical/feature.server.ts
  packages/richtext-lexical/src/utilities/migrateSlateToLexical/index.ts
  packages/richtext-lexical/src/validate/index.ts
Labels: v3, created-by: Payload team

#7796 feat: upload hasmany
  packages/db-mongodb/src/models/buildSchema.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/graphql/src/schema/buildMutationInputType.ts
  packages/graphql/src/schema/buildObjectType.ts
  packages/graphql/src/schema/fieldToWhereInputSchemaMap.ts
  packages/graphql/src/schema/withOperators.ts
  packages/next/src/views/List/Default/index.tsx
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/fields/validations.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  packages/ui/src/elements/AddNewRelation/index.scss
  packages/ui/src/elements/AddNewRelation/index.tsx
  packages/ui/src/elements/AddNewRelation/types.ts
  packages/ui/src/elements/AddNewRelation/useRelatedCollections.ts
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/elements/DocumentDrawer/index.tsx
  packages/ui/src/elements/FileDetails/DraggableFileDetails/index.scss
  packages/ui/src/elements/FileDetails/DraggableFileDetails/index.tsx
  packages/ui/src/elements/FileDetails/StaticFileDetails/index.scss
  packages/ui/src/elements/FileDetails/StaticFileDetails/index.tsx
  packages/ui/src/elements/FileDetails/index.tsx
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/elements/ListDrawer/DrawerContent.tsx
  packages/ui/src/elements/ListDrawer/index.tsx
  packages/ui/src/elements/ListDrawer/types.ts
  packages/ui/src/elements/SelectMany/index.tsx
  packages/ui/src/fields/Relationship/AddNew/types.ts
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Upload/HasMany/index.scss
  packages/ui/src/fields/Upload/HasMany/index.tsx
  packages/ui/src/fields/Upload/HasOne/Input.tsx
  packages/ui/src/fields/Upload/HasOne/index.scss
  packages/ui/src/fields/Upload/HasOne/index.tsx
  packages/ui/src/fields/Upload/index.tsx
  packages/ui/src/forms/buildStateFromSchema/addFieldStatePromise.ts
  packages/ui/src/providers/ListInfo/index.tsx
  packages/ui/src/providers/Selection/index.tsx
  test/fields/collections/UploadMulti/.gitignore
  test/fields/collections/UploadMulti/index.ts
  test/fields/collections/UploadMulti/shared.ts
  test/fields/collections/UploadMultiPoly/.gitignore
  test/fields/collections/UploadMultiPoly/index.ts
  test/fields/collections/UploadMultiPoly/shared.ts
  test/fields/collections/UploadPoly/.gitignore
  test/fields/collections/UploadPoly/index.ts
  test/fields/collections/UploadPoly/shared.ts
  test/fields/config.ts
  test/fields/payload-types.ts
  test/fields/seed.ts
  test/fields/slugs.ts
  test/uploads/payload-types.ts
Labels: v3, created-by: Contributor

#7804 fix(ui): upload has many no rows error
  packages/ui/src/fields/Upload/HasMany/index.scss
  packages/ui/src/fields/Upload/HasMany/index.tsx
  test/fields/collections/RichText/e2e.spec.ts
Labels: created-by: Contributor

#7802 fix(richtext-lexical): slate => lexical migrator improvements
  packages/richtext-lexical/src/features/migrations/slateToLexical/converter/converters/link/converter.ts
  packages/richtext-lexical/src/utilities/migrateSlateToLexical/index.ts
Labels: v3, created-by: Payload team

#7807 chore(ui): expose useCollapsible hook
  packages/ui/src/exports/client/index.ts
Labels: v3

#7811 chore: fix dev importmap for windows
  test/initDevAndTest.ts
Labels: v3, created-by: Contributor

#7814 fix(ui): relationship field "add new" button styling
  packages/ui/src/elements/AddNewRelation/index.scss
  packages/ui/src/elements/AddNewRelation/index.tsx
Labels: v3, created-by: Payload team

#7816 feat(ui): add styling for no docs and clear all on hasmany upload
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/fields/Upload/HasMany/index.scss
  packages/ui/src/fields/Upload/HasMany/index.tsx
Labels: v3, created-by: Contributor

#7815 fix: weaken JsonObject type to allow types from payload-types being assigned to it
  packages/payload/src/types/index.ts
  packages/plugin-stripe/src/routes/rest.ts
Labels: v3, created-by: Payload team

#7822 feat(richtext-lexical): improve upload and relationship node types
  packages/richtext-lexical/src/features/relationship/client/components/RelationshipComponent.tsx
  packages/richtext-lexical/src/features/relationship/server/nodes/RelationshipNode.tsx
  packages/richtext-lexical/src/features/upload/client/component/index.tsx
  packages/richtext-lexical/src/features/upload/server/nodes/UploadNode.tsx
Labels: v3, created-by: Payload team

#7827 build(deps): update turborepo
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: v3, created-by: Payload team

#7817 chore(richtext-*): improved typography styles, darkmode lexical toolbar
  packages/next/src/scss/app.scss
  packages/next/src/scss/type.scss
  packages/richtext-lexical/src/features/blocks/client/component/index.scss
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.scss
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/index.scss
  packages/richtext-lexical/src/features/relationship/client/components/index.scss
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.scss
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.scss
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarButton/index.scss
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.scss
  packages/richtext-lexical/src/features/upload/client/component/index.scss
  packages/richtext-lexical/src/lexical/LexicalEditor.scss
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/index.scss
  packages/richtext-lexical/src/lexical/plugins/handles/DraggableBlockPlugin/index.scss
  packages/richtext-lexical/src/lexical/plugins/handles/DraggableBlockPlugin/index.tsx
  packages/richtext-lexical/src/lexical/plugins/handles/DraggableBlockPlugin/setTargetLine.ts
  packages/richtext-lexical/src/lexical/plugins/handles/utils/setHandlePosition.ts
  packages/richtext-lexical/src/lexical/theme/EditorTheme.scss
  packages/richtext-lexical/src/lexical/ui/icons/Caret/index.svg
  packages/richtext-lexical/src/lexical/utils/setFloatingElemPosition.ts
  packages/richtext-lexical/src/scss/app.scss
  packages/richtext-lexical/src/scss/type.scss
  packages/richtext-slate/src/field/elements/link/Element/index.scss
  packages/richtext-slate/src/field/index.scss
  packages/richtext-slate/src/scss/app.scss
  packages/richtext-slate/src/scss/type.scss
  packages/ui/src/scss/app.scss
  packages/ui/src/scss/type.scss
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#7834 fix: trim down accepted args of getPayloadHMR
  package.json
  packages/next/src/utilities/getPayloadHMR.ts
Labels: v3, created-by: Payload team

#7837 chore: hide node deprecation warnings in monorepo
  package.json
Labels: v3, created-by: Payload team

#7839 feat: enable react compiler for @payloadcms/next package
  .gitignore
  packages/db-postgres/package.json
  packages/db-vercel-postgres/package.json
  packages/next/babel.config.cjs
  packages/next/eslint.config.js
  packages/next/package.json
  packages/next/src/elements/LeaveWithoutSaving/usePreventLeave.tsx
  packages/next/src/views/API/LocaleSelector/index.tsx
  packages/next/src/views/LivePreview/Context/context.ts
  packages/next/src/views/Version/Default/SetStepNav.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Iterable/index.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Nested/index.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Select/index.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Tabs/index.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Text/index.tsx
  packages/payload/package.json
  packages/richtext-lexical/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  test/package.json
Labels: v3, created-by: Payload team

#7870 feat(richtext-lexical): more lenient url validation, URL-encode invalid urls on save
  packages/richtext-lexical/src/features/link/server/baseFields.ts
  packages/richtext-lexical/src/lexical/utils/url.ts
Labels: v3, created-by: Payload team

#7868 feat: add nextjs and react version checks to dependency checker
  next.config.mjs
  packages/payload/src/checkPayloadDependencies.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/dependencies/dependencyChecker.ts
  packages/payload/src/utilities/dependencies/versionUtils.ts
  packages/richtext-lexical/src/index.ts
  test/helpers/initPayloadE2E.ts
  test/helpers/initPayloadE2ENoConfig.ts
  test/jest.setup.js
Labels: v3, created-by: Payload team

#7875 fix: exports richtext-slate useSlatePlugin
  packages/richtext-slate/src/exports/client/index.ts
Labels: v3, created-by: Payload team

#7876 fix: sanitizes modifyResponseHeaders from client config
  packages/payload/src/collections/config/client.ts
  packages/payload/src/index.ts
  packages/ui/src/providers/Config/createClientConfig/collections.tsx
Labels: v3, created-by: Payload team

#7877 fix(templates): website bug fixes for slug generation and form builder and adds support for strictNullChecks: true
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/page.tsx
  templates/website/src/app/(frontend)/posts/page/[pageNumber]/page.tsx
  templates/website/src/app/(payload)/admin/importMap.js
  templates/website/src/app/blocks/ArchiveBlock/index.tsx
  templates/website/src/app/blocks/CallToAction/index.tsx
  templates/website/src/app/blocks/Code/Code.client.tsx
  templates/website/src/app/blocks/Content/index.tsx
  templates/website/src/app/blocks/Form/Checkbox/index.tsx
  templates/website/src/app/blocks/Form/Message/index.tsx
  templates/website/src/app/blocks/Form/buildInitialFormState.tsx
  templates/website/src/app/blocks/Form/index.tsx
  templates/website/src/app/components/Header/index.client.tsx
  templates/website/src/app/components/Link/index.tsx
  templates/website/src/app/components/LivePreviewListener/index.tsx
  templates/website/src/app/components/Media/ImageMedia/index.tsx
  templates/website/src/app/heros/HighImpact/index.tsx
  templates/website/src/app/heros/LowImpact/index.tsx
  templates/website/src/app/heros/MediumImpact/index.tsx
  templates/website/src/app/next/preview/route.ts
  templates/website/src/app/providers/HeaderTheme/index.tsx
  templates/website/src/app/utilities/generateMeta.ts
  templates/website/src/app/utilities/getMeUser.ts
  templates/website/src/app/utilities/useClickableCard.ts
  templates/website/src/payload-types.ts
  templates/website/src/payload.config.ts
  templates/website/src/payload/access/authenticated.ts
  templates/website/src/payload/collections/Posts/hooks/populateAuthors.ts
  templates/website/src/payload/utilities/formatSlug.ts
  templates/website/tsconfig.json
Labels: v3, created-by: Contributor

#7878 fix: error when closing the live preview popup window
  packages/next/src/views/LivePreview/Device/index.tsx
Labels: v3, created-by: Contributor

#7879 fix(plugin-seo): remove dependency on import from payload/next package
  packages/plugin-seo/src/index.tsx
Labels: v3, created-by: Contributor

#7881 fix(templates): website live preview and code block
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/app/blocks/Code/Code.client.tsx
  templates/website/src/app/blocks/MediaBlock/index.tsx
  templates/website/src/app/components/Blocks/index.tsx
  templates/website/src/app/components/RichText/serialize.tsx
  templates/website/src/app/next/preview/route.ts
Labels: v3, created-by: Contributor

#7882 feat: implement info command
  packages/payload/src/bin/index.ts
  packages/payload/src/bin/info.ts
  packages/payload/src/checkPayloadDependencies.ts
  packages/payload/src/versions/payloadPackageList.ts
Labels: v3, created-by: Payload team

#7888 fix(richtext-lexical): dependency checker suggesting incorrect version
  packages/payload/src/utilities/dependencies/dependencyChecker.ts
  packages/richtext-lexical/src/index.ts
Labels: v3, created-by: Payload team

#7889 fix: bugs in versions UI with perPage, pagination and diffs not showing for tabs. publish button no longer double saves when using keyboard
  packages/next/src/views/Version/RenderFieldsToDiff/index.tsx
  packages/next/src/views/Versions/index.client.tsx
  packages/ui/src/elements/PublishButton/index.tsx
Labels: v3, created-by: Contributor

#7891 fix: locale selector + autosave race condition
  packages/next/src/views/Document/index.tsx
Labels: v3, created-by: Payload team

#7890 fix(richtext-lexical): html converters can populate relationships infinitely
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/utilities/getDataByPath.ts
  packages/richtext-lexical/src/features/blockquote/server/index.ts
  packages/richtext-lexical/src/features/converters/html/converter/converters/paragraph.ts
  packages/richtext-lexical/src/features/converters/html/converter/index.ts
  packages/richtext-lexical/src/features/converters/html/converter/types.ts
  packages/richtext-lexical/src/features/converters/html/field/index.ts
  packages/richtext-lexical/src/features/experimental_table/server/index.ts
  packages/richtext-lexical/src/features/heading/server/index.ts
  packages/richtext-lexical/src/features/link/server/index.ts
  packages/richtext-lexical/src/features/lists/htmlConverter.ts
  packages/richtext-lexical/src/features/upload/server/feature.server.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/utils/url.ts
Labels: v3, created-by: Payload team

#7895 feat(templates): add new slug component to the website
  templates/website/src/app/(payload)/admin/importMap.js
  templates/website/src/payload-types.ts
  templates/website/src/payload/collections/Pages/index.ts
  templates/website/src/payload/collections/Posts/index.ts
  templates/website/src/payload/fields/slug.ts
  templates/website/src/payload/fields/slug/SlugComponent.tsx
  templates/website/src/payload/fields/slug/formatSlug.ts
  templates/website/src/payload/fields/slug/index.scss
  templates/website/src/payload/fields/slug/index.ts
  templates/website/tsconfig.json
Labels: v3, created-by: Contributor

#7894 fix: upload has many field updates
  packages/next/src/templates/Default/index.tsx
  packages/next/src/views/List/Default/index.tsx
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/ui/src/elements/BulkUpload/AddFilesView/index.scss
  packages/ui/src/elements/BulkUpload/AddFilesView/index.tsx
  packages/ui/src/elements/BulkUpload/AddingFilesView/index.tsx
  packages/ui/src/elements/BulkUpload/DiscardWithoutSaving/index.tsx
  packages/ui/src/elements/BulkUpload/DrawerCloseButton/index.tsx
  packages/ui/src/elements/BulkUpload/EditForm/index.tsx
  packages/ui/src/elements/BulkUpload/FileSidebar/index.scss
  packages/ui/src/elements/BulkUpload/FileSidebar/index.tsx
  packages/ui/src/elements/BulkUpload/FormsManager/index.tsx
  packages/ui/src/elements/BulkUpload/Header/index.tsx
  packages/ui/src/elements/BulkUpload/index.tsx
  packages/ui/src/elements/DocumentDrawer/DrawerContent.tsx
  packages/ui/src/elements/DocumentDrawer/types.ts
  packages/ui/src/elements/DraggableSortable/index.tsx
  packages/ui/src/elements/Dropzone/index.scss
  packages/ui/src/elements/Dropzone/index.tsx
  packages/ui/src/elements/FileDetails/DraggableFileDetails/index.tsx
  packages/ui/src/elements/FileDetails/StaticFileDetails/index.scss
  packages/ui/src/elements/FileDetails/StaticFileDetails/index.tsx
  packages/ui/src/elements/ListDrawer/index.scss
  packages/ui/src/elements/ShimmerEffect/index.tsx
  packages/ui/src/elements/Thumbnail/index.tsx
  packages/ui/src/elements/Upload/index.scss
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/fields/Upload/HasMany/index.scss
  packages/ui/src/fields/Upload/HasMany/index.tsx
  packages/ui/src/fields/Upload/HasOne/Input.tsx
  packages/ui/src/fields/Upload/HasOne/index.scss
  packages/ui/src/fields/Upload/HasOne/index.tsx
  packages/ui/src/fields/Upload/Input.tsx
  packages/ui/src/fields/Upload/RelationshipContent/index.scss
  packages/ui/src/fields/Upload/RelationshipContent/index.tsx
  packages/ui/src/fields/Upload/UploadCard/index.scss
  packages/ui/src/fields/Upload/UploadCard/index.tsx
  packages/ui/src/fields/Upload/index.scss
  packages/ui/src/fields/Upload/index.tsx
  packages/ui/src/providers/Root/index.tsx
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Upload/e2e.spec.ts
  test/uploads/collections/Upload1/index.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
Labels: v3, created-by: Contributor

#7897 fix: depth not being respected by upload has many
  packages/payload/src/fields/config/types.ts
Labels: v3, created-by: Contributor

#7899 build: update turborepo npm scripts
  package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#7901 chore: update v3 issue template
  .github/ISSUE_TEMPLATE/1.bug_report_v3.yml
Labels: created-by: Payload team

#7919 fix(richtext-lexical): ensure html converter text is escaped
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/converters/html/converter/converters/text.ts
  packages/richtext-lexical/src/features/link/server/index.ts
  pnpm-lock.yaml
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#7924 fix(plugin-cloud): better logging on static handler
  packages/plugin-cloud/src/staticHandler.ts
Labels: created-by: Payload team

#7900 fix(db-postgres, db-sqlite): hasMany text, number, poly relationship, blocks, arrays within localized fields
  packages/db-sqlite/src/schema/build.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/build.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/transform/read/hasManyNumber.ts
  packages/drizzle/src/transform/read/hasManyText.ts
  packages/drizzle/src/transform/read/relationship.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/drizzle/src/transform/write/array.ts
  packages/drizzle/src/transform/write/blocks.ts
  packages/drizzle/src/transform/write/traverseFields.ts
  test/localization/collections/Blocks/index.ts
  test/localization/collections/NestedArray/index.ts
  test/localization/collections/NestedFields/index.ts
  test/localization/config.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
Labels: v3, created-by: Payload team

#7926 fix(richtext-lexical): enabledCollections and disabledCollections props in RelationshipFeature
  packages/richtext-lexical/src/features/relationship/server/index.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/collections/LexicalRelationships/index.ts
  test/fields/config.ts
  test/fields/payload-types.ts
  test/fields/seed.ts
  test/fields/slugs.ts
Labels: v3

#7929 chore: move ui and translations into deps from peerDeps
  packages/plugin-seo/package.json
  packages/plugin-stripe/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#7874 fix: incorrect config.upload types
  packages/next/package.json
  packages/next/src/fetchAPI-multipart/fileFactory.ts
  packages/next/src/fetchAPI-multipart/handlers.ts
  packages/next/src/fetchAPI-multipart/index.ts
  packages/next/src/fetchAPI-multipart/processMultipart.ts
  packages/next/src/fetchAPI-multipart/utilities.ts
  packages/next/src/utilities/addDataAndFileToRequest.ts
  packages/payload/package.json
  packages/payload/src/config/types.ts
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#7932 chore: upload dropzone style changes
  packages/next/src/views/List/Default/index.tsx
  packages/ui/src/elements/BulkUpload/AddFilesView/index.tsx
  packages/ui/src/elements/Dropzone/index.scss
  packages/ui/src/elements/Table/DefaultCell/fields/File/index.scss
  packages/ui/src/elements/Upload/index.scss
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/fields/Upload/Input.tsx
  packages/ui/src/fields/Upload/index.scss
Labels: v3, created-by: Contributor

#7938 feat: reduce package size and amount of dependencies by upgrading json-schema-to-typescript
  packages/payload/package.json
  pnpm-lock.yaml
  test/array-update/payload-types.ts
  test/auth/payload-types.ts
  test/collections-graphql/payload-types.ts
  test/collections-rest/payload-types.ts
  test/config/payload-types.ts
  test/custom-graphql/payload-types.ts
  test/database/payload-types.ts
  test/dataloader/payload-types.ts
  test/email-nodemailer/payload-types.ts
  test/email-resend/payload-types.ts
  test/email/payload-types.ts
  test/endpoints/payload-types.ts
  test/field-error-states/payload-types.ts
  test/field-perf/payload-types.ts
  test/fields/payload-types.ts
  test/globals/payload-types.ts
  test/graphql-schema-gen/payload-types.ts
  test/hooks/payload-types.ts
  test/live-preview/payload-types.ts
  test/localization-rtl/payload-types.ts
  test/localization/payload-types.ts
  test/migrations-cli/payload-types.ts
  test/nested-fields/payload-types.ts
  test/plugin-cloud-storage/payload-types.ts
  test/plugin-cloud/payload-types.ts
  test/plugin-form-builder/payload-types.ts
  test/plugin-nested-docs/payload-types.ts
  test/plugin-relationship-object-ids/payload-types.ts
  test/plugin-search/payload-types.ts
  test/plugin-sentry/payload-types.ts
  test/plugin-seo/payload-types.ts
  test/plugin-stripe/payload-types.ts
  test/plugins/payload-types.ts
  test/relationships/payload-types.ts
  test/storage-azure/payload-types.ts
  test/storage-gcs/payload-types.ts
  test/storage-s3/payload-types.ts
Labels: v3, created-by: Payload team
