Repository payloadcms/payload, pull requests merged in 2024-10, with the labels that each got.

#8489 feat!: upgrade next to 15.0.0-canary.173, react to 19.0.0-rc-3edc000d-20240926 in the monorepo
  app/(payload)/admin/[[...segments]]/not-found.tsx
  app/(payload)/admin/[[...segments]]/page.tsx
  package.json
  packages/live-preview-react/package.json
  packages/next/package.json
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/routes/rest/index.ts
  packages/next/src/utilities/getNextRequestI18n.ts
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initReq.ts
  packages/next/src/views/NotFound/index.tsx
  packages/next/src/views/Root/index.tsx
  packages/next/src/views/Root/meta.ts
  packages/payload/package.json
  packages/plugin-form-builder/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-seo/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  test/live-preview/app/live-preview/(pages)/[slug]/page.tsx
  test/live-preview/app/live-preview/(pages)/posts/[slug]/page.tsx
  test/live-preview/app/live-preview/(pages)/ssr-autosave/[slug]/page.tsx
  test/live-preview/app/live-preview/(pages)/ssr/[slug]/page.tsx
  test/package.json
Labels: v3, created-by: Payload team

#8505 fix(next): current published version label
  packages/next/src/views/Version/index.tsx
  packages/next/src/views/Versions/getLatestVersion.ts
  packages/next/src/views/Versions/index.tsx
Labels: v3, created-by: Payload team

#8509 docs: fix formatting on join field specifying additional fields section
  docs/fields/join.mdx
Labels: v3, created-by: Payload team

#8514 fix(templates): fixed drafts not being unpublished in the frontend of the website template
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/page.tsx
  templates/website/src/app/(frontend)/posts/page/[pageNumber]/page.tsx
  templates/website/src/fields/slug/SlugComponent.tsx
  templates/website/src/search/Component.tsx
Labels: v3, created-by: Payload team

#8520 fix(templates): remove lock from website template
  templates/website/pnpm-lock.yaml
Labels: v3, created-by: Payload team

#8521 fix: properly resolves cjs withPayload export
  packages/next/package.json
Labels: v3, created-by: Payload team

#8524 fix(next): safely checks user within useEffect
  packages/next/src/views/Edit/Default/index.tsx
  packages/next/src/views/LivePreview/index.client.tsx
Labels: v3, created-by: Payload team

#8527 fix(templates): add force-static to pages and posts
  templates/website/components.json
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
Labels: v3, created-by: Payload team

#8526 fix: ui crashes editing doc with deleted upload
  packages/ui/src/fields/Upload/HasOne/index.tsx
  packages/ui/src/fields/Upload/Input.tsx
Labels: v3, created-by: Payload team

#8532 chore: enable databaseAdapter writing again for pnpm dev [skip ci]
  test/dev.ts
Labels: v3, created-by: Payload team

#8542 fix(templates): dark and light mode not correctly working on website template's header
  templates/website/src/Header/Nav/index.tsx
  templates/website/src/app/(frontend)/[slug]/page.client.tsx
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/page.client.tsx
  templates/website/src/app/(frontend)/posts/page.tsx
  templates/website/src/app/(frontend)/posts/page/[pageNumber]/page.client.tsx
  templates/website/src/app/(frontend)/posts/page/[pageNumber]/page.tsx
  templates/website/src/app/(frontend)/search/page.client.tsx
  templates/website/src/app/(frontend)/search/page.tsx
Labels: v3, created-by: Payload team

#8380 docs: change req.params to req.routeParams
  docs/rest-api/overview.mdx
Labels: v3

#8546 fix(plugin-seo): now respects serverURL and api routes configuration
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/fields/Preview/PreviewComponent.tsx
Labels: v3, created-by: Payload team

#8540 fix(ui): disableBulkEdit on ui fields, defaults to true
  docs/admin/fields.mdx
  docs/fields/ui.mdx
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/FieldSelect/index.tsx
Labels: v3, created-by: Payload team

#8539 fix(drizzle): row / collapsible inside of localized fields
  packages/drizzle/src/transform/write/traverseFields.ts
  test/localization/collections/Group/index.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
Labels: v3, created-by: Payload team

#8439 fix(drizzle)!: convert column names for radio and select fields to snake_case
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
Labels: v3, created-by: Payload team

#8556 fix(db-postgres): missing types for db.pool by moving @types/pg from devDependencies to dependencies
  packages/db-postgres/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#8547 chore(templates): update templates with next.js promises
  templates/_template/package.json
  templates/_template/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/blank/package.json
  templates/blank/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  templates/blank/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/vercel-postgres/package.json
  templates/vercel-postgres/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/website/package.json
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(frontend)/layout.tsx
  templates/website/src/app/(frontend)/next/exit-preview/GET.ts
  templates/website/src/app/(frontend)/next/exit-preview/route.ts
  templates/website/src/app/(frontend)/next/preview/route.ts
  templates/website/src/app/(frontend)/posts/[slug]/page.tsx
  templates/website/src/app/(frontend)/posts/page/[pageNumber]/page.tsx
  templates/website/src/app/(frontend)/search/page.tsx
  templates/website/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  templates/with-payload-cloud/package.json
  templates/with-payload-cloud/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  templates/with-postgres/package.json
  templates/with-postgres/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-mongodb/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/app/(payload)/admin/[[...segments]]/not-found.tsx
Labels: v3, created-by: Payload team

#8552 fix: duplicate with uploads
  .gitignore
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/operations/duplicate.ts
  packages/payload/src/collections/operations/local/duplicate.ts
  packages/payload/src/uploads/generateFileData.ts
  packages/ui/src/elements/DocumentControls/index.tsx
  test/uploads/config.ts
  test/uploads/int.spec.ts
Labels: v3, created-by: Payload team

#8559 chore: deflakes lexical e2e test
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
Labels: v3, created-by: Payload team

#8560 fix(templates): await params/cookies properly
  templates/website/src/app/(frontend)/[slug]/page.tsx
  templates/website/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/website/src/utilities/getMeUser.ts
Labels: v3, created-by: Payload team

#8558 chore: removes duplicative join field test
  test/joins/e2e.spec.ts
Labels: v3, created-by: Payload team

#8578 chore(eslint): payload logger usage
  eslint.config.js
  packages/eslint-plugin/customRules/proper-payload-logger-usage.js
  packages/eslint-plugin/index.mjs
  packages/eslint-plugin/tests/proper-payload-logger-usage.js
Labels: v3, created-by: Payload team

#8548 docs: updates array field admin.components.RowLabel example
  docs/fields/array.mdx
Labels: v3, created-by: Payload team

#8513 fix(richtext-lexical): linkFeature doesn't respect admin.routes from payload.config.ts
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
Labels: v3

#8585 docs: specifies `defaultLocale` as a required property for localization
  docs/configuration/localization.mdx
Labels: v3, created-by: Payload team

#8586 docs: specifies `defaultLocale` as a required property for localization
  docs/configuration/localization.mdx
Labels: created-by: Payload team

#8572 fix(ui): add unstyled prop to react-select so that payload styles take priority
  packages/ui/src/elements/ReactSelect/index.scss
  packages/ui/src/elements/ReactSelect/index.tsx
Labels: v3, created-by: Payload team

#8593 fix(drizzle): handle hasMany rels within join field
  packages/drizzle/src/find/buildFindManyArgs.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/queries/buildQuery.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  test/relationships/int.spec.ts
Labels: created-by: Payload team

#8599 chore(templates): more next.js promises
  templates/_template/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  templates/with-payload-cloud/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/with-postgres/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/with-vercel-mongodb/src/app/(payload)/admin/[[...segments]]/page.tsx
  templates/with-vercel-postgres/src/app/(payload)/admin/[[...segments]]/page.tsx
Labels: v3, created-by: Payload team

#8598 fix(db-vercel-postgres): add pg dep
  packages/db-vercel-postgres/package.json
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#7781 feat(plugin-cloud-storage): add credentials to connect to azure
  packages/plugin-cloud-storage/README.md
  packages/plugin-cloud-storage/package.json
  packages/plugin-cloud-storage/src/adapters/azure/index.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#8493 feat: join field works with hasMany relationships
  packages/db-sqlite/src/init.ts
  packages/db-sqlite/src/schema/build.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/find/buildFindManyArgs.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/postgres/init.ts
  packages/drizzle/src/postgres/schema/build.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/queries/buildQuery.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/fields/config/sanitizeJoinField.ts
  packages/payload/src/index.ts
  test/joins/collections/Categories.ts
  test/joins/collections/Posts.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
  test/relationships/int.spec.ts
Labels: v3, created-by: Payload team

#8600 chore!: improve auth provider setting user and user cookie
  packages/next/src/views/CreateFirstUser/index.client.tsx
  packages/next/src/views/Login/LoginForm/index.tsx
  packages/next/src/views/Logout/LogoutClient.tsx
  packages/ui/src/providers/Auth/index.tsx
Labels: v3, created-by: Payload team

#8528 fix(payload): applies resize after cropping if `resizeOptions` are defined
  packages/payload/src/uploads/generateFileData.ts
  test/uploads/e2e.spec.ts
Labels: v3, created-by: Payload team

#8510 fix: calculates correct aspect ratio dimensions on sharp based files
  packages/payload/src/uploads/imageResizer.ts
  test/uploads/e2e.spec.ts
  test/uploads/ios-image.jpeg
Labels: created-by: Payload team

#8537 fix(payload): calculates correct aspect ratio dimensions on sharp based files
  packages/payload/src/uploads/imageResizer.ts
  test/uploads/e2e.spec.ts
  test/uploads/ios-image.jpeg
Labels: v3, created-by: Payload team

#8609 chore(next): adds export for `mergeHeaders` utility function
  packages/next/src/exports/utilities.ts
Labels: v3, created-by: Payload team

#8619 chore: clarifies i18n docs
  docs/configuration/i18n.mdx
Labels: v3, created-by: Payload team

#8613 feat(plugin-sentry): update plugin to 3.0
  app/global-error.tsx
  docs/plugins/sentry.mdx
  instrumentation.ts
  next.config.mjs
  package.json
  packages/plugin-form-builder/package.json
  packages/plugin-redirects/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-sentry/src/captureException.ts
  packages/plugin-sentry/src/exports/client.ts
  packages/plugin-sentry/src/index.ts
  packages/plugin-sentry/src/mocks/mockFile.js
  packages/plugin-sentry/src/plugin.spec.ts
  packages/plugin-sentry/src/plugin.ts
  packages/plugin-sentry/src/providers/AdminErrorBoundary.tsx
  packages/plugin-sentry/src/startSentry.ts
  packages/plugin-sentry/src/types.ts
  packages/plugin-sentry/tsconfig.json
  packages/plugin-stripe/package.json
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.server.config.ts
  test/package.json
  test/plugin-sentry/TestErrors.tsx
  test/plugin-sentry/config.ts
  test/plugin-sentry/payload-types.ts
  tsconfig.json
Labels: v3, created-by: Payload team

#8627 fix: corrects useAuth generics
  packages/ui/src/providers/Auth/index.tsx
Labels: v3, created-by: Payload team

#8629 chore: do not use withSentryConfig for dev/e2e next config if not needed
  instrumentation.ts
  next.config.mjs
Labels: v3, created-by: Payload team

#8633 fix(drizzle): hasMany joins - localized, add limit and schema path to subquery
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/payload/src/fields/config/sanitizeJoinField.ts
  packages/payload/src/fields/config/types.ts
  test/joins/collections/Categories.ts
  test/joins/collections/Posts.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
Labels: v3, created-by: Payload team

#8620 fix: sanitize virtual fields in `admin.useAsTitle`
  docs/admin/collections.mdx
  packages/payload/src/collections/config/useAsTitle.ts
  packages/payload/src/fields/config/types.ts
Labels: v3, created-by: Payload team

#8638 chore: improve i18n docs
  docs/configuration/i18n.mdx
Labels: v3, created-by: Payload team

#8643 fix: commonjs exports missing for withPayload
  packages/next/package.json
Labels: v3, created-by: Payload team

#8655 feat(db-postgres, db-vercel-postgres): add createDatabase, create db automatically if it doesn't exist
  docs/database/postgres.mdx
  packages/db-postgres/src/connect.ts
  packages/db-postgres/src/index.ts
  packages/db-postgres/src/types.ts
  packages/db-vercel-postgres/src/connect.ts
  packages/db-vercel-postgres/src/index.ts
  packages/db-vercel-postgres/src/types.ts
  packages/drizzle/src/exports/postgres.ts
  packages/drizzle/src/postgres/createDatabase.ts
  packages/drizzle/src/postgres/types.ts
Labels: v3, created-by: Payload team

#8432 fix(drizzle): indexes / unique with relationships, properly handle createdAt in versions
  packages/db-sqlite/src/schema/build.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/drizzle/src/postgres/schema/build.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  test/fields/collections/Indexed/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#8656 feat: add limit property to bulk update operation
  packages/next/src/routes/rest/collections/update.ts
  packages/payload/src/collections/operations/local/update.ts
  packages/payload/src/collections/operations/update.ts
  test/collections-rest/int.spec.ts
Labels: v3, created-by: Payload team

#8395 fix(db-mongodb): add validation to relationship ids
  packages/db-mongodb/src/utilities/sanitizeRelationshipIDs.ts
  test/database/int.spec.ts
Labels: v3, created-by: Contributor

#8607 chore: use custom jest reporter to achieve sane jest logs
  jest.config.js
  pnpm-lock.yaml
  test/_community/payload-types.ts
  test/jest-spec-reporter.cjs
  test/jest.config.js
  test/jest.setup.js
  test/jestreporter.cjs
Labels: v3, created-by: Payload team

#8660 chore(eslint): payload-logger proper usage works with template literals
  packages/db-postgres/src/connect.ts
  packages/db-vercel-postgres/src/connect.ts
  packages/drizzle/src/migrateReset.ts
  packages/drizzle/src/postgres/createDatabase.ts
  packages/eslint-plugin/customRules/proper-payload-logger-usage.js
  packages/eslint-plugin/tests/proper-payload-logger-usage.js
  packages/payload/src/database/migrations/migrateReset.ts
Labels: v3, created-by: Payload team

#8687 fix: ensure Component is not required in MappedComponent types
  packages/payload/src/admin/types.ts
Labels: v3, created-by: Payload team

#8624 fix(ui): hasMany selecting single docs clicking through instead of selecting a document
  packages/ui/src/elements/ListDrawer/DrawerContent.tsx
Labels: v3, created-by: Payload team

#8658 fix(ui): export useListRelationships
  packages/ui/src/exports/client/index.ts
Labels: v3, created-by: Payload team

#8689 fix: ensure dropzone respects canCreate permissions
  packages/ui/src/fields/Upload/Input.tsx
Labels: v3, created-by: Payload team

#8696 fix: validate should not always equate valid to true
  packages/ui/src/forms/useField/index.tsx
Labels: v3, created-by: Payload team

#8695 fix(ui): prevents `react-select` styles being injected into `hasMany` `number` fields
  packages/ui/src/elements/ReactSelect/index.tsx
Labels: v3, created-by: Payload team

#8697 feat: add disableTransaction to local api
  docs/database/transactions.mdx
  docs/local-api/overview.mdx
  packages/payload/src/collections/operations/create.ts
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/deleteByID.ts
  packages/payload/src/collections/operations/duplicate.ts
  packages/payload/src/collections/operations/local/create.ts
  packages/payload/src/collections/operations/local/delete.ts
  packages/payload/src/collections/operations/local/duplicate.ts
  packages/payload/src/collections/operations/local/update.ts
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/collections/operations/updateByID.ts
  packages/payload/src/globals/operations/update.ts
  test/database/config.ts
  test/database/int.spec.ts
Labels: v3, created-by: Payload team

#8699 chore: use indexes in jobs and disable transactions
  packages/payload/src/queues/config/jobsCollection.ts
  packages/payload/src/queues/operations/runAllJobs/index.ts
  packages/payload/src/queues/operations/runJob/getUpdateJobFunction.ts
Labels: created-by: Payload team

#8703 chore: when dev server restarts, ensure exiting the parent process kills child process
  test/dev.ts
  test/safelyRunScript.ts
Labels: v3, created-by: Payload team

#8704 fix: local update limit
  packages/payload/src/collections/operations/local/update.ts
  test/database/int.spec.ts
Labels: v3, created-by: Payload team

#8433 fix: ensure beforeValidate hook runs for reset password
  packages/payload/src/auth/operations/resetPassword.ts
Labels: v3, created-by: Payload team

#8706 fix(drizzle, ui): properly filters out number field values with the exists operator filter
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  packages/ui/src/elements/Table/DefaultCell/index.tsx
Labels: v3, created-by: Payload team

#8700 fix(next): returns proper document id type from init page result
  packages/next/src/utilities/initPage/handleAdminPage.ts
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Versions/index.tsx
  packages/payload/src/admin/views/types.ts
  test/joins/payload-types.ts
Labels: v3, created-by: Payload team

#8714 fix(templates): website template issue with previewing drafts
  templates/website/src/app/(frontend)/next/preview/route.ts
Labels: v3, created-by: Payload team

#8717 fix(ui): removes `overflow: hidden` style from actions wrapper
  packages/ui/src/elements/AppHeader/index.scss
Labels: v3, created-by: Payload team

#8617 fix(db-postgres, db-sqlite)!: bump drizzle-kit drizzle-orm @libsql/client
  package.json
  packages/db-postgres/package.json
  packages/db-sqlite/package.json
  packages/db-sqlite/src/connect.ts
  packages/db-sqlite/src/defaultSnapshot.ts
  packages/db-sqlite/src/types.ts
  packages/db-vercel-postgres/package.json
  packages/drizzle/package.json
  packages/drizzle/src/postgres/defaultSnapshot.ts
  packages/drizzle/src/postgres/types.ts
  pnpm-lock.yaml
  test/package.json
Labels: v3, created-by: Payload team

#8721 chore: bump drizzle-kit 0.26.1
  package.json
  packages/db-postgres/package.json
  packages/db-sqlite/package.json
  packages/db-vercel-postgres/package.json
  pnpm-lock.yaml
  test/package.json
Labels: v3, created-by: Payload team

#8723 fix(ui): add missing styles under the payload-default css layer
  packages/next/src/elements/DocumentHeader/Tabs/Tab/index.scss
  packages/next/src/elements/DocumentHeader/Tabs/index.scss
  packages/next/src/elements/DocumentHeader/index.scss
  packages/next/src/elements/DocumentLocked/index.scss
  packages/next/src/elements/DocumentTakeOver/index.scss
  packages/next/src/elements/FormHeader/index.scss
  packages/next/src/elements/LeaveWithoutSaving/index.scss
  packages/next/src/elements/Nav/NavWrapper/index.scss
  packages/next/src/elements/Nav/index.scss
  packages/next/src/templates/Default/Wrapper/index.scss
  packages/next/src/templates/Default/index.scss
  packages/next/src/templates/Minimal/index.scss
  packages/next/src/views/API/RenderJSON/index.scss
  packages/richtext-lexical/src/features/migrations/lexicalPluginToLexical/nodes/unknownConvertedNode/index.scss
  packages/richtext-lexical/src/features/migrations/slateToLexical/nodes/unknownConvertedNode/index.scss
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarButton/index.scss
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/index.scss
  packages/richtext-slate/src/field/elements/blockquote/index.scss
  packages/richtext-slate/src/field/elements/link/Element/index.scss
  packages/richtext-slate/src/field/elements/link/LinkDrawer/index.scss
  packages/richtext-slate/src/field/elements/ol/index.scss
  packages/richtext-slate/src/field/elements/relationship/Button/index.scss
  packages/richtext-slate/src/field/elements/relationship/Element/index.scss
  packages/richtext-slate/src/field/elements/ul/index.scss
  packages/richtext-slate/src/field/elements/upload/Button/index.scss
  packages/richtext-slate/src/field/elements/upload/Element/index.scss
Labels: v3, created-by: Payload team

#8725 ci: auto-close issues without repro, auto-label
  .github/ISSUE_TEMPLATE/1.bug_report_v3.yml
  .github/comments/invalid-reproduction.md
  .github/workflows/triage.yml
Labels: created-by: Payload team

#8726 fix: corrects schemaPath passing
  packages/payload/src/fields/config/sanitize.ts
Labels: v3, created-by: Payload team

#8747 chore: improves getLatestCollectionVersion where constraints
  packages/payload/src/versions/drafts/appendVersionToQueryKey.ts
  packages/payload/src/versions/getLatestCollectionVersion.ts
Labels: created-by: Payload team

#8746 chore: improves getLatestCollectionVersion where constraints
  packages/payload/src/versions/drafts/appendVersionToQueryKey.ts
  packages/payload/src/versions/getLatestCollectionVersion.ts
Labels: v3, created-by: Payload team

#8744 fix: disables document locking of `payload-locked-documents`, `preferences`, & `migrations` collections
  packages/payload/src/database/migrations/migrationsCollection.ts
  packages/payload/src/lockedDocuments/lockedDocumentsCollection.ts
  packages/payload/src/preferences/preferencesCollection.ts
  packages/payload/src/utilities/checkDocumentLockStatus.ts
  test/locked-documents/int.spec.ts
Labels: v3, created-by: Payload team

#8750 chore: bump drizzle-kit 0.26.2
  package.json
  packages/db-postgres/package.json
  packages/db-sqlite/package.json
  packages/db-vercel-postgres/package.json
  pnpm-lock.yaml
  test/package.json
Labels: v3, created-by: Payload team

#8753 fix: pg where filters not respected in policy generation
  packages/payload/src/utilities/getEntityPolicies.ts
Labels: v3, created-by: Payload team

#8737 fix(drizzle): select hasMany nested to array + tab/group
  packages/drizzle/src/transform/write/traverseFields.ts
  test/fields/collections/Select/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#8754 fix(drizzle): enforce uniqueness on index names
  packages/db-postgres/src/index.ts
  packages/db-sqlite/src/index.ts
  packages/db-sqlite/src/schema/build.ts
  packages/db-sqlite/src/schema/createIndex.ts
  packages/db-sqlite/src/schema/traverseFields.ts
  packages/db-vercel-postgres/src/index.ts
  packages/drizzle/src/index.ts
  packages/drizzle/src/postgres/schema/build.ts
  packages/drizzle/src/postgres/schema/createIndex.ts
  packages/drizzle/src/postgres/schema/traverseFields.ts
  packages/drizzle/src/types.ts
  packages/drizzle/src/utilities/buildIndexName.ts
  test/fields/collections/Indexed/index.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#8758 fix(db-postgres): esm compatible import of pg
  packages/drizzle/src/postgres/createDatabase.ts
Labels: v3, created-by: Payload team

#8759 fix(drizzle): bump drizzle-orm in drizzle package to 0.35.1
  packages/drizzle/package.json
Labels: v3, created-by: Payload team

#8765 fix(plugin-seo): description and title fields now respect given minLength and maxLength rules for passing validation
  docs/plugins/seo.mdx
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/fields/Overview/OverviewComponent.tsx
  packages/plugin-seo/src/fields/Overview/index.tsx
Labels: v3, created-by: Payload team

#8029 fix(richtext-lexical): fix CLS on collapsed/expanded state of Lexical blocks
  packages/richtext-lexical/src/features/blocks/client/component/BlockContent.tsx
Labels: v3, status: awaiting-reply

#8767 fix(ui): padding on relationship fields when no options or loading text is displayed
  packages/ui/src/elements/ReactSelect/index.scss
Labels: v3, created-by: Payload team

#8733 fix(db-mongodb): virtual fields within row / collapsible / tabs
  packages/db-mongodb/src/models/buildSchema.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: v3, created-by: Payload team

#8773 fix(richtext-*): ensure admin panel doesn't freeze with some field configurations consisting of 2+ richtext fields
  packages/ui/src/providers/Config/createClientConfig/fields.tsx
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/collections/LexicalObjectReferenceBug/index.ts
  test/fields/config.ts
Labels: v3, created-by: Payload team

#8755 chore: add internationalization guidelines to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: v3

#8774 fix(richtext-lexical): richtext fields in drawers aren't editable, inline toolbar artifacts are shown for readOnly editors
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.tsx
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-lexical/src/lexical/LexicalProvider.tsx
  test/buildConfigWithDefaults.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/collections/Lexical/index.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#8775 chore: upgrade typescript from 5.6.2 to 5.6.3, upgrade playwright from 1.46.0 to 1.48.1
  package.json
  packages/eslint-config/package.json
  packages/eslint-plugin/package.json
  packages/translations/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/vercel-postgres/package.json
  templates/website/package.json
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  test/package.json
Labels: v3, created-by: Payload team

#8776 perf: upgrade pino and pino-pretty, reducing the total amount of dependencies
  packages/payload/package.json
  packages/payload/src/utilities/logger.ts
  pnpm-lock.yaml
Labels: v3, created-by: Payload team

#8769 docs: corrects old imports
  docs/access-control/collections.mdx
  docs/access-control/fields.mdx
  docs/admin/collections.mdx
  docs/admin/locked-documents.mdx
  docs/admin/metadata.mdx
  docs/authentication/custom-strategies.mdx
  docs/authentication/email.mdx
  docs/authentication/overview.mdx
  docs/configuration/collections.mdx
  docs/configuration/i18n.mdx
  docs/configuration/overview.mdx
  docs/fields/array.mdx
  docs/fields/blocks.mdx
  docs/fields/checkbox.mdx
  docs/fields/code.mdx
  docs/fields/collapsible.mdx
  docs/fields/date.mdx
  docs/fields/email.mdx
  docs/fields/group.mdx
  docs/fields/join.mdx
  docs/fields/json.mdx
  docs/fields/number.mdx
  docs/fields/point.mdx
  docs/fields/radio.mdx
  docs/fields/relationship.mdx
  docs/fields/rich-text.mdx
  docs/fields/row.mdx
  docs/fields/select.mdx
  docs/fields/tabs.mdx
  docs/fields/text.mdx
  docs/fields/textarea.mdx
  docs/fields/ui.mdx
  docs/fields/upload.mdx
  docs/plugins/nested-docs.mdx
  docs/rest-api/overview.mdx
  docs/rich-text/slate.mdx
  docs/upload/overview.mdx
Labels: v3, created-by: Payload team

#8790 fix(ui): unique ids for nested rows on row duplicate to prevent errors with postgres
  packages/ui/src/forms/Form/fieldReducer.ts
  test/fields/collections/Blocks/e2e.spec.ts
Labels: v3, created-by: Payload team

#8813 fix(next, ui): ensures `selectAll` in the list view ignores locked documents
  packages/next/src/routes/rest/collections/delete.ts
  packages/next/src/routes/rest/collections/deleteByID.ts
  packages/next/src/routes/rest/collections/update.ts
  packages/next/src/routes/rest/collections/updateByID.ts
  packages/next/src/views/Edit/Default/index.tsx
  packages/ui/src/elements/DeleteMany/index.tsx
  packages/ui/src/elements/PublishMany/index.tsx
  packages/ui/src/elements/UnpublishMany/index.tsx
  packages/ui/src/providers/Selection/index.tsx
  test/locked-documents/e2e.spec.ts
Labels: v3, created-by: Payload team

#8818 fix: drizzle init args
  packages/db-postgres/src/connect.ts
  packages/db-vercel-postgres/src/connect.ts
Labels: v3, created-by: Payload team

#8825 feat!: bump next.js to 15.0.0
  package.json
  packages/live-preview-react/package.json
  packages/next/package.json
  packages/next/src/layouts/Root/index.tsx
  packages/payload/package.json
  packages/plugin-form-builder/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-seo/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/vercel-postgres/package.json
  templates/website/package.json
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  test/package.json
Labels: v3, created-by: Payload team

#8823 fix(drizzle): reuse existing joins for nested/localized fields when querying
  packages/drizzle/src/queries/addJoinTable.ts
  packages/drizzle/src/queries/buildOrderBy.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/drizzle/src/utilities/getNameFromDrizzleTable.ts
  test/fields/collections/Array/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: v3, created-by: Payload team

#8831 docs: append the beta tag to plugins installation command
  docs/graphql/graphql-schema.mdx
  docs/plugins/form-builder.mdx
  docs/plugins/nested-docs.mdx
  docs/plugins/redirects.mdx
  docs/plugins/search.mdx
  docs/plugins/sentry.mdx
  docs/plugins/seo.mdx
  docs/plugins/stripe.mdx
  docs/upload/storage-adapters.mdx
Labels: v3, created-by: Payload team

#8834 chore: fixes dev server doesn't drop the database
  test/dev.ts
Labels: v3, created-by: Payload team

#8810 chore: jest reporter log failed tests count
  test/jest-spec-reporter.cjs
Labels: v3, created-by: Payload team

#8602 feat: add localized indicator to field label
  packages/payload/src/admin/forms/Label.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/fields/Checkbox/index.tsx
  packages/ui/src/fields/FieldLabel/index.scss
  packages/ui/src/fields/FieldLabel/index.tsx
Labels: v3, created-by: Payload team

#8846 fix: reduce import map diff when config changes
  packages/payload/src/bin/generateImportMap/index.ts
Labels: v3, created-by: Payload team

#8857 chore(cpa): pin monorepo templates to tag
  packages/create-payload-app/src/lib/templates.ts
Labels: created-by: Payload team

#8839 fix(drizzle): sort by localized fields
  packages/db-sqlite/src/countDistinct.ts
  packages/drizzle/src/postgres/countDistinct.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  test/dev.ts
  test/localization/int.spec.ts
Labels: v3, created-by: Payload team

#8855 fix(cpa): properly detect if pnpm exists on windows
  packages/create-payload-app/src/lib/get-package-manager.ts
Labels: v3, created-by: Payload team

#8821 perf: use indexes on updatedAt and globals versions timestamps by default
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/versions/buildGlobalFields.ts
Labels: v3, created-by: Payload team

#8724 fix(ui): leave without saving popup being triggered by changing the theme in the /account page
  packages/next/src/views/Account/ToggleTheme/index.tsx
  packages/payload/src/admin/fields/Radio.ts
  packages/ui/src/fields/RadioGroup/index.tsx
Labels: v3, created-by: Payload team

#8860 fix(ui): upload buttons being hidden at mobile screen widths
  packages/ui/src/elements/Upload/index.scss
Labels: v3, created-by: Payload team

#8847 fix(plugin-search): issues with overriding the search collection slug consistently across hooks
  packages/plugin-search/src/Search/hooks/deleteFromSearch.ts
  packages/plugin-search/src/Search/hooks/syncWithSearch.ts
  packages/plugin-search/src/Search/index.ts
  packages/plugin-search/src/Search/ui/index.client.tsx
  packages/plugin-search/src/Search/ui/index.tsx
  packages/plugin-search/src/index.ts
  packages/plugin-search/src/types.ts
Labels: v3, created-by: Payload team

#8828 feat!: rename @payloadcms/plugin-cloud
  docs/cloud/projects.mdx
  package.json
  packages/create-payload-app/src/lib/init-next.ts
  packages/create-payload-app/src/lib/replacements.ts
  packages/db-postgres/package.json
  packages/payload-cloud/.gitignore
  packages/payload-cloud/.prettierignore
  packages/payload-cloud/.swcrc-build
  packages/payload-cloud/LICENSE.md
  packages/payload-cloud/README.md
  packages/payload-cloud/eslint.config.js
  packages/payload-cloud/jest.config.js
  packages/payload-cloud/package.json
  packages/payload-cloud/src/email.spec.ts
  packages/payload-cloud/src/email.ts
  packages/payload-cloud/src/hooks/afterDelete.ts
  packages/payload-cloud/src/hooks/beforeChange.ts
  packages/payload-cloud/src/hooks/uploadCache.ts
  packages/payload-cloud/src/index.ts
  packages/payload-cloud/src/plugin.spec.ts
  packages/payload-cloud/src/plugin.ts
  packages/payload-cloud/src/staticHandler.ts
  packages/payload-cloud/src/types.ts
  packages/payload-cloud/src/utilities/authAsCognitoUser.ts
  packages/payload-cloud/src/utilities/createKey.ts
  packages/payload-cloud/src/utilities/getIncomingFiles.ts
  packages/payload-cloud/src/utilities/getStorageClient.ts
  packages/payload-cloud/tsconfig.json
  packages/payload/src/versions/payloadPackageList.ts
  packages/plugin-cloud/src/admin.js
  pnpm-lock.yaml
  scripts/lib/publishList.ts
  test/import-test/import-all-2-exports.ts
  test/package.json
  test/payload-cloud/collections/Media.ts
  test/payload-cloud/collections/Users.ts
  test/payload-cloud/config.ts
  test/payload-cloud/eslint.config.js
  test/payload-cloud/int.spec.ts
  test/payload-cloud/payload-types.ts
  test/payload-cloud/tsconfig.eslint.json
  test/payload-cloud/tsconfig.json
  test/setupProd.ts
  test/tsconfig.typecheck.json
  tsconfig.json
Labels: v3, created-by: Payload team

#8869 chore: update docs mention on payload cloud plugin
  docs/cloud/projects.mdx
Labels: v3, created-by: Payload team

#8871 chore(templates): use payload cloud
  templates/_template/package.json
  templates/blank/package.json
  templates/website/README.md
  templates/website/package.json
  templates/website/src/payload.config.ts
  templates/with-payload-cloud/package.json
  templates/with-payload-cloud/src/payload.config.ts
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
Labels: v3, created-by: Payload team

#8872 fix(richtext-lexical): ensure editor cursor / selection state is preserved when working with drawers
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.tsx
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/features/relationship/client/components/RelationshipComponent.tsx
  packages/richtext-lexical/src/features/relationship/client/drawer/index.tsx
  packages/richtext-lexical/src/features/upload/client/component/index.tsx
  packages/richtext-lexical/src/features/upload/client/drawer/index.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/Drawer.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/useLexicalDocumentDrawer.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/useLexicalDrawer.tsx
  packages/richtext-lexical/src/utilities/fieldsDrawer/useLexicalListDrawer.tsx
  packages/ui/src/elements/Button/index.scss
  packages/ui/src/elements/DocumentDrawer/index.tsx
  packages/ui/src/elements/DocumentDrawer/types.ts
  packages/ui/src/elements/ListDrawer/index.tsx
  packages/ui/src/elements/ListDrawer/types.ts
  packages/ui/src/exports/client/index.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: v3, created-by: Payload team

#8743 fix(cpa): write POSTGRES_URL instead of DATABASE_URI to .env for vercel postgres
  packages/create-payload-app/src/lib/write-env-file.ts
  packages/create-payload-app/src/main.ts
  packages/drizzle/src/postgres/createDatabase.ts
Labels: v3, created-by: Payload team

#8905 fix: #8903, form-builder payment static value field
  packages/plugin-form-builder/src/collections/Forms/DynamicPriceSelector.tsx
Labels: v3, created-by: Payload team

#8894 fix: autosave potentially losing latest: true w/ race condition
  packages/payload/src/versions/saveVersion.ts
Labels: v3, created-by: Payload team

#8908 feat: join field defaultLimit and defaultSort
  docs/fields/join.mdx
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/payload/src/fields/config/types.ts
  test/joins/collections/Categories.ts
  test/joins/int.spec.ts
Labels: v3, created-by: Payload team

#8910 fix(db-mongodb): id in querying with an aggregation using a comma-delimited value
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
  test/joins/int.spec.ts
Labels: v3, created-by: Payload team

#8899 fix(next, ui): only show locked docs that are not expired
  packages/next/src/views/Edit/Default/index.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/DocumentInfo/types.ts
  packages/ui/src/utilities/buildFormState.ts
Labels: v3, created-by: Payload team

#8917 docs: fix dead link for local API
  docs/admin/components.mdx
Labels: v3, created-by: Payload team

#8921 chore: adds additional locked documents e2e tests
  test/locked-documents/e2e.spec.ts
Labels: v3, created-by: Payload team

#8927 fix(ui): missing localization label on text area fields
  packages/ui/src/fields/Textarea/index.tsx
Labels: v3, created-by: Payload team

#8913 fix(ui): sanitize limit for preferences
  packages/ui/src/providers/ListQuery/index.tsx
Labels: v3, created-by: Payload team

#8925 chore: corrects package import paths for live preview test
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.tsx
Labels: v3, created-by: Payload team

#8930 chore: uses custom live preview component if one is provided
  packages/next/src/views/Document/getViewsFromConfig.tsx
Labels: v3, created-by: Payload team

#8938 fix: plugin-search with localization enabled
  docs/plugins/search.mdx
  packages/plugin-search/src/Search/hooks/syncWithSearch.ts
  packages/plugin-search/src/Search/index.ts
  packages/plugin-search/src/index.ts
  packages/plugin-search/src/types.ts
  test/plugin-search/int.spec.ts
Labels: v3, created-by: Payload team

#8933 fix(db-mongodb): joins with singular collection name
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  test/joins/collections/Categories.ts
  test/joins/collections/Singular.ts
  test/joins/config.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
Labels: v3, created-by: Payload team

#8943 chore: updates payload cloud plugin docs
  packages/payload-cloud/README.md
Labels: v3, created-by: Payload team

#8820 feat!: custom views are now public by default and fixed some issues with notFound page
  docs/admin/views.mdx
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initPage/isCustomAdminView.ts
  packages/next/src/utilities/initPage/shared.ts
  packages/next/src/views/NotFound/index.tsx
  packages/next/src/views/Root/index.tsx
  packages/payload/src/config/client.ts
  test/admin/components/views/CustomProtectedView/index.tsx
  test/admin/config.ts
  test/admin/e2e/1/e2e.spec.ts
  test/admin/globals/Settings.ts
  test/admin/payload-types.ts
  test/admin/shared.ts
  test/admin/slugs.ts
Labels: v3, created-by: Payload team

#8926 fix(ui): broken buttons in the bulk upload drawer
  packages/ui/src/elements/BulkUpload/ActionsBar/index.scss
  packages/ui/src/elements/BulkUpload/FileSidebar/index.scss
  packages/ui/src/elements/BulkUpload/FileSidebar/index.tsx
Labels: v3, created-by: Payload team

#8940 chore: relax logging for jobs
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/handleWorkflowError.ts
Labels: created-by: Payload team

#8934 feat: add `defaultPopulate` property to collection config
  docs/configuration/collections.mdx
  docs/queries/select.mdx
  packages/payload/src/collections/config/types.ts
  packages/payload/src/collections/dataloader.ts
  packages/payload/src/fields/hooks/afterRead/relationshipPopulationPromise.ts
  packages/richtext-lexical/src/features/relationship/server/index.ts
  packages/richtext-lexical/src/features/upload/server/feature.server.ts
  packages/richtext-lexical/src/populateGraphQL/populate.ts
  packages/richtext-slate/src/data/populate.ts
  packages/richtext-slate/src/data/recurseNestedFields.ts
  packages/richtext-slate/src/data/richTextRelationshipPromise.ts
  test/select/collections/Pages/index.ts
  test/select/config.ts
  test/select/int.spec.ts
  test/select/payload-types.ts
Labels: v3, created-by: Payload team

#8932 fix(db-mongodb): ensure relationships are stored in `ObjectID`
  packages/payload/src/utilities/traverseFields.ts
  test/joins/int.spec.ts
Labels: v3, created-by: Payload team

#8944 fix(ui): performance improvements in the bulk uploader when adding lots of images at once
  packages/ui/src/elements/BulkUpload/FileSidebar/index.tsx
  packages/ui/src/elements/BulkUpload/FormsManager/index.tsx
  packages/ui/src/elements/Thumbnail/createThumbnail.ts
  packages/ui/src/elements/Thumbnail/index.tsx
Labels: v3, created-by: Payload team

#8228 feat: adds jobs queue
  docs/database/transactions.mdx
  docs/jobs-queue/overview.mdx
  packages/payload/package.json
  packages/payload/src/bin/index.ts
  packages/payload/src/config/client.ts
  packages/payload/src/config/defaults.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/config/types.ts
  packages/payload/src/index.ts
  packages/payload/src/queues/config/generateJobsJSONSchemas.ts
  packages/payload/src/queues/config/jobsCollection.ts
  packages/payload/src/queues/config/types/index.ts
  packages/payload/src/queues/config/types/taskTypes.ts
  packages/payload/src/queues/config/types/workflowJSONTypes.ts
  packages/payload/src/queues/config/types/workflowTypes.ts
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJSONJob/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/calculateBackoffWaitUntil.ts
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/getUpdateJobFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/handleWorkflowError.ts
  packages/payload/src/queues/operations/runJobs/runJob/importHandlerPath.ts
  packages/payload/src/queues/operations/runJobs/runJob/index.ts
  packages/payload/src/queues/restEndpointRun.ts
  packages/payload/src/queues/utilities/getJobTaskStatus.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.tsx
  packages/storage-vercel-blob/src/index.ts
  packages/storage-vercel-blob/src/staticHandler.ts
  pnpm-lock.yaml
  templates/website/src/app/(payload)/admin/importMap.js
  test/_community/payload-types.ts
  test/fields/payload-types.ts
  test/helpers/e2e/reorderColumns.ts
  test/import-test/import-all-2-exports.ts
  test/queues/.gitignore
  test/queues/config.ts
  test/queues/e2e.spec.ts
  test/queues/eslint.config.js
  test/queues/int.spec.ts
  test/queues/payload-types.ts
  test/queues/runners/externalTask.ts
  test/queues/runners/externalWorkflow.ts
  test/queues/runners/updatePost.ts
  test/queues/schema.graphql
  test/queues/seed.ts
  test/queues/tsconfig.eslint.json
  test/queues/tsconfig.json
Labels: v3, created-by: Payload team

#8954 fix: bulk upload mimetype wildcard file selection
  packages/payload/src/exports/shared.ts
  packages/payload/src/uploads/mimeTypeValidator.ts
  packages/payload/src/utilities/validateMimeType.ts
  packages/translations/src/clientKeys.ts
  packages/ui/src/elements/BulkUpload/index.tsx
Labels: v3, created-by: Payload team

#8951 docs: fix `defaultPopulate` docs formatting
  docs/queries/select.mdx
Labels: v3, created-by: Payload team

#8952 fix(ui): overly large width on stay logged in modal content
  packages/ui/src/elements/StayLoggedIn/index.scss
Labels: v3, created-by: Payload team

#8953 fix: return type of `findByID` with `strict: true`
  packages/payload/src/types/index.ts
Labels: v3, created-by: Payload team

#8735 fix(ui): increase react-select z-index
  packages/ui/src/elements/ReactSelect/index.scss
Labels: v3, created-by: Payload team

#8949 ci: port all templates, actions, and workflows from main
  .github/ISSUE_TEMPLATE/1.bug_report_v3.yml
  .github/ISSUE_TEMPLATE/2.design_issue.yml
  .github/ISSUE_TEMPLATE/3.bug_report_v2.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/triage/LICENSE
  .github/actions/triage/README.md
  .github/actions/triage/action.yml
  .github/actions/triage/jest.config.js
  .github/actions/triage/package.json
  .github/actions/triage/pnpm-lock.yaml
  .github/actions/triage/src/index.ts
  .github/actions/triage/tsconfig.json
  .github/comments/invalid-reproduction.md
  .github/dependabot.yml
  .github/pnpm-lock.yaml
  .github/workflows/label-author.yml
  .github/workflows/label-on-change.yml
  .github/workflows/lock-issues.yml
  .github/workflows/stale.yml
  .github/workflows/triage.yml
Labels: v3, created-by: Payload team

#8958 feat(plugin-seo)!: support overriding default fields via a function instead and fixes bugs regarding localized labels
  docs/plugins/seo.mdx
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/index.tsx
  packages/plugin-seo/src/types.ts
  test/plugin-seo/components/AfterInput.tsx
  test/plugin-seo/components/BeforeInput.tsx
  test/plugin-seo/config.ts
  test/plugin-seo/e2e.spec.ts
Labels: v3, created-by: Payload team

#8950 fix: handle case where `read` access on `users` is restricted by access control for locked documents
  packages/next/src/elements/DocumentLocked/index.tsx
  packages/next/src/views/Dashboard/Default/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/next/src/views/Edit/Default/index.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/globals/operations/findOne.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/elements/Locked/index.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/DocumentInfo/types.ts
  packages/ui/src/utilities/buildFormState.ts
  packages/ui/src/utilities/getFormState.ts
  packages/ui/src/utilities/handleTakeOver.tsx
  packages/ui/src/utilities/isClientUserObject.ts
  test/locked-documents/collections/Users/index.ts
  test/locked-documents/config.ts
  test/locked-documents/e2e.spec.ts
  test/locked-documents/payload-types.ts
Labels: v3, created-by: Payload team

#8967 fix(next): overly large width on document locked modal content
  packages/next/src/elements/DocumentLocked/index.scss
Labels: v3, created-by: Payload team

#8966 fix(db-mongodb): `select` with unnamed tabs
  packages/db-mongodb/src/utilities/buildProjectionFromSelect.ts
  packages/drizzle/src/find/traverseFields.ts
  test/select/collections/Posts/index.ts
  test/select/int.spec.ts
  test/select/payload-types.ts
Labels: v3, created-by: Payload team

#8972 fix(templates): website template error inside the populateAuthors hook
  templates/website/src/collections/Posts/hooks/populateAuthors.ts
  templates/website/src/payload-types.ts
Labels: v3, created-by: Payload team
