Repository payloadcms/payload, pull requests merged in 2025-02, with the labels that each got.

#10931 examples: added missing sharp dependency to the remix website package
  examples/remix/website/package.json
Labels: created-by: Contributor

#10937 docs: correct grammar and improve clarity on preventing-abuse.mdx
  docs/production/preventing-abuse.mdx
Labels: created-by: Contributor

#10950 chore(deps): bump packages used to build payload
  .github/actions/triage/package.json
  .github/pnpm-lock.yaml
  package.json
  packages/create-payload-app/package.json
  packages/db-postgres/package.json
  packages/db-vercel-postgres/package.json
  packages/next/package.json
  packages/payload/package.json
  packages/richtext-lexical/package.json
  packages/translations/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  templates/plugin/package.json
  test/package.json
Labels: created-by: Payload team

#10632 fix(plugin-search): gets api route from useConfig
  packages/plugin-search/src/Search/index.ts
  packages/plugin-search/src/Search/ui/ReindexButton/index.client.tsx
  packages/plugin-search/src/Search/ui/ReindexButton/index.tsx
  packages/plugin-search/src/Search/ui/ReindexButton/types.ts
Labels: created-by: Contributor

#10954 fix(richtext-lexical): link drawer has no fields if parent document `create` access control is `false`
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/ui/src/forms/RenderFields/index.tsx
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/collections/LexicalAccessControl/index.ts
  test/fields/config.ts
  test/fields/payload-types.ts
  test/fields/seed.ts
  test/fields/slugs.ts
Labels: created-by: Payload team

#10953 chore(plugin-search): deprecates apiBasePath from config
  packages/plugin-search/src/Search/ui/ReindexButton/index.client.tsx
  packages/plugin-search/src/index.ts
  packages/plugin-search/src/types.ts
Labels: created-by: Payload team

#10910 fix(plugin-search): generates full docURL with basePath from next config
  packages/plugin-search/src/Search/ui/LinkToDoc/index.client.tsx
  tsconfig.base.json
Labels: created-by: Payload team

#10956 test: admin list view custom components
  test/admin/e2e/list-view/e2e.spec.ts
Labels: created-by: Contributor

#10959 docs: correct broken NPM badge images on plugin documentation
  docs/plugins/form-builder.mdx
  docs/plugins/multi-tenant.mdx
  docs/plugins/nested-docs.mdx
  docs/plugins/redirects.mdx
  docs/plugins/search.mdx
  docs/plugins/sentry.mdx
  docs/plugins/stripe.mdx
Labels: created-by: Payload team

#10979 templates: set pnpm engines to version 9
  templates/_template/package.json
  templates/blank/package.json
  templates/plugin/package.json
  templates/website/package.json
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-website/package.json
Labels: created-by: Payload team

#10419 fix: allow public errors to thread through on response
  packages/payload/src/utilities/routeError.ts
Labels: created-by: Payload team

#10985 docs: fixes dynamic, fully qualified live preview url args
  docs/live-preview/overview.mdx
Labels: created-by: Payload team

#10984 feat: exposes helpful args to ts schema gen
  packages/payload/src/config/types.ts
  packages/payload/src/utilities/configToJSONSchema.ts
Labels: created-by: Payload team

#10992 fix(plugin-multi-tenant): incorrect tenant selection with postgres
  packages/plugin-multi-tenant/src/components/TenantSelector/index.tsx
  packages/plugin-multi-tenant/src/providers/TenantSelectionProvider/index.tsx
  packages/plugin-multi-tenant/src/utilities/getTenantFromCookie.ts
Labels: created-by: Payload team

#10993 fix(plugin-search): deleting docs even when there's a published version
  packages/plugin-search/src/types.ts
  packages/plugin-search/src/utilities/syncDocAsSearchIndex.ts
  test/plugin-search/config.ts
  test/plugin-search/int.spec.ts
Labels: created-by: Payload team

#10997 fix(richtext-lexical): removes css from jsx converter
  packages/richtext-lexical/src/exports/react/components/RichText/converter/converters/list.tsx
  packages/richtext-lexical/src/exports/react/components/RichText/index.css
  packages/richtext-lexical/src/exports/react/components/RichText/index.tsx
Labels: created-by: Payload team

#11006 fix(next): viewing modified-only diff view containing localized arrays throws error
  packages/next/src/views/Version/RenderFieldsToDiff/buildVersionFields.tsx
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#11003 test: cleans up fields-relationship test suite
  test/fields-relationship/PrePopulateFieldUI/index.tsx
  test/fields-relationship/baseFields.ts
  test/fields-relationship/collections/Collection1/index.ts
  test/fields-relationship/collections/Collection2/index.ts
  test/fields-relationship/collections/FilterFalse/index.ts
  test/fields-relationship/collections/FilterTrue/index.ts
  test/fields-relationship/collections/MixedMedia/index.ts
  test/fields-relationship/collections/Podcast/index.ts
  test/fields-relationship/collections/Relation1/index.ts
  test/fields-relationship/collections/Relation2/index.ts
  test/fields-relationship/collections/RelationWithTitle/index.ts
  test/fields-relationship/collections/Relationship/index.ts
  test/fields-relationship/collections/RelationshipFiltered/index.ts
  test/fields-relationship/collections/Restricted/index.ts
  test/fields-relationship/collections/UpdatedExternally/index.ts
  test/fields-relationship/collections/Versions/index.ts
  test/fields-relationship/collections/Video/index.ts
  test/fields-relationship/config.ts
  test/fields-relationship/e2e.spec.ts
  test/fields-relationship/int.spec.ts
  test/fields-relationship/payload-types.ts
  test/fields-relationship/seed.ts
  test/fields-relationship/slugs.ts
  test/fields/payload-types.ts
  test/uploads/e2e.spec.ts
  tsconfig.base.json
Labels: created-by: Payload team

#10976 feat(ui): improve hasMany TextField UX
  packages/ui/src/elements/ReactSelect/MultiValueLabel/index.scss
  packages/ui/src/elements/ReactSelect/MultiValueLabel/index.tsx
  packages/ui/src/elements/ReactSelect/types.ts
  packages/ui/src/fields/Text/Input.tsx
  test/fields/collections/Text/e2e.spec.ts
  test/fields/collections/Text/index.ts
Labels: created-by: Contributor

#10999 fix(ui): allow schedule publish to be accessed without changes
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Button/types.ts
  packages/ui/src/elements/PublishButton/index.tsx
Labels: created-by: Payload team

#11013 chore(richtext-lexical): fix unchecked indexed acess in lexical blocks feature
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/component/removeEmptyArrayValues.ts
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/blocks/client/index.tsx
Labels: created-by: Payload team

#11014 chore(richtext-lexical): fix unchecked indexed access (part 3)
  packages/richtext-lexical/src/features/blocks/client/markdownTransformer.ts
  packages/richtext-lexical/src/features/blocks/server/linesFromMatchToContentAndPropsString.ts
  packages/richtext-lexical/src/features/blocks/server/markdownTransformer.ts
  packages/richtext-lexical/src/features/blocks/server/validate.ts
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/markdownTransformer.ts
  packages/richtext-lexical/src/features/heading/markdownTransformer.ts
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/features/link/nodes/LinkNode.ts
  packages/richtext-lexical/src/features/link/server/validate.ts
  packages/richtext-lexical/src/features/lists/shared/markdown.ts
Labels: created-by: Payload team

#11018 fix(plugin-multi-tenant): correctly set doc default value on load
  packages/plugin-multi-tenant/src/components/TenantField/index.client.tsx
Labels: created-by: Payload team

#10914 chore(cpa): add ts strict mode
  .github/CODEOWNERS
  packages/create-payload-app/src/lib/manage-env-files.ts
  packages/create-payload-app/src/lib/wrap-next-config.ts
  packages/create-payload-app/tsconfig.json
Labels: created-by: Payload team

#10961 fix(ui): improve useIgnoredEffect hook
  packages/eslint-config/package.json
  packages/eslint-plugin/package.json
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/elements/ListDrawer/DrawerContent.tsx
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/hooks/useEffectEvent.ts
  packages/ui/src/hooks/useIgnoredEffect.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#9869 fix(richtext-lexical): ensure sub-fields have access to full document data in form state
  docs/admin/hooks.mdx
  packages/next/src/views/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/payload/src/admin/forms/Form.ts
  packages/payload/src/auth/strategies/local/generatePasswordSaltHash.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterChange/promise.ts
  packages/payload/src/fields/hooks/afterChange/traverseFields.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/afterRead/traverseFields.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/hooks/beforeChange/traverseFields.ts
  packages/payload/src/fields/hooks/beforeDuplicate/promise.ts
  packages/payload/src/fields/hooks/beforeDuplicate/traverseFields.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/fields/hooks/beforeValidate/traverseFields.ts
  packages/payload/src/fields/validations.ts
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/blocks/server/validate.ts
  packages/richtext-lexical/src/features/link/server/validate.ts
  packages/richtext-lexical/src/features/upload/server/validate.ts
  packages/richtext-lexical/src/field/rscEntry.tsx
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/utilities/buildInitialState.ts
  packages/richtext-lexical/src/utilities/fieldsDrawer/DrawerContent.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/fields/Password/index.tsx
  packages/ui/src/forms/Form/context.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/types.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  packages/ui/src/forms/useField/index.tsx
  packages/ui/src/utilities/buildFormState.ts
  packages/ui/src/views/Edit/Auth/APIKey.tsx
  packages/ui/src/views/Edit/index.tsx
  test/fields/collections/Lexical/blockComponents/BlockComponentRSC.tsx
  test/fields/collections/Lexical/blocks.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Lexical/index.ts
  test/playwright.config.ts
Labels: created-by: Payload team, prioritized

#11021 fix(ui): relationship filter clearing on blur
  packages/ui/src/elements/WhereBuilder/Condition/Date/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/DefaultFilter/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Number/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/exports/client/index.ts
  test/fields-relationship/payload-types.ts
Labels: created-by: Payload team

#11024 chore: fix lexical tests that are failing on main branch
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
Labels: created-by: Payload team

#11025 fix(richtext-lexical): duplicative error paths in validation
  packages/richtext-lexical/src/features/blocks/server/validate.ts
  packages/richtext-lexical/src/features/link/server/validate.ts
  packages/richtext-lexical/src/features/upload/server/validate.ts
Labels: created-by: Payload team

#11027 refactor: do not use description functions for generated types JSDocs
  packages/payload/src/utilities/configToJSONSchema.ts
Labels: created-by: Payload team

#11026 test: addListFilter helper
  test/admin/e2e/list-view/e2e.spec.ts
  test/fields-relationship/collections/Relationship/index.ts
  test/fields-relationship/e2e.spec.ts
  test/fields/collections/Checkbox/e2e.spec.ts
  test/fields/collections/Email/e2e.spec.ts
  test/fields/collections/Number/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/payload-types.ts
  test/helpers/e2e/addListFilter.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11012 fix(db-postgres): select has many with autosave
  packages/drizzle/src/transform/write/array.ts
  packages/drizzle/src/transform/write/blocks.ts
  packages/drizzle/src/transform/write/traverseFields.ts
  test/fields/collections/SelectVersions/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#10938 fix(db-postgres): ensure globals have `createdAt`, `updatedAt` and `globalType` fields
  packages/drizzle/src/createGlobal.ts
  packages/drizzle/src/transform/write/traverseFields.ts
  packages/drizzle/src/updateGlobal.ts
  packages/payload/src/globals/operations/update.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#11007 feat(ui): adds filtering config option and implementation for filtering a…
  packages/next/src/layouts/Root/index.tsx
  packages/payload/src/config/types.ts
Labels: created-by: Payload team

#11030 chore(plugin-multi-tenant): add better defaults for imported components
  packages/plugin-multi-tenant/src/defaults.ts
  packages/plugin-multi-tenant/src/fields/tenantField/index.ts
  packages/plugin-multi-tenant/src/fields/tenantsArrayField/index.ts
  packages/plugin-multi-tenant/src/index.ts
Labels: created-by: Payload team

#11023 fix(ui): clearing value from relationship filter leaves stale query
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  test/admin/e2e/list-view/e2e.spec.ts
  tsconfig.base.json
Labels: created-by: Payload team

#10981 feat(ui): adds admin.components.listControlsMenu option
  docs/configuration/collections.mdx
  packages/next/src/views/List/renderListViewSlots.tsx
  packages/payload/src/bin/generateImportMap/iterateCollections.ts
  packages/payload/src/collections/config/types.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/icons/Dots/index.scss
  packages/ui/src/icons/Dots/index.tsx
  packages/ui/src/views/List/index.tsx
  test/admin/collections/Posts.ts
  test/admin/e2e/list-view/e2e.spec.ts
Labels: created-by: Payload team

#11034 chore: deflake joins e2e tests
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Checkbox/e2e.spec.ts
  test/fields/collections/Collapsible/e2e.spec.ts
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  test/fields/collections/CustomID/e2e.spec.ts
  test/fields/collections/Date/e2e.spec.ts
  test/fields/collections/Email/e2e.spec.ts
  test/fields/collections/Indexed/e2e.spec.ts
  test/fields/collections/JSON/e2e.spec.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/collections/Number/e2e.spec.ts
  test/fields/collections/Point/e2e.spec.ts
  test/fields/collections/Radio/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/collections/RichText/e2e.spec.ts
  test/fields/collections/Row/e2e.spec.ts
  test/fields/collections/Select/e2e.spec.ts
  test/fields/collections/Tabs/e2e.spec.ts
  test/fields/collections/Tabs2/e2e.spec.ts
  test/fields/collections/Text/e2e.spec.ts
  test/fields/collections/UI/e2e.spec.ts
  test/fields/collections/Upload/e2e.spec.ts
  test/fields/collections/UploadRestricted/e2e.spec.ts
  test/helpers/rest.ts
  test/joins/e2e.spec.ts
  test/joins/seed.ts
  test/localization/e2e.spec.ts
  test/playwright.config.ts
  test/uploads/e2e.spec.ts
Labels: created-by: Payload team

#11035 chore: fix flaky lexical test
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/payload-types.ts
  test/playwright.config.ts
Labels: created-by: Payload team

#11036 chore: fix eslint wasn't running in test dir
  eslint.config.js
  test/eslint.config.js
Labels: created-by: Payload team

#11043 chore: find and use an available port in tests
  test/dev.ts
Labels: created-by: Payload team

#11044 chore: `pnpm dev` defaults to the _community test suite
  test/dev.ts
Labels: created-by: Payload team

#11032 fix(ui): removing final condition closes where builder
  packages/ui/src/elements/ListControls/index.tsx
  test/admin/e2e/list-view/e2e.spec.ts
Labels: created-by: Payload team

#11047 revert(ui): adds admin.components.listControlsMenu option
  docs/configuration/collections.mdx
  packages/next/src/views/List/renderListViewSlots.tsx
  packages/payload/src/bin/generateImportMap/iterateCollections.ts
  packages/payload/src/collections/config/types.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/icons/Dots/index.scss
  packages/ui/src/icons/Dots/index.tsx
  packages/ui/src/views/List/index.tsx
  test/admin/collections/Posts.ts
  test/admin/e2e/list-view/e2e.spec.ts
Labels: created-by: Payload team

#11050 fix(richtext-lexical): fixed the positioning of the button to add columns or rows in tables
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableHoverActionsPlugin/index.tsx
Labels: created-by: Payload team

#11045 docs(plugin-multi-tenant): update tenantsArrayField config options
  docs/plugins/multi-tenant.mdx
Labels: created-by: Contributor

#11048 chore(richtext-lexical): fix unchecked indexed access (part 4)
  packages/richtext-lexical/src/features/link/client/plugins/autoLink/index.tsx
  packages/richtext-lexical/src/features/toolbars/fixed/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.tsx
  packages/richtext-lexical/src/features/upload/server/feature.server.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/LexicalMenu.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/useMenuTriggerMatch.ts
  packages/richtext-lexical/src/lexical/plugins/handles/utils/getNodeCloseToPoint.ts
Labels: created-by: Payload team

#11054 feat(richtext-lexical): expose client config to client features
  packages/richtext-lexical/src/features/typesClient.ts
  packages/richtext-lexical/src/field/index.tsx
  packages/richtext-lexical/src/lexical/config/client/loader.ts
  packages/richtext-lexical/src/utilities/createClientFeature.ts
Labels: created-by: Payload team

#11056 fix: error when passing functions to array or block fields labels property
  packages/payload/src/fields/config/client.ts
  test/_community/payload-types.ts
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Array/index.ts
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Blocks/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#11057 fix: unhelpful "cannot overwrite model once compiled" errors swallowing actual error
  packages/payload/src/index.ts
  packages/payload/src/utilities/routeError.ts
Labels: created-by: Payload team

#11063 docs: typo in jobs queue workflows
  docs/jobs-queue/workflows.mdx
Labels: created-by: Contributor

#11065 chore: ensure jest respects PAYLOAD_DATABASE env variable
  test/helpers/startMemoryDB.ts
  test/jest.setup.js
Labels: created-by: Payload team

#11074 fix(richtext-lexical): toggling between internal and custom links does not update fields
  packages/richtext-lexical/src/features/link/server/baseFields.ts
  templates/website/src/fields/defaultLexical.ts
  templates/with-vercel-website/src/fields/defaultLexical.ts
Labels: created-by: Payload team

#11078 docs: fix typo in `BlockquoteFeature` name
  docs/rich-text/overview.mdx
Labels: created-by: Payload team

#11079 docs: adds `usePayloadAPI` hook to React Hooks documentation
  docs/admin/hooks.mdx
Labels: created-by: Payload team

#11075 chore(richtext-lexical): add test converage for internal links
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#11083 fix(next): allows relative live preview urls
  docs/live-preview/overview.mdx
  packages/next/src/views/LivePreview/index.client.tsx
  templates/website/src/utilities/generatePreviewPath.ts
  templates/with-vercel-website/src/utilities/generatePreviewPath.ts
  test/live-preview/next-env.d.ts
  test/live-preview/payload-types.ts
  test/live-preview/utilities/formatLivePreviewURL.ts
Labels: created-by: Payload team

#11022 fix(richtext-lexical): improve keyboard navigation on DecoratorNodes
  packages/richtext-lexical/src/lexical/plugins/DecoratorPlugin/index.tsx
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#11087 fix(db-mongodb): ensures same level operators are respected
  packages/db-mongodb/src/queries/parseParams.ts
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  test/database/int.spec.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#11092 feat: adds new jobs.shouldAutoRun property
  docs/jobs-queue/queues.mdx
  packages/payload-cloud/src/plugin.ts
  packages/payload/src/index.ts
  packages/payload/src/queues/config/types/index.ts
Labels: created-by: Payload team

#11096 fix(db-postgres): incorrect pagination results when querying hasMany relationships multiple times
  packages/db-sqlite/src/countDistinct.ts
  packages/drizzle/src/postgres/countDistinct.ts
  packages/drizzle/src/queries/addJoinTable.ts
  packages/drizzle/src/queries/buildQuery.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  test/relationships/int.spec.ts
Labels: created-by: Payload team

#11097 fix(ui): incorrectly incrementing version counts if maxPerDoc is set to 0
  packages/ui/src/providers/DocumentInfo/index.tsx
  test/versions/collections/Drafts.ts
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#11090 feat(ui): add timezone support to scheduled publish
  packages/ui/src/elements/PublishButton/ScheduleDrawer/buildUpcomingColumns.tsx
  packages/ui/src/elements/PublishButton/ScheduleDrawer/index.tsx
  packages/ui/src/elements/PublishButton/ScheduleDrawer/types.ts
  packages/ui/src/utilities/formatDate.ts
  packages/ui/src/utilities/schedulePublishHandler.ts
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#10904 docs: adds options table to payload-wide upload options
  docs/upload/overview.mdx
Labels: created-by: Contributor

#11110 docs: update custom endpoints docs, `handler` does not accept array of functions anymore
  docs/rest-api/overview.mdx
Labels: created-by: Payload team

#11080 fix(ui): relationship filter renders stale values when changing fields
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/elements/ViewDescription/index.scss
  packages/ui/src/elements/ViewDescription/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/DefaultFilter/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Select/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Select/types.ts
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/types.ts
  packages/ui/src/elements/WhereBuilder/field-types.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/elements/WhereBuilder/reduceFields.tsx
  packages/ui/src/elements/WhereBuilder/types.ts
  packages/ui/src/elements/WhereBuilder/validateWhereQuery.ts
  test/admin/collections/Posts.ts
  test/admin/config.ts
  test/admin/e2e/list-view/e2e.spec.ts
  test/admin/payload-types.ts
  test/fields-relationship/e2e.spec.ts
  test/fields/collections/Checkbox/e2e.spec.ts
  test/fields/collections/Email/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/helpers/e2e/addListFilter.ts
Labels: created-by: Payload team

#11112 templates: bump engines pnpm version to support 10
  templates/website/package.json
  templates/with-vercel-website/package.json
Labels: created-by: Payload team

#11113 fix(payload-cloud): handle socket closures
  packages/payload-cloud/src/plugin.ts
  packages/payload-cloud/src/staticHandler.ts
  packages/payload-cloud/src/types.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11089 fix(richtext-lexical): unindent button in toolbar is never active
  packages/richtext-lexical/src/features/indent/client/index.tsx
Labels: created-by: Payload team

#11115 templates: bump for v3.23.0
  templates/website/src/endpoints/seed/index.ts
  templates/with-postgres/src/migrations/20250211_180301_initial.json
  templates/with-postgres/src/migrations/20250211_180301_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-postgres/src/payload-types.ts
  templates/with-vercel-postgres/src/migrations/20250211_180236_initial.json
  templates/with-vercel-postgres/src/migrations/20250211_180236_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/payload-types.ts
  templates/with-vercel-website/src/migrations/20250211_180251_initial.json
  templates/with-vercel-website/src/migrations/20250211_180251_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
  templates/with-vercel-website/src/payload-types.ts
Labels: area: templates, created-by: Payload team

#10982 chore(richtext-lexical): improve types of UploadData
  packages/payload/src/uploads/types.ts
  packages/richtext-lexical/src/exports/react/components/RichText/converter/converters/upload.tsx
  packages/richtext-lexical/src/features/upload/server/nodes/UploadNode.tsx
Labels: created-by: Payload team

#11122 fix(richtext-lexical): reliably install exact lexical version by removing it from peerDeps
  eslint.config.js
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/dependencyChecker.spec.ts
Labels: created-by: Payload team

#11117 feat: add siblingFields to field hooks
  docs/hooks/fields.mdx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterChange/promise.ts
  packages/payload/src/fields/hooks/afterChange/traverseFields.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/afterRead/traverseFields.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/hooks/beforeChange/traverseFields.ts
  packages/payload/src/fields/hooks/beforeDuplicate/promise.ts
  packages/payload/src/fields/hooks/beforeDuplicate/traverseFields.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/fields/hooks/beforeValidate/traverseFields.ts
  packages/richtext-lexical/src/features/converters/html/field/index.ts
Labels: created-by: Payload team

#11131 templates: add new readme for quick start on vercel platform
  templates/with-vercel-website/README.md
Labels: created-by: Payload team

#11135 fix(ui): safe call within useEffect teardown
  packages/ui/src/elements/Nav/context.tsx
Labels: created-by: Contributor

#11140 chore: typo in migrate:fresh command
  packages/payload/src/bin/migrate.ts
Labels: created-by: Payload team

#11031 docs: filterAvailableLocales
  docs/configuration/localization.mdx
  test/localization/config.ts
  test/localization/e2e.spec.ts
  test/localization/payload-types.ts
Labels: created-by: Payload team

#11039 chore(plugin-import-export): refactor import-export
  packages/payload/src/collections/config/types.ts
  packages/plugin-import-export/package.json
  packages/plugin-import-export/src/components/CollectionField/index.tsx
  packages/plugin-import-export/src/components/Dots/index.scss
  packages/plugin-import-export/src/components/Dots/index.tsx
  packages/plugin-import-export/src/components/ExportButton/index.tsx
  packages/plugin-import-export/src/components/ExportDrawer/index.tsx
  packages/plugin-import-export/src/components/FieldsToExport/index.scss
  packages/plugin-import-export/src/components/FieldsToExport/index.tsx
  packages/plugin-import-export/src/components/FieldsToExport/reduceFields.tsx
  packages/plugin-import-export/src/components/ImportExportProvider/index.tsx
  packages/plugin-import-export/src/components/Preview/index.scss
  packages/plugin-import-export/src/components/Preview/index.tsx
  packages/plugin-import-export/src/components/SortBy/index.scss
  packages/plugin-import-export/src/components/SortBy/index.tsx
  packages/plugin-import-export/src/components/WhereField/index.scss
  packages/plugin-import-export/src/components/WhereField/index.tsx
  packages/plugin-import-export/src/export/createExport.ts
  packages/plugin-import-export/src/export/createExportCollectionTask.ts
  packages/plugin-import-export/src/export/getCreateExportCollectionTask.ts
  packages/plugin-import-export/src/export/getFields.ts
  packages/plugin-import-export/src/export/getSelect.ts
  packages/plugin-import-export/src/export/modifyFields.ts
  packages/plugin-import-export/src/exportFields.ts
  packages/plugin-import-export/src/exports/rsc.ts
  packages/plugin-import-export/src/getExportCollection.ts
  packages/plugin-import-export/src/index.ts
  packages/plugin-import-export/src/types.ts
  packages/ui/src/elements/ListControls/ExportDrawer/exportFields.ts
  packages/ui/src/elements/ListControls/ExportDrawer/index.scss
  packages/ui/src/elements/ListControls/ExportDrawer/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/views/List/index.tsx
  pnpm-lock.yaml
  test/plugin-import-export/config.ts
  test/plugin-import-export/int.spec.ts
  test/plugin-import-export/payload-types.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11151 chore: update codeowners
  .github/CODEOWNERS
Labels: created-by: Payload team

#9275 feat: route transitions
  docs/admin/hooks.mdx
  packages/next/src/elements/DocumentHeader/Tabs/Tab/TabLink.tsx
  packages/next/src/elements/Nav/index.client.tsx
  packages/next/src/elements/Nav/index.tsx
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/next/src/views/ForgotPassword/index.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/next/src/views/Login/LoginForm/index.tsx
  packages/next/src/views/Login/index.tsx
  packages/next/src/views/Logout/LogoutClient.tsx
  packages/next/src/views/NotFound/index.client.tsx
  packages/next/src/views/ResetPassword/index.tsx
  packages/next/src/views/Unauthorized/index.tsx
  packages/next/src/views/Verify/index.client.tsx
  packages/next/src/views/Version/Default/index.tsx
  packages/next/src/views/Version/Restore/index.tsx
  packages/next/src/views/Versions/cells/CreatedAt/index.tsx
  packages/plugin-search/src/Search/ui/LinkToDoc/index.client.tsx
  packages/richtext-lexical/src/cell/rscEntry.tsx
  packages/richtext-slate/src/cell/rscEntry.tsx
  packages/ui/src/elements/AppHeader/index.tsx
  packages/ui/src/elements/Banner/index.tsx
  packages/ui/src/elements/BulkUpload/EditForm/index.tsx
  packages/ui/src/elements/CopyLocaleData/index.tsx
  packages/ui/src/elements/DeleteDocument/index.tsx
  packages/ui/src/elements/DeleteMany/index.tsx
  packages/ui/src/elements/DocumentLocked/index.tsx
  packages/ui/src/elements/DocumentTakeOver/index.tsx
  packages/ui/src/elements/DuplicateDocument/index.tsx
  packages/ui/src/elements/LeaveWithoutSaving/index.tsx
  packages/ui/src/elements/LeaveWithoutSaving/usePreventLeave.tsx
  packages/ui/src/elements/Link/formatUrl.ts
  packages/ui/src/elements/Link/index.tsx
  packages/ui/src/elements/Pill/index.tsx
  packages/ui/src/elements/Popup/PopupButtonList/index.tsx
  packages/ui/src/elements/StayLoggedIn/index.tsx
  packages/ui/src/elements/Table/DefaultCell/index.tsx
  packages/ui/src/elements/UnpublishMany/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/providers/Auth/index.tsx
  packages/ui/src/providers/Root/index.tsx
  packages/ui/src/providers/RouteTransition/ProgressBar/index.scss
  packages/ui/src/providers/RouteTransition/ProgressBar/index.tsx
  packages/ui/src/providers/RouteTransition/index.tsx
  packages/ui/src/utilities/renderTable.tsx
  packages/ui/src/views/Edit/index.tsx
  packages/ui/src/views/List/ListHeader/index.tsx
  packages/ui/src/views/List/index.tsx
  test/_community/payload-types.ts
  test/admin/e2e/general/e2e.spec.ts
  test/admin/payload-types.ts
Labels: created-by: Payload team

#11155 refactor(ui): deprecates Link props
  packages/next/src/elements/Nav/index.tsx
  packages/next/src/views/Dashboard/Default/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/next/src/views/ForgotPassword/index.tsx
  packages/next/src/views/Logout/LogoutClient.tsx
  packages/next/src/views/NotFound/index.client.tsx
  packages/next/src/views/ResetPassword/index.tsx
  packages/next/src/views/Unauthorized/index.tsx
  packages/ui/src/elements/AppHeader/index.tsx
  packages/ui/src/elements/Button/index.tsx
  packages/ui/src/elements/Button/types.ts
  packages/ui/src/elements/Card/index.tsx
  packages/ui/src/elements/Logout/index.tsx
  packages/ui/src/elements/StepNav/index.tsx
  packages/ui/src/views/List/ListHeader/index.tsx
  packages/ui/src/views/List/index.tsx
Labels: created-by: Payload team

#11138 test: add types testing for select and joins
  test/types/config.ts
  test/types/payload-types.ts
  test/types/types.spec.ts
Labels: created-by: Payload team

#11161 chore(deps): bumps @monaco-editor/react to v4.7.0 to suppress react 19 warnings
  packages/payload/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#11157 fix(ui): adds delay to progress bar for fast networks
  packages/ui/src/providers/RouteTransition/ProgressBar/index.tsx
  tsconfig.base.json
Labels: created-by: Payload team

#11167 feat(ui): refines progress bar animation curve
  packages/ui/src/providers/RouteTransition/index.tsx
Labels: created-by: Payload team

#11146 fix(ui): prevent omitting fileSize from non-images
  packages/ui/src/fields/Upload/RelationshipContent/index.tsx
Labels: created-by: Contributor

#11123 fix: json schema
  packages/ui/src/fields/JSON/index.tsx
Labels: created-by: Payload team

#11174 docs: fix invalid link
  docs/production/deployment.mdx
Labels: created-by: Payload team

#11028 fix(db-mongodb): remove duplicative indexing of timestamps
  packages/db-mongodb/src/models/buildCollectionSchema.ts
Labels: db: mongodb, created-by: Contributor

#11170 fix: join field does not show validation error
  packages/ui/src/fields/Join/index.tsx
  test/joins/collections/Categories.ts
  test/joins/e2e.spec.ts
  test/joins/payload-types.ts
Labels: created-by: Payload team

#11184 fix(ui): hide array field "add" button if `admin.readOnly: true` is set
  packages/ui/src/fields/Array/index.tsx
  test/fields/collections/Array/e2e.spec.ts
Labels: created-by: Payload team

#11188 docs: remove file extension from import statement in useLexicalComposerContext
  docs/rich-text/custom-features.mdx
Labels: created-by: Payload team

#11189 fix(plugin-multi-tenant): corrects default value for tenantsArrayTenantFieldName
  examples/multi-tenant/src/collections/Users/index.ts
  packages/plugin-multi-tenant/src/fields/tenantsArrayField/index.ts
Labels: created-by: Payload team

#11147 fix(ui): respect locale in buildTableState
  packages/ui/src/utilities/buildTableState.ts
  test/joins/collections/Posts.ts
  test/joins/config.ts
  test/joins/e2e.spec.ts
  test/joins/payload-types.ts
  test/joins/seed.ts
Labels: created-by: Contributor

#11192 fix(next): document header padding on tablet sized screens
  packages/next/src/elements/DocumentHeader/index.scss
Labels: created-by: Payload team

#11193 feat(richtext-lexical): export INSERT_BLOCK_COMMAND and INSERT_INLINE_BLOCK_COMMAND
  packages/richtext-lexical/src/exports/client/index.ts
Labels: created-by: Payload team

#11198 fix(ui): properly handle singular and plural bulk edit labels
  packages/ui/src/elements/BulkUpload/EditMany/DrawerContent.tsx
  packages/ui/src/elements/DeleteMany/index.tsx
  packages/ui/src/elements/EditMany/DrawerContent.tsx
Labels: created-by: Contributor

#11195 test(db-mongodb): unit test assertion for relationship sanitization inside `blockReferences`
  packages/db-mongodb/src/utilities/sanitizeRelationshipIDs.spec.ts
Labels: created-by: Payload team

#11208 fix(db-postgres): ensure `countDistinct` works correctly and achieve better performance when the query has table joins
  packages/db-sqlite/src/countDistinct.ts
  packages/drizzle/src/postgres/countDistinct.ts
  test/relationships/config.ts
  test/relationships/int.spec.ts
  test/relationships/payload-types.ts
Labels: created-by: Payload team

#11219 fix: ensure leavesFirst option works correctly in traverseFields utility
  packages/payload/src/utilities/traverseFields.ts
  pnpm-lock.yaml
  test/helpers/autoDedupeBlocksPlugin/index.ts
  test/package.json
Labels: created-by: Payload team

#11069 docs: adds onInit to payload config options
  docs/configuration/overview.mdx
Labels: created-by: Contributor

#11220 chore: move dequal to devDependencies
  pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#11228 templates: allow to pass `resource={null}` to `Media` component
  examples/localization/src/components/Media/types.ts
  templates/website/src/components/Media/types.ts
  templates/with-vercel-website/src/components/Media/types.ts
Labels: created-by: Payload team

#11227 fix: `populate` is ignored for nested relationships
  packages/payload/src/collections/dataloader.ts
  packages/payload/src/fields/hooks/afterRead/relationshipPopulationPromise.ts
  test/select/collections/Pages/index.ts
  test/select/int.spec.ts
  test/select/payload-types.ts
Labels: created-by: Payload team

#11231 fix: upload and auth endpoints are mounted for all collections
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/endpoints/index.ts
  packages/payload/src/uploads/endpoints/getFile.ts
  packages/payload/src/uploads/endpoints/getFileFromURL.ts
  packages/payload/src/uploads/endpoints/index.ts
  test/collections-rest/int.spec.ts
Labels: created-by: Payload team

#10898 ci: updates `actions/upload-artifact` to `v4` & explicitly use ubuntu-24.04 instead of latest
  .github/workflows/label-on-change.yml
  .github/workflows/lock-issues.yml
  .github/workflows/main.yml
  .github/workflows/post-release.yml
  .github/workflows/release-canary.yml
  .github/workflows/stale.yml
  .github/workflows/triage.yml
  package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#11223 test: resolves `locked-documents` type errors
  test/locked-documents/e2e.spec.ts
  test/locked-documents/int.spec.ts
Labels: created-by: Payload team

#11237 perf: do not populate globals when calculating permissions, cleanup getEntityPolicies
  packages/payload/src/database/combineQueries.ts
  packages/payload/src/utilities/getEntityPolicies.ts
Labels: created-by: Payload team

#11235 test: resolves `select` type errors
  test/select/int.spec.ts
Labels: created-by: Payload team

#11238 test: regenerate `payload-types.ts` for all test suites
  test/access-control/payload-types.ts
  test/admin-root/payload-types.ts
  test/admin/payload-types.ts
  test/array-update/payload-types.ts
  test/auth-basic/payload-types.ts
  test/auth/payload-types.ts
  test/collections-graphql/payload-types.ts
  test/collections-rest/payload-types.ts
  test/config/payload-types.ts
  test/custom-graphql/payload-types.ts
  test/database/payload-types.ts
  test/dataloader/payload-types.ts
  test/email-nodemailer/payload-types.ts
  test/email-resend/payload-types.ts
  test/email/payload-types.ts
  test/endpoints/payload-types.ts
  test/field-error-states/payload-types.ts
  test/field-perf/payload-types.ts
  test/fields-relationship/payload-types.ts
  test/globals/payload-types.ts
  test/graphql-schema-gen/payload-types.ts
  test/graphql/payload-types.ts
  test/hooks/payload-types.ts
  test/i18n/payload-types.ts
  test/joins/payload-types.ts
  test/lexical-mdx/payload-types.ts
  test/live-preview/payload-types.ts
  test/localization-rtl/payload-types.ts
  test/localization/payload-types.ts
  test/locked-documents/payload-types.ts
  test/login-with-username/payload-types.ts
  test/migrations-cli/payload-types.ts
  test/nested-fields/payload-types.ts
  test/payload-cloud/payload-types.ts
  test/plugin-cloud-storage/payload-types.ts
  test/plugin-form-builder/payload-types.ts
  test/plugin-multi-tenant/payload-types.ts
  test/plugin-nested-docs/payload-types.ts
  test/plugin-redirects/payload-types.ts
  test/plugin-search/payload-types.ts
  test/plugin-sentry/payload-types.ts
  test/plugin-seo/payload-types.ts
  test/plugin-stripe/payload-types.ts
  test/plugins/payload-types.ts
  test/queues/payload-types.ts
  test/sort/payload-types.ts
  test/storage-azure/payload-types.ts
  test/storage-gcs/payload-types.ts
  test/storage-s3/payload-types.ts
  test/storage-uploadthing/payload-types.ts
  test/storage-vercel-blob/payload-types.ts
  test/types/payload-types.ts
  test/versions/payload-types.ts
Labels: created-by: Payload team

#10998 feat: add `page` query parameter for `joins`
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/graphql/src/schema/buildObjectType.ts
  packages/payload/src/database/sanitizeJoinQuery.ts
  packages/payload/src/types/index.ts
  packages/payload/src/utilities/sanitizeJoinParams.ts
  test/joins/int.spec.ts
Labels: created-by: Payload team

#11218 fix(ui): selection status not updating after toggleAll in useSelection hook
  packages/ui/src/providers/Selection/index.tsx
  test/admin/e2e/general/e2e.spec.ts
  test/admin/payload-types.ts
Labels: created-by: Payload team

#11254 fix(plugin-seo): add missing supported languages
  packages/plugin-seo/src/translations/ar.ts
  packages/plugin-seo/src/translations/az.ts
  packages/plugin-seo/src/translations/bg.ts
  packages/plugin-seo/src/translations/ca.ts
  packages/plugin-seo/src/translations/da.ts
  packages/plugin-seo/src/translations/et.ts
  packages/plugin-seo/src/translations/he.ts
  packages/plugin-seo/src/translations/hr.ts
  packages/plugin-seo/src/translations/hu.ts
  packages/plugin-seo/src/translations/index.ts
  packages/plugin-seo/src/translations/ja.ts
  packages/plugin-seo/src/translations/ko.ts
  packages/plugin-seo/src/translations/my.ts
  packages/plugin-seo/src/translations/nl.ts
  packages/plugin-seo/src/translations/pt.ts
  packages/plugin-seo/src/translations/ro.ts
  packages/plugin-seo/src/translations/rs.ts
  packages/plugin-seo/src/translations/rsLatin.ts
  packages/plugin-seo/src/translations/sk.ts
  packages/plugin-seo/src/translations/sl.ts
  packages/plugin-seo/src/translations/th.ts
  packages/plugin-seo/src/translations/zh.ts
  packages/plugin-seo/src/translations/zhTw.ts
Labels: created-by: Contributor

#11236 perf: optimize permissions calculation with lots of blocks
  packages/payload/src/auth/getAccessResults.ts
  packages/payload/src/collections/operations/docAccess.ts
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  packages/payload/src/globals/operations/docAccess.ts
  packages/payload/src/utilities/getEntityPolicies.ts
Labels: created-by: Payload team

#11252 fix(ui): allow selectinputs to reset to their initial values if theres no provided value
  packages/ui/src/fields/Select/Input.tsx
  test/admin/collections/CustomFields/fields/Select/CustomInput.tsx
  test/admin/collections/CustomFields/index.ts
  test/admin/e2e/document-view/e2e.spec.ts
  test/admin/payload-types.ts
Labels: created-by: Payload team

#11258 docs: add missing jsdocs to version config
  packages/payload/src/versions/types.ts
Labels: created-by: Payload team

#11233 fix(ui): issues with prevent leave and autosave when the form is submitted but invalid
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/elements/LeaveWithoutSaving/index.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/initContextState.ts
  packages/ui/src/forms/Form/types.ts
  test/helpers/waitForAutoSaveToRunAndComplete.ts
  test/versions/collections/AutosaveWithValidate.ts
  test/versions/collections/DraftsWithValidate.ts
  test/versions/config.ts
  test/versions/e2e.spec.ts
  test/versions/payload-types.ts
  test/versions/seed.ts
  test/versions/slugs.ts
Labels: created-by: Payload team

#10919 feat: join field across many collections
  .vscode/settings.json
  packages/db-mongodb/src/count.ts
  packages/db-mongodb/src/countGlobalVersions.ts
  packages/db-mongodb/src/countVersions.ts
  packages/db-mongodb/src/deleteMany.ts
  packages/db-mongodb/src/deleteOne.ts
  packages/db-mongodb/src/deleteVersions.ts
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobal.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findOne.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/init.ts
  packages/db-mongodb/src/models/buildCollectionSchema.ts
  packages/db-mongodb/src/models/buildGlobalModel.ts
  packages/db-mongodb/src/queries/buildQuery.ts
  packages/db-mongodb/src/queries/getBuildQueryPlugin.ts
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
  packages/db-mongodb/src/queryDrafts.ts
  packages/db-mongodb/src/types.ts
  packages/db-mongodb/src/updateGlobalVersion.ts
  packages/db-mongodb/src/updateOne.ts
  packages/db-mongodb/src/updateVersion.ts
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/graphql/src/schema/buildObjectType.ts
  packages/payload/src/admin/functions/index.ts
  packages/payload/src/collections/config/client.ts
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/database/getLocalizedPaths.ts
  packages/payload/src/database/sanitizeJoinQuery.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/sanitizeJoinField.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterRead/relationshipPopulationPromise.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  packages/ui/src/elements/RelationshipTable/index.scss
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/elements/TableColumns/buildPolymorphicColumnState.tsx
  packages/ui/src/elements/TableColumns/index.tsx
  packages/ui/src/fields/Join/index.tsx
  packages/ui/src/utilities/buildTableState.ts
  packages/ui/src/utilities/renderTable.tsx
  test/joins/config.ts
  test/joins/e2e.spec.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
  test/joins/seed.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11259 test: blocks field helpers
  test/fields/collections/Blocks/e2e.spec.ts
  test/helpers/e2e/addBlock.ts
  test/helpers/e2e/openBlocksDrawer.ts
  test/helpers/e2e/removeAllBlocks.ts
  test/helpers/e2e/reorderBlocks.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11267 fix(db-mongodb): properly handle document notfound cases for update and delete operations
  packages/db-mongodb/src/deleteOne.ts
  packages/db-mongodb/src/updateGlobal.ts
  packages/db-mongodb/src/updateGlobalVersion.ts
  packages/db-mongodb/src/updateOne.ts
  packages/db-mongodb/src/updateVersion.ts
  packages/payload/src/database/types.ts
Labels: created-by: Payload team

#11270 fix(ui): database errors when running autosave and ensure autosave doesn't run unnecessarily
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/forms/Form/index.tsx
Labels: created-by: Payload team

#11243 feat(translations): add support for lithuanian
  packages/payload/src/exports/i18n/lt.ts
  packages/plugin-seo/src/translations/index.ts
  packages/plugin-seo/src/translations/lt.ts
  packages/translations/src/exports/all.ts
  packages/translations/src/importDateFNSLocale.ts
  packages/translations/src/languages/lt.ts
  packages/translations/src/types.ts
  packages/translations/src/utilities/languages.ts
Labels: created-by: Payload team

#11277 feat: add support for interfaceName on radio and select fields to create reusable top level types
  docs/fields/radio.mdx
  docs/fields/select.mdx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  test/types/config.ts
  test/types/payload-types.ts
  test/types/types.spec.ts
Labels: created-by: Payload team

#11249 docs: fix variable name typo in usePayloadAPI (error → isError)
  docs/admin/react-hooks.mdx
Labels: created-by: Payload team

#11278 refactor(ui): simplifies confirmation modal callback
  packages/next/src/views/Account/ResetPreferences/index.tsx
  packages/next/src/views/Version/Restore/index.tsx
  packages/plugin-search/src/Search/ui/ReindexButton/index.client.tsx
  packages/ui/src/elements/ConfirmationModal/index.tsx
  packages/ui/src/elements/DeleteDocument/index.tsx
  packages/ui/src/elements/DeleteMany/index.tsx
  packages/ui/src/elements/DuplicateDocument/index.tsx
  packages/ui/src/elements/GenerateConfirmation/index.tsx
  packages/ui/src/elements/LeaveWithoutSaving/index.tsx
  packages/ui/src/elements/PublishMany/index.tsx
  packages/ui/src/elements/Status/index.tsx
  packages/ui/src/elements/StayLoggedIn/index.tsx
  packages/ui/src/elements/UnpublishMany/index.tsx
  packages/ui/src/exports/client/index.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11273 fix: db transaction errors caused by checkDocumentLockStatus
  packages/payload/src/utilities/checkDocumentLockStatus.ts
Labels: created-by: Payload team

#11214 feat: add locale selectors to localizer component
  packages/ui/src/elements/Localizer/LocalizerLabel/index.tsx
  packages/ui/src/elements/Localizer/index.tsx
Labels: created-by: Contributor

#11203 fix(ui): timezone issue related to date only fields in Pacific timezones
  docs/fields/date.mdx
  packages/ui/src/fields/DateTime/index.tsx
  test/fields/collections/Date/e2e.spec.ts
Labels: created-by: Payload team

#11279 fix(next): imports toast from @payloadcms/ui
  packages/next/package.json
  packages/next/src/views/API/index.client.tsx
  packages/next/src/views/Version/Restore/index.tsx
  pnpm-lock.yaml
Labels: created-by: Contributor

#11232 fix(ui): disabledLocalStrategy.enableFields missing email/username fields
  packages/ui/src/views/Edit/Auth/index.tsx
  test/auth/config.ts
  test/auth/int.spec.ts
  test/auth/payload-types.ts
  test/auth/shared.ts
Labels: created-by: Payload team

#11282 fix(ui): minor issues with tabs and publish buttons when in RTL
  packages/ui/src/elements/Button/index.scss
  packages/ui/src/fields/Tabs/Tab/index.scss
  templates/website/src/blocks/ArchiveBlock/Component.tsx
  templates/with-vercel-website/src/blocks/ArchiveBlock/Component.tsx
Labels: created-by: Payload team

#11288 fix(richtext-lexical): incorrect UploadData types
  packages/richtext-lexical/src/exports/react/components/RichText/converter/converters/upload.tsx
  packages/richtext-lexical/src/features/upload/server/nodes/UploadNode.tsx
Labels: created-by: Payload team

#11289 docs: fix invalid jsx in banner block
  docs/fields/date.mdx
Labels: created-by: Payload team

#11290 feat(richtext-lexical): support single-quoted jsx property values in mdx converter
  packages/richtext-lexical/src/utilities/jsx/extractPropsFromJSXPropsString.ts
  packages/richtext-lexical/src/utilities/jsx/jsx.spec.ts
  test/lexical-mdx/tests/default.test.ts
Labels: created-by: Payload team

#11291 docs: removes outdated `rateLimit` option
  docs/configuration/overview.mdx
Labels: created-by: Payload team

#11229 fix(next): uses assetPrefix from next config in webpack-hmr URL
  packages/next/src/withPayload.js
  packages/payload/src/index.ts
Labels: created-by: Payload team

#10841 chore(translations): adds missing client keys and removes translated validation errors
  packages/payload/src/fields/validations.ts
  packages/translations/src/clientKeys.ts
Labels: created-by: Payload team

#11300 docs: fix formatting in field hooks table
  docs/hooks/fields.mdx
Labels: created-by: Contributor

#11302 perf(next): avoid unnecessary upsertPreferences call on page load
  packages/next/src/layouts/Root/index.tsx
Labels: created-by: Payload team

#11305 fix(ui): confirmation modal should build off of drawerDepth, instead …
  packages/ui/src/elements/ConfirmationModal/index.tsx
Labels: created-by: Payload team

#11239 feat(ui): adds support for block groups
  docs/fields/blocks.mdx
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/fields/Blocks/BlocksDrawer/index.scss
  packages/ui/src/fields/Blocks/BlocksDrawer/index.tsx
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Blocks/index.ts
  test/fields/payload-types.ts
Labels: created-by: Contributor

#11265 chore: add JSDoc for collection Local API operations properties
  packages/payload/src/collections/operations/local/count.ts
  packages/payload/src/collections/operations/local/countVersions.ts
  packages/payload/src/collections/operations/local/create.ts
  packages/payload/src/collections/operations/local/delete.ts
  packages/payload/src/collections/operations/local/duplicate.ts
  packages/payload/src/collections/operations/local/find.ts
  packages/payload/src/collections/operations/local/findByID.ts
  packages/payload/src/collections/operations/local/findVersionByID.ts
  packages/payload/src/collections/operations/local/findVersions.ts
  packages/payload/src/collections/operations/local/restoreVersion.ts
  packages/payload/src/collections/operations/local/update.ts
Labels: created-by: Payload team

#11295 chore: cut down logging noise when file was not found on the disk
  packages/payload/src/uploads/endpoints/getFile.ts
Labels: created-by: Payload team

#11313 chore: add JSDoc for globals Local API operations
  packages/payload/src/globals/operations/local/countGlobalVersions.ts
  packages/payload/src/globals/operations/local/findOne.ts
  packages/payload/src/globals/operations/local/findVersionByID.ts
  packages/payload/src/globals/operations/local/findVersions.ts
  packages/payload/src/globals/operations/local/restoreVersion.ts
  packages/payload/src/globals/operations/local/update.ts
Labels: created-by: Payload team

#11287 fix: db transaction errors caused by checkDocumentLockStatus
  packages/payload/src/utilities/checkDocumentLockStatus.ts
Labels: created-by: Payload team

#11318 perf(next): reduce getNavPrefs calls from 3 to 1 per page load
  packages/next/src/elements/Nav/getNavPrefs.ts
  packages/next/src/elements/Nav/index.tsx
  packages/next/src/layouts/Root/index.tsx
Labels: created-by: Payload team

#11293 perf(db-mongodb): remove `JSON.parse(JSON.stringify)` copying of results
  packages/db-mongodb/src/create.ts
  packages/db-mongodb/src/createGlobal.ts
  packages/db-mongodb/src/createGlobalVersion.ts
  packages/db-mongodb/src/createVersion.ts
  packages/db-mongodb/src/deleteOne.ts
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobal.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findOne.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/models/buildSchema.ts
  packages/db-mongodb/src/predefinedMigrations/migrateRelationshipsV2_V3.ts
  packages/db-mongodb/src/queryDrafts.ts
  packages/db-mongodb/src/updateGlobal.ts
  packages/db-mongodb/src/updateGlobalVersion.ts
  packages/db-mongodb/src/updateOne.ts
  packages/db-mongodb/src/updateVersion.ts
  packages/db-mongodb/src/utilities/sanitizeInternalFields.ts
  packages/db-mongodb/src/utilities/sanitizeRelationshipIDs.ts
  packages/db-mongodb/src/utilities/transform.spec.ts
  packages/db-mongodb/src/utilities/transform.ts
  test/joins/int.spec.ts
  test/select/int.spec.ts
Labels: created-by: Payload team

#11294 fix: working `bin` configuration for custom scripts
  docs/configuration/overview.mdx
  packages/payload/src/bin/index.ts
  test/config/bin.ts
  test/config/config.ts
  test/config/customScript.ts
  test/config/int.spec.ts
  test/config/testFilePath.ts
Labels: created-by: Payload team

#11324 docs: fix docs/rich-text/overview
  docs/rich-text/overview.mdx
Labels: created-by: Contributor

#11319 perf: add limit: 1 and pagination: false to various payload queries
  packages/payload/src/auth/strategies/jwt.ts
  packages/plugin-multi-tenant/src/utilities/getGlobalViewRedirect.ts
  packages/plugin-search/src/Search/hooks/deleteFromSearch.ts
  packages/plugin-search/src/utilities/syncDocAsSearchIndex.ts
  packages/plugin-stripe/src/webhooks/handleCreatedOrUpdated.ts
  packages/plugin-stripe/src/webhooks/handleDeleted.ts
Labels: created-by: Payload team
