Repository payloadcms/payload, pull requests merged in 2025-04, with the labels that each got.

#11937 fix(translations): improve Swedish translations for query presets
  packages/translations/src/languages/sv.ts
Labels: created-by: Contributor

#11906 fix(ui): nested fields disappear when manipulating rows in form state
  packages/payload/src/admin/forms/Form.ts
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/forms/Form/fieldReducer.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/initContextState.ts
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/Form/types.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  test/eslint.config.js
  test/form-state/e2e.spec.ts
  test/helpers/e2e/assertRequestBody.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11941 fix: typescriptSchema override required to false
  packages/payload/src/utilities/configToJSONSchema.spec.ts
  packages/payload/src/utilities/configToJSONSchema.ts
Labels: created-by: Payload team

#11869 fix(graphql): respect `draft: true` when querying joins
  packages/graphql/src/schema/fieldToSchemaMap.ts
  test/joins/collections/Versions.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
Labels: created-by: Payload team

#11935 feat(drizzle): export buildQuery and parseParams
  packages/drizzle/src/index.ts
  packages/drizzle/src/queries/parseParams.ts
Labels: created-by: Payload team

#11957 update row lastRenderedPath handling
  packages/payload/src/admin/forms/Form.ts
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/forms/fieldSchemasToFormState/types.ts
  test/form-state/collections/Posts/ArrayRowLabel.tsx
  test/form-state/collections/Posts/index.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11892 fix: do not append `doc` input for scheduled publish job if it's enabled only for globals
  packages/payload/src/versions/schedule/job.ts
Labels: created-by: Payload team

#11954 feat(storage-uploadthing): configurable upload router input config
  packages/storage-uploadthing/src/getClientUploadRoute.ts
  packages/storage-uploadthing/src/index.ts
Labels: created-by: Payload team

#11904 fix: `ValidationError` error message when `label` is a function
  packages/drizzle/src/upsertRow/index.ts
  packages/payload/src/errors/ValidationError.ts
  packages/payload/src/fields/hooks/beforeChange/index.ts
Labels: created-by: Payload team

#11910 fix(db-postgres): down migration fails because `migrationTableExists` doesn't check in the current transaction
  packages/drizzle/src/migrateDown.ts
  packages/drizzle/src/migrateRefresh.ts
  packages/drizzle/src/migrateReset.ts
  packages/drizzle/src/utilities/migrationTableExists.ts
  test/database/up-down-migration/int.spec.ts
  test/database/up-down-migration/migrations/20250328_185055.json
  test/database/up-down-migration/migrations/20250328_185055.ts
  test/database/up-down-migration/migrations/index.ts
Labels: created-by: Payload team

#11962 fix(storage-uploadthing): pass `clientUploads.routerInputConfig` to the handler
  packages/storage-uploadthing/src/index.ts
Labels: created-by: Payload team

#11963 docs: fix variable names for lexical markdown conversion
  docs/rich-text/converting-markdown.mdx
Labels: created-by: Payload team

#11929 chore(plugin-form-builder): enable TypeScript strict
  packages/plugin-form-builder/src/collections/FormSubmissions/hooks/sendEmail.ts
  packages/plugin-form-builder/src/collections/FormSubmissions/index.ts
  packages/plugin-form-builder/src/collections/Forms/DynamicFieldSelector.tsx
  packages/plugin-form-builder/src/collections/Forms/index.ts
  packages/plugin-form-builder/src/utilities/replaceDoubleCurlys.ts
  packages/plugin-form-builder/src/utilities/slate/serializeSlate.ts
  packages/plugin-form-builder/tsconfig.json
Labels: created-by: Payload team

#11930 chore(plugin-nested-docs): enable TypeScript strict
  packages/plugin-nested-docs/src/fields/parentFilterOptions.ts
  packages/plugin-nested-docs/src/hooks/resaveChildren.ts
  packages/plugin-nested-docs/src/hooks/resaveSelfAfterCreate.ts
  packages/plugin-nested-docs/src/utilities/formatBreadcrumb.ts
  packages/plugin-nested-docs/src/utilities/getParents.ts
  packages/plugin-nested-docs/tsconfig.json
Labels: created-by: Payload team

#11931 chore(plugin-redirects): enable TypeScript strict
  packages/plugin-redirects/src/index.ts
  packages/plugin-redirects/tsconfig.json
Labels: created-by: Payload team

#10856 chore(richtext-lexical): add DebugJsxConverterFeature
  packages/richtext-lexical/src/exports/client/index.ts
  packages/richtext-lexical/src/features/debug/jsxConverter/client/index.tsx
  packages/richtext-lexical/src/features/debug/jsxConverter/client/plugin/index.tsx
  packages/richtext-lexical/src/features/debug/jsxConverter/server/index.ts
  packages/richtext-lexical/src/index.ts
Labels: created-by: Payload team

#11850 chore(plugin-cloud-storage): enable TypeScript strict
  packages/plugin-cloud-storage/src/admin/fields/getFields.ts
  packages/plugin-cloud-storage/src/fields/getFields.ts
  packages/plugin-cloud-storage/src/hooks/afterDelete.ts
  packages/plugin-cloud-storage/src/hooks/afterRead.ts
  packages/plugin-cloud-storage/src/hooks/beforeChange.ts
  packages/plugin-cloud-storage/src/plugin.ts
  packages/plugin-cloud-storage/src/utilities/initClientUploads.ts
  packages/plugin-cloud-storage/tsconfig.json
Labels: created-by: Payload team

#11959 feat(ui): use drag overlay in orderable table
  packages/ui/src/elements/DraggableSortable/index.tsx
  packages/ui/src/elements/DraggableSortable/types.ts
  packages/ui/src/elements/Table/OrderableRow.tsx
  packages/ui/src/elements/Table/OrderableRowDragPreview.tsx
  packages/ui/src/elements/Table/OrderableTable.tsx
  packages/ui/src/elements/Table/index.scss
Labels: created-by: Contributor

#11961 fix(ui): optimistic rows disappear while form state requests are pending
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
Labels: created-by: Payload team

#11946 perf(ui): significantly optimize form state component rendering, up to 96% smaller and 75% faster
  docs/configuration/collections.mdx
  packages/payload/src/admin/forms/Form.ts
  packages/richtext-lexical/src/features/upload/server/validate.ts
  packages/richtext-lexical/src/index.ts
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/forms/Form/fieldReducer.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/forms/fieldSchemasToFormState/types.ts
  packages/ui/src/providers/ListQuery/types.ts
  packages/ui/src/utilities/buildFormState.ts
  test/database/up-down-migration/migrations/20250328_185055.ts
  test/form-state/collections/Posts/ArrayRowLabel.tsx
  test/form-state/collections/Posts/index.ts
  test/form-state/e2e.spec.ts
  test/form-state/int.spec.ts
  test/helpers/e2e/assertRequestBody.ts
  test/helpers/e2e/assertResponseBody.ts
  test/queues/config.ts
  test/queues/int.spec.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11632 fix(db-postgres): `deleteOne` fails when the `where` query does not resolve to any document
  packages/drizzle/src/deleteOne.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#11996 docs: fix invalid markdown
  docs/production/deployment.mdx
Labels: created-by: Payload team

#11992 templates: set packageManager pnpm version for vercel templates
  templates/website/package.json
  templates/with-postgres/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-website/package.json
  tools/scripts/src/generate-template-variations.ts
Labels: created-by: Payload team

#11997 fix: postgres null value breaks orderable hook
  packages/payload/src/config/orderable/index.ts
Labels: created-by: Payload team

#11993 docs: fix and normalize links
  docs/custom-components/edit-view.mdx
  docs/query-presets/overview.mdx
  docs/rich-text/custom-features.mdx
Labels: created-by: Contributor

#12003 templates: bump for v3.33.0
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/app/(payload)/admin/importMap.js
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250404_194252_initial.json
  templates/with-postgres/src/migrations/20250404_194252_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250404_194215_initial.json
  templates/with-vercel-postgres/src/migrations/20250404_194215_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/app/(payload)/admin/importMap.js
  templates/with-vercel-website/src/migrations/20250404_194237_initial.json
  templates/with-vercel-website/src/migrations/20250404_194237_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: created-by: Payload team

#11988 test: temp skip blocks e2e
  test/fields/collections/Blocks/e2e.spec.ts
Labels: created-by: Payload team

#11948 fix(ui): prefer adminThumbnail even if file is non-image
  packages/ui/src/elements/Table/DefaultCell/fields/File/index.tsx
  packages/ui/src/elements/Thumbnail/index.tsx
  packages/ui/src/fields/Upload/RelationshipContent/index.tsx
Labels: created-by: Contributor

#12025 docs: clarify file upload example with `_payload` & field explanation
  docs/admin/locked-documents.mdx
  docs/upload/overview.mdx
Labels: created-by: Payload team

#12001 fix(ui): upload edits handling for bulk uploads
  packages/ui/src/elements/BulkUpload/AddingFilesView/index.tsx
  packages/ui/src/elements/BulkUpload/EditForm/index.tsx
  packages/ui/src/elements/BulkUpload/EditForm/types.ts
  packages/ui/src/elements/BulkUpload/FormsManager/index.tsx
  packages/ui/src/elements/BulkUpload/FormsManager/reducer.ts
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/providers/UploadEdits/index.tsx
  packages/ui/src/views/Edit/index.tsx
Labels: created-by: Payload team

#12021 chore: add logging templates script and fix engines for pnpm v10
  templates/_template/package.json
  templates/blank/package.json
  templates/plugin/package.json
  templates/website/package.json
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  tools/scripts/src/generate-template-variations.ts
Labels: created-by: Payload team

#11995 fix(db-postgres): long array field table aliases cause error even when `dbName` is used
  packages/drizzle/src/deleteOne.ts
  packages/drizzle/src/find/findMany.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/schema/traverseFields.ts
  packages/drizzle/src/transform/read/index.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/drizzle/src/upsertRow/index.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#11999 fix: querying by polymorphic join field `relationTo` with `overrideAccess: false`
  packages/payload/src/database/queryValidation/validateQueryPaths.ts
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  packages/payload/src/database/sanitizeJoinQuery.ts
  test/joins/config.ts
  test/joins/int.spec.ts
Labels: created-by: Payload team

#11902 docs: adds server function and access control sections to local API docs
  docs/local-api/access-control.mdx
  docs/local-api/server-functions.mdx
Labels: created-by: Payload team

#12037 fix: array minRow validation should not show when non-required with no rows
  packages/ui/src/fields/Array/index.tsx
Labels: created-by: Payload team

#11136 fix(ui): resets value in where builder when operator changes
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/validOperators.ts
  test/admin/e2e/list-view/e2e.spec.ts
Labels: created-by: Payload team

#11994 chore: run `dev:generate-types`
  test/access-control/payload-types.ts
  test/admin-bar/payload-types.ts
  test/admin/payload-types.ts
  test/array-update/payload-types.ts
  test/auth-basic/payload-types.ts
  test/benchmark-blocks/payload-types.ts
  test/collections-graphql/payload-types.ts
  test/collections-rest/payload-types.ts
  test/config/payload-types.ts
  test/custom-graphql/payload-types.ts
  test/dataloader/payload-types.ts
  test/email-nodemailer/payload-types.ts
  test/email-resend/payload-types.ts
  test/email/payload-types.ts
  test/endpoints/payload-types.ts
  test/field-error-states/payload-types.ts
  test/field-perf/payload-types.ts
  test/fields-relationship/payload-types.ts
  test/globals/payload-types.ts
  test/graphql-schema-gen/payload-types.ts
  test/graphql/payload-types.ts
  test/hooks/payload-types.ts
  test/i18n/payload-types.ts
  test/lexical-mdx/payload-types.ts
  test/live-preview/payload-types.ts
  test/localization-rtl/payload-types.ts
  test/localization/payload-types.ts
  test/locked-documents/payload-types.ts
  test/login-with-username/payload-types.ts
  test/migrations-cli/payload-types.ts
  test/nested-fields/payload-types.ts
  test/payload-cloud/payload-types.ts
  test/plugin-cloud-storage/payload-types.ts
  test/plugin-form-builder/payload-types.ts
  test/plugin-import-export/payload-types.ts
  test/plugin-multi-tenant/payload-types.ts
  test/plugin-nested-docs/payload-types.ts
  test/plugin-redirects/payload-types.ts
  test/plugin-search/payload-types.ts
  test/plugin-sentry/payload-types.ts
  test/plugin-seo/payload-types.ts
  test/plugin-stripe/payload-types.ts
  test/plugins/payload-types.ts
  test/select/payload-types.ts
  test/storage-azure/payload-types.ts
  test/storage-gcs/payload-types.ts
  test/storage-s3/payload-types.ts
  test/storage-uploadthing/payload-types.ts
  test/storage-vercel-blob/payload-types.ts
  test/types/payload-types.ts
Labels: created-by: Payload team

#12058 docs: adjust formatting on Local API - Server Functions documentation
  docs/local-api/server-functions.mdx
Labels: created-by: Payload team

#12064 docs: formatting tweaks for local api docs
  docs/local-api/access-control.mdx
  docs/local-api/server-functions.mdx
Labels: created-by: Payload team

#12053 fix(ui): adds multi select inputs for number fields in where builder
  packages/ui/src/elements/WhereBuilder/Condition/Date/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Date/types.ts
  packages/ui/src/elements/WhereBuilder/Condition/DefaultFilter/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Number/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Number/types.ts
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/types.ts
  packages/ui/src/elements/WhereBuilder/Condition/Select/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Select/types.ts
  packages/ui/src/elements/WhereBuilder/Condition/Text/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Text/types.ts
  packages/ui/src/elements/WhereBuilder/Condition/index.tsx
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/elements/WhereBuilder/types.ts
  test/fields/collections/Number/e2e.spec.ts
Labels: created-by: Payload team

#12067 chore(deps): bump next.js to 15.3.0 and related dependencies
  package.json
  packages/admin-bar/package.json
  packages/live-preview-react/package.json
  packages/next/package.json
  packages/next/src/withPayload.js
  packages/plugin-cloud-storage/package.json
  packages/plugin-form-builder/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-seo/package.json
  packages/plugin-stripe/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/translations/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/plugin/package.json
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-website/package.json
  test/package.json
Labels: created-by: Payload team

#12046 perf(richtext-lexical): debounce field `onChange` handler
  packages/richtext-lexical/src/field/Field.tsx
Labels: created-by: Contributor

#12062 fix: image previews getting stuck in list view when paginating
  packages/ui/src/elements/Table/index.tsx
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#12041 fix: cannot define a join field when the target relationship is nested to a second or higher tab
  packages/payload/src/fields/config/sanitizeJoinField.ts
  test/joins/collections/Categories.ts
  test/joins/collections/Posts.ts
  test/joins/payload-types.ts
Labels: created-by: Payload team

#12054 fix(ui): adds multi select inputs for text fields in where builder
  packages/ui/src/elements/WhereBuilder/Condition/DefaultFilter/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Text/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Text/types.ts
  test/fields/collections/Number/e2e.spec.ts
  test/fields/collections/Text/e2e.spec.ts
  test/fields/collections/Text/shared.ts
Labels: created-by: Payload team

#12026 fix(ui): form state race conditions
  packages/payload/src/admin/forms/Form.ts
  packages/ui/src/forms/Form/fieldReducer.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/mergeErrorPaths.ts
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/Form/types.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/utilities/arraysHaveSameStrings.ts
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Blocks/e2e.spec.ts
  test/form-state/collections/Posts/TextField.tsx
  test/form-state/collections/Posts/index.ts
  test/form-state/e2e.spec.ts
  test/form-state/int.spec.ts
  test/form-state/payload-types.ts
  tsconfig.base.json
Labels: created-by: Payload team

#12073 feat: add support for time format config on scheduled publish
  packages/payload/src/index.ts
  packages/payload/src/versions/types.ts
  packages/ui/src/elements/PublishButton/ScheduleDrawer/index.tsx
  packages/ui/src/elements/PublishButton/index.tsx
  test/versions/collections/Drafts.ts
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#12074 fix(ui): ensure `file` field is only serialized at top-level for upload-enabled collections
  packages/ui/src/forms/Form/index.tsx
  test/admin/collections/Posts.ts
  test/admin/e2e/document-view/e2e.spec.ts
  test/admin/payload-types.ts
Labels: created-by: Payload team

#12070 templates: update readme on blank template and blank template variations for Vercel
  templates/blank/README.md
  templates/with-vercel-mongodb/.env.example
  templates/with-vercel-mongodb/README.md
  templates/with-vercel-postgres/.env.example
  templates/with-vercel-postgres/README.md
  tools/scripts/src/generate-template-variations.ts
Labels: created-by: Payload team

#11933 chore(plugin-seo): enable TypeScript strict
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaDescription/index.ts
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/index.ts
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/index.ts
  packages/plugin-seo/src/fields/Overview/OverviewComponent.tsx
  packages/plugin-seo/src/fields/Overview/index.tsx
  packages/plugin-seo/src/fields/Preview/PreviewComponent.tsx
  packages/plugin-seo/src/fields/Preview/index.tsx
  packages/plugin-seo/src/index.tsx
  packages/plugin-seo/tsconfig.json
Labels: created-by: Payload team

#12075 feat: support `where` querying by join fields
  docs/fields/join.mdx
  packages/db-mongodb/src/queries/buildSearchParams.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/payload/src/database/getLocalizedPaths.ts
  test/joins/int.spec.ts
Labels: created-by: Payload team

#12078 fix(ui): issue with schedule publish disappearing on autosave collections
  packages/ui/src/elements/PublishButton/index.tsx
  test/versions/collections/Autosave.ts
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#12092 chore: assign available port to env variable in dev suite
  test/dev.ts
Labels: created-by: Payload team

#11950 feat(ui): use defaultDepth in API view
  packages/next/src/views/API/index.client.tsx
Labels: created-by: Contributor

#11478 feat(db-postgres): dependency inject pg to allow Sentry instrumentation
  packages/db-postgres/src/connect.ts
  packages/db-postgres/src/index.ts
  packages/db-postgres/src/types.ts
Labels: stale

#12107 fix(db-sqlite): text field converts to floating point number
  packages/drizzle/src/transform/write/traverseFields.ts
  test/database/config.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#12042 fix(richtext-lexical): allow to indent children even if their parents are not indentable
  packages/richtext-lexical/src/features/indent/client/index.tsx
Labels: created-by: Contributor

#12109 fix: reordering draft documents causes data loss
  packages/payload/src/config/orderable/index.ts
  test/sort/collections/Drafts/index.ts
  test/sort/int.spec.ts
Labels: created-by: Payload team

#11973 fix(ui): stale paths on custom components within rows
  packages/plugin-import-export/src/components/FieldsToExport/index.tsx
  packages/plugin-import-export/src/components/SortBy/index.tsx
  packages/plugin-import-export/src/components/WhereField/index.tsx
  packages/plugin-multi-tenant/src/components/TenantField/index.client.tsx
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-slate/src/field/RichText.tsx
  packages/ui/src/elements/QueryPresets/fields/ColumnsField/index.tsx
  packages/ui/src/elements/QueryPresets/fields/WhereField/index.tsx
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/fields/Checkbox/index.tsx
  packages/ui/src/fields/Code/index.tsx
  packages/ui/src/fields/DateTime/index.tsx
  packages/ui/src/fields/Email/index.tsx
  packages/ui/src/fields/Hidden/index.tsx
  packages/ui/src/fields/JSON/index.tsx
  packages/ui/src/fields/Join/index.tsx
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/Point/index.tsx
  packages/ui/src/fields/RadioGroup/index.tsx
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Select/index.tsx
  packages/ui/src/fields/Tabs/index.tsx
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/fields/Textarea/index.tsx
  packages/ui/src/fields/Upload/index.tsx
  packages/ui/src/forms/RenderFields/context.ts
  packages/ui/src/forms/RenderFields/index.tsx
  packages/ui/src/forms/useField/index.tsx
  packages/ui/src/forms/useField/types.ts
  test/field-error-states/e2e.spec.ts
  test/fields-relationship/PopulateFieldButton/index.tsx
  test/fields-relationship/collections/UpdatedExternally/index.ts
  test/form-state/collections/Posts/index.ts
  test/form-state/e2e.spec.ts
  test/form-state/payload-types.ts
  tsconfig.base.json
Labels: created-by: Payload team

#12091 fix: ensures cors headers are run against custom endpoints
  packages/payload/src/utilities/handleEndpoints.ts
Labels: created-by: Payload team

#12124 fix: respects boolean query preset constraints
  packages/payload/src/query-presets/access.ts
  packages/payload/src/query-presets/constraints.ts
  packages/payload/src/query-presets/types.ts
  test/query-presets/config.ts
  test/query-presets/int.spec.ts
  test/query-presets/payload-types.ts
  test/query-presets/seed.ts
  tsconfig.base.json
Labels: created-by: Payload team

#12133 chore: adjusts ChevronIcon styling to match other icons
  packages/next/src/views/LivePreview/Toolbar/Controls/index.tsx
  packages/ui/src/elements/BulkUpload/ActionsBar/index.scss
  packages/ui/src/elements/Button/index.scss
  packages/ui/src/elements/Localizer/LocalizerLabel/index.scss
  packages/ui/src/elements/Localizer/LocalizerLabel/index.tsx
  packages/ui/src/elements/PerPage/index.scss
  packages/ui/src/elements/Pill/index.scss
  packages/ui/src/elements/Popup/PopupTrigger/index.scss
  packages/ui/src/elements/ReactSelect/index.scss
  packages/ui/src/elements/SortColumn/index.scss
  packages/ui/src/icons/Chevron/index.scss
  packages/ui/src/icons/Chevron/index.tsx
Labels: created-by: Payload team

#12132 feat: threads operation through field condition function
  docs/fields/overview.mdx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  test/fields/collections/ConditionalLogic/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#11805 feat: queriable / sortable / `useAsTitle` virtual fields linked with a relationship field
  docs/configuration/overview.mdx
  docs/fields/blocks.mdx
  docs/getting-started/installation.mdx
  packages/payload/src/collections/config/useAsTitle.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/collections/operations/utilities/sanitizeSortQuery.ts
  packages/payload/src/database/queryValidation/validateQueryPaths.ts
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/afterRead/virtualFieldPopulationPromise.ts
  packages/plugin-seo/src/translations/es.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#12144 fix(next): missing @payloadcms/next/auth export
  packages/next/package.json
Labels: created-by: Payload team

#12150 feat: adds `showSaveDraftButton` option to show draft button with autosave enabled
  docs/versions/autosave.mdx
  packages/payload/src/versions/types.ts
  packages/ui/src/elements/DocumentControls/index.tsx
  test/versions/collections/AutosaveWithDraftButton.ts
  test/versions/config.ts
  test/versions/e2e.spec.ts
  test/versions/globals/AutosaveWithDraftButton.ts
  test/versions/payload-types.ts
  test/versions/slugs.ts
Labels: created-by: Payload team

#12104 feat: adds `beforeDocumentControls` slot to allow custom component injection next to document controls
  docs/custom-components/edit-view.mdx
  packages/next/src/views/Document/renderDocumentSlots.tsx
  packages/payload/src/admin/types.ts
  packages/payload/src/admin/views/document.ts
  packages/payload/src/bin/generateImportMap/iterateCollections.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/globals/config/types.ts
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/views/Edit/index.tsx
  test/admin/collections/Posts.ts
  test/admin/components/BeforeDocumentControls/CustomDraftButton/index.tsx
  test/admin/components/BeforeDocumentControls/CustomSaveButton/index.tsx
  test/admin/e2e/document-view/e2e.spec.ts
  test/admin/globals/Global.ts
Labels: created-by: Payload team

#12148 fix(plugin-search): delete does not also delete the search doc
  packages/plugin-search/src/Search/hooks/deleteFromSearch.ts
  packages/plugin-search/src/index.ts
  packages/plugin-search/src/types.ts
  test/plugin-search/int.spec.ts
Labels: created-by: Payload team

#12159 perf: optimize virtual fields that reference ID
  packages/payload/src/fields/hooks/afterRead/virtualFieldPopulationPromise.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#12158 fix(db-mongodb): fallback `version` when not selected
  packages/db-mongodb/src/queryDrafts.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#12145 docs: virtual fields linking with relationship fields
  docs/configuration/collections.mdx
  docs/fields/array.mdx
  docs/fields/blocks.mdx
  docs/fields/checkbox.mdx
  docs/fields/code.mdx
  docs/fields/date.mdx
  docs/fields/email.mdx
  docs/fields/json.mdx
  docs/fields/number.mdx
  docs/fields/point.mdx
  docs/fields/radio.mdx
  docs/fields/relationship.mdx
  docs/fields/rich-text.mdx
  docs/fields/select.mdx
  docs/fields/tabs.mdx
  docs/fields/text.mdx
  docs/fields/textarea.mdx
  docs/fields/upload.mdx
  docs/queries/sort.mdx
Labels: created-by: Payload team

#12183 fix(richtext-lexical): reset indent on node transforms
  packages/richtext-lexical/src/features/indent/client/IndentPlugin.tsx
Labels: created-by: Contributor

#12185 fix(db-postgres): sort by distance when the `near` operator is used
  packages/drizzle/src/queries/buildAndOrConditions.ts
  packages/drizzle/src/queries/buildQuery.ts
  packages/drizzle/src/queries/parseParams.ts
  test/collections-rest/int.spec.ts
Labels: created-by: Payload team

#12182 fix(richtext-lexical): allow to indent and outdent if at least one selected node allows it
  packages/richtext-lexical/src/features/indent/client/index.tsx
Labels: created-by: Contributor

#12156 docs: fix query preset config link
  docs/configuration/collections.mdx
  docs/configuration/globals.mdx
  docs/query-presets/overview.mdx
Labels: created-by: Contributor

#12233 fix(examples): incorrect documentation links for Live Preview example
  examples/live-preview/README.md
  examples/live-preview/src/migrations/seed.ts
Labels: created-by: Payload team

#12034 fix: user validation error inside the forgotPassword operation in the cases where user had localised fields
  packages/payload/src/auth/operations/forgotPassword.ts
  payload-types.ts
  test/auth/forgot-password-localized/config.ts
  test/auth/forgot-password-localized/int.spec.ts
  test/auth/forgot-password-localized/payload-types.ts
Labels: created-by: Contributor

#12176 fix(ui): relationship using list drawer correctly updates when hasMany is true
  packages/ui/src/fields/Relationship/index.tsx
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/collections/Relationship/index.ts
Labels: created-by: Contributor

#12224 perf(plugin-nested-docs): remove extra find call
  packages/plugin-nested-docs/src/hooks/resaveChildren.ts
  packages/plugin-nested-docs/src/hooks/resaveSelfAfterCreate.ts
Labels: created-by: Payload team

#12225 perf(plugin-search): reduce query depth in hooks
  packages/plugin-search/src/utilities/generateReindexHandler.ts
  packages/plugin-search/src/utilities/syncDocAsSearchIndex.ts
Labels: created-by: Payload team

#12249 docs: adds warning about handling different environments with migrations
  docs/database/migrations.mdx
Labels: created-by: Payload team

#12251 perf(ui): only select necessary data for relationship options
  packages/ui/src/fields/Relationship/index.tsx
Labels: created-by: Contributor

#12077 fix(richtext-lexical): prevent extra paragraph when inserting blocks or uploadNodes. Add preemptive selection normalization
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
  packages/richtext-lexical/src/features/relationship/client/plugins/index.tsx
  packages/richtext-lexical/src/features/upload/client/plugin/index.tsx
  packages/richtext-lexical/src/lexical/LexicalEditor.tsx
  packages/richtext-lexical/src/lexical/plugins/NormalizeSelection/index.tsx
  test/lexical/baseConfig.ts
  test/lexical/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/lexical/collections/Lexical/e2e/main/e2e.spec.ts
  test/lexical/collections/_LexicalFullyFeatured/e2e.spec.ts
  test/lexical/collections/_LexicalFullyFeatured/index.ts
  test/lexical/collections/_LexicalFullyFeatured/utils.ts
  test/lexical/components/CollectionsExplained.tsx
  test/lexical/payload-types.ts
  test/lexical/slugs.ts
Labels: created-by: Payload team

#12128 fix(richtext-lexical): ensure state is up-to-date on inline-block restore
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  test/lexical/collections/Lexical/e2e/blocks/e2e.spec.ts
Labels: created-by: Contributor

#12258 fix(plugin-import-export): csv export column order
  packages/plugin-import-export/src/export/createExport.ts
  packages/plugin-import-export/src/export/flattenObject.ts
  test/plugin-import-export/int.spec.ts
Labels: created-by: Payload team

#12261 perf(db-postgres): skip pagination overhead if `limit: 0` is passed
  packages/drizzle/src/find/findMany.ts
Labels: created-by: Payload team

#12273 fix(db-postgres): `count` crashes when query contains subqueries and doesn't return any rows
  packages/db-sqlite/src/countDistinct.ts
  packages/drizzle/src/postgres/countDistinct.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#12274 fix: duplicate with orderable
  packages/payload/src/config/orderable/index.ts
  test/sort/int.spec.ts
Labels: created-by: Payload team

#12275 perf: optimize file access promises
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/getFileByPath.ts
Labels: created-by: Payload team
