Repository payloadcms/payload, pull requests merged in 2025-10, with the labels that each got.

#14009 fix(sdk): incorrect `fetch` initialization on cloudflare
  packages/sdk/src/index.ts
Labels: created-by: Payload team

#14014 examples: fix revalidation hook in localization example
  examples/localization/pnpm-lock.yaml
  examples/localization/src/collections/Pages/hooks/revalidatePage.ts
  examples/localization/src/collections/Posts/hooks/revalidatePost.ts
Labels: created-by: Payload team

#14008 fix(db-postgres): joins count with hasMany relationships
  packages/drizzle/src/find/traverseFields.ts
  test/joins/int.spec.ts
Labels: created-by: Payload team

#13986 fix(ui): array fields not respecting width styles in row layouts
  packages/ui/src/fields/Array/index.tsx
  test/fields/collections/Row/e2e.spec.ts
  test/fields/collections/Row/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#14001 fix: `autosave: true` doesn't work on `payload.update` with `where`
  packages/payload/src/collections/operations/update.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#14020 feat: bundle types
  eslint.config.js
  packages/payload/eslint.config.js
  packages/payload/package.json
  packages/payload/rollup.dts.config.mjs
  packages/payload/tsconfig.bundletypes.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#13994 fix(translations): fixes to Swedish translation
  packages/richtext-lexical/src/features/blocks/server/i18n.ts
  packages/translations/src/languages/sv.ts
Labels: created-by: Contributor

#14037 fix(ui): add support back for custom live preview components
  packages/next/src/views/Document/renderDocumentSlots.tsx
  packages/payload/src/admin/types.ts
  packages/ui/src/exports/client/index.ts
  packages/ui/src/views/Edit/index.tsx
  test/live-preview/app/live-preview/(pages)/custom-live-preview/[slug]/RefreshRouteOnSave.tsx
  test/live-preview/app/live-preview/(pages)/custom-live-preview/[slug]/page.tsx
  test/live-preview/collections/CustomLivePreview.ts
  test/live-preview/components/CustomLivePreview.tsx
  test/live-preview/components/styles.css
  test/live-preview/config.ts
  test/live-preview/e2e.spec.ts
  test/live-preview/payload-types.ts
  test/live-preview/seed/index.ts
  test/live-preview/shared.ts
Labels: created-by: Payload team

#14019 fix(ui): saving empty code editor throw error
  packages/ui/src/elements/CodeEditor/CodeEditor.tsx
Labels: created-by: Payload team

#14045 fix(templates): ecommerce wrong links in readme and docs and issue with missing graphql dependency
  docs/ecommerce/frontend.mdx
  pnpm-lock.yaml
  templates/ecommerce/README.md
  templates/ecommerce/package.json
Labels: created-by: Payload team

#14030 fix: update packages list for `pnpm payload info`
  packages/payload/src/versions/payloadPackageList.ts
Labels: created-by: Payload team

#14043 fix(ui): upload dropzone error when collectionConfig is undefined
  packages/ui/src/fields/Upload/RelationshipContent/index.tsx
Labels: created-by: Payload team

#14048 fix(next): force inactive live preview after passing conditions
  packages/next/src/views/Document/index.tsx
  packages/ui/src/providers/LivePreview/index.tsx
  test/live-preview/collections/ConditionalURL.ts
  test/live-preview/collections/StaticURL.ts
  test/live-preview/config.ts
  test/live-preview/e2e.spec.ts
Labels: created-by: Payload team

#14063 fix(templates): don't use remote bindings in cloudflare when developing locally
  templates/with-cloudflare-d1/next.config.ts
  templates/with-cloudflare-d1/package.json
  templates/with-cloudflare-d1/src/payload.config.ts
  templates/with-cloudflare-d1/wrangler.jsonc
Labels: created-by: Contributor

#14064 fix(templates): added missing CLOUDFLARE_ENV when optimizing database
  templates/with-cloudflare-d1/package.json
Labels: created-by: Contributor

#13711 perf(graphql): select only the requested columns
  packages/drizzle/src/find/traverseFields.ts
  packages/graphql/src/resolvers/collections/find.ts
  packages/graphql/src/resolvers/collections/findByID.ts
  packages/graphql/src/resolvers/collections/findVersionByID.ts
  packages/graphql/src/resolvers/collections/findVersions.ts
  packages/graphql/src/resolvers/globals/findOne.ts
  packages/graphql/src/resolvers/globals/findVersionByID.ts
  packages/graphql/src/resolvers/globals/findVersions.ts
  packages/graphql/src/resolvers/types.ts
  packages/graphql/src/schema/fieldToSchemaMap.ts
  packages/graphql/src/schema/initCollections.ts
  packages/graphql/src/schema/initGlobals.ts
  packages/graphql/src/utilities/select.ts
Labels: created-by: Contributor

#13988 fix(storage-r2): upload with the correct contentType
  packages/storage-r2/src/handleUpload.ts
  packages/storage-r2/src/types.ts
Labels: created-by: Contributor

#14069 perf(templates): added cloudflare cache headers for static files
  templates/with-cloudflare-d1/public/_headers
Labels: created-by: Contributor

#14067 fix(templates): ignore wrangler when bundling to fix template styles
  templates/with-cloudflare-d1/src/payload.config.ts
Labels: created-by: Contributor

#14040 feat(db-*): adds support for readReplicas in D1 adapter config
  .github/workflows/pr-title.yml
  docs/database/sqlite.mdx
  packages/db-d1-sqlite/src/connect.ts
  packages/db-d1-sqlite/src/index.ts
  packages/db-d1-sqlite/src/types.ts
  templates/with-cloudflare-d1/.env.example
  templates/with-cloudflare-d1/README.md
Labels: created-by: Payload team

#14055 ci: update pr-title commit scopes
  .github/workflows/pr-title.yml
Labels: created-by: Payload team

#14085 fix: add detection for --experimental-https flag
  packages/payload/src/index.ts
Labels: created-by: Payload team

#14068 fix(ui): phantom fields when duplicating rows with rows
  packages/ui/src/forms/Form/fieldReducer.ts
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Array/index.ts
  test/helpers/e2e/fields/array/duplicateArrayRow.ts
Labels: created-by: Payload team

#14090 feat: support any depth for relationships in `findDistinct`
  packages/db-mongodb/src/findDistinct.ts
  packages/drizzle/src/findDistinct.ts
  packages/payload/src/collections/operations/findDistinct.ts
  packages/payload/src/utilities/getFieldByPath.ts
  test/database/getConfig.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#14094 feat(next): export views, pass all props to custom dashboard view
  packages/next/package.json
  packages/next/src/elements/DocumentHeader/index.tsx
  packages/next/src/elements/Nav/NavHamburger/index.tsx
  packages/next/src/elements/Nav/NavWrapper/index.tsx
  packages/next/src/elements/Nav/index.client.tsx
  packages/next/src/esbuildEntry.ts
  packages/next/src/exports/client.ts
  packages/next/src/exports/rsc.ts
  packages/next/src/exports/views.ts
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/Dashboard/Default/index.tsx
  packages/next/src/views/Dashboard/index.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/Root/getRouteData.ts
Labels: created-by: Payload team

#14091 feat(cpa): add cloudflare template to create-payload-app command
  packages/create-payload-app/src/lib/init-next.ts
  packages/create-payload-app/src/lib/manage-env-files.ts
  packages/create-payload-app/src/lib/replacements.ts
  packages/create-payload-app/src/lib/select-db.ts
  packages/create-payload-app/src/lib/templates.ts
  packages/create-payload-app/src/types.ts
  templates/with-cloudflare-d1/package.json
  templates/with-cloudflare-d1/src/payload.config.ts
Labels: created-by: Payload team

#14018 fix(ui): update memory user when autoLogin enabled
  packages/ui/src/providers/Auth/index.tsx
Labels: created-by: Payload team

#14107 fix(plugin-multi-tenant): not setting cookie properly on login
  packages/plugin-multi-tenant/src/providers/TenantSelectionProvider/index.client.tsx
Labels: created-by: Payload team, plugin: multi-tenant

#14111 feat(richtext-lexical): add collection filtering to UploadFeature, refactor relationship hooks
  docs/rich-text/official-features.mdx
  packages/richtext-lexical/src/features/relationship/client/components/RelationshipComponent.tsx
  packages/richtext-lexical/src/features/relationship/client/drawer/index.tsx
  packages/richtext-lexical/src/features/relationship/client/plugins/index.tsx
  packages/richtext-lexical/src/features/relationship/client/utils/EnabledRelationshipsCondition.tsx
  packages/richtext-lexical/src/features/relationship/client/utils/useEnabledRelationships.tsx
  packages/richtext-lexical/src/features/upload/client/component/index.tsx
  packages/richtext-lexical/src/features/upload/client/drawer/index.tsx
  packages/richtext-lexical/src/features/upload/client/index.tsx
  packages/richtext-lexical/src/features/upload/client/plugin/index.tsx
  packages/richtext-lexical/src/features/upload/server/index.ts
  test/lexical/collections/Lexical/e2e/main/e2e.spec.ts
  test/lexical/collections/LexicalRelationships/index.ts
  test/lexical/payload-types.ts
Labels: created-by: Payload team

#14113 docs: revert sentry docs change
  docs/plugins/sentry.mdx
Labels: created-by: Payload team
