Repository payloadcms/payload, pull requests merged in 2025-06, with the labels that each got.

#11789 fix(next): cannot override tab of default views
  packages/next/src/elements/DocumentHeader/Tabs/index.tsx
  test/admin/collections/CustomViews2.ts
  test/admin/components/CustomTabComponent/client.tsx
  test/admin/components/CustomTabComponent/index.tsx
  test/admin/e2e/document-view/e2e.spec.ts
  test/admin/globals/CustomViews2.ts
  test/admin/shared.ts
Labels: stale

#12653 refactor(ui): improve relationship field option loading reliability using queues
  packages/ui/src/fields/Relationship/Input.tsx
  packages/ui/src/fields/Relationship/types.ts
Labels: created-by: Payload team

#12652 ci: ability to test against turbopack
  .github/workflows/main.yml
Labels: created-by: Payload team

#12650 fix(ui): clear miliseconds in date fields unless theyre explicitly provided in the display format
  packages/ui/src/elements/DatePicker/DatePicker.tsx
  test/fields/collections/Date/e2e.spec.ts
  test/fields/collections/Date/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#12649 feat(ui): adds new editMenuItems custom component
  docs/configuration/collections.mdx
  docs/custom-components/edit-view.mdx
  docs/custom-components/list-view.mdx
  packages/next/src/views/Document/renderDocumentSlots.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/next/src/views/LivePreview/index.tsx
  packages/payload/src/admin/elements/EditMenuItems.ts
  packages/payload/src/admin/types.ts
  packages/payload/src/bin/generateImportMap/iterateCollections.ts
  packages/payload/src/collections/config/types.ts
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/views/Edit/index.tsx
  test/admin/collections/editMenuItems.ts
  test/admin/components/EditMenuItems/index.tsx
  test/admin/config.ts
  test/admin/e2e/document-view/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/slugs.ts
Labels: created-by: Payload team

#12473 fix(ui): correctly thread through the autoComplete attribute from admin config to the text input
  packages/ui/src/elements/EmailAndUsername/index.tsx
  packages/ui/src/fields/Text/Input.tsx
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/fields/Text/types.ts
Labels: created-by: Payload team

#12665 perf(ui): prevent unnecessary client config sanitization
  packages/ui/src/providers/Config/index.tsx
Labels: created-by: Payload team

#12667 ci: skip flaky test on supabase
  test/queues/int.spec.ts
Labels: created-by: Payload team

#12661 fix(db-postgres): `in` query with `null`
  packages/drizzle/src/queries/parseParams.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#11787 fix(db-postgres): ensure deletion of numbers and texts in upsertRow
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/drizzle/src/transform/write/array.ts
  packages/drizzle/src/transform/write/blocks.ts
  packages/drizzle/src/transform/write/index.ts
  packages/drizzle/src/transform/write/traverseFields.ts
  packages/drizzle/src/transform/write/types.ts
  packages/drizzle/src/upsertRow/index.ts
  packages/ui/src/fields/Number/index.tsx
  packages/ui/src/fields/Text/Input.tsx
  test/fields/int.spec.ts
Labels: created-by: Contributor

#12675 fix(ui): fully traverse child nodes in #12419
  packages/ui/src/utilities/extractTextFromReactNode.ts
Labels: created-by: Contributor

#12670 chore: fix various e2e test setup issues
  package.json
  packages/db-mongodb/package.json
  packages/db-mongodb/src/connect.ts
  packages/db-mongodb/src/destroy.ts
  pnpm-lock.yaml
  templates/plugin/package.json
  test/admin/seed.ts
  test/buildConfigWithDefaults.ts
  test/fields-relationship/config.ts
  test/fields-relationship/seed.ts
  test/fields/baseConfig.ts
  test/generateDatabaseAdapter.ts
  test/helpers/isErrorWithCode.ts
  test/helpers/reInitEndpoint.ts
  test/helpers/reInitializeDB.ts
  test/helpers/reset.ts
  test/helpers/seed.ts
  test/helpers/snapshot.ts
  test/helpers/startMemoryDB.ts
  test/helpers/stopMemoryDB.ts
  test/joins/seed.ts
  test/lexical/baseConfig.ts
  test/lexical/collections/Lexical/e2e/main/e2e.spec.ts
  test/locked-documents/seed.ts
  test/package.json
  test/query-presets/seed.ts
  test/queues/config.ts
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#12676 feat(ui): use document drawers for folder edit/create
  packages/ui/src/elements/DocumentDrawer/DrawerHeader/index.scss
  packages/ui/src/elements/DocumentDrawer/DrawerHeader/index.tsx
  packages/ui/src/elements/DrawerActionHeader/index.scss
  packages/ui/src/elements/DrawerActionHeader/index.tsx
  packages/ui/src/elements/FolderView/CurrentFolderActions/index.tsx
  packages/ui/src/elements/FolderView/Drawers/DrawerHeader/index.scss
  packages/ui/src/elements/FolderView/Drawers/DrawerHeader/index.tsx
  packages/ui/src/elements/FolderView/Drawers/EditFolderAction/index.tsx
  packages/ui/src/elements/FolderView/Drawers/MoveToFolder/index.scss
  packages/ui/src/elements/FolderView/Drawers/MoveToFolder/index.tsx
  packages/ui/src/elements/FolderView/Drawers/NewFolder/index.tsx
  packages/ui/src/elements/FolderView/Drawers/RenameFolder/index.tsx
  packages/ui/src/elements/ListHeader/TitleActions/ListCreateNewDocInFolderButton.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/views/CollectionFolder/ListSelection/index.tsx
  packages/ui/src/views/Edit/index.tsx
  test/folders/config.ts
  test/folders/payload-types.ts
Labels: created-by: Payload team

#12677 templates: do not expose users in example custom routes
  examples/astro/payload/src/app/my-route/route.ts
  examples/remix/payload/src/app/my-route/route.ts
  templates/_template/src/app/my-route/route.ts
  templates/blank/src/app/my-route/route.ts
  templates/plugin/dev/app/my-route/route.ts
  templates/with-payload-cloud/src/app/my-route/route.ts
  templates/with-postgres/src/app/my-route/route.ts
  templates/with-vercel-mongodb/src/app/my-route/route.ts
  templates/with-vercel-postgres/src/app/my-route/route.ts
Labels: created-by: Payload team

#12683 fix(ui): remove React text node extraction
  packages/ui/src/elements/WhereBuilder/reduceFields.tsx
  packages/ui/src/utilities/extractTextFromReactNode.ts
Labels: created-by: Payload team

#12681 docs: improve module augmentation docs for request context
  docs/hooks/context.mdx
Labels: created-by: Payload team

#12419 fix(ui): safely extract text from React nodes
  packages/ui/src/elements/WhereBuilder/reduceFields.tsx
  tsconfig.base.json
Labels: created-by: Payload team

#12668 fix(richtext-lexical): prevent runtime error if using TextStateFeature without props
  packages/richtext-lexical/src/features/textState/feature.server.ts
Labels: created-by: Payload team

#12693 fix(richtext-slate): add 'li' string literal to RichTextElement type
  docs/rich-text/slate.mdx
  packages/richtext-slate/src/types.ts
Labels: created-by: Payload team

#12694 docs: removes duplicate headline in building without a db connection
  docs/production/building-without-a-db-connection.mdx
Labels: created-by: Payload team

#12575 docs: enhance drafts documentation with examples for REST, Local, and GraphQL APIs
  docs/versions/drafts.mdx
Labels: created-by: Payload team

#12697 docs: fix formatting in custom components > edit view paragraph
  docs/custom-components/edit-view.mdx
Labels: created-by: Payload team

#12642 fix(translations): correct i18n dynamic variable name for 'movingFromFolder'
  packages/plugin-import-export/src/translations/languages/zh.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/hy.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/lt.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
Labels: created-by: Contributor

#12726 fix(richtext-lexical): text state css not applied if 2+ text state groups present
  packages/richtext-lexical/src/features/textState/textState.ts
  test/lexical/collections/_LexicalFullyFeatured/index.ts
Labels: created-by: Payload team

#12711 fix: adds routeParams to the req on views
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initPage/types.ts
  packages/next/src/views/Root/getRouteData.ts
Labels: created-by: Payload team

#12533 feat(plugin-import-export): add custom toCSV function on fields
  docs/plugins/form-builder.mdx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/traverseFields.ts
  packages/plugin-import-export/src/export/createExport.ts
  packages/plugin-import-export/src/export/flattenObject.ts
  packages/plugin-import-export/src/export/getCustomFieldFunctions.ts
  packages/plugin-import-export/src/export/getSelect.ts
  packages/plugin-import-export/src/exports/types.ts
  packages/plugin-import-export/src/getExportCollection.ts
  packages/plugin-import-export/src/index.ts
  packages/plugin-import-export/src/types.ts
  test/plugin-import-export/collections/Pages.ts
  test/plugin-import-export/int.spec.ts
  test/plugin-import-export/payload-types.ts
  test/plugin-import-export/seed/index.ts
  tsconfig.base.json
Labels: created-by: Payload team

#12611 fix: proper globals max versions clean up
  packages/db-mongodb/src/deleteVersions.ts
  packages/drizzle/src/deleteVersions.ts
  packages/payload/src/database/types.ts
  packages/payload/src/versions/enforceMaxVersions.ts
  test/versions/config.ts
  test/versions/globals/MaxVersions.ts
  test/versions/int.spec.ts
  test/versions/payload-types.ts
Labels: created-by: Payload team

#12730 fix(plugin-import-export): incorrect config extension of jobs
  packages/plugin-import-export/src/export/createExport.ts
  packages/plugin-import-export/src/export/getCreateExportCollectionTask.ts
  packages/plugin-import-export/src/index.ts
Labels: created-by: Payload team

#12734 docs: fix invalid code block language
  docs/plugins/form-builder.mdx
Labels: created-by: Payload team

#12718 docs: add info about localized/built-in validation error messages
  docs/fields/overview.mdx
Labels: created-by: Contributor

#12736 fix(translations): reformats `bnBD` and `bnIN` translation imports to camelCase
  packages/translations/src/exports/all.ts
  packages/translations/src/languages/bnBd.ts
  packages/translations/src/languages/bnIn.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/utilities/languages.ts
Labels: created-by: Payload team

#12740 fix(db-sqlite): sqlite unique validation messages
  packages/drizzle/src/upsertRow/index.ts
  test/database/config.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#12560 fix: ensure redirect route is correctly formatted for "Copy to locale"
  packages/ui/src/elements/CopyLocaleData/index.tsx
Labels: created-by: Contributor

#12743 perf(ui): do not re-animate drawer on re-render, reduce useEffects
  packages/ui/src/elements/Drawer/index.tsx
Labels: created-by: Payload team

#12757 chore: remove invalid colon from workspaces key in package.json
  package.json
Labels: created-by: Contributor

#12755 fix(db-mongodb): bump `mongoose` to `8.15.1`
  packages/db-mongodb/package.json
  pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#11733 fix(storage-s3): return error status 404 when file is not found instead of 500
  packages/storage-s3/src/staticHandler.ts
  test/storage-s3/int.spec.ts
Labels: created-by: Contributor

#12758 fix: orderable has incorrect sort results depending on capitalization
  packages/payload/src/config/orderable/fractional-indexing.js
  test/sort/int.spec.ts
Labels: created-by: Payload team

#11734 fix(storage-azure): return error status 404 when file is not found instead of 500
  packages/storage-azure/src/staticHandler.ts
  pnpm-lock.yaml
  test/package.json
  test/storage-azure/int.spec.ts
  tsconfig.base.json
Labels: created-by: Contributor

#12737 fix: reduce global DOM/Node type conflicts in server-only packages
  package.json
  packages/create-payload-app/package.json
  packages/create-payload-app/src/lib/examples.ts
  packages/create-payload-app/src/utils/getLatestPackageVersion.ts
  packages/create-payload-app/tsconfig.json
  packages/db-mongodb/tsconfig.json
  packages/db-postgres/tsconfig.json
  packages/db-sqlite/tsconfig.json
  packages/db-vercel-postgres/tsconfig.json
  packages/drizzle/tsconfig.json
  packages/email-nodemailer/tsconfig.json
  packages/email-resend/tsconfig.json
  packages/graphql/tsconfig.json
  packages/payload-cloud/tsconfig.json
  packages/payload/src/fields/validations.ts
  packages/payload/src/preferences/requestHandlers/delete.ts
  packages/payload/src/preferences/requestHandlers/findOne.ts
  packages/payload/src/preferences/requestHandlers/update.ts
  packages/payload/src/utilities/addDataAndFileToRequest.ts
  packages/payload/src/utilities/handleEndpoints.ts
  packages/payload/src/utilities/routeError.ts
  packages/payload/tsconfig.json
  packages/plugin-cloud-storage/tsconfig.json
  packages/plugin-redirects/tsconfig.json
  packages/plugin-sentry/tsconfig.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/storage-azure/src/client/AzureClientUploadHandler.ts
  packages/storage-azure/src/generateSignedURL.ts
  packages/storage-azure/tsconfig.json
  packages/storage-gcs/src/client/GcsClientUploadHandler.ts
  packages/storage-gcs/src/generateSignedURL.ts
  packages/storage-gcs/tsconfig.json
  packages/storage-s3/src/client/S3ClientUploadHandler.ts
  packages/storage-s3/src/generateSignedURL.ts
  packages/storage-s3/src/staticHandler.ts
  packages/storage-s3/tsconfig.json
  packages/storage-uploadthing/tsconfig.json
  packages/storage-vercel-blob/src/staticHandler.ts
  packages/storage-vercel-blob/tsconfig.json
  packages/translations/tsconfig.json
  pnpm-lock.yaml
  tsconfig.base.json
Labels: created-by: Payload team

#12774 fix: remove unsupported path property from default document view configs
  docs/custom-components/document-views.mdx
  packages/next/src/elements/DocumentHeader/Tabs/getCustomViews.ts
  packages/next/src/elements/DocumentHeader/Tabs/getViewConfig.ts
  packages/next/src/elements/DocumentHeader/Tabs/index.tsx
  packages/next/src/views/Document/getDocumentView.tsx
  packages/next/src/views/Document/getMetaBySegment.tsx
  packages/next/src/views/Document/index.tsx
  packages/payload/src/collections/config/types.ts
  packages/payload/src/config/types.ts
  test/types/types.spec.ts
Labels: created-by: Payload team

#12622 chore: adds filters
  packages/payload/package.json
  packages/payload/src/uploads/getExternalFile.ts
  packages/payload/src/uploads/safeFetch.ts
  pnpm-lock.yaml
  test/uploads/config.ts
  test/uploads/int.spec.ts
  test/uploads/payload-types.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#12777 refactor(next): simplify document view routing
  packages/next/src/views/Document/getDocumentView.tsx
  packages/next/src/views/Document/getMetaBySegment.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/Unauthorized/index.scss
  packages/next/src/views/Unauthorized/index.tsx
Labels: created-by: Payload team

#12795 refactor(next): simplify document tab rendering logic
  packages/next/src/elements/DocumentHeader/Tabs/Tab/index.tsx
  packages/next/src/elements/DocumentHeader/Tabs/getCustomViews.ts
  packages/next/src/elements/DocumentHeader/Tabs/getViewConfig.ts
  packages/next/src/elements/DocumentHeader/Tabs/index.tsx
  packages/next/src/elements/DocumentHeader/Tabs/tabs/index.tsx
  packages/next/src/elements/DocumentHeader/index.tsx
  test/admin/payload-types.ts
Labels: created-by: Payload team

#12801 docs: fix header custom component example
  docs/custom-components/root-components.mdx
Labels: created-by: Payload team

#12800 fix(db-mongodb): 4x and more level deep relationships querying
  packages/db-mongodb/src/queries/buildSearchParams.ts
  test/relationships/config.ts
  test/relationships/int.spec.ts
  test/relationships/payload-types.ts
Labels: created-by: Payload team

#12799 fix: change payload.jobs.run and bin script to only run jobs from `default` queue by default, adds support for allQueues argument
  docs/jobs-queue/queues.mdx
  packages/payload/src/bin/index.ts
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/restEndpointRun.ts
Labels: created-by: Payload team

#12803 fix(ui): reordering with a join field inside a group
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/fields/Join/index.tsx
  test/sort/collections/OrderableJoin/index.ts
  test/sort/e2e.spec.ts
  test/sort/payload-types.ts
Labels: created-by: Payload team

#11615 feat: admin upload controls
  packages/next/src/views/Document/renderDocumentSlots.tsx
  packages/payload/src/admin/types.ts
  packages/payload/src/bin/generateImportMap/iterateCollections.ts
  packages/payload/src/uploads/types.ts
  packages/ui/src/elements/BulkUpload/EditForm/index.tsx
  packages/ui/src/elements/BulkUpload/index.tsx
  packages/ui/src/elements/Upload/index.scss
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/providers/UploadControls/index.tsx
  packages/ui/src/views/Edit/index.tsx
  test/uploads/collections/AdminUploadControl/components/UploadControl/index.client.tsx
  test/uploads/collections/AdminUploadControl/components/UploadControl/index.tsx
  test/uploads/collections/AdminUploadControl/index.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#12805 fix(plugin-import-export): download button in collection edit view
  packages/plugin-import-export/src/getExportCollection.ts
  packages/plugin-import-export/src/index.ts
Labels: created-by: Payload team

#12808 fix: ensure job autoruns are not triggered if jobs collection not enabled
  packages/payload/src/config/sanitize.ts
  packages/payload/src/config/types.ts
  packages/payload/src/index.ts
  packages/payload/src/queues/config/index.ts
  packages/payload/src/queues/config/types/index.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/restEndpointRun.ts
Labels: created-by: Payload team

#12766 feat(ui): adds constructorOptions to upload config
  docs/upload/overview.mdx
  packages/payload/src/uploads/generateFileData.ts
  packages/payload/src/uploads/types.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#12256 fix(db-postgres): reordering of enum values, bump `drizzle-kit@0.31.0` and `drizzle-orm@0.43.1`
  package.json
  packages/db-postgres/package.json
  packages/db-sqlite/package.json
  packages/db-vercel-postgres/package.json
  packages/drizzle/package.json
  packages/drizzle/src/transform/read/hasManyNumber.ts
  packages/drizzle/src/upsertRow/index.ts
  pnpm-lock.yaml
  test/localization/collections/NestedArray/index.ts
  test/package.json
Labels: created-by: Payload team

#12750 feat(db-postgres): allow to store blocks in a JSON column
  docs/database/postgres.mdx
  docs/database/sqlite.mdx
  packages/db-postgres/src/index.ts
  packages/db-postgres/src/types.ts
  packages/db-sqlite/src/index.ts
  packages/db-sqlite/src/types.ts
  packages/db-vercel-postgres/src/index.ts
  packages/db-vercel-postgres/src/types.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/drizzle/src/queries/parseParams.ts
  packages/drizzle/src/schema/traverseFields.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/drizzle/src/transform/write/traverseFields.ts
  packages/drizzle/src/types.ts
  test/database/int.spec.ts
  test/database/up-down-migration/migrations/20250616_190121.json
  test/database/up-down-migration/migrations/20250616_190121.ts
  test/database/up-down-migration/migrations/index.ts
Labels: created-by: Payload team

#12816 refactor: simplify job type
  packages/db-mongodb/src/updateJobs.ts
  packages/payload/src/database/defaultUpdateJobs.ts
  packages/payload/src/database/types.ts
  packages/payload/src/index.ts
  packages/payload/src/queues/config/index.ts
  packages/payload/src/queues/config/types/taskTypes.ts
  packages/payload/src/queues/config/types/workflowJSONTypes.ts
  packages/payload/src/queues/config/types/workflowTypes.ts
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJSONJob/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/getUpdateJobFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/handleWorkflowError.ts
  packages/payload/src/queues/operations/runJobs/runJob/index.ts
  packages/payload/src/queues/utilities/getJobTaskStatus.ts
  packages/payload/src/queues/utilities/updateJob.ts
  test/queues/config.ts
  test/queues/runners/updatePost.ts
Labels: created-by: Payload team

#12831 templates: bump for v3.43.0
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250609_185613_initial.ts
  templates/with-postgres/src/migrations/20250616_201724_initial.json
  templates/with-postgres/src/migrations/20250616_201724_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250609_185543_initial.ts
  templates/with-vercel-postgres/src/migrations/20250616_201653_initial.json
  templates/with-vercel-postgres/src/migrations/20250616_201653_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/migrations/20250609_185559_initial.ts
  templates/with-vercel-website/src/migrations/20250616_201710_initial.json
  templates/with-vercel-website/src/migrations/20250616_201710_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#12841 fix(ui): support react node content in ConfirmationModal heading and body
  packages/ui/src/elements/ConfirmationModal/index.tsx
Labels: created-by: Payload team

#12845 fix: deleteJobOnComplete deletes failed jobs, simplify job queue error handling
  packages/payload/src/queues/errors/calculateBackoffWaitUntil.ts
  packages/payload/src/queues/errors/getWorkflowRetryBehavior.ts
  packages/payload/src/queues/errors/handleTaskError.ts
  packages/payload/src/queues/errors/handleWorkflowError.ts
  packages/payload/src/queues/errors/index.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJSONJob/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/getUpdateJobFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/handleWorkflowError.ts
  packages/payload/src/queues/operations/runJobs/runJob/importHandlerPath.ts
  packages/payload/src/queues/operations/runJobs/runJob/index.ts
  packages/payload/src/queues/restEndpointRun.ts
  packages/payload/src/queues/utilities/updateJob.ts
  test/helpers/initPayloadInt.ts
  test/queues/config.ts
  test/queues/int.spec.ts
  test/queues/payload-types.ts
  test/queues/seed.ts
  test/queues/workflows/failsImmediately.ts
Labels: created-by: Payload team

#12842 fix(ui): should select document after creation from relationship field
  packages/ui/src/elements/AddNewRelation/index.tsx
  packages/ui/src/elements/Autosave/index.tsx
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#12848 fix(richtext-lexical): consistent html converter inline padding
  packages/richtext-lexical/src/features/blockquote/server/index.ts
  packages/richtext-lexical/src/features/converters/lexicalToHtml/shared/findConverterForNode.ts
  packages/richtext-lexical/src/features/converters/lexicalToHtml_deprecated/converter/converters/paragraph.ts
  packages/richtext-lexical/src/features/heading/server/index.ts
  test/lexical/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#12229 docs(plugin-sentry): add pg query instrumentation guide
  docs/plugins/sentry.mdx
Labels: created-by: Contributor

#12503 chore: fix withPayload helper jsdoc
  packages/next/src/withPayload.js
Labels: stale

#12900 test: fix seeding script with postgres
  test/versions/seed.ts
Labels: created-by: Payload team

#12906 ci: revert bump pnpm to v10 (#12840)
  .github/actions/setup/action.yml
  .github/workflows/main.yml
  .github/workflows/post-release-templates.yml
  .github/workflows/post-release.yml
  .github/workflows/publish-prerelease.yml
  .tool-versions
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/package.json
Labels: created-by: Payload team

#12868 fix: querying virtual fields deeply with `draft: true`
  packages/payload/src/collections/operations/count.ts
  packages/payload/src/collections/operations/countVersions.ts
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/collections/operations/findVersions.ts
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/database/queryValidation/validateSearchParams.ts
  packages/payload/src/database/sanitizeWhereQuery.ts
  test/database/config.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#12919 test: fix `database` integration tests with postgres
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
  test/database/up-down-migration/migrations/20250616_190121.ts
  test/database/up-down-migration/migrations/20250624_142145.json
  test/database/up-down-migration/migrations/20250624_142145.ts
  test/database/up-down-migration/migrations/index.ts
Labels: created-by: Payload team

#12920 fix(next): prevent errors in globals version view
  packages/next/src/views/Version/Default/index.tsx
  packages/next/src/views/Version/SelectComparison/VersionDrawer/index.tsx
  packages/next/src/views/Version/SelectComparison/index.tsx
  packages/next/src/views/Version/SelectComparison/types.ts
  packages/next/src/views/Version/index.tsx
  test/versions/e2e.spec.ts
Labels: created-by: Contributor

#12923 fix(plugin-import-export): omit CSV columns when toCSV returns undefined
  packages/plugin-import-export/src/export/flattenObject.ts
  test/plugin-import-export/int.spec.ts
  test/plugin-import-export/payload-types.ts
Labels: created-by: Payload team

#12922 test: fix `database/int.spec.ts` with postgres custom schema
  test/database/int.spec.ts
Labels: created-by: Payload team

#12938 test: guard against null values in custom toCSV functions
  test/plugin-import-export/collections/Pages.ts
Labels: created-by: Payload team

#12917 fix(ui): align caret on error tooltip for checkbox field
  packages/ui/src/fields/Checkbox/index.tsx
Labels: created-by: Payload team

#12939 chore: set trimTrailingWhitespace and insertFinalNewline in vscode settings
  .vscode/settings.json
Labels: created-by: Payload team

#12861 fix(ui): toggle list selections off on successful bulk action
  packages/ui/src/elements/EditMany/DrawerContent.tsx
  packages/ui/src/elements/EditMany/index.tsx
  packages/ui/src/elements/PublishMany/DrawerContent.tsx
  packages/ui/src/elements/PublishMany/index.tsx
  packages/ui/src/elements/UnpublishMany/DrawerContent.tsx
  packages/ui/src/elements/UnpublishMany/index.tsx
  packages/ui/src/views/List/ListSelection/index.tsx
  test/bulk-edit/e2e.spec.ts
Labels: created-by: Contributor

#12947 fix(next): live preview popup triggers leave without saving modal
  packages/next/src/views/LivePreview/Toolbar/Controls/index.tsx
Labels: created-by: Payload team

#12925 fix(live-preview): foreign postMessage events reset client-side state
  packages/live-preview/src/handleMessage.ts
Labels: created-by: Payload team

#12902 fix(drizzle): skip column if undefined in findMany
  packages/drizzle/src/find/findMany.ts
  test/database/int.spec.ts
Labels: created-by: Contributor

#12954 test: adds test for skipSafeFetch allowList
  test/uploads/config.ts
  test/uploads/int.spec.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#12950 test: bulk edit flaky selectors
  test/bulk-edit/e2e.spec.ts
  test/helpers.ts
  test/localization/e2e.spec.ts
Labels: created-by: Payload team

#12948 feat(plugin-import-export): preview displays CSV and JSON data accurately
  packages/plugin-import-export/src/components/Preview/index.tsx
  packages/plugin-import-export/src/index.ts
Labels: created-by: Payload team

#12930 fix(ui): properly render create new button in polymorphic joins
  packages/ui/src/elements/RelationshipTable/AddNewButton.tsx
  packages/ui/src/elements/RelationshipTable/index.scss
  packages/ui/src/elements/RelationshipTable/index.tsx
Labels: created-by: Contributor

#12921 docs: remove group from list of default field validations
  docs/fields/overview.mdx
Labels: created-by: Contributor

#12699 fix(ui): vertically align table headers to the middle
  packages/ui/src/elements/Table/index.scss
Labels: created-by: Contributor

#12909 feat: collection-level preferences
  packages/next/src/views/List/handleServerFunction.tsx
  packages/next/src/views/List/index.tsx
  packages/payload/src/admin/views/list.ts
  packages/payload/src/index.ts
  packages/payload/src/preferences/types.ts
  packages/payload/src/query-presets/types.ts
  packages/plugin-import-export/src/components/FieldsToExport/index.tsx
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/providers/ListQuery/types.ts
  packages/ui/src/providers/TableColumns/buildColumnState/index.tsx
  packages/ui/src/providers/TableColumns/getInitialColumns.ts
  packages/ui/src/providers/TableColumns/types.ts
  packages/ui/src/utilities/buildTableState.ts
  packages/ui/src/utilities/renderTable.tsx
  tsconfig.base.json
Labels: created-by: Payload team

#12931 feat: add silent flag for running jobs
  packages/payload/src/index.ts
  packages/payload/src/queues/config/types/index.ts
  packages/payload/src/queues/endpoints/run.ts
  packages/payload/src/queues/errors/handleTaskError.ts
  packages/payload/src/queues/errors/handleWorkflowError.ts
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJSONJob/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/index.ts
  test/queues/getConfig.ts
  test/queues/int.spec.ts
Labels: created-by: Payload team

#12968 fix: strict custom view paths
  docs/admin/overview.mdx
  docs/custom-components/custom-views.mdx
  packages/payload/src/admin/views/index.ts
  packages/payload/src/config/types.ts
  test/types/types.spec.ts
Labels: created-by: Payload team

#12973 ci: template errors not being caught due. fix: error due to updated generated-types User type
  .github/workflows/main.yml
  packages/next/src/utilities/initPage/handleAuthRedirect.ts
  packages/next/src/utilities/initReq.ts
  packages/next/src/views/Account/ResetPreferences/index.tsx
  packages/next/src/views/Account/Settings/index.tsx
  packages/next/src/views/Version/fetchVersions.ts
  packages/next/src/views/Versions/types.ts
  packages/payload/src/admin/forms/Field.ts
  packages/payload/src/auth/operations/login.ts
  packages/payload/src/auth/operations/me.ts
  packages/payload/src/auth/sendVerificationEmail.ts
  packages/payload/src/auth/strategies/apiKey.ts
  packages/payload/src/auth/types.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/createLocalReq.ts
  packages/payload/src/versions/schedule/job.ts
  packages/plugin-import-export/src/export/createExport.ts
  packages/plugin-import-export/src/export/getCreateExportCollectionTask.ts
  packages/plugin-multi-tenant/src/providers/TenantSelectionProvider/index.tsx
  packages/plugin-multi-tenant/src/queries/findTenantOptions.ts
  packages/plugin-multi-tenant/src/types.ts
  packages/plugin-multi-tenant/src/utilities/getGlobalViewRedirect.ts
  packages/plugin-multi-tenant/src/utilities/withTenantAccess.ts
  packages/richtext-lexical/src/features/link/server/baseFields.ts
  packages/richtext-slate/src/field/elements/link/LinkDrawer/baseFields.ts
  packages/ui/src/forms/Form/types.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/index.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/iterateFields.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/promise.ts
  packages/ui/src/providers/Auth/index.tsx
  packages/ui/src/providers/Root/index.tsx
  templates/blank/src/payload-types.ts
  templates/plugin/package.json
  templates/website/src/payload-types.ts
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250629_202651_initial.json
  templates/with-postgres/src/migrations/20250629_202651_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-postgres/src/payload-types.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-mongodb/src/payload-types.ts
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250629_202637_initial.json
  templates/with-vercel-postgres/src/migrations/20250629_202637_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/payload-types.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/migrations/20250629_202644_initial.json
  templates/with-vercel-website/src/migrations/20250629_202644_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
  templates/with-vercel-website/src/payload-types.ts
  tools/scripts/src/build-template-with-local-pkgs.ts
  tools/scripts/src/generate-template-variations.ts
Labels: created-by: Payload team

#12980 fix(db-postgres): joins with `hasMany: true` relationships nested to an array
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  test/joins/collections/Categories.ts
  test/joins/collections/Posts.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
  test/relationships/config.ts
  test/relationships/int.spec.ts
  test/relationships/payload-types.ts
Labels: created-by: Payload team
