Repository payloadcms/payload, pull requests merged in 2025-09, with the labels that each got.

#13459 fix(ui): should not show publish specific locale button when no localized fields exist
  packages/ui/src/elements/PublishButton/index.tsx
  packages/ui/src/utilities/traverseForLocalizedFields.ts
  test/localization/collections/NoLocalizedFields/index.ts
  test/localization/e2e.spec.ts
Labels: created-by: Payload team

#11694 fix(db-sqlite): convert Date to ISO 8601 string in queries
  packages/drizzle/src/queries/sanitizeQueryValue.ts
  test/fields/int.spec.ts
Labels: stale

#13529 docs(plugin-form-builder): add RadioField documentation
  docs/plugins/form-builder.mdx
Labels: created-by: Payload team

#13673 fix(ui): await for publish success to update the UI
  packages/ui/src/elements/PublishButton/index.tsx
Labels: created-by: Payload team

#13676 fix(ui): field.admin.condition data attribute missing document ID when document is being edited
  packages/ui/src/utilities/buildFormState.ts
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  test/fields/collections/ConditionalLogic/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#13667 fix: update user session on reset
  packages/payload/src/auth/operations/resetPassword.ts
Labels: created-by: Payload team

#13688 chore: add AGENTS.md
  AGENTS.md
  CLAUDE.md
Labels: created-by: Payload team

#13686 fix(ui): cannot filter by virtual relationship fields in WhereBuilder
  packages/ui/src/utilities/reduceFieldsToOptions.tsx
  test/admin/collections/Virtuals.ts
  test/admin/config.ts
  test/admin/e2e/list-view/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/slugs.ts
Labels: created-by: Payload team

#13717 fix: set X-Payload-HTTP-Method-Override as allowed cross origin header
  packages/payload/src/utilities/headersWithCors.ts
Labels: created-by: Contributor

#13712 fix(ui): consistent searchbar across folders and lists
  packages/ui/src/elements/ListControls/index.scss
  packages/ui/src/elements/ListControls/index.tsx
  packages/ui/src/elements/SearchBar/index.scss
  packages/ui/src/elements/SearchBar/index.tsx
  packages/ui/src/elements/SearchFilter/index.tsx
  packages/ui/src/elements/SearchFilter/types.ts
Labels: created-by: Payload team

#13718 fix: ensure client-side live preview correctly updates for globals
  packages/live-preview/src/mergeData.ts
  packages/payload/src/globals/endpoints/findOne.ts
  packages/payload/src/globals/operations/findOne.ts
  packages/payload/src/globals/operations/local/findOne.ts
Labels: created-by: Payload team

#13682 feat(ui): adds admin.autoRefresh root config property
  docs/admin/overview.mdx
  docs/authentication/overview.mdx
  packages/next/src/auth/refresh.ts
  packages/payload/src/config/types.ts
  packages/ui/src/elements/Status/index.tsx
  packages/ui/src/forms/RowLabel/Context/index.tsx
  packages/ui/src/providers/Auth/index.tsx
  templates/website/src/app/(frontend)/next/preview/route.ts
  templates/with-vercel-website/src/app/(frontend)/next/preview/route.ts
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Collapsible/e2e.spec.ts
Labels: created-by: Payload team

#13684 chore(ui): prevent loading orphaned documents when viewing root collection folders
  packages/next/src/views/CollectionFolders/buildView.tsx
  packages/payload/src/folders/utils/getFolderData.ts
  packages/ui/src/views/BrowseByFolder/index.tsx
  packages/ui/src/views/CollectionFolder/index.tsx
  test/folders/e2e.spec.ts
  test/helpers/folders/createFolder.ts
  test/helpers/folders/expectNoResultsAndCreateFolderButton.ts
Labels: created-by: Payload team

#12955 fix(next): display deleted relations and uploads in version diff views
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Relationship/generateLabelFromValue.ts
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Relationship/index.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Upload/index.tsx
  test/versions/e2e.spec.ts
Labels: created-by: Contributor, prioritized

#13746 fix(storage-vercel-blob): filename is incorrectly stored encoded when addRandomSuffix is true
  packages/storage-vercel-blob/src/handleUpload.ts
Labels: created-by: Payload team

#13721 fix(next): version diff view not handling all field permissions correctly
  packages/next/src/views/Version/RenderFieldsToDiff/buildVersionFields.tsx
  packages/next/src/views/Version/index.tsx
  packages/payload/src/admin/forms/Diff.ts
  packages/payload/src/auth/types.ts
  packages/payload/src/utilities/getFieldPermissions.ts
  packages/ui/src/elements/FieldSelect/reduceFieldOptions.ts
  packages/ui/src/forms/RenderFields/index.tsx
  packages/ui/src/views/Edit/Auth/index.tsx
  test/versions/collections/Diff/index.ts
  test/versions/e2e.spec.ts
  test/versions/payload-types.ts
  test/versions/seed.ts
Labels: created-by: Payload team

#13670 fix(plugin-search): update with db adapter on create
  .vscode/launch.json
  packages/plugin-search/src/utilities/syncDocAsSearchIndex.ts
Labels: created-by: Payload team

#13699 feat: adds disableListColumn and disableListFilter to imageSize admin props
  docs/upload/overview.mdx
  packages/payload/src/uploads/getBaseFields.ts
  packages/payload/src/uploads/types.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#13757 templates: ensure blank template installs matching react-dom version
  pnpm-lock.yaml
  templates/blank/package.json
Labels: created-by: Payload team

#13668 fix(ui): listSearchableFields can resolve to multiple fields with the same name when using tabs
  packages/ui/src/elements/ListControls/getTextFieldsToBeSearched.ts
Labels: created-by: Payload team

#11514 fix: presentational-field types incorrectly exposing hooks
  docs/fields/overview.mdx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterChange/promise.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/hooks/beforeDuplicate/promise.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/fields/setDefaultBeforeDuplicate.ts
  packages/plugin-cloud-storage/src/fields/getFields.ts
Labels: stale

#13771 fix(ui): safely access preferences when loading list view
  packages/next/src/views/Root/index.tsx
Labels: created-by: Payload team

#13768 feat: global beforeOperation hook
  docs/hooks/collections.mdx
  docs/hooks/globals.mdx
  packages/payload/src/collections/config/types.ts
  packages/payload/src/globals/config/sanitize.ts
  packages/payload/src/globals/config/types.ts
  packages/payload/src/globals/operations/countGlobalVersions.ts
  packages/payload/src/globals/operations/findOne.ts
  packages/payload/src/globals/operations/restoreVersion.ts
  packages/payload/src/globals/operations/update.ts
  packages/payload/src/index.ts
  test/hooks/int.spec.ts
Labels: created-by: Payload team

#13564 feat: crons for all bin scripts, new jobs:handle-schedules script, more reliable job system crons
  docs/configuration/overview.mdx
  docs/jobs-queue/queues.mdx
  docs/jobs-queue/schedules.mdx
  packages/payload/src/bin/index.ts
  packages/payload/src/index.ts
Labels: created-by: Payload team

#13810 fix(examples): secure mt example users collection
  examples/multi-tenant/src/collections/Users/index.ts
Labels: created-by: Payload team

#13807 fix: skip validation when trashing documents with empty required fields
  packages/payload/src/collections/operations/utilities/update.ts
  test/trash/collections/Posts/index.ts
  test/trash/int.spec.ts
  test/trash/payload-types.ts
Labels: created-by: Payload team

#13820 fix(ui): undefined operators for virtual field with unsupported field types
  packages/ui/src/forms/Form/createNestedClientFieldPath.ts
  packages/ui/src/utilities/reduceFieldsToOptions.tsx
Labels: created-by: Payload team

#13763 fix: add missed `pagination` property to `findVersions` and `findGlobalVersions` and handle it properly
  packages/payload/src/collections/operations/findVersions.ts
  packages/payload/src/collections/operations/local/findVersions.ts
  packages/payload/src/globals/operations/findVersions.ts
  packages/payload/src/globals/operations/local/findVersions.ts
  test/versions/config.ts
  test/versions/globals/DraftUnlimited.ts
  test/versions/int.spec.ts
  test/versions/payload-types.ts
  test/versions/slugs.ts
Labels: created-by: Payload team

#13831 fix(next): unnamed, unlabeled groups displayed without label in version view
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Group/index.scss
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Group/index.tsx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/utilities/getTranslatedLabel.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/bnBd.ts
  packages/translations/src/languages/bnIn.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/hy.ts
  packages/translations/src/languages/id.ts
  packages/translations/src/languages/is.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/lt.ts
  packages/translations/src/languages/lv.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  test/versions/collections/Diff/index.ts
  test/versions/e2e.spec.ts
  test/versions/payload-types.ts
  test/versions/seed.ts
Labels: created-by: Payload team

#13840 fix: support `hasMany: true` relationships in `findDistinct`
  packages/db-mongodb/src/findDistinct.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/payload/src/collections/operations/findDistinct.ts
  test/database/getConfig.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#13850 fix(graphql): graphql tab schema not handling tabs correctly
  .vscode/launch.json
  packages/graphql/src/schema/buildPoliciesType.ts
  packages/graphql/src/schema/recursivelyBuildNestedPaths.ts
  test/graphql/schema.graphql
Labels: created-by: Payload team

#13864 fix(ui): ensures visible list view thumbnails with enableListViewSelectAPI
  packages/next/src/views/List/appendUploadSelectFields.ts
  packages/next/src/views/List/index.tsx
Labels: created-by: Payload team

#13865 fix(ui): bulk upload with locale param
  packages/ui/src/elements/BulkUpload/FormsManager/index.tsx
Labels: created-by: Payload team

#13862 docs: corrects link for experimental features topic
  docs/configuration/overview.mdx
  docs/experimental/overview.mdx
Labels: created-by: Payload team

#13832 perf(ui): use select API in RelationshipProvider to speed up load times in RelationshipCell
  packages/next/src/views/List/index.tsx
  packages/payload/src/exports/shared.ts
  packages/payload/src/utilities/appendUploadSelectFields.ts
  packages/ui/src/elements/Table/RelationshipProvider/index.tsx
Labels: created-by: Contributor

#13879 feat: support `hasMany` virtual relationship fields
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/hooks/afterRead/virtualFieldPopulationPromise.ts
  packages/payload/src/globals/config/sanitize.ts
  test/database/getConfig.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#13869 fix: admin.hidden not respected for RSCs, render-field server function not respecting field-overrides client-side
  packages/ui/src/forms/RenderFields/RenderField.tsx
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/forms/fieldSchemasToFormState/serverFunctions/renderFieldServerFn.ts
  packages/ui/src/forms/fieldSchemasToFormState/types.ts
  test/lexical/collections/OnDemandForm/e2e.spec.ts
  test/lexical/collections/OnDemandOutsideForm/Component.tsx
  test/lexical/collections/OnDemandOutsideForm/index.ts
  test/lexical/payload-types.ts
Labels: created-by: Payload team

#13897 fix(ui): revert-to-published button showing on new drafts
  packages/ui/src/elements/Status/index.tsx
Labels: created-by: Payload team

#13875 fix: `findDistinct` with polymorphic relationships
  packages/db-mongodb/src/findDistinct.ts
  packages/drizzle/src/findDistinct.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  test/database/getConfig.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#13801 feat: conditional blocks
  docs/fields/blocks.mdx
  packages/payload/src/admin/forms/Form.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/validations.spec.ts
  packages/payload/src/fields/validations.ts
  packages/payload/src/index.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/bnBd.ts
  packages/translations/src/languages/bnIn.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/hy.ts
  packages/translations/src/languages/id.ts
  packages/translations/src/languages/is.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/lt.ts
  packages/translations/src/languages/lv.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/useField/index.tsx
  packages/ui/src/forms/useField/types.ts
  test/fields/baseConfig.ts
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Blocks/index.ts
Labels: created-by: Payload team

#13902 fix: add missing translation key
  packages/translations/src/languages/ta.ts
Labels: created-by: Payload team

#13917 fix(plugin-import-export): collectionSlug field regression from hidden field changes
  packages/plugin-import-export/src/export/getFields.ts
  test/plugin-import-export/payload-types.ts
Labels: created-by: Payload team

#13868 feat(richtext-lexical): support copy & pasting and drag & dopping files/images into the editor
  .github/workflows/main.yml
  packages/richtext-lexical/src/features/upload/client/component/pending/index.tsx
  packages/richtext-lexical/src/features/upload/client/nodes/UploadNode.tsx
  packages/richtext-lexical/src/features/upload/client/plugin/index.tsx
  packages/richtext-lexical/src/features/upload/server/nodes/UploadNode.tsx
  packages/richtext-lexical/src/features/upload/server/nodes/conversions.ts
  packages/ui/src/elements/BulkUpload/FileSidebar/index.scss
  packages/ui/src/elements/BulkUpload/FileSidebar/index.tsx
  packages/ui/src/elements/BulkUpload/FormsManager/index.tsx
  packages/ui/src/elements/BulkUpload/FormsManager/reducer.ts
  packages/ui/src/elements/BulkUpload/index.tsx
  packages/ui/src/fields/Upload/Input.tsx
  test/lexical/baseConfig.ts
  test/lexical/collections/LexicalHeadingFeature/e2e.spec.ts
  test/lexical/collections/Upload/index.ts
  test/lexical/collections/_LexicalFullyFeatured/db/e2e.spec.ts
  test/lexical/collections/_LexicalFullyFeatured/e2e.spec.ts
  test/lexical/collections/utils.ts
  test/lexical/components/Image.tsx
  test/lexical/payload-types.ts
  test/lexical/seed.ts
  test/lexical/slugs.ts
  test/runE2E.ts
Labels: created-by: Payload team

#11283 fix(ui): array field state to return empty array instead of 0
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  test/fields/collections/Array/GetDataByPathTest.tsx
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Array/index.ts
  test/fields/payload-types.ts
  test/form-state/int.spec.ts
Labels: created-by: Payload team

#13922 fix(ui): corrects url for publish specific url
  packages/ui/src/elements/PublishButton/index.tsx
Labels: created-by: Payload team

#13878 fix: server component readonly state issues with document locking
  packages/next/src/views/Document/getIsLocked.ts
  packages/ui/src/elements/DocumentLocked/index.tsx
  packages/ui/src/elements/DocumentTakeOver/index.tsx
  packages/ui/src/utilities/handleTakeOver.tsx
  packages/ui/src/views/Edit/index.tsx
  test/locked-documents/collections/Posts/fields/CustomTextFieldServer.tsx
  test/locked-documents/collections/ServerComponents/index.ts
  test/locked-documents/config.ts
  test/locked-documents/e2e.spec.ts
  test/locked-documents/payload-types.ts
Labels: created-by: Payload team

#13773 feat: adds admin.formatDocURL function to control list view linking
  docs/configuration/collections.mdx
  packages/next/src/views/List/index.tsx
  packages/payload/src/admin/elements/Cell.ts
  packages/payload/src/collections/config/client.ts
  packages/payload/src/collections/config/types.ts
  packages/ui/src/elements/Table/DefaultCell/index.tsx
  packages/ui/src/providers/TableColumns/buildColumnState/index.tsx
  packages/ui/src/providers/TableColumns/buildColumnState/renderCell.tsx
  packages/ui/src/utilities/renderTable.tsx
  test/admin/collections/FormatDocURL/index.ts
  test/admin/config.ts
  test/admin/e2e/list-view/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/slugs.ts
Labels: created-by: Payload team

#13895 perf(graphql): use depth 0 in auth/apiKey for graphQL requests
  packages/payload/src/auth/strategies/apiKey.ts
Labels: created-by: Contributor

#13923 fix(plugin-multi-tenant): improve Norwegian translation for "tenant"
  packages/plugin-multi-tenant/src/translations/languages/nb.ts
Labels: created-by: Contributor

#13913 fix(next): clear bfcache on forward/back
  packages/ui/src/providers/RouteCache/index.tsx
  test/admin/e2e/general/e2e.spec.ts
Labels: created-by: Payload team

#13928 revert: "feat: adds new experimental.localizeStatus option (#13207)"
  docs/configuration/localization.mdx
  docs/configuration/overview.mdx
  docs/experimental/overview.mdx
  packages/db-mongodb/src/createGlobalVersion.ts
  packages/db-mongodb/src/createVersion.ts
  packages/db-mongodb/src/queryDrafts.ts
  packages/drizzle/src/createGlobalVersion.ts
  packages/drizzle/src/createVersion.ts
  packages/drizzle/src/queryDrafts.ts
  packages/next/src/views/Versions/cells/AutosaveCell/index.tsx
  packages/payload/src/collections/operations/create.ts
  packages/payload/src/collections/operations/utilities/update.ts
  packages/payload/src/config/client.ts
  packages/payload/src/config/defaults.ts
  packages/payload/src/config/types.ts
  packages/payload/src/database/types.ts
  packages/payload/src/globals/operations/update.ts
  packages/payload/src/versions/baseFields.ts
  packages/payload/src/versions/buildCollectionFields.ts
  packages/payload/src/versions/buildGlobalFields.ts
  packages/payload/src/versions/drafts/replaceWithDraftIfAvailable.ts
  packages/payload/src/versions/saveVersion.ts
  packages/payload/src/versions/types.ts
  packages/ui/src/elements/Status/index.tsx
  test/localization/config.ts
  test/localization/e2e.spec.ts
  test/versions/e2e.spec.ts
Labels: created-by: Payload team

#13946 fix(ui): move collection description below title in document view
  packages/next/src/elements/DocumentHeader/index.scss
  packages/next/src/elements/DocumentHeader/index.tsx
  packages/next/src/views/Document/index.tsx
  packages/ui/src/elements/DocumentDrawer/DrawerHeader/index.scss
  packages/ui/src/elements/DocumentDrawer/DrawerHeader/index.tsx
  packages/ui/src/elements/DocumentFields/index.tsx
  packages/ui/src/elements/IDLabel/index.scss
  packages/ui/src/views/Edit/index.tsx
  packages/ui/src/views/List/index.scss
  test/admin/components/Banner/index.tsx
  test/admin/components/ViewDescription/index.scss
  test/admin/components/ViewDescription/index.tsx
  test/admin/e2e/document-view/e2e.spec.ts
Labels: created-by: Payload team

#13949 fix(next): static live preview url corrupt after save
  packages/ui/src/views/Edit/index.tsx
  test/live-preview/collections/StaticURL.ts
  test/live-preview/config.ts
  test/live-preview/e2e.spec.ts
  test/live-preview/payload-types.ts
Labels: created-by: Payload team

#13959 ci: add cron to activity notifications [skip ci]
  .github/workflows/activity-notifications.yml
Labels: created-by: Payload team

#13962 fix(richtext-lexical): editor re-mounting on save due to json key order not being preserved in postgres
  packages/richtext-lexical/src/field/Field.tsx
  test/lexical/collections/_LexicalFullyFeatured/db/e2e.spec.ts
Labels: created-by: Payload team

#9463 feat: add Payload SDK package
  .github/workflows/pr-title.yml
  docs/rest-api/overview.mdx
  package.json
  packages/sdk/.prettierignore
  packages/sdk/.swcrc
  packages/sdk/eslint.config.js
  packages/sdk/license.md
  packages/sdk/package.json
  packages/sdk/src/auth/forgotPassword.ts
  packages/sdk/src/auth/login.ts
  packages/sdk/src/auth/me.ts
  packages/sdk/src/auth/refreshToken.ts
  packages/sdk/src/auth/resetPassword.ts
  packages/sdk/src/auth/verifyEmail.ts
  packages/sdk/src/collections/count.ts
  packages/sdk/src/collections/create.ts
  packages/sdk/src/collections/delete.ts
  packages/sdk/src/collections/find.ts
  packages/sdk/src/collections/findByID.ts
  packages/sdk/src/collections/findVersionByID.ts
  packages/sdk/src/collections/findVersions.ts
  packages/sdk/src/collections/restoreVersion.ts
  packages/sdk/src/collections/update.ts
  packages/sdk/src/globals/findOne.ts
  packages/sdk/src/globals/findVersionByID.ts
  packages/sdk/src/globals/findVersions.ts
  packages/sdk/src/globals/restoreVersion.ts
  packages/sdk/src/globals/update.ts
  packages/sdk/src/index.ts
  packages/sdk/src/types.ts
  packages/sdk/src/utilities/buildSearchParams.ts
  packages/sdk/src/utilities/resolveFileFromOptions.ts
  packages/sdk/tsconfig.json
  pnpm-lock.yaml
  test/helpers/getSDK.ts
  test/helpers/initPayloadInt.ts
  test/package.json
  test/sdk/.gitignore
  test/sdk/collections/Posts.ts
  test/sdk/collections/Users.ts
  test/sdk/config.ts
  test/sdk/eslint.config.js
  test/sdk/image.jpg
  test/sdk/int.spec.ts
  test/sdk/payload-types.ts
  test/sdk/shared.ts
  test/sdk/tsconfig.eslint.json
  test/sdk/tsconfig.json
  test/setupProd.ts
  tsconfig.json
Labels: created-by: Payload team

#13971 chore: update templates and docs links
  packages/create-payload-app/src/lib/templates.ts
  templates/ecommerce/src/endpoints/seed/index.ts
  templates/with-cloudflare-d1/README.md
Labels: created-by: Payload team
