Repository payloadcms/payload, pull requests merged in 2025-01, with the labels that each got.

#10291 docs: explicit `payload` usage from `req` to avoid `import payload` confusion
  docs/hooks/context.mdx
Labels: created-by: Payload team

#10083 fix(ui): disable save button until the upload file is uploaded / ready
  packages/ui/src/elements/PublishButton/index.tsx
  packages/ui/src/elements/SaveButton/index.tsx
  packages/ui/src/elements/SaveDraftButton/index.tsx
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/DocumentInfo/types.ts
  test/fields/collections/Upload/e2e.spec.ts
Labels: created-by: Payload team

#10303 chore(examples): fix JSX rendering of internal links
  templates/website/src/components/RichText/index.tsx
Labels: created-by: Payload team

#10128 fix(richtext-lexical): allow any priority of FOCUS_COMMAND
  packages/richtext-lexical/src/features/indent/client/index.tsx
  packages/richtext-lexical/src/features/indent/client/plugins/index.tsx
  packages/richtext-lexical/src/lexical/LexicalEditor.tsx
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#10307 fix(next): returns proper verb tenses from update and delete routes
  packages/next/src/routes/rest/collections/delete.ts
  packages/next/src/routes/rest/collections/update.ts
Labels: created-by: Payload team

#10275 fix: safely executes form state conditions, validations, and default values
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/promise.ts
  packages/ui/src/forms/fieldSchemasToFormState/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  packages/ui/src/providers/ServerFunctions/index.tsx
  test/_community/payload-types.ts
  test/joins/payload-types.ts
  tsconfig.base.json
Labels: created-by: Payload team

#10310 templates: fix media block generating an error if referenced media is missing
  templates/website/src/blocks/MediaBlock/Component.tsx
  templates/with-vercel-website/src/blocks/MediaBlock/Component.tsx
Labels: created-by: Payload team

#10313 fix: 'oldValue' must be a string error when viewing version diffs in postgres
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Relationship/index.tsx
Labels: created-by: Payload team

#10305 fix(ui): unable to find user field schemas when updating password
  packages/next/src/views/CreateFirstUser/index.client.tsx
  packages/ui/src/utilities/buildClientFieldSchemaMap/index.ts
  packages/ui/src/utilities/buildFieldSchemaMap/index.ts
  packages/ui/src/views/Edit/Auth/index.tsx
  packages/ui/src/views/Edit/Auth/types.ts
  packages/ui/src/views/Edit/index.tsx
Labels: created-by: Payload team

#10317 fix: ensure scheduled publish restriction
  packages/payload/src/config/sanitize.ts
  packages/payload/src/versions/schedule/job.ts
  packages/payload/src/versions/schedule/types.ts
  packages/ui/src/utilities/schedulePublishHandler.ts
  test/versions/collections/Drafts.ts
  test/versions/int.spec.ts
  test/versions/payload-types.ts
Labels: created-by: Payload team

#10324 templates: bump for v3.14.0
  templates/blank/Dockerfile
  templates/with-postgres/src/migrations/20250103_134356_initial.json
  templates/with-postgres/src/migrations/20250103_134356_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20250103_134332_initial.json
  templates/with-vercel-postgres/src/migrations/20250103_134332_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/Dockerfile
  templates/with-vercel-website/src/components/RichText/index.tsx
  templates/with-vercel-website/src/migrations/20250103_134345_initial.json
  templates/with-vercel-website/src/migrations/20250103_134345_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#10312 fix(cpa): ensures .env & .env.example file modifications occur before git initialization
  packages/create-payload-app/src/lib/create-project.ts
  packages/create-payload-app/src/main.ts
  templates/_template/.env.example
  templates/blank/.env.example
  templates/website/.env.example
  templates/with-payload-cloud/.env.example
Labels: created-by: Payload team

#10330 fix: adds path to server field component prop types
  packages/payload/src/admin/fields/Array.ts
  packages/payload/src/admin/fields/Blocks.ts
  packages/payload/src/admin/fields/Checkbox.ts
  packages/payload/src/admin/fields/Code.ts
  packages/payload/src/admin/fields/Date.ts
  packages/payload/src/admin/fields/Email.ts
  packages/payload/src/admin/fields/Group.ts
  packages/payload/src/admin/fields/JSON.ts
  packages/payload/src/admin/fields/Join.ts
  packages/payload/src/admin/fields/Number.ts
  packages/payload/src/admin/fields/Point.ts
  packages/payload/src/admin/fields/Radio.ts
  packages/payload/src/admin/fields/Relationship.ts
  packages/payload/src/admin/fields/RichText.ts
  packages/payload/src/admin/fields/Select.ts
  packages/payload/src/admin/fields/Text.ts
  packages/payload/src/admin/fields/Textarea.ts
  packages/payload/src/admin/fields/UI.ts
  packages/payload/src/admin/fields/Upload.ts
Labels: created-by: Payload team

#10318 fix(richtext-lexical): open inline block drawer on mount
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
Labels: created-by: Payload team

#10304 feat(next): adds support for resetting preferences
  packages/next/src/views/Account/ResetPreferences/ConfirmResetModal/index.scss
  packages/next/src/views/Account/ResetPreferences/ConfirmResetModal/index.tsx
  packages/next/src/views/Account/ResetPreferences/index.tsx
  packages/next/src/views/Account/Settings/index.tsx
  packages/next/src/views/Account/index.tsx
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  test/admin/e2e/general/e2e.spec.ts
Labels: created-by: Contributor

#10331 chore(templates): removes all instances of React.forwardRef
  templates/website/src/components/ui/button.tsx
  templates/website/src/components/ui/card.tsx
  templates/website/src/components/ui/checkbox.tsx
  templates/website/src/components/ui/input.tsx
  templates/website/src/components/ui/label.tsx
  templates/website/src/components/ui/pagination.tsx
  templates/website/src/components/ui/select.tsx
  templates/website/src/components/ui/textarea.tsx
  templates/with-vercel-website/src/components/ui/button.tsx
  templates/with-vercel-website/src/components/ui/card.tsx
  templates/with-vercel-website/src/components/ui/checkbox.tsx
  templates/with-vercel-website/src/components/ui/input.tsx
  templates/with-vercel-website/src/components/ui/label.tsx
  templates/with-vercel-website/src/components/ui/pagination.tsx
  templates/with-vercel-website/src/components/ui/select.tsx
  templates/with-vercel-website/src/components/ui/textarea.tsx
Labels: created-by: Payload team

#10334 chore(examples): removes all instances of React.forwardRef
  examples/auth/src/app/(app)/_components/Gutter/index.tsx
  examples/draft-preview/src/components/Gutter/index.tsx
  examples/form-builder/src/components/Gutter/index.tsx
  examples/live-preview/src/app/(app)/_components/Gutter/index.tsx
  examples/localization/src/components/ui/button.tsx
  examples/localization/src/components/ui/card.tsx
  examples/localization/src/components/ui/checkbox.tsx
  examples/localization/src/components/ui/input.tsx
  examples/localization/src/components/ui/label.tsx
  examples/localization/src/components/ui/pagination.tsx
  examples/localization/src/components/ui/select.tsx
  examples/localization/src/components/ui/textarea.tsx
  examples/tailwind-shadcn-ui/src/components/ui/alert.tsx
  packages/ui/src/elements/Gutter/index.tsx
  test/live-preview/app/live-preview/_components/Gutter/index.tsx
  test/live-preview/prod/app/live-preview/_components/Gutter/index.tsx
Labels: created-by: Payload team

#10327 fix(storage-vercel-blob): return 404 when file is not found
  packages/storage-vercel-blob/src/staticHandler.ts
Labels: created-by: Contributor

#10292 fix: copy to locale with localized arrays and blocks generate new IDs to prevent errors in postgres
  packages/ui/src/utilities/copyDataFromLocale.ts
  test/localization/collections/NestedToArrayAndBlock/index.ts
  test/localization/e2e.spec.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
Labels: created-by: Payload team

#10336 fix: allow to set `maxDepth: 0` for join fields, improve join field JSDoc
  packages/payload/src/fields/config/sanitizeJoinField.ts
  packages/payload/src/fields/config/types.ts
  test/joins/config.ts
  test/joins/int.spec.ts
  test/joins/payload-types.ts
Labels: created-by: Payload team

#10339 fix(ui): ensures list drawer does not change underlying step nav
  packages/ui/src/views/List/index.tsx
  test/admin/collections/Posts.ts
  test/admin/e2e/document-view/e2e.spec.ts
Labels: created-by: Payload team

#10268 fix(ui): properly reflects hook changes in ui
  packages/ui/src/fields/Text/index.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/useField/index.tsx
  packages/ui/src/views/Edit/index.tsx
  test/hooks/collections/BeforeChange/index.ts
  test/hooks/config.ts
  test/hooks/e2e.spec.ts
  test/hooks/payload-types.ts
Labels: created-by: Payload team

#10338 fix(ui): make relationship fields update the collection when it is changed in the drawer dropdown
  packages/richtext-lexical/src/features/relationship/client/drawer/index.tsx
  packages/richtext-slate/src/field/elements/relationship/Button/index.tsx
  packages/ui/src/elements/ListDrawer/DrawerContent.tsx
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#10346 docs: fix links and formatting
  docs/access-control/collections.mdx
  docs/access-control/fields.mdx
  docs/access-control/globals.mdx
  docs/access-control/overview.mdx
  docs/admin/components.mdx
  docs/admin/fields.mdx
  docs/admin/overview.mdx
  docs/admin/views.mdx
  docs/authentication/api-keys.mdx
  docs/authentication/email.mdx
  docs/authentication/token-data.mdx
  docs/configuration/overview.mdx
  docs/database/migrations.mdx
  docs/fields/blocks.mdx
  docs/fields/code.mdx
  docs/fields/date.mdx
  docs/fields/relationship.mdx
  docs/fields/select.mdx
  docs/fields/ui.mdx
  docs/graphql/overview.mdx
  docs/hooks/overview.mdx
  docs/local-api/outside-nextjs.mdx
  docs/local-api/overview.mdx
  docs/plugins/build-your-own.mdx
  docs/upload/storage-adapters.mdx
Labels: created-by: Contributor

#10348 chore(richtext-lexical): improve block not found error message
  packages/richtext-lexical/src/features/blocks/server/validate.ts
Labels: created-by: Payload team

#10366 chore(deps): bumps react-datepicker to v7.6.0 to suppress react 19 warnings
  packages/payload/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#10370 chore(examples): remove outdated testing example
  docs/examples/overview.mdx
  examples/testing/.env.example
  examples/testing/README.md
  examples/testing/jest.config.ts
  examples/testing/nodemon.json
  examples/testing/package.json
  examples/testing/src/payload-types.ts
  examples/testing/src/payload.config.ts
  examples/testing/src/server.ts
  examples/testing/src/tests/credentials.ts
  examples/testing/src/tests/globalSetup.ts
  examples/testing/src/tests/login.spec.ts
  examples/testing/tsconfig.json
  examples/testing/yarn.lock
Labels: created-by: Payload team

#10343 feat(next): pass through query params from document view to find operations
  packages/next/src/views/Account/index.tsx
  packages/next/src/views/CreateFirstUser/index.tsx
  packages/next/src/views/Document/getDocumentData.ts
  packages/next/src/views/Document/index.tsx
Labels: created-by: Payload team

#10372 chore: export RunInlineTaskFunction type
  packages/payload/src/index.ts
Labels: created-by: Payload team

#10380 docs: fix link to live-preview example and remove empty placeholder
  docs/live-preview/overview.mdx
Labels: created-by: Contributor

#10364 templates: prevent plugin template from including nested next folder in git
  templates/plugin/.gitignore
Labels: created-by: Contributor

#10386 chore(templates): unpin payload packages
  templates/_template/package.json
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-postgres/Dockerfile
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250106_144518_initial.json
  templates/with-postgres/src/migrations/20250106_144518_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/Dockerfile
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/Dockerfile
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250106_144508_initial.json
  templates/with-vercel-postgres/src/migrations/20250106_144508_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/components/ui/button.tsx
  templates/with-vercel-website/src/components/ui/card.tsx
  templates/with-vercel-website/src/migrations/20250106_144513_initial.json
  templates/with-vercel-website/src/migrations/20250106_144513_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
  templates/with-vercel-website/src/payload-types.ts
Labels: created-by: Payload team

#10385 docs: fix all other links to live-preview example
  docs/live-preview/client.mdx
  docs/live-preview/server.mdx
  examples/live-preview/README.md
Labels: created-by: Contributor

#10384 fix(db-postgres): handle undefined for `adapter.schemaName` in relationships migration
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/migrateRelationships.ts
Labels: created-by: Payload team

#10390 templates: use `cross-env` in the plugin template to achieve compatibility with Windows
  templates/plugin/package.json
Labels: created-by: Payload team

#10391 feat: warn if deploying to vercel and any upload collection missing storage adapter
  packages/payload/src/index.ts
Labels: created-by: Payload team

#10398 fix(richtext-lexical): modify JSXConvertersFunction type to support block types in strict mode
  packages/richtext-lexical/src/exports/react/components/RichText/index.tsx
Labels: created-by: Payload team

#10400 fix: increase safety of findConfig
  packages/payload/src/config/find.ts
Labels: created-by: Payload team

#10399 fix: extends type `all` to the locale type definition in req
  packages/payload/src/types/index.ts
Labels: created-by: Payload team

#10403 templates: fix nested docs url generation for categories
  templates/website/src/collections/Categories.ts
  templates/website/src/endpoints/seed/index.ts
  templates/website/src/payload-types.ts
  templates/website/src/plugins/index.ts
  templates/with-vercel-website/src/collections/Categories.ts
  templates/with-vercel-website/src/endpoints/seed/index.ts
  templates/with-vercel-website/src/payload-types.ts
  templates/with-vercel-website/src/plugins/index.ts
Labels: created-by: Payload team

#10407 fix(email-resend): add reply_to to the API when sending emails
  packages/email-resend/src/index.ts
Labels: created-by: Payload team

#10412 fix(next): live preview tab did not display custom edit view components
  packages/next/src/views/LivePreview/index.client.tsx
  packages/next/src/views/LivePreview/index.tsx
Labels: created-by: Payload team

#10406 test: fixes flaky localization e2e once and for all
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/elements/PublishButton/index.tsx
  packages/ui/src/elements/SaveButton/index.tsx
  packages/ui/src/elements/SaveDraftButton/index.tsx
  test/localization/e2e.spec.ts
Labels: created-by: Payload team

#10413 fix(richtext-lexical): formatted inline code resulted in incorrect markdown export
  packages/richtext-lexical/src/packages/@lexical/markdown/MarkdownExport.ts
Labels: created-by: Payload team

#10414 docs: minor lexical docs improvements
  docs/fields/rich-text.mdx
  docs/plugins/seo.mdx
  docs/rich-text/overview.mdx
Labels: created-by: Payload team

#10411 fix(ui): drawer component missing closing bracket in style calc
  packages/ui/src/elements/Drawer/index.tsx
Labels: created-by: Payload team

#10373 feat: allow running sub-tasks from tasks
  docs/jobs-queue/tasks.mdx
  packages/payload/src/index.ts
  packages/payload/src/queues/config/jobsCollection.ts
  packages/payload/src/queues/config/types/index.ts
  packages/payload/src/queues/config/types/taskTypes.ts
  packages/payload/src/queues/config/types/workflowTypes.ts
  packages/payload/src/queues/operations/runJobs/runJob/getRunTaskFunction.ts
  test/queues/config.ts
  test/queues/int.spec.ts
  test/queues/payload-types.ts
Labels: created-by: Payload team

#10424 fix(richtext-lexical): fix default arg in normalizeMarkdown
  packages/richtext-lexical/src/utilities/jsx/lexicalMarkdownCopy.ts
Labels: created-by: Payload team

#10429 fix: deprecates admin.disable property
  docs/admin/overview.mdx
  packages/payload/src/config/client.ts
  packages/payload/src/config/defaults.ts
  packages/payload/src/config/types.ts
Labels: created-by: Payload team

#10434 fix: vercel upload adapter warning false positive
  packages/payload/src/index.ts
Labels: created-by: Payload team

#10426 fix(ui): removes edit drawer button from `uploads` collection edit view
  packages/ui/src/elements/FileDetails/FileMeta/index.tsx
  packages/ui/src/elements/FileDetails/StaticFileDetails/index.tsx
Labels: created-by: Payload team

#10405 fix(ui): stale doc status when publishing, reverting and unpublishing
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/elements/PublishButton/index.tsx
  packages/ui/src/elements/Status/index.tsx
Labels: created-by: Payload team

#10421 feat(v2): allows filtering on group field types from list view
  packages/payload/src/admin/components/elements/FieldSelect/index.tsx
  packages/payload/src/admin/components/elements/WhereBuilder/index.tsx
  test/admin/e2e.spec.ts
Labels: created-by: Payload team

#10455 templates: add support for scheduled publish to the website template [no lint]
  scripts/generate-template-variations.ts
  templates/website/.env.example
  templates/website/README.md
  templates/website/src/collections/Pages/index.ts
  templates/website/src/collections/Posts/index.ts
  templates/website/src/payload-types.ts
  templates/website/src/payload.config.ts
  templates/with-vercel-website/.env.example
  templates/with-vercel-website/README.md
  templates/with-vercel-website/src/collections/Pages/index.ts
  templates/with-vercel-website/src/collections/Posts/index.ts
  templates/with-vercel-website/src/payload-types.ts
  templates/with-vercel-website/src/payload.config.ts
  templates/with-vercel-website/vercel.json
Labels: created-by: Payload team

#10401 feat: autoRun jobs
  docs/jobs-queue/queues.mdx
  packages/payload/src/index.ts
  packages/payload/src/queues/config/types/index.ts
Labels: created-by: Payload team

#10457 templates: adjusted the cron job schedule so its compatible with hobby tiers as well
  templates/with-vercel-website/vercel.json
Labels: created-by: Payload team

#10458 chore(templates): generate new migrations for vercel
  templates/with-vercel-website/src/migrations/20250108_203010_initial.json
  templates/with-vercel-website/src/migrations/20250108_203010_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: created-by: Payload team

#10430 feat: export the default JWTAuthentication strategy
  packages/payload/src/auth/executeAuthStrategies.ts
  packages/payload/src/auth/extractJWT.ts
  packages/payload/src/auth/strategies/jwt.ts
  packages/payload/src/auth/types.ts
  packages/payload/src/index.ts
Labels: created-by: Payload team

#10461 fix: schedule publish allowed before saving draft
  packages/ui/src/elements/PublishButton/index.tsx
Labels: created-by: Payload team

#10465 fix: properly validates preferences json
  packages/payload/src/preferences/preferencesCollection.ts
Labels: created-by: Payload team

#10451 fix(next): properly instantiates locale context
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/utilities/getPreference.ts
  packages/next/src/utilities/getRequestLocale.ts
  packages/next/src/utilities/getRequestLocales.ts
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/views/Root/index.tsx
  packages/payload/src/preferences/requestHandlers/update.ts
  packages/ui/src/providers/Locale/index.tsx
  packages/ui/src/providers/Root/index.tsx
  test/fields/collections/Text/e2e.spec.ts
  test/helpers/e2e/upsertPrefs.ts
  test/localization/e2e.spec.ts
  tsconfig.base.json
Labels: created-by: Payload team

#10467 fix(payload-cloud): infinite recursion on init
  packages/payload-cloud/src/plugin.ts
Labels: created-by: Payload team

#10474 feat: exports ListPreferences from payload
  packages/next/src/views/List/handleServerFunction.tsx
  packages/next/src/views/List/index.tsx
  packages/payload/src/index.ts
  packages/payload/src/preferences/types.ts
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/elements/TableColumns/getInitialColumns.ts
  packages/ui/src/elements/TableColumns/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/providers/ListQuery/index.tsx
  packages/ui/src/utilities/buildTableState.ts
  packages/ui/src/utilities/renderTable.tsx
  packages/ui/src/views/List/index.tsx
  packages/ui/src/views/List/types.ts
Labels: created-by: Payload team

#10480 fix(richtext-lexical): inline Block drawers opened when document mounts
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/blocks/client/plugin/index.tsx
  packages/richtext-lexical/src/lexical/config/client/EditorConfigProvider.tsx
Labels: created-by: Payload team

#10483 fix: do not autorun jobs during next build process
  packages/payload/src/exports/shared.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/isNextBuild.ts
Labels: created-by: Payload team

#10487 fix: collection access endpoint optional ID and use 404 for not found response
  packages/payload/src/collections/endpoints/docAccess.ts
  packages/payload/src/collections/endpoints/index.ts
  packages/payload/src/utilities/getRequestEntity.ts
  packages/payload/src/utilities/handleEndpoints.ts
Labels: created-by: Payload team

#10486 fix(richtext-lexical): allow external state mutation of block node from outside the form
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/richtext-lexical/src/features/blocks/client/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/features/blocks/client/nodes/InlineBlocksNode.tsx
  packages/richtext-lexical/src/features/blocks/server/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/features/blocks/server/nodes/InlineBlocksNode.tsx
  test/fields/collections/Lexical/ModifyInlineBlockFeature/feature.client.ts
  test/fields/collections/Lexical/ModifyInlineBlockFeature/feature.server.ts
  test/fields/collections/Lexical/ModifyInlineBlockFeature/plugin.tsx
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Lexical/index.ts
Labels: created-by: Payload team

#10497 fix(richtext-lexical): properly handle error if blocks or inline blocks are not found
  packages/richtext-lexical/src/features/blocks/client/component/index.scss
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.scss
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
Labels: created-by: Payload team

#10498 fix(richtext-lexical): respect defaultValue config of link feature url and linkType fields
  packages/richtext-lexical/src/features/link/client/index.tsx
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/types.ts
  packages/richtext-lexical/src/features/link/client/plugins/link/index.tsx
  packages/richtext-lexical/src/features/link/nodes/LinkNode.ts
  packages/richtext-lexical/src/features/link/server/index.ts
Labels: created-by: Payload team

#10479 chore: adds tests for `forceRenderAllFields` admin prop
  packages/payload/src/admin/components/forms/RenderFields/index.tsx
  packages/payload/src/admin/components/forms/field-types/Array/ArrayRow.tsx
  packages/payload/src/admin/components/forms/field-types/Array/index.tsx
  packages/payload/src/admin/components/forms/field-types/Array/types.ts
  packages/payload/src/admin/components/forms/field-types/Blocks/index.tsx
  packages/payload/src/admin/components/forms/field-types/Blocks/types.ts
  packages/payload/src/admin/components/forms/field-types/Collapsible/index.tsx
  packages/payload/src/admin/components/forms/field-types/Collapsible/types.ts
  packages/payload/src/admin/components/forms/field-types/Group/index.tsx
  packages/payload/src/admin/components/forms/field-types/Group/types.ts
  packages/payload/src/admin/components/forms/field-types/Row/index.tsx
  packages/payload/src/admin/components/forms/field-types/Row/types.ts
  packages/payload/src/admin/components/forms/field-types/Tabs/index.tsx
  packages/payload/src/admin/components/forms/field-types/Tabs/types.ts
  test/admin/collections/CustomIdTab.ts
  test/admin/collections/ForceRender.ts
  test/admin/collections/NoForceRender.ts
  test/admin/config.ts
  test/admin/e2e.spec.ts
  test/admin/globals/ForceRender.ts
  test/admin/globals/NoForceRender.ts
  test/admin/slugs.ts
Labels: created-by: Payload team

#8705 fix(ui): disables form during locale change
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/utilities/getPreferences.ts
  packages/next/src/utilities/getRequestLocale.ts
  packages/next/src/utilities/initPage/index.ts
  packages/ui/src/elements/Localizer/index.tsx
  packages/ui/src/elements/Popup/PopupButtonList/index.tsx
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/Locale/index.tsx
  packages/ui/src/utilities/buildTableState.ts
  packages/ui/src/utilities/fetchPreferences.ts
  packages/ui/src/utilities/upsertPreferences.ts
  test/helpers.ts
  test/localization/e2e.spec.ts
Labels: created-by: Payload team

#10463 chore: update year in licenses
  LICENSE.md
  packages/create-payload-app/LICENSE.md
  packages/db-mongodb/LICENSE.md
  packages/db-postgres/LICENSE.md
  packages/db-sqlite/LICENSE.md
  packages/db-vercel-postgres/license.md
  packages/drizzle/LICENSE.md
  packages/email-nodemailer/LICENSE.md
  packages/email-resend/LICENSE.md
  packages/eslint-config/LICENSE.md
  packages/eslint-plugin/LICENSE.md
  packages/graphql/LICENSE.md
  packages/live-preview-react/LICENSE.md
  packages/live-preview-vue/LICENSE.md
  packages/live-preview/LICENSE.md
  packages/next/LICENSE.md
  packages/payload-cloud/LICENSE.md
  packages/payload/LICENSE.md
  packages/plugin-cloud-storage/LICENSE.md
  packages/plugin-form-builder/LICENSE.md
  packages/plugin-nested-docs/LICENSE.md
  packages/plugin-redirects/LICENSE.md
  packages/plugin-search/LICENSE.md
  packages/plugin-sentry/LICENSE.md
  packages/plugin-seo/LICENSE.md
  packages/plugin-stripe/LICENSE.md
  packages/richtext-lexical/LICENSE.md
  packages/richtext-slate/LICENSE.md
  packages/storage-azure/LICENSE.md
  packages/storage-gcs/LICENSE.md
  packages/storage-s3/LICENSE.md
  packages/storage-uploadthing/LICENSE.md
  packages/storage-vercel-blob/LICENSE.md
  packages/translations/LICENSE.md
  packages/ui/LICENSE.md
Labels: created-by: Payload team

#10499 templates: bump for v3.16.0
  templates/website/pnpm-lock.yaml
  templates/website/src/payload.config.ts
  templates/with-postgres/src/migrations/20250110_192021_initial.json
  templates/with-postgres/src/migrations/20250110_192021_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20250110_191955_initial.json
  templates/with-vercel-postgres/src/migrations/20250110_191955_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/.env.example
  templates/with-vercel-website/src/migrations/20250110_192009_initial.json
  templates/with-vercel-website/src/migrations/20250110_192009_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#10501 feat(richtext-lexical): upgrade lexical from 0.20.0 to 0.21.0. Fixes table selection & scrollable table bugs
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/debug/testRecorder/client/plugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableHoverActionsPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.tsx
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/LinkEditor/index.tsx
  packages/richtext-lexical/src/features/toolbars/inline/client/Toolbar/index.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/index.tsx
  packages/richtext-lexical/src/lexical/theme/EditorTheme.tsx
  pnpm-lock.yaml
Labels: created-by: Payload team

#10410 fix: localized tabs with empty data and an array field inside lead to crash in `afterChange`
  packages/payload/src/fields/hooks/afterChange/promise.ts
  test/localization/collections/Tab/index.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
Labels: created-by: Payload team

#10502 fix(richtext-lexical): lexical editor behind a drawer was incorrectly registered as parent editor of lexical editor within drawer
  packages/richtext-lexical/src/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/lexical/config/client/EditorConfigProvider.tsx
  test/fields/collections/LexicalRelationships/index.ts
Labels: created-by: Payload team

#10449 chore(next): cleans up initPage through initReq overrides and consolidated return types
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initReq.ts
  tsconfig.base.json
Labels: created-by: Payload team

#10523 fix(richtext-lexical): adds support for localized placeholder
  packages/richtext-lexical/src/field/rscEntry.tsx
  packages/richtext-lexical/src/lexical/config/client/sanitize.ts
  packages/richtext-lexical/src/lexical/config/types.ts
  packages/richtext-lexical/src/types.ts
Labels: created-by: Contributor

#10525 ci: fix e2e test suite retries not working
  .github/workflows/main.yml
  package.json
Labels: created-by: Payload team

#10528 refactor: improve error logging during onInit and website template seed
  .github/workflows/main.yml
  examples/localization/src/endpoints/seedHandler.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/routeError.ts
  templates/website/src/app/(frontend)/next/seed/route.ts
Labels: created-by: Payload team

#10531 fix(richtext-lexical): editor placeholder had incorrect padding set for small viewports
  packages/richtext-lexical/src/field/Field.tsx
  packages/richtext-lexical/src/lexical/LexicalEditor.tsx
  packages/richtext-lexical/src/lexical/LexicalProvider.tsx
  packages/richtext-lexical/src/lexical/ui/ContentEditable.scss
Labels: created-by: Payload team

#10532 feat(richtext-lexical): respect imageURL for blocks and inline blocks
  packages/richtext-lexical/src/features/blocks/client/getBlockImageComponent.tsx
  packages/richtext-lexical/src/features/blocks/client/index.tsx
Labels: created-by: Payload team

#10535 fix: rest api with Next.js `basePath` option
  packages/next/src/routes/rest/index.ts
  packages/payload/src/utilities/handleEndpoints.ts
Labels: created-by: Payload team

#9998 feat: consolidates logic in update and updateByID operations
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/collections/operations/updateByID.ts
  packages/payload/src/collections/operations/utilities/update.ts
Labels: created-by: Payload team

#10470 fix(richtext-lexical): combine 2 normalizeMarkdown implementations and fix code block regex
  packages/richtext-lexical/src/features/blocks/client/markdownTransformer.ts
  packages/richtext-lexical/src/features/blocks/server/markdownTransformer.ts
  packages/richtext-lexical/src/features/experimental_table/markdownTransformer.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/MarkdownTransformers.ts
  packages/richtext-lexical/src/packages/@lexical/markdown/index.ts
  packages/richtext-lexical/src/utilities/jsx/lexicalMarkdownCopy.ts
  test/lexical-mdx/int.spec.ts
Labels: created-by: Payload team

#10503 fix(ui): fixed issue with updatedAt timestamps not updating in the UI when drafts are updated
  packages/payload/src/versions/saveVersion.ts
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/views/Edit/index.tsx
  test/versions/config.ts
  test/versions/e2e.spec.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#10319 feat: add ability to disable cache tags for admin thumbnails
  .gitignore
  docs/upload/overview.mdx
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/uploads/types.ts
  packages/ui/src/elements/Thumbnail/index.tsx
  packages/ui/src/elements/Upload/index.tsx
  test/uploads/collections/AdminThumbnailWithSearchQueries/index.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#10533 fix(next): ensures req.locale is populated before running access control
  packages/next/src/utilities/initPage/index.ts
  packages/next/src/utilities/initReq.ts
  test/localization/config.ts
  test/localization/e2e.spec.ts
  test/localization/payload-types.ts
  test/localization/shared.ts
  tsconfig.base.json
Labels: created-by: Payload team

#10541 fix: aligns first render for hydration of dates in list view
  packages/ui/src/utilities/formatDate.ts
Labels: created-by: Payload team

#10415 fix(richtext-lexical): remove alteration of lexical text format constant
  packages/richtext-lexical/src/features/typesClient.ts
  packages/richtext-lexical/src/lexical/plugins/TextPlugin/index.tsx
Labels: created-by: Contributor

#10481 fix(ui): scheduled publish not showing related events in postgres
  packages/payload/src/versions/schedule/types.ts
  packages/ui/src/elements/PublishButton/ScheduleDrawer/index.tsx
Labels: created-by: Payload team

#10358 fix(translations): update etTranslations type to DefaultTranslationsObject
  packages/translations/README.md
  packages/translations/src/languages/et.ts
Labels: created-by: Contributor

#10547 fix(ui): passes serverProps to custom label components within table columns
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
Labels: created-by: Payload team

#10530 feat(richtext-lexical): add new paragraph button below the editor
  docs/rich-text/overview.mdx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.scss
  packages/richtext-lexical/src/lexical/LexicalEditor.tsx
  packages/richtext-lexical/src/lexical/plugins/InsertParagraphAtEnd/index.scss
  packages/richtext-lexical/src/lexical/plugins/InsertParagraphAtEnd/index.tsx
  packages/richtext-lexical/src/types.ts
Labels: created-by: Payload team

#10549 fix(cpa): proper debug logging
  packages/create-payload-app/src/lib/manage-env-files.ts
Labels: created-by: Payload team

#10552 fix(richtext-lexical): insert paragraph at end button overlaps floating link toolbar
  packages/richtext-lexical/src/lexical/plugins/InsertParagraphAtEnd/index.scss
Labels: created-by: Payload team

#10504 feat: delete scheduled published events
  packages/payload/src/versions/schedule/types.ts
  packages/ui/src/elements/PublishButton/ScheduleDrawer/buildUpcomingColumns.tsx
  packages/ui/src/elements/PublishButton/ScheduleDrawer/index.scss
  packages/ui/src/elements/PublishButton/ScheduleDrawer/index.tsx
  packages/ui/src/utilities/schedulePublishHandler.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#10551 fix(ui): reset pagination when typing in WhereBuilder select menu
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
Labels: created-by: Payload team

#10550 fix: better messaging when no arg passed to payload cli
  packages/payload/src/bin/index.ts
  packages/payload/src/bin/migrate.ts
Labels: created-by: Payload team

#10554 fix: respect res header immutability
  packages/payload/src/utilities/handleEndpoints.ts
Labels: created-by: Payload team

#10557 fix(richtext-lexical): error when deleting links
  packages/richtext-lexical/src/features/link/client/plugins/floatingLinkEditor/types.ts
  packages/richtext-lexical/src/features/link/client/plugins/link/index.tsx
  packages/richtext-lexical/src/features/link/nodes/LinkNode.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#10559 fix(richtext-lexical): incorrect lexical version in dependency checker
  packages/richtext-lexical/src/index.ts
Labels: created-by: Payload team

#10561 chore(richtext-lexical): add unit test that ensures lexical dependency checker is updated
  packages/richtext-lexical/src/dependencyChecker.spec.ts
  packages/richtext-lexical/src/index.ts
Labels: created-by: Payload team

#10563 fix(richtext-lexical): ensure jsx and html converters do not output linebreak if editor is empty
  packages/richtext-lexical/src/exports/react/components/RichText/converter/index.tsx
  packages/richtext-lexical/src/features/converters/html/converter/index.ts
Labels: created-by: Payload team

#10564 perf(richtext-lexical): ensure internal link nodes do not store url field, and vice versa
  packages/richtext-lexical/src/exports/react/components/RichText/converter/converters/link.tsx
  packages/richtext-lexical/src/features/link/client/plugins/autoLink/index.tsx
  packages/richtext-lexical/src/features/link/nodes/LinkNode.ts
  packages/richtext-lexical/src/features/link/nodes/types.ts
  packages/richtext-lexical/src/features/link/server/baseFields.ts
  packages/richtext-lexical/src/features/link/server/index.ts
Labels: created-by: Payload team

#10565 feat(richtext-lexical): add jsx and html converters for tab nodes
  packages/richtext-lexical/src/exports/react/components/RichText/converter/converters/tab.tsx
  packages/richtext-lexical/src/exports/react/components/RichText/converter/defaultConverters.ts
  packages/richtext-lexical/src/exports/react/index.ts
  packages/richtext-lexical/src/features/converters/html/converter/converters/linebreak.ts
  packages/richtext-lexical/src/features/converters/html/converter/converters/paragraph.ts
  packages/richtext-lexical/src/features/converters/html/converter/converters/tab.ts
  packages/richtext-lexical/src/features/converters/html/converter/converters/text.ts
  packages/richtext-lexical/src/features/converters/html/converter/defaultConverters.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/nodeTypes.ts
Labels: created-by: Payload team

#10567 docs: add section on localized access control
  docs/access-control/overview.mdx
Labels: created-by: Payload team

#9388 perf: significantly reduce form state response size by up to 3x
  packages/next/src/utilities/initPage/handleAdminPage.ts
  packages/payload/src/admin/forms/Field.ts
  packages/payload/src/admin/forms/Form.ts
  packages/payload/src/admin/types.ts
  packages/payload/src/config/types.ts
  packages/ui/src/elements/BulkUpload/FormsManager/reducer.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  test/buildConfigWithDefaults.ts
  tsconfig.base.json
Labels: created-by: Payload team

#10570 fix(payload-cloud): add ts strict mode and fix a couple of wrong runtime behaviors
  packages/payload-cloud/src/email.ts
  packages/payload-cloud/src/hooks/afterDelete.ts
  packages/payload-cloud/src/plugin.ts
  packages/payload-cloud/src/staticHandler.ts
  packages/payload-cloud/src/utilities/authAsCognitoUser.ts
  packages/payload-cloud/src/utilities/getStorageClient.ts
  packages/payload-cloud/tsconfig.json
Labels: created-by: Payload team

#10573 fix: missing find collection versions REST endpoint
  packages/payload/src/collections/endpoints/index.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#10576 fix: form state read access control args
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
Labels: created-by: Payload team

#10578 fix(richtext-lexical): inline blocks did not store nested fields correctly
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Collapsible/e2e.spec.ts
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  test/fields/collections/CustomID/e2e.spec.ts
  test/fields/collections/Date/e2e.spec.ts
  test/fields/collections/Email/e2e.spec.ts
  test/fields/collections/Indexed/e2e.spec.ts
  test/fields/collections/JSON/e2e.spec.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
  test/fields/collections/Lexical/index.ts
  test/fields/collections/Number/e2e.spec.ts
  test/fields/collections/Point/e2e.spec.ts
  test/fields/collections/Radio/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/fields/collections/RichText/e2e.spec.ts
  test/fields/collections/Row/e2e.spec.ts
  test/fields/collections/Select/e2e.spec.ts
  test/fields/collections/Tabs/e2e.spec.ts
  test/fields/collections/Tabs2/e2e.spec.ts
  test/fields/collections/Text/e2e.spec.ts
  test/fields/collections/UI/e2e.spec.ts
  test/fields/collections/Upload/e2e.spec.ts
  test/fields/collections/UploadRestricted/e2e.spec.ts
  test/fields/payload-types.ts
  test/locked-documents/e2e.spec.ts
  test/playwright.config.ts
Labels: created-by: Payload team

#10579 chore: make TypeScript strict by default in packages and 7 packages stricter
  packages/create-payload-app/tsconfig.json
  packages/db-mongodb/tsconfig.json
  packages/db-postgres/tsconfig.json
  packages/db-sqlite/tsconfig.json
  packages/db-vercel-postgres/tsconfig.json
  packages/drizzle/tsconfig.json
  packages/email-nodemailer/tsconfig.json
  packages/email-resend/tsconfig.json
  packages/graphql/tsconfig.json
  packages/live-preview-react/tsconfig.json
  packages/live-preview-vue/tsconfig.json
  packages/live-preview/tsconfig.json
  packages/next/tsconfig.json
  packages/payload-cloud/tsconfig.json
  packages/payload/tsconfig.json
  packages/plugin-cloud-storage/tsconfig.json
  packages/plugin-form-builder/tsconfig.json
  packages/plugin-nested-docs/tsconfig.json
  packages/plugin-redirects/tsconfig.json
  packages/plugin-search/tsconfig.json
  packages/plugin-seo/tsconfig.json
  packages/plugin-stripe/tsconfig.json
  packages/richtext-lexical/tsconfig.json
  packages/richtext-slate/tsconfig.json
  packages/storage-azure/tsconfig.json
  packages/storage-gcs/tsconfig.json
  packages/storage-uploadthing/tsconfig.json
  packages/translations/tsconfig.json
  packages/ui/tsconfig.json
  tsconfig.base.json
Labels: created-by: Payload team

#10581 fix(richtext-lexical): setting hideInsertParagraphAtEnd to true did not hide insert paragraph button
  packages/richtext-lexical/src/field/rscEntry.tsx
Labels: created-by: Payload team

#10582 chore: make TypeScript strict in test folder. Simplify tsconfig
  test/tsconfig.json
  test/tsconfig.typecheck.json
  test/types/tsconfig.json
Labels: created-by: Payload team

#10556 chore: update mongodb-memory-server v9 -> v10
  package.json
  packages/db-mongodb/package.json
  pnpm-lock.yaml
  test/queues/int.spec.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#10575 fix(db-mongodb): incorrect errors logging due to invalid logic in `handleError`
  packages/db-mongodb/src/utilities/handleError.ts
Labels: created-by: Payload team

#10588 chore: enable noImplicitOverride in all packages
  packages/create-payload-app/tsconfig.json
  packages/db-mongodb/tsconfig.json
  packages/db-postgres/tsconfig.json
  packages/db-sqlite/tsconfig.json
  packages/db-vercel-postgres/tsconfig.json
  packages/drizzle/tsconfig.json
  packages/graphql/tsconfig.json
  packages/live-preview-react/tsconfig.json
  packages/live-preview-vue/tsconfig.json
  packages/live-preview/tsconfig.json
  packages/next/tsconfig.json
  packages/payload/tsconfig.json
  packages/plugin-cloud-storage/tsconfig.json
  packages/plugin-form-builder/tsconfig.json
  packages/plugin-nested-docs/tsconfig.json
  packages/plugin-redirects/tsconfig.json
  packages/plugin-search/tsconfig.json
  packages/plugin-seo/tsconfig.json
  packages/plugin-stripe/tsconfig.json
  packages/richtext-lexical/src/features/blocks/client/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/features/blocks/client/nodes/InlineBlocksNode.tsx
  packages/richtext-lexical/src/features/blocks/server/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/features/blocks/server/nodes/InlineBlocksNode.tsx
  packages/richtext-lexical/src/features/horizontalRule/client/nodes/HorizontalRuleNode.tsx
  packages/richtext-lexical/src/features/horizontalRule/server/nodes/HorizontalRuleNode.tsx
  packages/richtext-lexical/src/features/link/nodes/AutoLinkNode.ts
  packages/richtext-lexical/src/features/link/nodes/LinkNode.ts
  packages/richtext-lexical/src/features/migrations/lexicalPluginToLexical/nodes/unknownConvertedNode/index.tsx
  packages/richtext-lexical/src/features/migrations/slateToLexical/nodes/unknownConvertedNode/index.tsx
  packages/richtext-lexical/src/features/relationship/client/nodes/RelationshipNode.tsx
  packages/richtext-lexical/src/features/relationship/server/nodes/RelationshipNode.tsx
  packages/richtext-lexical/src/features/upload/client/nodes/UploadNode.tsx
  packages/richtext-lexical/src/features/upload/server/nodes/UploadNode.tsx
  packages/richtext-lexical/tsconfig.json
  packages/richtext-slate/tsconfig.json
  packages/storage-azure/tsconfig.json
  packages/storage-uploadthing/tsconfig.json
  packages/translations/tsconfig.json
  packages/ui/tsconfig.json
Labels: created-by: Payload team

#9347 fix: UpsertArgs is not exported in payload
  packages/payload/src/index.ts
Labels: stale

#10592 chore: enable noUncheckedIndexedAccess in all packages except richtext-lexical
  packages/plugin-form-builder/tsconfig.json
  packages/plugin-nested-docs/tsconfig.json
  packages/plugin-redirects/tsconfig.json
  packages/plugin-search/tsconfig.json
  packages/plugin-seo/tsconfig.json
  packages/plugin-stripe/tsconfig.json
  packages/richtext-slate/tsconfig.json
  packages/storage-azure/src/utils/getRangeFromHeader.ts
  packages/storage-azure/tsconfig.json
  packages/storage-uploadthing/tsconfig.json
  packages/translations/tsconfig.json
  packages/ui/tsconfig.json
Labels: created-by: Payload team

#10584 fix: delete scheduled publish jobs when deleting documents
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/deleteByID.ts
  packages/payload/src/versions/deleteCollectionVersions.ts
  packages/payload/src/versions/deleteScheduledPublishJobs.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#10560 templates: bump for v3.17.1
  templates/with-postgres/src/migrations/20250114_010521_initial.json
  templates/with-postgres/src/migrations/20250114_010521_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-postgres/src/migrations/20250114_010454_initial.json
  templates/with-vercel-postgres/src/migrations/20250114_010454_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/src/app/(frontend)/next/seed/route.ts
  templates/with-vercel-website/src/migrations/20250114_010510_initial.json
  templates/with-vercel-website/src/migrations/20250114_010510_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#10524 perf: ensure unnecessary config translations are not sent to the client
  packages/next/src/layouts/Root/index.tsx
  packages/payload/src/config/client.ts
  packages/ui/src/providers/Root/index.tsx
  packages/ui/src/providers/Translation/index.tsx
  test/fields/collections/Lexical/e2e/main/e2e.spec.ts
Labels: created-by: Payload team

#10600 perf: do not send minRows and maxRows undefined values to client
  packages/payload/src/fields/config/sanitize.ts
Labels: created-by: Payload team

#10598 chore: multi-tenant plugin updates
  packages/payload/src/versions/payloadPackageList.ts
  packages/plugin-multi-tenant/src/components/TenantField/index.client.tsx
  packages/plugin-multi-tenant/src/components/TenantSelector/index.client.tsx
  packages/plugin-multi-tenant/src/components/TenantSelector/index.tsx
  packages/plugin-multi-tenant/src/exports/client.ts
  packages/plugin-multi-tenant/src/exports/rsc.ts
  packages/plugin-multi-tenant/src/index.ts
  packages/plugin-multi-tenant/src/providers/TenantSelectionProvider/index.client.tsx
  packages/plugin-multi-tenant/src/providers/TenantSelectionProvider/index.tsx
Labels: created-by: Payload team

#10607 perf(ui): speed up list view rendering, ensure root layout does not re-render when navigating to list view
  packages/next/src/views/List/index.tsx
  packages/next/src/views/Versions/index.tsx
  packages/ui/src/elements/EditMany/DrawerContent.tsx
  packages/ui/src/elements/EditMany/index.tsx
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/providers/ListQuery/index.tsx
Labels: created-by: Payload team

#10610 perf: reduce document data deepCopying in field hooks
  packages/payload/src/collections/operations/utilities/update.ts
  packages/payload/src/duplicateDocument/index.ts
  packages/payload/src/fields/hooks/afterChange/index.ts
  packages/payload/src/fields/hooks/afterRead/index.ts
  packages/payload/src/fields/hooks/beforeDuplicate/index.ts
  packages/payload/src/fields/hooks/beforeValidate/index.ts
  packages/payload/src/globals/operations/update.ts
  packages/payload/src/versions/drafts/replaceWithDraftIfAvailable.ts
  packages/payload/src/versions/getLatestGlobalVersion.ts
Labels: created-by: Payload team

#10609 perf: operations performance optimizations
  packages/db-mongodb/src/queries/buildSearchParams.ts
  packages/db-mongodb/src/queries/parseParams.ts
  packages/drizzle/src/queries/parseParams.ts
  packages/payload/src/auth/getAccessResults.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findVersions.ts
  packages/payload/src/database/queryValidation/validateQueryPaths.ts
  packages/payload/src/exports/shared.ts
  packages/payload/src/preferences/deleteUserPreferences.ts
  packages/payload/src/types/constants.ts
  packages/payload/src/types/index.ts
  packages/payload/src/utilities/sanitizeInternalFields.ts
  packages/ui/src/elements/WhereBuilder/validateWhereQuery.ts
Labels: created-by: Payload team

#10171 feat(examples): add example with Remix + Payload Local API
  examples/remix/.gitignore
  examples/remix/README.md
  examples/remix/package.json
  examples/remix/payload/.env.example
  examples/remix/payload/.prettierrc.json
  examples/remix/payload/Dockerfile
  examples/remix/payload/README.md
  examples/remix/payload/docker-compose.yml
  examples/remix/payload/eslint.config.mjs
  examples/remix/payload/next-env.d.ts
  examples/remix/payload/next.config.mjs
  examples/remix/payload/package.json
  examples/remix/payload/src/app/(payload)/admin/[[...segments]]/not-found.tsx
  examples/remix/payload/src/app/(payload)/admin/[[...segments]]/page.tsx
  examples/remix/payload/src/app/(payload)/admin/importMap.js
  examples/remix/payload/src/app/(payload)/api/[...slug]/route.ts
  examples/remix/payload/src/app/(payload)/api/graphql-playground/route.ts
  examples/remix/payload/src/app/(payload)/api/graphql/route.ts
  examples/remix/payload/src/app/(payload)/custom.scss
  examples/remix/payload/src/app/(payload)/layout.tsx
  examples/remix/payload/src/app/my-route/route.ts
  examples/remix/payload/src/collections/Media.ts
  examples/remix/payload/src/collections/Users.ts
  examples/remix/payload/src/index.ts
  examples/remix/payload/src/payload-types.ts
  examples/remix/payload/src/payload.config.ts
  examples/remix/payload/tsconfig.json
  examples/remix/pnpm-lock.yaml
  examples/remix/pnpm-workspace.yaml
  examples/remix/website/.env.example
  examples/remix/website/.eslintrc.cjs
  examples/remix/website/.gitignore
  examples/remix/website/README.md
  examples/remix/website/app/entry.client.tsx
  examples/remix/website/app/entry.server.tsx
  examples/remix/website/app/root.tsx
  examples/remix/website/app/routes/_index.tsx
  examples/remix/website/app/tailwind.css
  examples/remix/website/package.json
  examples/remix/website/postcss.config.js
  examples/remix/website/public/favicon.ico
  examples/remix/website/public/logo-dark.png
  examples/remix/website/public/logo-light.png
  examples/remix/website/tailwind.config.ts
  examples/remix/website/tsconfig.json
  examples/remix/website/vite.config.ts
Labels: created-by: Payload team

#10620 feat(ui): exposes context of the view being rendered on the server
  packages/next/src/elements/Nav/index.tsx
  packages/next/src/templates/Default/index.tsx
  packages/next/src/views/Document/handleServerFunction.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/List/handleServerFunction.tsx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/Root/attachViewActions.ts
  packages/next/src/views/Root/getDocumentViewInfo.ts
  packages/next/src/views/Root/getViewFromConfig.ts
  packages/next/src/views/Root/index.tsx
  packages/payload/src/admin/views/types.ts
  packages/payload/src/config/types.ts
  packages/plugin-multi-tenant/src/components/GlobalViewRedirect/index.ts
  packages/plugin-multi-tenant/src/components/TenantSelector/index.tsx
  packages/plugin-multi-tenant/src/index.ts
  packages/plugin-multi-tenant/src/utilities/getGlobalViewRedirect.ts
  packages/plugin-multi-tenant/tsconfig.json
Labels: created-by: Payload team

#10614 test: field level validation errors
  packages/db-mongodb/src/utilities/handleError.ts
  test/collections-rest/config.ts
  test/collections-rest/int.spec.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
  test/database/shared.ts
Labels: created-by: Payload team

#10624 feat: support JPEG XL image size calculation
  packages/payload/package.json
  packages/payload/src/uploads/isImage.ts
  packages/ui/src/elements/Upload/index.tsx
  pnpm-lock.yaml
Labels: created-by: Payload team

#10625 chore(deps): bumps path-to-regexp
  packages/next/package.json
  packages/payload/package.json
  pnpm-lock.yaml
Labels: created-by: Contributor

#9557 fix(ui): show outline on focus for sort column buttons
  packages/ui/src/elements/SortColumn/index.scss
Labels: stale

#10615 ci: disable integration tests retrying
  .github/workflows/main.yml
Labels: created-by: Payload team

#10004 feat: adds support for both client-side and server-side remote URL uploads fetching
  docs/upload/overview.mdx
  packages/payload/src/collections/endpoints/getFileFromURL.ts
  packages/payload/src/collections/endpoints/index.ts
  packages/payload/src/uploads/types.ts
  packages/payload/src/utilities/isURLAllowed.ts
  packages/ui/src/elements/Upload/index.tsx
  packages/ui/src/utilities/isURLAllowed.ts
  test/helpers.ts
  test/uploads/collections/Upload1/index.ts
  test/uploads/collections/Upload2/index.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/startMockCorsServer.ts
Labels: created-by: Payload team

#10601 fix: updates field validation error messages to use labels if applicable
  packages/payload/src/errors/ValidationError.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/utilities/getFormattedLabel.ts
  packages/payload/src/utilities/getTranslatedLabel.ts
  test/collections-graphql/int.spec.ts
  test/database/int.spec.ts
  test/fields/collections/Array/index.ts
  test/fields/collections/Collapsible/index.ts
  test/fields/int.spec.ts
  test/relationships/int.spec.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#10641 fix(ui): placement issue with sonner toasts
  packages/ui/package.json
  packages/ui/src/scss/toasts.scss
  pnpm-lock.yaml
Labels: created-by: Payload team

#10643 docs: removes live preview image placeholder comment
  docs/live-preview/overview.mdx
Labels: created-by: Payload team

#10647 templates: add cache tag to images so that they can be revalidated along with the page on website templates
  templates/website/src/components/Media/ImageMedia/index.tsx
  templates/with-vercel-website/src/components/Media/ImageMedia/index.tsx
Labels: created-by: Payload team

#10618 fix(ui): replace hard coded path to API with `serverURL` and `routes.api`
  packages/ui/src/providers/Locale/index.tsx
Labels: created-by: Payload team

#10658 docs: react hooks - update useForm import path
  docs/admin/hooks.mdx
Labels: created-by: Contributor

#10661 chore(examples): bumps custom components example to latest and runs seed on init
  examples/custom-components/next-env.d.ts
  examples/custom-components/package.json
  examples/custom-components/pnpm-lock.yaml
  examples/custom-components/src/payload-types.ts
Labels: created-by: Payload team

#10663 perf: remove deepCopying in sanitizeJoinQuery, optimize flattenWhereToOperators
  packages/payload/src/database/flattenWhereToOperators.ts
  packages/payload/src/database/queryValidation/validateQueryPaths.ts
  packages/payload/src/database/sanitizeJoinQuery.ts
  packages/payload/src/index.ts
Labels: created-by: Payload team

#10667 perf(ui): remove unnecessary deepCopy in reduceToSerializableFields
  packages/ui/src/forms/Form/reduceToSerializableFields.ts
Labels: created-by: Payload team

#10669 chore: run pnpm dev without dev - this improves error logging on init
  test/dev.ts
Labels: created-by: Payload team

#10671 fix(plugin-stripe): hooks did not use api key from plugin config
  packages/plugin-stripe/src/hooks/createNewInStripe.ts
  packages/plugin-stripe/src/hooks/deleteFromStripe.ts
  packages/plugin-stripe/src/hooks/syncExistingWithStripe.ts
  packages/plugin-stripe/src/index.ts
Labels: created-by: Payload team

#10653 build: move larger scripts into tools dir in workspace
  .github/workflows/main.yml
  eslint.config.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/publish-canary.ts
  test/dev.ts
  test/jest.setup.js
  test/package.json
  tools/constants/package.json
  tools/constants/src/index.ts
  tools/constants/tsconfig.json
  tools/releaser/package.json
  tools/releaser/src/index.ts
  tools/releaser/src/lib/getPackageDetails.ts
  tools/releaser/src/lib/getPackageRegistryVersions.ts
  tools/releaser/src/lib/getWorkspace.ts
  tools/releaser/src/lib/publishList.ts
  tools/releaser/src/publish-canary.ts
  tools/releaser/src/release.ts
  tools/releaser/src/utils/createDraftGitHubRelease.ts
  tools/releaser/src/utils/generateReleaseNotes.ts
  tools/releaser/src/utils/getLatestCommits.ts
  tools/releaser/src/utils/getRecommendedBump.ts
  tools/releaser/tsconfig.json
  tools/scripts/package.json
  tools/scripts/src/build-template-with-local-pkgs.ts
  tools/scripts/src/generate-template-variations.ts
  tools/scripts/src/index.ts
  tools/scripts/src/pack-all-to-dest.ts
  tools/scripts/tsconfig.json
  tsconfig.base.json
Labels: created-by: Payload team

#10681 templates: form fields will now respect 'required' flag from config on website template
  templates/website/src/app/(frontend)/globals.css
  templates/website/src/blocks/Form/Checkbox/index.tsx
  templates/website/src/blocks/Form/Country/index.tsx
  templates/website/src/blocks/Form/Email/index.tsx
  templates/website/src/blocks/Form/Number/index.tsx
  templates/website/src/blocks/Form/Select/index.tsx
  templates/website/src/blocks/Form/State/index.tsx
  templates/website/src/blocks/Form/Text/index.tsx
  templates/website/src/blocks/Form/Textarea/index.tsx
  templates/with-vercel-website/src/app/(frontend)/globals.css
  templates/with-vercel-website/src/blocks/Form/Checkbox/index.tsx
  templates/with-vercel-website/src/blocks/Form/Country/index.tsx
  templates/with-vercel-website/src/blocks/Form/Email/index.tsx
  templates/with-vercel-website/src/blocks/Form/Number/index.tsx
  templates/with-vercel-website/src/blocks/Form/Select/index.tsx
  templates/with-vercel-website/src/blocks/Form/State/index.tsx
  templates/with-vercel-website/src/blocks/Form/Text/index.tsx
  templates/with-vercel-website/src/blocks/Form/Textarea/index.tsx
Labels: created-by: Payload team

#10553 fix(ui): fixed many bugs in the WhereBuilder relationship select menu
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  test/admin/collections/With300Documents.ts
  test/admin/config.ts
  test/admin/e2e/list-view/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/seed.ts
  test/admin/slugs.ts
Labels: created-by: Payload team
