Repository payloadcms/payload, pull requests merged in 2025-03, with the labels that each got.

#11463 perf: automatically add index on a relationship field when used as target for a join field
  packages/payload/src/fields/config/sanitizeJoinField.ts
Labels: created-by: Payload team

#11462 fix(richtext-lexical): ensure nested forms do not use form element
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  packages/richtext-lexical/src/features/blocks/client/componentInline/index.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/Form/types.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
Labels: created-by: Payload team

#11476 fix(ui): uses query provider as single source of truth for where builder
  packages/ui/src/elements/WhereBuilder/index.tsx
  packages/ui/src/providers/ListQuery/index.tsx
Labels: created-by: Payload team

#11467 feat(richtext-lexical): add editorConfigFactory helper to streamline getting the editor config
  docs/rich-text/converters.mdx
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/types.ts
  packages/richtext-lexical/src/utilities/editorConfigFactory.ts
Labels: created-by: Payload team

#11479 feat(richtext-lexical): add htmlToLexical helper
  docs/rich-text/converters.mdx
  packages/richtext-lexical/src/features/converters/htmlToLexical/index.ts
  packages/richtext-lexical/src/index.ts
Labels: created-by: Payload team

#11483 chore(eslint): speed up no-imports-from-self rule by ensuring cache is used
  packages/eslint-plugin/customRules/no-imports-from-self.js
Labels: created-by: Payload team

#11485 templates: improve naming of richtext component import, add 'payload-richtext' classname
  templates/website/src/components/RichText/index.tsx
  templates/with-vercel-website/src/components/RichText/index.tsx
Labels: created-by: Payload team

#11486 templates: bump payload versions, upgrade next.js to 15.2.0, fix eslint errors
  templates/_template/package.json
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/blocks/Content/config.ts
  templates/website/src/blocks/Form/Component.tsx
  templates/website/src/endpoints/seed/index.ts
  templates/website/src/fields/defaultLexical.ts
  templates/website/src/payload-types.ts
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250303_013923_initial.json
  templates/with-postgres/src/migrations/20250303_013923_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250303_013913_initial.json
  templates/with-vercel-postgres/src/migrations/20250303_013913_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/blocks/Content/config.ts
  templates/with-vercel-website/src/blocks/Form/Component.tsx
  templates/with-vercel-website/src/endpoints/seed/index.ts
  templates/with-vercel-website/src/fields/defaultLexical.ts
  templates/with-vercel-website/src/migrations/20250303_013917_initial.json
  templates/with-vercel-website/src/migrations/20250303_013917_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: created-by: Payload team

#11487 chore: temporarily disables flaky "should execute a custom script" test
  test/config/int.spec.ts
Labels: created-by: Payload team

#11488 feat(db-*): support limit in db.updateMany
  packages/db-mongodb/src/updateMany.ts
  packages/drizzle/src/updateMany.ts
  packages/payload/src/database/types.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#11480 docs: fix documentation "CheckListFeature"
  docs/rich-text/overview.mdx
Labels: created-by: Contributor

#10902 chore: add docker volume directories to gitignore
  .gitignore
Labels: created-by: Payload team

#11498 ci: clarify version reporting in issue templates
  .github/ISSUE_TEMPLATE/1.bug_report_v3.yml
  .github/ISSUE_TEMPLATE/2.design_issue.yml
Labels: created-by: Payload team

#11499 chore(deps): bumps payload-admin-bar to v1.0.7 to suppress react 19 warnings
  examples/draft-preview/package.json
  examples/localization/package.json
  examples/localization/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-vercel-website/package.json
Labels: created-by: Payload team

#11500 templates: fix vercel website template importmap error caused by missing import
  templates/with-vercel-website/src/app/(payload)/admin/importMap.js
Labels: created-by: Payload team

#11501 fix(examples): ensure working multi-tenant example with pg
  examples/multi-tenant/.env.example
  examples/multi-tenant/README.md
  examples/multi-tenant/next-env.d.ts
  examples/multi-tenant/package.json
  examples/multi-tenant/pnpm-lock.yaml
  examples/multi-tenant/src/app/(app)/page.tsx
  examples/multi-tenant/src/app/(payload)/admin/importMap.js
  examples/multi-tenant/src/collections/Pages/hooks/ensureUniqueSlug.ts
  examples/multi-tenant/src/collections/Users/access/read.ts
  examples/multi-tenant/src/collections/Users/hooks/ensureUniqueUsername.ts
  examples/multi-tenant/src/collections/Users/hooks/setCookieBasedOnDomain.ts
  examples/multi-tenant/src/payload-types.ts
  examples/multi-tenant/src/payload.config.ts
  examples/multi-tenant/src/seed.ts
  examples/multi-tenant/src/utilities/getCollectionIDType.ts
Labels: created-by: Payload team

#11494 chore(translations): enable TypeScript strict mode
  packages/translations/src/importDateFNSLocale.ts
  packages/translations/src/utilities/copyFile.ts
  packages/translations/src/utilities/deepMergeSimple.ts
  packages/translations/src/utilities/ensureDirExists.ts
  packages/translations/src/utilities/getTranslation.ts
  packages/translations/src/utilities/getTranslationsByContext.ts
  packages/translations/src/utilities/init.ts
  packages/translations/src/utilities/languages.ts
  packages/translations/tsconfig.json
Labels: created-by: Payload team

#11508 chore(plugin-search): enable TypeScript strict mode
  packages/plugin-search/src/Search/index.ts
  packages/plugin-search/src/Search/ui/ReindexButton/index.client.tsx
  packages/plugin-search/src/Search/ui/ReindexButton/index.tsx
  packages/plugin-search/src/index.ts
  packages/plugin-search/src/types.ts
  packages/plugin-search/src/utilities/generateReindexHandler.ts
  packages/plugin-search/src/utilities/syncDocAsSearchIndex.ts
  packages/plugin-search/tsconfig.json
Labels: created-by: Payload team

#11505 fix: avif images not converting to `upload.formatOptions` set file types
  packages/payload/src/uploads/canResizeImage.ts
  test/uploads/e2e.spec.ts
  test/uploads/test-image-avif.avif
Labels: created-by: Payload team

#11511 fix(next): incorrect active state for partial matches of collection names in sidebar
  packages/next/src/elements/Nav/index.client.tsx
  test/admin/collections/UploadTwo.ts
  test/admin/config.ts
  test/admin/e2e/general/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/slugs.ts
Labels: created-by: Payload team

#11518 fix(storage-uploadthing): files are duplicated to the storage via client uploads
  packages/payload/src/types/index.ts
  packages/payload/src/utilities/addDataAndFileToRequest.ts
  packages/plugin-cloud-storage/src/hooks/beforeChange.ts
  packages/plugin-cloud-storage/src/types.ts
  packages/plugin-cloud-storage/src/utilities/getIncomingFiles.ts
  packages/storage-uploadthing/src/handleUpload.ts
Labels: created-by: Payload team

#11509 fix: format admin url inside forgot pw email
  packages/next/src/elements/DocumentHeader/Tabs/Tab/TabLink.tsx
  packages/next/src/elements/Nav/index.client.tsx
  packages/next/src/utilities/initPage/handleAuthRedirect.ts
  packages/next/src/views/Dashboard/Default/index.tsx
  packages/next/src/views/Document/index.tsx
  packages/next/src/views/ForgotPassword/index.tsx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/LivePreview/index.client.tsx
  packages/next/src/views/Login/LoginForm/index.tsx
  packages/next/src/views/Logout/LogoutClient.tsx
  packages/next/src/views/NotFound/index.tsx
  packages/next/src/views/ResetPassword/ResetPasswordForm/index.tsx
  packages/next/src/views/ResetPassword/index.tsx
  packages/next/src/views/Root/getViewFromConfig.ts
  packages/next/src/views/Root/index.tsx
  packages/next/src/views/Unauthorized/index.tsx
  packages/next/src/views/Verify/index.tsx
  packages/next/src/views/Version/Default/SetStepNav.tsx
  packages/next/src/views/Version/Restore/index.tsx
  packages/next/src/views/Versions/cells/CreatedAt/index.tsx
  packages/payload/src/auth/operations/forgotPassword.ts
  packages/payload/src/config/types.ts
  packages/payload/src/exports/shared.ts
  packages/payload/src/utilities/formatAdminURL.ts
  packages/plugin-search/src/Search/ui/LinkToDoc/index.client.tsx
  packages/richtext-lexical/src/cell/rscEntry.tsx
  packages/richtext-slate/src/cell/rscEntry.tsx
  packages/ui/src/elements/AppHeader/index.tsx
  packages/ui/src/elements/BulkUpload/EditForm/index.tsx
  packages/ui/src/elements/DeleteDocument/index.tsx
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/elements/DuplicateDocument/index.tsx
  packages/ui/src/elements/Logout/index.tsx
  packages/ui/src/elements/StayLoggedIn/index.tsx
  packages/ui/src/elements/Table/DefaultCell/index.tsx
  packages/ui/src/graphics/Account/index.tsx
  packages/ui/src/providers/Auth/index.tsx
  packages/ui/src/utilities/formatAdminURL.ts
  packages/ui/src/utilities/handleBackToDashboard.tsx
  packages/ui/src/utilities/handleGoBack.tsx
  packages/ui/src/views/Edit/SetDocumentStepNav/index.tsx
  packages/ui/src/views/Edit/index.tsx
  test/helpers.ts
  test/helpers/adminUrlUtil.ts
Labels: created-by: Payload team

#11524 fix: collection config deep merge during sanitization causing unpredictable behavior
  packages/payload/src/collections/config/defaults.ts
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/config/defaults.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/globals/config/sanitize.ts
  packages/payload/src/globals/config/types.ts
  packages/payload/src/queues/config/jobsCollection.ts
  packages/payload/src/utilities/configToJSONSchema.spec.ts
Labels: created-by: Payload team

#11529 ci: cache mongodb image to avoid rate limiting
  .github/workflows/main.yml
Labels: created-by: Payload team

#11531 fix(next): admin panel fails compiling when fullySpecified is set in next config
  next.config.mjs
  packages/next/package.json
  pnpm-lock.yaml
  test/fields/collections/ConditionalLogic/index.ts
  test/fields/collections/JSON/index.tsx
  test/next.config.mjs
Labels: created-by: Payload team

#11512 feat: compound indexes
  docs/configuration/collections.mdx
  packages/db-mongodb/src/init.ts
  packages/db-mongodb/src/models/buildCollectionSchema.ts
  packages/db-mongodb/src/models/buildSchema.ts
  packages/drizzle/src/schema/build.ts
  packages/drizzle/src/schema/buildRawSchema.ts
  packages/drizzle/src/schema/traverseFields.ts
  packages/payload/src/collections/config/client.ts
  packages/payload/src/collections/config/defaults.ts
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/config/sanitizeCompoundIndexes.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/getFieldByPath.ts
  packages/payload/src/versions/buildVersionCompoundIndexes.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#11527 fix(storage-gcs): client uploads are enabled even if `clientUploads` is not set
  packages/storage-gcs/src/index.ts
Labels: created-by: Payload team

#11535 chore: add plugin-import-export to publishList release tool
  tools/releaser/src/lib/publishList.ts
Labels: created-by: Payload team

#11534 chore: indexes are not iterable, corrects `indexes` default value sanitization
  packages/payload/src/collections/config/defaults.ts
  packages/payload/src/collections/config/sanitize.ts
Labels: created-by: Payload team

#11536 chore: cleanup generated configs
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/globals/operations/findOne.ts
  packages/payload/src/locked-documents/config.ts
  packages/payload/src/preferences/config.ts
  packages/payload/src/preferences/deleteUserPreferences.ts
  packages/payload/src/preferences/operations/delete.ts
  packages/payload/src/preferences/operations/findOne.ts
  packages/payload/src/preferences/operations/update.ts
  packages/payload/src/queues/config/index.ts
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/getUpdateJobFunction.ts
  packages/payload/src/utilities/checkDocumentLockStatus.ts
  packages/payload/src/utilities/sanitizePermissions.spec.ts
  packages/payload/src/versions/deleteScheduledPublishJobs.ts
Labels: created-by: Payload team

#11538 fix(ui): execute client upload handler only when file exists
  packages/ui/src/elements/BulkUpload/FormsManager/createFormData.ts
  packages/ui/src/forms/Form/index.tsx
Labels: created-by: Payload team

#11533 test: add unit tests for `getFieldByPath`
  packages/payload/src/utilities/getFieldByPath.spec.ts
Labels: created-by: Payload team

#11528 feat: threads path through field condition functions
  docs/fields/overview.mdx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  test/fields/collections/ConditionalLogic/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#11552 docs: remove dead links from client live-preview
  docs/live-preview/client.mdx
Labels: created-by: Contributor

#11551 fix(richtext-lexical): fix bug in $createAutoLinkNode when the link is preceded by a textnode
  packages/richtext-lexical/src/features/link/client/plugins/autoLink/index.tsx
Labels: created-by: Payload team

#11301 feat: allow hiding the blockName field visible in blocks' headers via admin.disableBlockName
  docs/fields/blocks.mdx
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/sanitize.spec.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/fields/Blocks/BlockRow.tsx
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Blocks/index.ts
  test/fields/collections/Blocks/shared.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#3684 feat: payload admin bar
  .github/workflows/main.yml
  .gitignore
  package.json
  packages/admin-bar/.prettierignore
  packages/admin-bar/.swcrc
  packages/admin-bar/LICENSE.md
  packages/admin-bar/README.md
  packages/admin-bar/eslint.config.js
  packages/admin-bar/package.json
  packages/admin-bar/src/AdminBar.tsx
  packages/admin-bar/src/index.ts
  packages/admin-bar/src/types.ts
  packages/admin-bar/tsconfig.json
  pnpm-lock.yaml
  test/admin-bar/.gitignore
  test/admin-bar/app/(payload)/admin/[[...segments]]/not-found.tsx
  test/admin-bar/app/(payload)/admin/[[...segments]]/page.tsx
  test/admin-bar/app/(payload)/admin/importMap.js
  test/admin-bar/app/(payload)/api/[...slug]/route.ts
  test/admin-bar/app/(payload)/api/graphql-playground/route.ts
  test/admin-bar/app/(payload)/api/graphql/route.ts
  test/admin-bar/app/(payload)/custom.scss
  test/admin-bar/app/(payload)/layout.tsx
  test/admin-bar/app/admin-bar/app.scss
  test/admin-bar/app/admin-bar/layout.tsx
  test/admin-bar/app/admin-bar/page.tsx
  test/admin-bar/collections/Media/index.ts
  test/admin-bar/collections/Posts/index.ts
  test/admin-bar/config.ts
  test/admin-bar/e2e.spec.ts
  test/admin-bar/eslint.config.js
  test/admin-bar/next-env.d.ts
  test/admin-bar/next.config.mjs
  test/admin-bar/payload-types.ts
  test/admin-bar/tsconfig.eslint.json
  test/admin-bar/tsconfig.json
  test/admin-bar/types.d.ts
  test/generateImportMap.ts
  test/package.json
  test/setupProd.ts
  test/tsconfig.typecheck.json
  tools/releaser/src/lib/publishList.ts
  tsconfig.base.json
  tsconfig.json
Labels: created-by: Payload team, keep

#11521 chore(ui): improves field error toast messages
  packages/payload/src/admin/RichText.ts
  packages/payload/src/fields/hooks/beforeChange/index.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/hooks/beforeChange/traverseFields.ts
  packages/payload/src/utilities/getLabelFromPath.ts
  packages/richtext-lexical/src/index.ts
  packages/ui/src/elements/Toasts/fieldErrors.tsx
  packages/ui/src/forms/Form/index.tsx
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/int.spec.ts
Labels: created-by: Payload team

#11515 fix: safe auth strategy execution
  packages/payload/src/auth/executeAuthStrategies.ts
Labels: created-by: Payload team

#10794 feat: allow specification of which JWT extraction methods are supported, and in which order
  packages/payload/src/auth/extractJWT.ts
  packages/payload/src/config/defaults.ts
  packages/payload/src/config/types.ts
Labels: created-by: Payload team

#11561 fix: add missing auth property to new defaults function
  packages/payload/src/config/defaults.ts
Labels: created-by: Payload team

#11563 feat(richtext-lexical): adds ability to disable auto link creation
  packages/richtext-lexical/src/features/link/client/index.tsx
  packages/richtext-lexical/src/features/link/server/index.ts
Labels: created-by: Payload team

#11565 ci: canary and internal releases [skip ci]
  .github/workflows/publish-prerelease.yml
  package.json
  tools/releaser/package.json
  tools/releaser/src/lib/getWorkspace.ts
  tools/releaser/src/publish-prerelease.ts
Labels: created-by: Payload team

#11558 feat(db-mongodb): strip keys from the data that don't exist in the schema from read results
  docs/database/mongodb.mdx
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/utilities/transform.ts
  packages/payload/src/utilities/flattenAllFields.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#11572 ci: adjust paths filter for workflows, only look at main.yml
  .github/workflows/main.yml
Labels: created-by: Payload team

#11564 feat(richtext-lexical): upgrade lexical from 0.21.0 to 0.27.1
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/blockquote/markdownTransformer.ts
  packages/richtext-lexical/src/features/blocks/server/nodes/BlocksNode.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableHoverActionsPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TablePlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/markdownTransformer.ts
  packages/richtext-lexical/src/features/horizontalRule/client/plugin/index.scss
  packages/richtext-lexical/src/features/indent/client/index.tsx
  packages/richtext-lexical/src/features/link/nodes/AutoLinkNode.ts
  packages/richtext-lexical/src/features/link/nodes/LinkNode.ts
  packages/richtext-lexical/src/features/link/nodes/types.ts
  packages/richtext-lexical/src/features/migrations/lexicalPluginToLexical/nodes/unknownConvertedNode/index.tsx
  packages/richtext-lexical/src/features/migrations/slateToLexical/nodes/unknownConvertedNode/index.tsx
  packages/richtext-lexical/src/features/relationship/server/nodes/RelationshipNode.tsx
  packages/richtext-lexical/src/features/toolbars/shared/ToolbarDropdown/DropDown.tsx
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical-proxy/@lexical-react/LexicalTableOfContents.tsx
  packages/richtext-lexical/src/lexical/plugins/SlashMenu/LexicalTypeaheadMenuPlugin/LexicalMenu.tsx
  packages/richtext-lexical/src/lexical/plugins/handles/AddBlockHandlePlugin/index.tsx
  packages/richtext-lexical/src/lexical/plugins/handles/DraggableBlockPlugin/index.tsx
  packages/richtext-lexical/src/lexical/theme/EditorTheme.scss
  packages/richtext-lexical/src/lexical/theme/EditorTheme.tsx
  packages/richtext-lexical/src/lexical/utils/guard.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#11566 chore(deps): bumps @payloadcms/admin-bar in templates and examples
  examples/draft-preview/README.md
  examples/draft-preview/package.json
  examples/draft-preview/pnpm-lock.yaml
  examples/draft-preview/src/components/AdminBar/index.tsx
  examples/draft-preview/src/seed/home.ts
  examples/localization/package.json
  examples/localization/pnpm-lock.yaml
  examples/localization/src/app/(frontend)/[locale]/layout.tsx
  examples/localization/src/components/AdminBar/index.scss
  examples/localization/src/components/AdminBar/index.tsx
  templates/website/README.md
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/components/AdminBar/index.tsx
  templates/with-vercel-website/README.md
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/components/AdminBar/index.tsx
Labels: created-by: Payload team

#11574 fix(ui): incorrect error states
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/ui/src/elements/Toasts/fieldErrors.tsx
  packages/ui/src/fields/Collapsible/index.tsx
  packages/ui/src/fields/Tabs/Tab/index.tsx
  packages/ui/src/forms/Form/mergeServerFormState.ts
  packages/ui/src/forms/WatchChildErrors/buildPathSegments.ts
  packages/ui/src/forms/WatchChildErrors/getFieldStateFromPaths.ts
  packages/ui/src/forms/WatchChildErrors/getNestedFieldState.ts
  packages/ui/src/forms/WatchChildErrors/index.tsx
  test/eslint.config.js
  test/fields-relationship/e2e.spec.ts
  test/fields/collections/Array/e2e.spec.ts
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/collections/Indexed/e2e.spec.ts
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/Number/e2e.spec.ts
  test/fields/collections/Relationship/e2e.spec.ts
  test/helpers/assertToastErrors.ts
  test/uploads/e2e.spec.ts
Labels: created-by: Payload team

#11576 chore(deps): bump next.js from 15.2.0 to 15.2.1 in monorepo
  package.json
  pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#11555 fix(ui): apply consistent styling to custom & default block thumbnails
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/ThumbnailCard/index.scss
  packages/ui/src/fields/Blocks/BlocksDrawer/index.scss
  packages/ui/src/fields/Blocks/BlocksDrawer/index.tsx
  packages/ui/src/graphics/DefaultBlockImage/index.tsx
  test/fields/collections/Blocks/index.ts
  test/fields/collections/Upload/payload480x320.jpg
  test/fields/payload-types.ts
  test/fields/seed.ts
Labels: created-by: Payload team

#11546 feat(ui): adds disable copy to locale option to collection config
  docs/configuration/collections.mdx
  packages/payload/src/collections/config/types.ts
  packages/ui/src/elements/DocumentControls/index.tsx
  test/admin/collections/DisableCopyToLocale.ts
  test/admin/config.ts
  test/admin/e2e/general/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/slugs.ts
Labels: created-by: Payload team

#11504 chore(ui): removes margin when row is empty and passes style from props
  packages/ui/src/fields/Row/index.scss
  packages/ui/src/fields/Row/index.tsx
Labels: created-by: Payload team

#11496 fix(ui): upload.displayPreview should affect all previews in the admin panel
  packages/ui/src/elements/FileDetails/StaticFileDetails/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/File/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
  packages/ui/src/fields/Upload/HasMany/index.tsx
  packages/ui/src/fields/Upload/HasOne/index.tsx
  packages/ui/src/fields/Upload/Input.tsx
  packages/ui/src/fields/Upload/RelationshipContent/index.tsx
  packages/ui/src/fields/Upload/index.tsx
  test/uploads/config.ts
Labels: created-by: Payload team

#11584 fix(ui): logic for showing copyToLocale button and adds test
  packages/ui/src/elements/DocumentControls/index.tsx
  test/admin-root/e2e.spec.ts
Labels: created-by: Payload team

#11556 fix(graphql): sanitize graphql field names for schema generation
  packages/graphql/src/schema/buildMutationInputType.ts
  packages/graphql/src/schema/buildObjectType.ts
  packages/graphql/src/schema/buildPoliciesType.ts
  packages/graphql/src/schema/fieldToSchemaMap.ts
  test/graphql/config.ts
  test/graphql/int.spec.ts
  test/graphql/payload-types.ts
  test/graphql/schema.graphql
Labels: created-by: Payload team

#11589 fix(db-mongodb): properly sanitize `updateVersion` read result
  packages/db-mongodb/src/updateVersion.ts
  test/versions/int.spec.ts
Labels: created-by: Payload team

#11590 fix(plugin-import-export): plugin breaks `i18n` configuration
  .github/workflows/pr-title.yml
  packages/plugin-import-export/src/index.ts
Labels: created-by: Payload team

#11591 feat: threads path through field validate function
  docs/fields/overview.mdx
  packages/next/src/views/ForgotPassword/ForgotPasswordForm/index.tsx
  packages/payload/src/auth/strategies/local/generatePasswordSaltHash.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/ui/src/fields/Password/index.tsx
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/useField/index.tsx
  packages/ui/src/views/Edit/Auth/APIKey.tsx
Labels: created-by: Payload team

#11609 fix(ui): stale list thumbnails when navigating
  packages/ui/src/elements/Thumbnail/index.tsx
Labels: created-by: Payload team

#11612 fix: upload imageSizes forces original file uploads to be compressed
  packages/payload/src/uploads/generateFileData.ts
Labels: created-by: Payload team

#11607 chore(ui): code/json field full height should include any padding added
  packages/ui/src/elements/CodeEditor/CodeEditor.tsx
  test/fields/collections/Code/index.tsx
Labels: created-by: Payload team

#11614 fix(ui): adds fallback locale when defaultLocale is unavailable
  packages/ui/src/fields/Array/index.tsx
  packages/ui/src/fields/Blocks/index.tsx
  packages/ui/src/forms/NullifyField/index.tsx
  packages/ui/src/providers/Locale/index.tsx
Labels: created-by: Payload team

#11386 docs: fix documentation about custom i18n types
  docs/configuration/i18n.mdx
Labels: created-by: Payload team

#11624 fix: ensure only authenticated users can access the `payload-locked-documents` collection
  packages/payload/src/locked-documents/config.ts
Labels: created-by: Payload team

#11594 perf: 50% faster compilation speed by skipping bundling of server-only packages during dev
  next.config.mjs
  packages/next/src/withPayload.js
  packages/payload-cloud/src/utilities/refreshSession.ts
  templates/_template/next.config.mjs
  templates/blank/next.config.mjs
  templates/plugin/dev/next.config.mjs
  templates/website/next.config.js
  templates/with-payload-cloud/next.config.mjs
  templates/with-postgres/next.config.mjs
  templates/with-vercel-mongodb/next.config.mjs
  templates/with-vercel-postgres/next.config.mjs
  templates/with-vercel-website/next.config.js
  test/next.config.mjs
Labels: created-by: Payload team

#11618 refactor: more reliable import map generation, supporting turbopack and tsconfig basePath
  packages/payload/src/bin/generateImportMap/generateImportMap.spec.ts
  packages/payload/src/bin/generateImportMap/index.ts
  packages/payload/src/bin/generateImportMap/utilities/addPayloadComponentToImportMap.ts
  packages/payload/src/bin/generateImportMap/utilities/getFromImportMap.ts
  packages/payload/src/bin/generateImportMap/utilities/getImportMapToBaseDirPath.ts
  packages/payload/src/bin/generateImportMap/utilities/parsePayloadComponent.ts
  packages/payload/src/bin/generateImportMap/utilities/resolveImportMapFilePath.ts
  packages/payload/src/exports/shared.ts
  packages/payload/src/fields/config/client.ts
Labels: created-by: Payload team

#11623 feat: defaults to noindex nofollow
  docs/admin/metadata.mdx
  packages/payload/src/config/defaults.ts
  test/admin/config.ts
  test/admin/e2e/general/e2e.spec.ts
Labels: created-by: Payload team

#11629 chore(deps): bump all eslint packages
  packages/eslint-config/configs/react/index.mjs
  packages/eslint-config/index.mjs
  packages/eslint-config/package.json
  packages/eslint-plugin/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#11631 feat(richtext-lexical): allow disabling indentation for specific nodes
  packages/richtext-lexical/src/features/indent/client/IndentPlugin.tsx
  packages/richtext-lexical/src/features/indent/client/index.tsx
  packages/richtext-lexical/src/features/indent/server/index.ts
Labels: created-by: Payload team

#11636 chore(deps): bump next.js from 15.2.1 to 15.2.2 in monorepo
  package.json
  pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#11638 docs: fix invalid ```txt language
  docs/admin/metadata.mdx
Labels: created-by: Payload team

#11642 fix: incorrect types for field Label, Description and Error server components
  packages/payload/src/admin/forms/Description.ts
  packages/payload/src/admin/forms/Error.ts
  packages/payload/src/admin/forms/Label.ts
Labels: created-by: Payload team

#11640 test: deflakes blocks e2e
  test/fields/collections/Blocks/components/AddCustomBlocks/index.scss
  test/fields/collections/Blocks/components/AddCustomBlocks/index.tsx
  test/fields/collections/Blocks/e2e.spec.ts
  test/fields/payload-types.ts
  test/helpers/e2e/scrollEntirePage.ts
  test/helpers/e2e/waitForPageStability.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11353 chore(translations): polish Swedish
  packages/translations/src/languages/sv.ts
Labels: created-by: Contributor

#11654 fix(translations): improve Swedish translations
  packages/translations/src/languages/sv.ts
Labels: created-by: Contributor

#11643 fix(ui): prevent fieldErrorsToast from showing empty errors list
  packages/ui/src/elements/Toasts/fieldErrors.tsx
Labels: created-by: Contributor

#11641 templates: bump Payload and Next.js dependencies
  templates/_template/package.json
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/website/src/blocks/Form/Error/index.tsx
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250311_214602_initial.json
  templates/with-postgres/src/migrations/20250311_214602_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250311_214549_initial.json
  templates/with-vercel-postgres/src/migrations/20250311_214549_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/migrations/20250311_214555_initial.json
  templates/with-vercel-website/src/migrations/20250311_214555_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: created-by: Payload team

#11664 fix(ui): add RowLabelProvider context for blocks row labels
  docs/fields/blocks.mdx
  packages/ui/src/fields/Blocks/BlockRow.tsx
  packages/ui/src/forms/RowLabel/index.tsx
  packages/ui/src/forms/RowLabel/types.ts
Labels: created-by: Payload team

#11665 fix(ui): form state infinite render
  packages/ui/src/hooks/useQueues.ts
  test/form-state/collections/Posts/RenderTracker.tsx
  test/form-state/collections/Posts/index.ts
  test/form-state/e2e.spec.ts
  test/form-state/payload-types.ts
  test/helpers.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11673 fix: exclude plugin-cloud-storage, plugin-sentry and plugin-stripe from bundling optimization
  packages/next/src/withPayload.js
Labels: created-by: Payload team

#11653 chore: fix typo (rename mognoose to mongoose)
  test/database/int.spec.ts
Labels: created-by: Payload team

#8720 feat: added support for conditional tabs
  packages/graphql/src/schema/recursivelyBuildNestedPaths.ts
  packages/payload/src/admin/fields/Tabs.ts
  packages/payload/src/fields/config/sanitize.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/fields/Tabs/Tab/index.scss
  packages/ui/src/fields/Tabs/Tab/index.tsx
  packages/ui/src/fields/Tabs/index.scss
  packages/ui/src/fields/Tabs/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  test/fields/collections/Tabs/e2e.spec.ts
  test/fields/collections/Tabs/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team, prioritized

#11683 feat(ui): don't trigger preventLeave when opening a new tab
  packages/ui/src/elements/LeaveWithoutSaving/usePreventLeave.tsx
  test/admin/e2e/general/e2e.spec.ts
Labels: created-by: Contributor

#11627 feat: add `forceSelect` collection / global config property
  docs/configuration/collections.mdx
  docs/configuration/globals.mdx
  docs/queries/select.mdx
  packages/payload/src/collections/config/types.ts
  packages/payload/src/collections/operations/create.ts
  packages/payload/src/collections/operations/delete.ts
  packages/payload/src/collections/operations/deleteByID.ts
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/collections/operations/findVersionByID.ts
  packages/payload/src/collections/operations/findVersions.ts
  packages/payload/src/collections/operations/restoreVersion.ts
  packages/payload/src/collections/operations/update.ts
  packages/payload/src/collections/operations/updateByID.ts
  packages/payload/src/globals/config/types.ts
  packages/payload/src/globals/operations/findOne.ts
  packages/payload/src/globals/operations/findVersionByID.ts
  packages/payload/src/globals/operations/findVersions.ts
  packages/payload/src/globals/operations/update.ts
  packages/payload/src/utilities/sanitizeSelect.ts
  test/_community/payload-types.ts
  test/select/collections/ForceSelect/index.tsx
  test/select/config.ts
  test/select/int.spec.ts
  test/select/payload-types.ts
Labels: created-by: Payload team

#11658 fix: ensures `select` & `radio` field option labels accept JSX elements
  packages/next/src/views/Version/RenderFieldsToDiff/fields/Select/index.tsx
  packages/payload/src/fields/config/types.ts
  packages/payload/src/index.ts
  packages/translations/src/utilities/getTranslation.ts
  packages/ui/src/elements/Table/DefaultCell/index.tsx
  packages/ui/src/elements/TableColumns/buildColumnState.tsx
  packages/ui/src/utilities/getDisplayedFieldValue.ts
  packages/ui/src/utilities/hasOptionLabelJSXElement.ts
  test/fields/collections/Radio/CustomJSXLabel.tsx
  test/fields/collections/Radio/e2e.spec.ts
  test/fields/collections/Radio/index.ts
  test/fields/collections/Select/CustomJSXLabel.tsx
  test/fields/collections/Select/e2e.spec.ts
  test/fields/collections/Select/index.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#11613 chore: simplify query parsing
  packages/payload/package.json
  packages/payload/src/express/middleware/addParsedQuery.ts
  packages/payload/src/express/middleware/index.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#11702 chore: bump dependencies
  package.json
  packages/bundler-vite/package.json
  packages/bundler-webpack/package.json
  packages/db-mongodb/package.json
  packages/eslint-config-payload/package.json
  packages/payload/package.json
  packages/plugin-cloud-storage/package.json
  packages/plugin-cloud/package.json
  packages/plugin-relationship-object-ids/package.json
  packages/plugin-sentry/package.json
  packages/plugin-stripe/package.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#11689 feat: form state select
  jest.config.js
  packages/payload/src/admin/forms/Form.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/createLocalReq.ts
  packages/payload/src/utilities/getBlockSelect.ts
  packages/payload/src/utilities/stripUnselectedFields.ts
  packages/ui/src/forms/Form/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/index.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/iterateFields.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/promise.ts
  packages/ui/src/forms/fieldSchemasToFormState/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/iterateFields.ts
  packages/ui/src/utilities/buildFormState.ts
  test/admin/e2e/general/e2e.spec.ts
  test/admin/payload-types.ts
  test/form-state/int.spec.ts
Labels: created-by: Payload team

#11693 fix(plugin-multi-tenant): missing key console message
  docs/plugins/multi-tenant.mdx
  packages/plugin-multi-tenant/README.md
  packages/plugin-multi-tenant/src/components/TenantSelector/index.tsx
  packages/plugin-multi-tenant/src/index.ts
  packages/plugin-multi-tenant/src/types.ts
Labels: created-by: Payload team

#11699 fix(ui): scheduled publish not displaying the timezone's label and timezones being reset when scheduling a publish, brisbane is now a default timezone
  packages/payload/src/fields/baseFields/timezone/defaultTimezones.ts
  packages/ui/src/elements/PublishButton/ScheduleDrawer/buildUpcomingColumns.tsx
  packages/ui/src/elements/PublishButton/ScheduleDrawer/index.tsx
Labels: created-by: Payload team

#11706 feat(richtext-lexical): upgrade lexical from 0.27.1 to 0.27.2
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.tsx
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableCellResizerPlugin/index.scss
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableCellResizerPlugin/index.tsx
  packages/richtext-lexical/src/index.ts
  pnpm-lock.yaml
Labels: created-by: Payload team

#11701 feat: aligns user _strategy returned from API
  packages/payload/src/auth/operations/login.ts
  packages/payload/src/auth/operations/me.ts
  packages/payload/src/auth/operations/refresh.ts
  packages/payload/src/auth/operations/registerFirstUser.ts
  packages/payload/src/auth/operations/resetPassword.ts
  packages/payload/src/auth/strategies/jwt.ts
  packages/payload/src/auth/types.ts
  packages/payload/src/index.ts
Labels: created-by: Payload team

#11743 fix(ui): fallback localization data was appearing in document
  packages/payload/src/utilities/addLocalesToRequest.ts
  packages/payload/src/utilities/createPayloadRequest.ts
  packages/payload/src/utilities/sanitizeFallbackLocale.ts
  test/localization/e2e.spec.ts
Labels: created-by: Payload team

#11656 feat(richtext-lexical): allow disabling TabNode
  packages/richtext-lexical/src/features/indent/client/IndentPlugin.tsx
  packages/richtext-lexical/src/features/indent/server/index.ts
Labels: created-by: Payload team

#10422 feat(db-postgres): add vector raw column type
  packages/drizzle/src/postgres/columnToCodeConverter.ts
  packages/drizzle/src/postgres/schema/buildDrizzleTable.ts
  packages/drizzle/src/types.ts
  test/database/postgres-vector.int.spec.ts
Labels: created-by: Payload team

#11708 perf(ui): implements select in bulk edit
  packages/ui/src/elements/BulkUpload/EditMany/DrawerContent.tsx
  packages/ui/src/elements/BulkUpload/EditMany/index.tsx
  packages/ui/src/elements/EditMany/DrawerContent.tsx
  packages/ui/src/elements/EditMany/index.tsx
  packages/ui/src/elements/FieldSelect/index.tsx
  packages/ui/src/forms/Form/fieldReducer.ts
  test/_community/payload-types.ts
  test/uploads/e2e.spec.ts
Labels: created-by: Payload team

#11748 chore(deps): bump next.js from 15.2.2 to 15.2.3 in monorepo
  package.json
  pnpm-lock.yaml
  test/package.json
Labels: created-by: Payload team

#11700 fix(ui): excess error css coming from group fields
  packages/ui/src/fields/Group/index.scss
Labels: created-by: Payload team

#11744 fix: bulk upload validation when files are missing
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/lt.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
  packages/ui/src/elements/BulkUpload/FileSidebar/index.tsx
  packages/ui/src/elements/BulkUpload/FormsManager/index.tsx
  packages/ui/src/elements/Thumbnail/index.tsx
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
Labels: created-by: Payload team

#11621 fix: field appending on duplicate should ignore non string values
  packages/payload/src/fields/setDefaultBeforeDuplicate.ts
Labels: created-by: Payload team

#11753 fix(plugin-multi-tenant): ensures redirect route is correctly formatted
  packages/plugin-multi-tenant/src/components/GlobalViewRedirect/index.ts
  packages/plugin-multi-tenant/src/defaults.ts
  packages/plugin-multi-tenant/src/index.ts
  packages/plugin-multi-tenant/src/types.ts
  packages/plugin-multi-tenant/src/utilities/getGlobalViewRedirect.ts
Labels: created-by: Payload team

#11754 fix(richtext-lexical): remove undefined rel and target attributes in link HTML converter
  packages/plugin-form-builder/src/utilities/lexical/converters/link.ts
  packages/richtext-lexical/src/features/converters/lexicalToHtml/async/converters/link.ts
  packages/richtext-lexical/src/features/converters/lexicalToHtml/sync/converters/link.ts
  packages/richtext-lexical/src/features/link/server/index.ts
Labels: created-by: Payload team

#11747 fix(richtext-lexical): unchecked list items were rendered as checked in html converter
  packages/richtext-lexical/src/features/converters/lexicalToHtml/async/converters/list.ts
  packages/richtext-lexical/src/features/converters/lexicalToHtml/sync/converters/list.ts
Labels: created-by: Payload team

#11756 test: dedicated bulk edit test suite
  .github/workflows/main.yml
  test/admin/collections/Posts.ts
  test/admin/e2e/general/e2e.spec.ts
  test/admin/payload-types.ts
  test/bulk-edit/.gitignore
  test/bulk-edit/collections/Posts/index.ts
  test/bulk-edit/config.ts
  test/bulk-edit/e2e.spec.ts
  test/bulk-edit/eslint.config.js
  test/bulk-edit/payload-types.ts
  test/bulk-edit/schema.graphql
  test/bulk-edit/shared.ts
  test/bulk-edit/tsconfig.eslint.json
  test/bulk-edit/tsconfig.json
  test/bulk-edit/types.d.ts
  test/versions/e2e.spec.ts
  test/versions/seed.ts
  test/versions/shared.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11647 feat: distinct error for unverified email login
  packages/payload/src/auth/operations/login.ts
  packages/payload/src/errors/UnverifiedEmail.ts
  packages/payload/src/errors/index.ts
  packages/payload/src/errors/types.ts
  packages/translations/src/clientKeys.ts
  packages/translations/src/languages/ar.ts
  packages/translations/src/languages/az.ts
  packages/translations/src/languages/bg.ts
  packages/translations/src/languages/ca.ts
  packages/translations/src/languages/cs.ts
  packages/translations/src/languages/da.ts
  packages/translations/src/languages/de.ts
  packages/translations/src/languages/en.ts
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/et.ts
  packages/translations/src/languages/fa.ts
  packages/translations/src/languages/fr.ts
  packages/translations/src/languages/he.ts
  packages/translations/src/languages/hr.ts
  packages/translations/src/languages/hu.ts
  packages/translations/src/languages/it.ts
  packages/translations/src/languages/ja.ts
  packages/translations/src/languages/ko.ts
  packages/translations/src/languages/lt.ts
  packages/translations/src/languages/my.ts
  packages/translations/src/languages/nb.ts
  packages/translations/src/languages/nl.ts
  packages/translations/src/languages/pl.ts
  packages/translations/src/languages/pt.ts
  packages/translations/src/languages/ro.ts
  packages/translations/src/languages/rs.ts
  packages/translations/src/languages/rsLatin.ts
  packages/translations/src/languages/ru.ts
  packages/translations/src/languages/sk.ts
  packages/translations/src/languages/sl.ts
  packages/translations/src/languages/sv.ts
  packages/translations/src/languages/th.ts
  packages/translations/src/languages/tr.ts
  packages/translations/src/languages/uk.ts
  packages/translations/src/languages/vi.ts
  packages/translations/src/languages/zh.ts
  packages/translations/src/languages/zhTw.ts
Labels: created-by: Contributor

#11757 fix: improves email validation format rules
  packages/payload/src/fields/validations.ts
Labels: created-by: Payload team

#11749 chore: export type FieldAccessArgs
  packages/payload/src/fields/config/types.ts
Labels: created-by: Payload team

#11758 fix(plugin-import-export): translated preview labels
  packages/plugin-import-export/src/components/Preview/index.tsx
  test/plugin-import-export/collections/Pages.ts
  test/plugin-import-export/payload-types.ts
Labels: created-by: Payload team

#11762 fix(plugin-import-export): export with draft true
  packages/plugin-import-export/src/export/createExport.ts
  packages/plugin-import-export/src/export/getFields.ts
  test/_community/payload-types.ts
  test/plugin-import-export/int.spec.ts
Labels: created-by: Payload team

#11685 feat: add find to payloadDataLoader to cache local API queries
  packages/payload/src/collections/dataloader.ts
  packages/payload/src/fields/validations.ts
  packages/payload/src/types/index.ts
  packages/richtext-lexical/src/features/converters/lexicalToHtml/async/converters/upload.ts
  packages/richtext-lexical/src/features/converters/lexicalToHtml/sync/converters/upload.ts
  packages/richtext-lexical/src/features/converters/lexicalToJSX/converter/converters/upload.tsx
  test/database/postgres-vector.int.spec.ts
  test/dataloader/int.spec.ts
Labels: created-by: Payload team

#11739 fix(richtext-lexical): make the toolbar indent button consider the disabledNodes property on IndentFeature
  packages/richtext-lexical/src/features/indent/client/index.tsx
Labels: created-by: Payload team

#11707 fix(richtext-lexical): error in admin panel when setting a richtext field in `useAsTitle`
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/elements/DocumentControls/index.tsx
  packages/ui/src/elements/PublishButton/ScheduleDrawer/buildUpcomingColumns.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Date/index.tsx
  packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
  packages/ui/src/elements/ThumbnailCard/index.tsx
  packages/ui/src/exports/shared/index.ts
  packages/ui/src/fields/Relationship/optionsReducer.ts
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/utilities/formatDocTitle/formatDateTitle.ts
  packages/ui/src/utilities/formatDocTitle/formatLexicalDocTitle.ts
  packages/ui/src/utilities/formatDocTitle/index.ts
  packages/ui/src/views/Edit/SetDocumentTitle/index.tsx
Labels: created-by: Payload team

#11761 fix: email format validation with hyphens
  packages/payload/src/fields/validations.ts
  test/auth/int.spec.ts
Labels: created-by: Payload team

#11768 feat(db-*): support sort in db.updateMany
  packages/db-mongodb/src/updateMany.ts
  packages/drizzle/src/updateMany.ts
  packages/payload/src/database/types.ts
  test/bulk-edit/payload-types.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
Labels: created-by: Payload team

#11769 feat: sort support for payload.update operation
  packages/payload/src/collections/endpoints/update.ts
  packages/payload/src/collections/operations/local/update.ts
  packages/payload/src/collections/operations/update.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#11764 feat(richtext-lexical): upgrade lexical from 0.27.2 to 0.28.0
  packages/richtext-lexical/package.json
  packages/richtext-lexical/src/features/experimental_table/client/plugins/TableActionMenuPlugin/index.tsx
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/theme/EditorTheme.scss
  pnpm-lock.yaml
Labels: created-by: Payload team

#11778 fix: wrap login redirect routes with encodeURIComponent
  packages/next/src/views/Login/LoginForm/index.tsx
  packages/next/src/views/Login/index.tsx
  packages/ui/src/views/Edit/index.tsx
Labels: created-by: Payload team

#11780 fix: save button styles in edit-many modal
  packages/ui/src/elements/EditMany/index.scss
Labels: created-by: Payload team

#11788 docs: mention correct --disable-transpile flag
  docs/local-api/outside-nextjs.mdx
Labels: created-by: Payload team

#11793 fix(db-mongodb): spread version schema options correctly
  packages/db-mongodb/src/init.ts
Labels: created-by: Payload team

#11771 fix(richtext-lexical): error in admin panel when block collapsed preference is not an array
  packages/richtext-lexical/src/utilities/buildInitialState.ts
Labels: created-by: Contributor

#11795 chore: de-Alessify updateJobs
  packages/payload/src/queues/utilities/updateJob.ts
Labels: created-by: Payload team

#11489 perf: use direct db calls in job-queue system
  packages/payload/src/config/sanitize.ts
  packages/payload/src/index.ts
  packages/payload/src/queues/config/index.ts
  packages/payload/src/queues/config/types/index.ts
  packages/payload/src/queues/localAPI.ts
  packages/payload/src/queues/operations/runJobs/index.ts
  packages/payload/src/queues/operations/runJobs/runJob/getUpdateJobFunction.ts
  packages/payload/src/queues/operations/runJobs/runJob/handleWorkflowError.ts
  packages/payload/src/queues/operations/runJobs/runJob/index.ts
  packages/payload/src/queues/utilities/sanitizeUpdateData.ts
  packages/payload/src/queues/utilities/updateJob.ts
  test/queues/workflows/noRetriesSet.ts
  test/queues/workflows/retries0.ts
  test/queues/workflows/retriesBackoffTest.ts
  test/queues/workflows/retriesTest.ts
  test/queues/workflows/retriesWorkflowLevelTest.ts
  test/queues/workflows/subTaskFails.ts
  test/queues/workflows/workflowAndTasksRetriesUndefined.ts
  test/queues/workflows/workflowRetries2TasksRetries0.ts
  test/queues/workflows/workflowRetries2TasksRetriesUndefined.ts
Labels: created-by: Payload team

#11802 feat: pass i18n through field label and description functions
  packages/next/src/views/Versions/index.tsx
  packages/payload/src/admin/forms/Description.ts
  packages/payload/src/collections/config/client.ts
  packages/payload/src/config/types.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/globals/config/client.ts
  packages/payload/src/utilities/getTranslatedLabel.ts
  packages/translations/src/utilities/getTranslation.ts
  packages/ui/src/fields/Tabs/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
  packages/ui/src/utilities/groupNavItems.ts
Labels: created-by: Payload team

#11785 test: deflakes conditional logic e2e
  test/fields/collections/ConditionalLogic/e2e.spec.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11803 feat(db-mongodb): support sorting by fields in other collections through a relationship field
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findGlobalVersions.ts
  packages/db-mongodb/src/findVersions.ts
  packages/db-mongodb/src/queries/buildSortParam.ts
  packages/db-mongodb/src/queryDrafts.ts
  packages/db-mongodb/src/updateMany.ts
  packages/db-mongodb/src/utilities/aggregatePaginate.ts
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  packages/payload/src/index.ts
  test/relationships/config.ts
  test/relationships/int.spec.ts
  test/relationships/payload-types.ts
Labels: created-by: Payload team

#11776 fix(ui): exclude fields lacking permissions from bulk edit
  packages/payload/src/exports/shared.ts
  packages/payload/src/utilities/getFieldPermissions.ts
  packages/ui/src/elements/BulkUpload/EditMany/DrawerContent.tsx
  packages/ui/src/elements/EditMany/DrawerContent.tsx
  packages/ui/src/elements/EditMany/index.tsx
  packages/ui/src/elements/FieldSelect/index.tsx
  packages/ui/src/elements/FieldSelect/reduceFieldOptions.ts
  packages/ui/src/forms/RenderFields/index.tsx
  test/bulk-edit/collections/Posts/index.ts
  test/bulk-edit/e2e.spec.ts
  test/bulk-edit/payload-types.ts
Labels: created-by: Payload team

#11770 docs: fix links to locked document docs
  docs/admin/react-hooks.mdx
Labels: created-by: Contributor

#11823 feat!: bump minimum next version to 15.2.3
  examples/astro/payload/package.json
  examples/auth/package.json
  examples/custom-components/package.json
  examples/custom-server/package.json
  examples/draft-preview/package.json
  examples/email/package.json
  examples/form-builder/package.json
  examples/live-preview/package.json
  examples/localization/package.json
  examples/multi-tenant/package.json
  examples/remix/payload/package.json
  examples/tailwind-shadcn-ui/package.json
  examples/whitelabel/package.json
  package.json
  packages/admin-bar/package.json
  packages/live-preview-react/package.json
  packages/next/package.json
  packages/plugin-cloud-storage/package.json
  packages/plugin-form-builder/package.json
  packages/plugin-multi-tenant/package.json
  packages/plugin-search/package.json
  packages/plugin-sentry/package.json
  packages/plugin-seo/package.json
  packages/plugin-stripe/package.json
  packages/richtext-lexical/package.json
  packages/richtext-slate/package.json
  packages/translations/package.json
  packages/ui/package.json
  pnpm-lock.yaml
  templates/_template/package.json
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/plugin/package.json
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-payload-cloud/package.json
  templates/with-postgres/package.json
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-website/package.json
  test/package.json
Labels: created-by: Payload team

#11763 fix: respect `draft: true` when querying docs for the join field
  packages/db-mongodb/src/find.ts
  packages/db-mongodb/src/findOne.ts
  packages/db-mongodb/src/utilities/buildJoinAggregation.ts
  packages/drizzle/src/find.ts
  packages/drizzle/src/find/buildFindManyArgs.ts
  packages/drizzle/src/find/findMany.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/findOne.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/next/src/layouts/Root/index.tsx
  packages/payload/src/collections/operations/find.ts
  packages/payload/src/collections/operations/findByID.ts
  packages/payload/src/database/types.ts
  packages/payload/src/index.ts
  packages/payload/src/versions/drafts/replaceWithDraftIfAvailable.ts
  packages/ui/src/fields/Upload/Input.tsx
  test/joins/int.spec.ts
Labels: created-by: Payload team

#11834 chore(admin-bar): enable TypeScript strict
  packages/admin-bar/tsconfig.json
Labels: created-by: Payload team

#11837 fix(richtext-lexical): ensure initial state for nested lexical fields
  packages/richtext-lexical/src/field/rscEntry.tsx
  test/fields/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/fields/collections/LexicalInBlock/index.ts
  test/fields/seed.ts
Labels: created-by: Payload team

#11808 fix(next): version view breaking for deeply nested tabs, rows and collapsibles
  packages/next/src/views/Version/RenderFieldsToDiff/buildVersionFields.tsx
  packages/next/src/views/Version/RenderFieldsToDiff/utilities/getFieldPathsModified.ts
  packages/payload/src/fields/utilities/getFieldPaths.ts
  test/versions/collections/Diff.ts
  test/versions/e2e.spec.ts
  test/versions/payload-types.ts
  test/versions/seed.ts
Labels: created-by: Payload team

#11833 chore(db-vercel-postgres): enable TypeScript strict
  packages/db-vercel-postgres/src/connect.ts
  packages/db-vercel-postgres/src/index.ts
  packages/db-vercel-postgres/tsconfig.json
Labels: created-by: Payload team

#11842 refactor(richtext-lexical): ensure field can be rendered outside EntityVisibilityProvider
  packages/richtext-lexical/src/exports/client/index.ts
  packages/richtext-lexical/src/features/relationship/client/utils/EnabledRelationshipsCondition.tsx
  packages/richtext-lexical/src/features/upload/client/component/index.tsx
  packages/richtext-lexical/src/features/upload/client/index.tsx
  packages/richtext-lexical/src/features/upload/client/plugin/index.tsx
  packages/richtext-lexical/src/features/upload/server/graphQLPopulationPromise.ts
  packages/richtext-lexical/src/features/upload/server/index.ts
  packages/richtext-lexical/src/features/upload/server/validate.ts
  packages/richtext-lexical/src/index.ts
  packages/richtext-lexical/src/lexical/config/server/default.ts
Labels: created-by: Payload team

#11831 chore(db-sqlite): enable TypeScript strict
  packages/db-sqlite/package.json
  packages/db-sqlite/src/columnToCodeConverter.ts
  packages/db-sqlite/src/connect.ts
  packages/db-sqlite/src/countDistinct.ts
  packages/db-sqlite/src/createJSONQuery/index.ts
  packages/db-sqlite/src/deleteWhere.ts
  packages/db-sqlite/src/dropDatabase.ts
  packages/db-sqlite/src/execute.ts
  packages/db-sqlite/src/index.ts
  packages/db-sqlite/src/init.ts
  packages/db-sqlite/src/insert.ts
  packages/db-sqlite/src/schema/buildDrizzleTable.ts
  packages/db-sqlite/tsconfig.json
  pnpm-lock.yaml
Labels: created-by: Payload team

#11814 fix(next): adds safe redirect utility and apply to login redirects
  packages/next/src/utilities/getSafeRedirect.ts
  packages/next/src/views/Login/LoginForm/index.tsx
  packages/next/src/views/Login/index.tsx
Labels: created-by: Payload team

#11857 feat: add Armenian translation
  packages/payload/src/exports/i18n/hy.ts
  packages/translations/src/exports/all.ts
  packages/translations/src/languages/hy.ts
  packages/translations/src/types.ts
  packages/translations/src/utilities/languages.ts
Labels: created-by: Payload team

#11858 test: rearrange relationships test blocks properly
  test/relationships/int.spec.ts
Labels: created-by: Payload team

#11860 ci: add license-check script
  .gitignore
  package.json
  pnpm-lock.yaml
  tools/releaser/src/lib/getPackageDetails.ts
  tools/scripts/package.json
  tools/scripts/src/license-check.ts
Labels: created-by: Payload team

#11847 perf(drizzle): remove unnecessary db.select call in updateOne operation
  packages/drizzle/src/updateOne.ts
Labels: created-by: Payload team

#11861 fix: auth fields distrupt field paths within the field schema map
  packages/next/src/views/Version/RenderFieldsToDiff/buildVersionFields.tsx
  packages/next/src/views/Version/index.tsx
  packages/ui/src/utilities/buildClientFieldSchemaMap/index.ts
  packages/ui/src/utilities/buildFieldSchemaMap/index.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11846 perf: reduce job queue db calls
  packages/db-mongodb/src/index.ts
  packages/db-mongodb/src/updateJobs.ts
  packages/db-postgres/src/index.ts
  packages/db-sqlite/src/index.ts
  packages/db-vercel-postgres/src/index.ts
  packages/drizzle/src/index.ts
  packages/drizzle/src/updateJobs.ts
  packages/payload/src/database/createDatabaseAdapter.ts
  packages/payload/src/database/defaultUpdateJobs.ts
  packages/payload/src/database/types.ts
  packages/payload/src/index.ts
  packages/payload/src/queues/utilities/updateJob.ts
Labels: created-by: Payload team

#11779 feat: orderable join field
  docs/fields/join.mdx
  packages/next/src/views/List/index.tsx
  packages/next/src/views/Versions/index.tsx
  packages/payload/src/admin/functions/index.ts
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/config/orderable/fractional-indexing.js
  packages/payload/src/config/orderable/index.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/flattenAllFields.ts
  packages/ui/src/elements/RelationshipTable/index.tsx
  packages/ui/src/elements/SortHeader/index.tsx
  packages/ui/src/elements/SortRow/index.tsx
  packages/ui/src/elements/Table/OrderableTable.tsx
  packages/ui/src/providers/ListQuery/index.tsx
  packages/ui/src/providers/ListQuery/types.ts
  packages/ui/src/utilities/buildTableState.ts
  packages/ui/src/utilities/renderTable.tsx
  test/sort/collections/Orderable/index.ts
  test/sort/collections/OrderableJoin/index.ts
  test/sort/collections/Sortable/index.ts
  test/sort/config.ts
  test/sort/e2e.spec.ts
  test/sort/payload-types.ts
Labels: created-by: Payload team

#11867 fix(ui): nested custom components sometimes disappear when queued in form state
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/forms/Form/index.tsx
  test/form-state/collections/Posts/index.ts
  test/form-state/e2e.spec.ts
  test/form-state/payload-types.ts
Labels: created-by: Payload team

#11872 fix(ui): query presets are available for unrelated collections
  packages/ui/src/elements/ListControls/useQueryPresets.tsx
  test/query-presets/collections/Posts/index.ts
  test/query-presets/config.ts
  test/query-presets/e2e.spec.ts
  test/query-presets/helpers/openQueryPresetDrawer.ts
  test/query-presets/payload-types.ts
  test/query-presets/slugs.ts
  tsconfig.base.json
Labels: created-by: Payload team

#11881 docs: fix links in custom components and custom features
  docs/custom-components/custom-views.mdx
  docs/custom-components/list-view.mdx
  docs/rich-text/custom-features.mdx
Labels: created-by: Contributor

#11880 fix(plugin-cloud-storage): ensure client handlers are added to import map regardless of enabled state
  packages/payload/src/bin/generateImportMap/iterateConfig.ts
  packages/payload/src/config/types.ts
  packages/plugin-cloud-storage/src/utilities/initClientUploads.ts
Labels: created-by: Payload team

#11844 perf(ui): download only images and optimize image selection for document edit view, prioritize best-fit size
  packages/ui/src/elements/Table/DefaultCell/fields/File/index.tsx
  packages/ui/src/fields/Upload/HasMany/index.tsx
  packages/ui/src/fields/Upload/HasOne/index.tsx
  packages/ui/src/fields/Upload/RelationshipContent/index.tsx
  packages/ui/src/utilities/getBestFitFromSizes.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/payload-types.ts
Labels: created-by: Contributor

#11750 chore(ui): added selected option as a class to list table cell
  packages/ui/src/elements/Table/DefaultCell/index.tsx
  test/admin/collections/Posts.ts
  test/admin/e2e/list-view/e2e.spec.ts
Labels: created-by: Payload team
