Repository payloadcms/payload, pull requests merged in 2025-05, with the labels that each got.

#10636 fix(cpa): overwrites existing env variables
  packages/create-payload-app/src/lib/create-project.spec.ts
  packages/create-payload-app/src/lib/manage-env-files.ts
Labels: created-by: Payload team

#12289 fix(graphql): population of joins that target relationship fields that have `relationTo` as an array
  packages/graphql/src/schema/buildObjectType.ts
  packages/graphql/src/schema/fieldToSchemaMap.ts
  packages/graphql/src/schema/fieldToWhereInputSchemaMap.ts
  packages/graphql/src/schema/initCollections.ts
  test/joins/int.spec.ts
Labels: created-by: Payload team

#11925 feat(ui): allow array fields to be filtered in list view
  packages/ui/src/elements/WhereBuilder/reduceFields.tsx
  test/admin/collections/Array.ts
  test/admin/config.ts
  test/admin/e2e/list-view/e2e.spec.ts
  test/admin/payload-types.ts
  test/admin/slugs.ts
Labels: created-by: Contributor

#12253 feat(ui): make select and relationship field placeholder configurable
  docs/fields/relationship.mdx
  docs/fields/select.mdx
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/ReactSelect/index.tsx
  packages/ui/src/elements/ReactSelect/types.ts
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Select/index.tsx
  packages/ui/src/elements/WhereBuilder/Condition/Select/types.ts
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Select/Input.tsx
  packages/ui/src/fields/Select/index.tsx
  test/admin/collections/Placeholder.ts
  test/admin/config.ts
  test/admin/e2e/list-view/e2e.spec.ts
  test/admin/slugs.ts
Labels: created-by: Contributor

#11983 fix(ui): fix version list status for unpublished documents
  packages/next/src/views/Version/SelectComparison/index.tsx
  packages/next/src/views/Versions/index.tsx
  test/versions/e2e.spec.ts
Labels: created-by: Contributor

#12207 fix(ui): blockType ignored when merging server form state
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  test/form-state/int.spec.ts
Labels: created-by: Contributor

#11939 feat(ui): add option to open related documents in a new tab
  packages/ui/src/elements/ReactSelect/types.ts
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Relationship/select-components/MultiValueLabel/index.tsx
  packages/ui/src/fields/Relationship/select-components/SingleValue/index.tsx
  test/fields/collections/Relationship/e2e.spec.ts
  test/helpers/e2e/toggleDocDrawer.ts
  tsconfig.base.json
Labels: created-by: Contributor

#12304 chore(storage-uploadthing): enable TypeScript strict
  packages/storage-uploadthing/src/client/UploadthingClientUploadHandler.ts
  packages/storage-uploadthing/src/staticHandler.ts
  packages/storage-uploadthing/tsconfig.json
Labels: created-by: Payload team

#12201 fix(graphql): `nextPage` and `prevPage` are non nullable even though they can be `null` sometimes
  packages/graphql/src/schema/buildPaginatedListType.ts
  test/graphql/int.spec.ts
Labels: created-by: Payload team

#12302 fix(db-postgres): start transaction in v2-v3 migration only after drizzle prompts to avoid timeout
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/index.ts
Labels: created-by: Payload team

#11985 feat(ui): update RelationshipFilter if only filterOptions are changed
  packages/ui/src/elements/WhereBuilder/Condition/Relationship/index.tsx
Labels: stale

#12309 feat: exports additional login helper utils
  packages/payload/src/auth/isLocked.ts
  packages/payload/src/auth/isUserLocked.ts
  packages/payload/src/auth/operations/login.ts
  packages/payload/src/index.ts
Labels: created-by: Payload team

#12307 feat(storage-s3): presigned URLs for file downloads
  docs/upload/storage-adapters.mdx
  packages/storage-s3/src/index.ts
  packages/storage-s3/src/staticHandler.ts
  test/storage-s3/collections/MediaWithSignedDownloads.ts
  test/storage-s3/config.ts
  test/storage-s3/int.spec.ts
  test/storage-s3/payload-types.ts
  test/storage-s3/shared.ts
Labels: created-by: Payload team

#12243 docs: add pagination and limit: 0 information in pagination for API docs
  docs/queries/pagination.mdx
Labels: created-by: Payload team

#11898 feat(ui): display the actual error message on unpublish if available
  packages/ui/src/elements/Status/index.tsx
  test/versions/collections/ErrorOnUnpublish.ts
  test/versions/config.ts
  test/versions/e2e.spec.ts
  test/versions/payload-types.ts
  test/versions/slugs.ts
Labels: created-by: Contributor

#9562 fix(upload): ensure only image files are read for preview
  packages/payload/src/admin/components/views/collections/Edit/Upload/index.tsx
Labels: v2, keep

#12359 templates: fix categories search sync
  examples/localization/src/search/beforeSync.ts
  examples/localization/src/search/fieldOverrides.ts
  templates/website/src/payload-types.ts
  templates/website/src/search/beforeSync.ts
  templates/website/src/search/fieldOverrides.ts
  templates/with-vercel-website/src/payload-types.ts
  templates/with-vercel-website/src/search/beforeSync.ts
  templates/with-vercel-website/src/search/fieldOverrides.ts
Labels: created-by: Payload team

#12354 fix(db-mongodb): localized dates being returned as date objects instead of strings
  packages/db-mongodb/src/utilities/transform.ts
  test/localization/collections/LocalizedDateFields/index.ts
  test/localization/config.ts
  test/localization/int.spec.ts
  test/localization/payload-types.ts
  test/localization/shared.ts
Labels: created-by: Payload team

#12303 chore(plugin-stripe): enable TypeScript strict
  packages/plugin-stripe/src/hooks/createNewInStripe.ts
  packages/plugin-stripe/src/hooks/deleteFromStripe.ts
  packages/plugin-stripe/src/hooks/syncExistingWithStripe.ts
  packages/plugin-stripe/src/index.ts
  packages/plugin-stripe/src/routes/rest.ts
  packages/plugin-stripe/src/routes/webhooks.ts
  packages/plugin-stripe/tsconfig.json
Labels: created-by: Payload team

#12365 fix(db-postgres): selectDistinct might remove expected rows when querying with nested fields or relations
  packages/drizzle/src/find/findMany.ts
  test/fields/collections/Date/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#12387 fix(db-mongodb): sort by fields in relationships with `draft: true`
  packages/db-mongodb/src/queries/buildSortParam.ts
  packages/db-mongodb/src/queryDrafts.ts
  test/relationships/int.spec.ts
Labels: created-by: Payload team

#12385 docs: add local api instructions for vercel content link
  docs/integrations/vercel-content-link.mdx
Labels: created-by: Payload team

#12352 fix(ui): passes value to server component args
  packages/payload/src/admin/forms/Field.ts
  packages/ui/src/forms/fieldSchemasToFormState/renderField.tsx
Labels: created-by: Payload team

#12394 chore: add no-frozen-lockfile flag for templates script
  tools/scripts/src/generate-template-variations.ts
Labels: created-by: Payload team

#12353 docs: remove link to outdated ecommerce template from stripe plugin docs
  docs/plugins/stripe.mdx
Labels: created-by: Payload team

#12390 chore: add NODE_OPTIONS to vscode settings by default in the repo for playwright extension
  .vscode/settings.json
Labels: created-by: Payload team

#12086 perf: actually debounce rich text editor field value updates to only process latest state
  packages/richtext-lexical/src/field/Field.tsx
Labels: created-by: Contributor

#12322 feat: prevent query preset lockout
  .vscode/launch.json
  packages/payload/src/admin/RichText.ts
  packages/payload/src/collections/operations/local/create.ts
  packages/payload/src/query-presets/config.ts
  packages/payload/src/query-presets/constraints.ts
  packages/payload/src/query-presets/preventLockout.ts
  packages/payload/src/utilities/getEntityPolicies.ts
  packages/ui/src/elements/ListControls/useQueryPresets.tsx
  packages/ui/src/elements/QueryPresets/fields/WhereField/index.tsx
  test/query-presets/collections/Pages/index.ts
  test/query-presets/collections/Posts/index.ts
  test/query-presets/config.ts
  test/query-presets/e2e.spec.ts
  test/query-presets/fields/roles.ts
  test/query-presets/int.spec.ts
  test/query-presets/payload-types.ts
  test/query-presets/seed.ts
  tsconfig.base.json
Labels: created-by: Payload team

#12402 perf: remove duplicative deep loops during field sanitization
  packages/payload/src/collections/config/reservedFieldNames.ts
  packages/payload/src/collections/config/sanitize.ts
  packages/payload/src/collections/config/useAsTitle.ts
  packages/payload/src/config/sanitize.ts
  packages/payload/src/fields/config/reservedFieldNames.spec.ts
  packages/payload/src/fields/config/reservedFieldNames.ts
  packages/payload/src/fields/config/sanitize.spec.ts
  packages/payload/src/fields/config/sanitize.ts
Labels: created-by: Payload team

#12318 feat: allow group fields to have an optional name
  docs/fields/group.mdx
  packages/db-mongodb/src/models/buildSchema.ts
  packages/db-mongodb/src/queries/sanitizeQueryValue.ts
  packages/db-mongodb/src/utilities/buildProjectionFromSelect.ts
  packages/graphql/src/schema/buildMutationInputType.ts
  packages/graphql/src/schema/fieldToSchemaMap.ts
  packages/payload/src/auth/getFieldsToSign.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/hooks/afterChange/promise.ts
  packages/payload/src/fields/hooks/afterRead/promise.ts
  packages/payload/src/fields/hooks/beforeChange/promise.ts
  packages/payload/src/fields/hooks/beforeDuplicate/promise.ts
  packages/payload/src/fields/hooks/beforeValidate/promise.ts
  packages/payload/src/index.ts
  packages/payload/src/utilities/configToJSONSchema.ts
  packages/payload/src/utilities/fieldSchemaToJSON.ts
  packages/payload/src/utilities/flattenAllFields.ts
  packages/payload/src/utilities/traverseFields.ts
  packages/ui/src/elements/WhereBuilder/reduceFields.tsx
  packages/ui/src/fields/Group/index.tsx
  packages/ui/src/fields/Join/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/fieldSchemasToFormState/calculateDefaultValues/promise.ts
  packages/ui/src/utilities/buildClientFieldSchemaMap/traverseFields.ts
  packages/ui/src/utilities/buildFieldSchemaMap/traverseFields.ts
  packages/ui/src/utilities/copyDataFromLocale.ts
  test/fields/collections/Group/e2e.spec.ts
  test/fields/collections/Group/index.ts
  test/fields/collections/Group/shared.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
  test/fields/seed.ts
  test/types/config.ts
  test/types/payload-types.ts
  test/types/types.spec.ts
  tools/scripts/src/generateTranslations/utils/index.ts
  tsconfig.base.json
Labels: created-by: Payload team

#12408 fix(ui): respect `filterOptions: { id: { in: [] } }`
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/utilities/sanitizeFilterOptionsQuery.ts
Labels: created-by: Payload team

#12310 fix(db-postgres): v2-v3 migration errors with relation already exists
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/groupUpSQLStatements.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/index.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/migrateRelationships.ts
Labels: created-by: Payload team

#12389 fix(richtext-lexical): newTab not being able to be checked to true by default
  packages/richtext-lexical/src/features/link/client/index.tsx
  test/lexical/baseConfig.ts
  test/lexical/collections/LexicalLinkFeature/e2e.spec.ts
  test/lexical/collections/LexicalLinkFeature/index.ts
  test/lexical/collections/LexicalLinkFeature/utils.ts
  test/lexical/payload-types.ts
  test/lexical/slugs.ts
Labels: created-by: Payload team

#12237 fix(db-postgres): `dbName` in arrays regression with long generated drizzle relation names
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/schema/traverseFields.ts
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/drizzle/src/utilities/getArrayRelationName.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
  test/database/up-down-migration/migrations/20250328_185055.json
  test/database/up-down-migration/migrations/20250328_185055.ts
  test/database/up-down-migration/migrations/20250428_121536.json
  test/database/up-down-migration/migrations/20250428_121536.ts
  test/database/up-down-migration/migrations/index.ts
Labels: created-by: Payload team

#12240 fix(db-postgres): build `near` sort query properly for point fields
  packages/drizzle/src/queries/buildOrderBy.ts
  packages/drizzle/src/queries/buildQuery.ts
  packages/drizzle/src/queries/parseParams.ts
Labels: created-by: Payload team

#12213 fix(ui): req not being threaded through to views
  packages/next/src/elements/Nav/getNavPrefs.ts
  packages/next/src/elements/Nav/index.tsx
  packages/next/src/layouts/Root/index.tsx
  packages/next/src/templates/Default/index.tsx
  packages/next/src/views/Document/getDocumentData.ts
  packages/next/src/views/Root/index.tsx
Labels: created-by: Payload team

#12339 feat(ui): extracts relationship input for external use
  packages/create-payload-app/src/lib/manage-env-files.ts
  packages/payload/src/fields/config/types.ts
  packages/ui/src/elements/AddNewRelation/index.tsx
  packages/ui/src/elements/AddNewRelation/types.ts
  packages/ui/src/exports/client/index.ts
  packages/ui/src/fields/Relationship/Input.tsx
  packages/ui/src/fields/Relationship/createRelationMap.ts
  packages/ui/src/fields/Relationship/findOptionsByValue.ts
  packages/ui/src/fields/Relationship/index.tsx
  packages/ui/src/fields/Relationship/optionsReducer.ts
  packages/ui/src/fields/Relationship/types.ts
  packages/ui/src/hooks/useDebouncedCallback.ts
  test/admin/payload-types.ts
  test/helpers.ts
  tools/scripts/src/generateTranslations/utils/index.ts
Labels: created-by: Payload team

#12423 chore: add ignores .next folder in eslint config for templates template
  templates/_template/eslint.config.mjs
Labels: created-by: Payload team

#12434 templates: bump for v3.38.0
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250516_145237_initial.json
  templates/with-postgres/src/migrations/20250516_145237_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/.env.example
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/.env.example
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250516_145207_initial.json
  templates/with-vercel-postgres/src/migrations/20250516_145207_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/blocks/Form/Select/index.tsx
  templates/with-vercel-website/src/components/Media/ImageMedia/index.tsx
  templates/with-vercel-website/src/components/Media/VideoMedia/index.tsx
  templates/with-vercel-website/src/migrations/20250516_145223_initial.json
  templates/with-vercel-website/src/migrations/20250516_145223_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#12433 fix(ui): render missing group children fields for unnamed group
  packages/ui/src/fields/Group/index.tsx
Labels: created-by: Contributor

#12432 fix(templates): make images visible in live preview if it is not running on port 3000
  templates/website/next.config.js
  templates/with-vercel-website/next.config.js
Labels: created-by: Payload team

#12436 perf(ui): useAsTitle field lags on slow cpu
  packages/plugin-multi-tenant/src/components/WatchTenantCollection/index.tsx
  packages/plugin-seo/src/fields/MetaDescription/MetaDescriptionComponent.tsx
  packages/plugin-seo/src/fields/MetaImage/MetaImageComponent.tsx
  packages/plugin-seo/src/fields/MetaTitle/MetaTitleComponent.tsx
  packages/plugin-seo/src/fields/Preview/PreviewComponent.tsx
  packages/ui/src/elements/Autosave/index.tsx
  packages/ui/src/elements/DeleteDocument/index.tsx
  packages/ui/src/elements/DocumentDrawer/DrawerHeader/index.tsx
  packages/ui/src/elements/PublishButton/ScheduleDrawer/index.tsx
  packages/ui/src/elements/RenderTitle/index.tsx
  packages/ui/src/elements/SaveDraftButton/index.tsx
  packages/ui/src/elements/Status/index.tsx
  packages/ui/src/exports/client/index.ts
  packages/ui/src/providers/DocumentInfo/index.tsx
  packages/ui/src/providers/DocumentInfo/types.ts
  packages/ui/src/providers/DocumentTitle/context.ts
  packages/ui/src/providers/DocumentTitle/index.tsx
  packages/ui/src/utilities/formatDocTitle/index.ts
  packages/ui/src/views/Edit/Auth/index.tsx
  packages/ui/src/views/Edit/SetDocumentStepNav/index.tsx
  packages/ui/src/views/Edit/SetDocumentTitle/index.tsx
  test/form-state/e2e.spec.ts
Labels: created-by: Payload team

#12422 fix: orderable with groups and tabs requires migration
  packages/drizzle/src/transform/read/traverseFields.ts
  packages/payload/src/config/orderable/index.ts
  packages/ui/src/elements/Table/OrderableTable.tsx
  test/sort/payload-types.ts
Labels: created-by: Payload team

#12440 fix: sanitize duplicate blocks
  packages/payload/src/fields/config/sanitize.spec.ts
  packages/payload/src/fields/config/sanitize.ts
Labels: created-by: Payload team

#12428 chore(drizzle): fix lint errors in `@payloadcms/drizzle`
  packages/drizzle/src/count.ts
  packages/drizzle/src/countGlobalVersions.ts
  packages/drizzle/src/countVersions.ts
  packages/drizzle/src/createGlobal.ts
  packages/drizzle/src/createGlobalVersion.ts
  packages/drizzle/src/createVersion.ts
  packages/drizzle/src/deleteOne.ts
  packages/drizzle/src/find/findMany.ts
  packages/drizzle/src/find/traverseFields.ts
  packages/drizzle/src/index.ts
  packages/drizzle/src/postgres/predefinedMigrations/v2-v3/fetchAndResave/traverseFields.ts
  packages/drizzle/src/queries/buildOrderBy.ts
  packages/drizzle/src/queries/buildQuery.ts
  packages/drizzle/src/queries/getTableColumnFromPath.ts
  packages/drizzle/src/queries/operatorMap.ts
  packages/drizzle/src/queries/selectDistinct.ts
  packages/drizzle/src/transactions/commitTransaction.ts
  packages/drizzle/src/transform/write/relationships.ts
  packages/drizzle/src/updateGlobal.ts
  packages/drizzle/src/updateGlobalVersion.ts
  packages/drizzle/src/updateMany.ts
  packages/drizzle/src/updateOne.ts
  packages/drizzle/src/updateVersion.ts
  packages/drizzle/src/upsertRow/insertArrays.ts
  packages/drizzle/src/upsertRow/types.ts
Labels: created-by: Payload team

#12447 fix(db-*): ensure consistent sorting even when sorting on non-unique fields or no sort parameters at all
  packages/db-mongodb/src/queries/buildSortParam.ts
  packages/drizzle/src/queries/buildOrderBy.ts
  test/sort/collections/NonUniqueSort/index.ts
  test/sort/config.ts
  test/sort/int.spec.ts
  test/sort/payload-types.ts
Labels: created-by: Payload team

#12448 fix(plugin-multi-tenant): add missing translation for Assigned Tenant field
  packages/plugin-multi-tenant/src/fields/tenantField/index.ts
  packages/plugin-multi-tenant/src/translations/languages/ar.ts
  packages/plugin-multi-tenant/src/translations/languages/az.ts
  packages/plugin-multi-tenant/src/translations/languages/bg.ts
  packages/plugin-multi-tenant/src/translations/languages/ca.ts
  packages/plugin-multi-tenant/src/translations/languages/cs.ts
  packages/plugin-multi-tenant/src/translations/languages/da.ts
  packages/plugin-multi-tenant/src/translations/languages/de.ts
  packages/plugin-multi-tenant/src/translations/languages/en.ts
  packages/plugin-multi-tenant/src/translations/languages/es.ts
  packages/plugin-multi-tenant/src/translations/languages/et.ts
  packages/plugin-multi-tenant/src/translations/languages/fa.ts
  packages/plugin-multi-tenant/src/translations/languages/fr.ts
  packages/plugin-multi-tenant/src/translations/languages/he.ts
  packages/plugin-multi-tenant/src/translations/languages/hr.ts
  packages/plugin-multi-tenant/src/translations/languages/hu.ts
  packages/plugin-multi-tenant/src/translations/languages/hy.ts
  packages/plugin-multi-tenant/src/translations/languages/it.ts
  packages/plugin-multi-tenant/src/translations/languages/ja.ts
  packages/plugin-multi-tenant/src/translations/languages/ko.ts
  packages/plugin-multi-tenant/src/translations/languages/lt.ts
  packages/plugin-multi-tenant/src/translations/languages/lv.ts
  packages/plugin-multi-tenant/src/translations/languages/my.ts
  packages/plugin-multi-tenant/src/translations/languages/nb.ts
  packages/plugin-multi-tenant/src/translations/languages/nl.ts
  packages/plugin-multi-tenant/src/translations/languages/pl.ts
  packages/plugin-multi-tenant/src/translations/languages/pt.ts
  packages/plugin-multi-tenant/src/translations/languages/ro.ts
  packages/plugin-multi-tenant/src/translations/languages/rs.ts
  packages/plugin-multi-tenant/src/translations/languages/rsLatin.ts
  packages/plugin-multi-tenant/src/translations/languages/ru.ts
  packages/plugin-multi-tenant/src/translations/languages/sk.ts
  packages/plugin-multi-tenant/src/translations/languages/sl.ts
  packages/plugin-multi-tenant/src/translations/languages/sv.ts
  packages/plugin-multi-tenant/src/translations/languages/th.ts
  packages/plugin-multi-tenant/src/translations/languages/tr.ts
  packages/plugin-multi-tenant/src/translations/languages/uk.ts
  packages/plugin-multi-tenant/src/translations/languages/vi.ts
  packages/plugin-multi-tenant/src/translations/languages/zh.ts
  packages/plugin-multi-tenant/src/translations/languages/zhTw.ts
  packages/plugin-multi-tenant/src/translations/types.ts
Labels: created-by: Payload team

#12444 fix(plugin-multi-tenant): multi-locale tenant select label
  packages/plugin-multi-tenant/src/components/TenantSelector/index.tsx
  test/plugin-multi-tenant/config.ts
Labels: created-by: Payload team

#12351 test: add test for sorting by a virtual field with a reference
  test/database/config.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#12291 fix: prevent resizing of original file with `withoutEnlargement` on update
  packages/payload/src/uploads/cropImage.ts
  packages/payload/src/uploads/generateFileData.ts
  test/uploads/config.ts
  test/uploads/e2e.spec.ts
  test/uploads/shared.ts
Labels: created-by: Payload team

#12461 fix: auto inject req.user into query preset constraints
  packages/payload/src/query-presets/constraints.ts
  packages/payload/src/query-presets/preventLockout.ts
  test/query-presets/int.spec.ts
Labels: created-by: Payload team

#12439 chore: ignore .idea run configuration templates
  .gitignore
Labels: created-by: Payload team

#12464 fix(db-mongodb): remove `limit` from nested querying
  packages/db-mongodb/src/queries/buildSearchParams.ts
Labels: created-by: Payload team

#12416 feat(plugin-form-builder): add new date field
  docs/plugins/form-builder.mdx
  packages/plugin-form-builder/src/collections/Forms/fields.ts
  packages/plugin-form-builder/src/types.ts
  test/plugin-form-builder/config.ts
  test/plugin-form-builder/e2e.spec.ts
  test/plugin-form-builder/payload-types.ts
  test/plugin-form-builder/seed/index.ts
Labels: created-by: Payload team

#12465 docs: update rich text to HTML conversion documentation
  docs/rich-text/converting-html.mdx
  docs/rich-text/converting-jsx.mdx
  docs/rich-text/converting-markdown.mdx
  docs/rich-text/converting-plaintext.mdx
Labels: created-by: Payload team

#12481 fix(ui): set gap to 0 in sort column buttons to remove unneeded spacing
  packages/ui/src/elements/SortColumn/index.scss
Labels: created-by: Payload team

#12167 chore(live-preview): load schemaJSON from proper client config in integration tests
  test/live-preview/int.spec.ts
Labels: created-by: Contributor

#12488 fix(cpa): ensure it always installs the latest version of the templates
  packages/create-payload-app/src/lib/constants.ts
  packages/create-payload-app/src/lib/templates.ts
  packages/create-payload-app/src/lib/update-payload-in-project.ts
  packages/create-payload-app/src/main.ts
  packages/create-payload-app/src/utils/getLatestPackageVersion.ts
Labels: created-by: Payload team

#12498 templates: bump for v3.39.0
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250522_142559_initial.json
  templates/with-postgres/src/migrations/20250522_142559_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250522_142529_initial.json
  templates/with-vercel-postgres/src/migrations/20250522_142529_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/migrations/20250522_142545_initial.json
  templates/with-vercel-website/src/migrations/20250522_142545_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#12499 templates: include ui package
  templates/_template/package.json
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250522_150852_initial.json
  templates/with-postgres/src/migrations/20250522_150852_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250522_150833_initial.json
  templates/with-vercel-postgres/src/migrations/20250522_150833_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/src/migrations/20250522_150837_initial.json
  templates/with-vercel-website/src/migrations/20250522_150837_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: created-by: Payload team

#12500 docs: folders beta
  docs/folders/overview.mdx
  packages/payload/src/collections/config/types.ts
  packages/payload/src/config/types.ts
Labels: created-by: Payload team

#12501 fix: update folders export paths
  packages/ui/src/elements/FolderView/Cell/index.client.tsx
  packages/ui/src/elements/FolderView/Field/index.server.tsx
  packages/ui/src/exports/client/index.ts
Labels: created-by: Payload team

#12504 templates: bump for v3.39.1
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250522_154901_initial.json
  templates/with-postgres/src/migrations/20250522_154901_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250522_154829_initial.json
  templates/with-vercel-postgres/src/migrations/20250522_154829_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/migrations/20250522_154847_initial.json
  templates/with-vercel-website/src/migrations/20250522_154847_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#12445 fix(db-*): `migrate:reset` executes in a wrong order
  packages/drizzle/src/migrateReset.ts
  packages/payload/src/database/migrations/migrateReset.ts
  test/database/int.spec.ts
Labels: created-by: Payload team

#12507 fix: delete subfolders hook with relational databases
  packages/payload/src/folders/createFolderCollection.ts
  packages/payload/src/folders/hooks/deleteSubfoldersAfterDelete.ts
  test/folders/int.spec.ts
Labels: created-by: Payload team

#12487 feat: select field filter options
  docs/fields/array.mdx
  docs/fields/blocks.mdx
  docs/fields/code.mdx
  docs/fields/collapsible.mdx
  docs/fields/date.mdx
  docs/fields/email.mdx
  docs/fields/group.mdx
  docs/fields/json.mdx
  docs/fields/number.mdx
  docs/fields/radio.mdx
  docs/fields/relationship.mdx
  docs/fields/select.mdx
  docs/fields/text.mdx
  docs/fields/textarea.mdx
  packages/next/src/views/List/resolveAllFilterOptions.ts
  packages/payload/src/admin/fields/Select.ts
  packages/payload/src/admin/forms/Form.ts
  packages/payload/src/fields/config/client.ts
  packages/payload/src/fields/config/types.ts
  packages/payload/src/fields/validations.spec.ts
  packages/payload/src/fields/validations.ts
  packages/ui/src/fields/Select/Input.tsx
  packages/ui/src/fields/Select/index.tsx
  packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
  packages/ui/src/forms/useField/index.tsx
  packages/ui/src/forms/useField/types.ts
  test/fields/collections/Select/e2e.spec.ts
  test/fields/collections/Select/index.ts
  test/fields/int.spec.ts
  test/fields/payload-types.ts
Labels: created-by: Payload team

#12509 fix(next): folder redirects not working
  packages/next/src/views/BrowseByFolder/buildView.tsx
  packages/next/src/views/BrowseByFolder/index.tsx
  packages/next/src/views/CollectionFolders/buildView.tsx
  packages/next/src/views/CollectionFolders/index.tsx
Labels: created-by: Payload team

#12514 perf: folder views download only images and get best fit from image sizes
  packages/payload/src/exports/shared.ts
  packages/payload/src/folders/utils/formatFolderOrDocumentItem.ts
  packages/payload/src/utilities/getBestFitFromSizes.ts
  packages/ui/src/elements/Table/DefaultCell/fields/File/index.tsx
  packages/ui/src/fields/Upload/HasMany/index.tsx
  packages/ui/src/fields/Upload/HasOne/index.tsx
Labels: created-by: Contributor

#12519 fix(ui): index based ids without useAsTitle breaks folders
  packages/payload/src/folders/utils/formatFolderOrDocumentItem.ts
  packages/ui/src/elements/FolderView/Drawers/MoveToFolder/index.tsx
  packages/ui/src/providers/Folders/index.tsx
  packages/ui/src/views/BrowseByFolder/index.tsx
  packages/ui/src/views/CollectionFolder/index.tsx
Labels: created-by: Payload team

#12523 fix: thread req into interal folder payload operations
  packages/next/src/views/BrowseByFolder/buildView.tsx
  packages/next/src/views/CollectionFolders/buildView.tsx
  packages/payload/src/folders/endpoints/populateFolderData.ts
  packages/payload/src/folders/utils/getFolderBreadcrumbs.ts
  packages/payload/src/folders/utils/getFolderData.ts
  packages/payload/src/folders/utils/getFoldersAndDocumentsFromJoin.ts
  packages/payload/src/folders/utils/getOrphanedDocs.ts
Labels: created-by: Payload team

#12525 fix(ui): only and files/folders to the grid/list if they were added to the current folder
  packages/ui/src/elements/FolderView/CurrentFolderActions/index.tsx
  packages/ui/src/elements/FolderView/Drawers/MoveToFolder/index.tsx
  packages/ui/src/elements/FolderView/Drawers/NewFolder/index.tsx
  packages/ui/src/elements/FolderView/Drawers/RenameFolder/index.tsx
  packages/ui/src/providers/Folders/index.tsx
Labels: created-by: Payload team

#12528 chore: fixes monorepo dev plugin-import-export
  tsconfig.base.json
Labels: created-by: Payload team

#12480 docs: fix typos, duplicated words, wrong property names etc.
  docs/access-control/globals.mdx
  docs/admin/preview.mdx
  docs/admin/react-hooks.mdx
  docs/authentication/cookies.mdx
  docs/authentication/email.mdx
  docs/authentication/jwt.mdx
  docs/authentication/operations.mdx
  docs/authentication/overview.mdx
  docs/authentication/token-data.mdx
  docs/configuration/collections.mdx
  docs/configuration/globals.mdx
  docs/configuration/overview.mdx
  docs/custom-components/document-views.mdx
  docs/custom-components/root-components.mdx
  docs/database/postgres.mdx
  docs/database/sqlite.mdx
  docs/fields/radio.mdx
  docs/hooks/context.mdx
  docs/jobs-queue/tasks.mdx
  docs/live-preview/client.mdx
  docs/rich-text/converting-jsx.mdx
  docs/versions/autosave.mdx
Labels: created-by: Contributor

#12557 fix(translations): correct Norwegian terms for “locale” and language labels
  packages/translations/src/languages/nb.ts
Labels: created-by: Contributor

#12548 fix: improve translation script prompt and fix some incorrectly used terms in spanish and dutch
  packages/translations/src/languages/es.ts
  packages/translations/src/languages/nl.ts
  tools/scripts/src/generateTranslations/utils/translateText.ts
Labels: created-by: Payload team

#12559 fix(storage-vercel-blob): client uploads with a prefix
  packages/storage-vercel-blob/src/client/VercelBlobClientUploadHandler.ts
  packages/storage-vercel-blob/src/index.ts
  packages/storage-vercel-blob/src/staticHandler.ts
Labels: created-by: Payload team

#12524 chore(ui): finish adding folders e2e tests
  test/folders/e2e.spec.ts
Labels: created-by: Payload team

#12570 fix(examples): update live-preview example to ESM
  examples/live-preview/next-env.d.ts
  examples/live-preview/package.json
  examples/live-preview/pnpm-lock.yaml
  examples/live-preview/src/migrations/seed.ts
  examples/live-preview/src/payload-types.ts
Labels: created-by: Payload team

#12305 fix(templates): update template/plugin and fix import map issue
  packages/create-payload-app/src/lib/configure-plugin-project.ts
  packages/create-payload-app/src/lib/create-project.spec.ts
  templates/plugin/.gitignore
  templates/plugin/README.md
  templates/plugin/dev/e2e.spec.ts
  templates/plugin/dev/helpers/NextRESTClient.ts
  templates/plugin/dev/int.spec.ts
  templates/plugin/dev/next.config.mjs
  templates/plugin/dev/payload.config.ts
  templates/plugin/dev/server.ts
  templates/plugin/eslint.config.js
  templates/plugin/jest.config.js
  templates/plugin/package.json
  templates/plugin/playwright.config.js
  templates/plugin/src/endpoints/customEndpointHandler.ts
  templates/plugin/src/index.ts
  templates/plugin/tsconfig.json
  templates/plugin/vitest.config.js
Labels: created-by: Payload team

#12579 fix(ui): filtering on hasMany fields
  packages/ui/src/elements/WhereBuilder/field-types.tsx
  packages/ui/src/elements/WhereBuilder/reduceFields.tsx
Labels: created-by: Payload team

#12529 fix(richtext-lexical, ui): opening relationship field with appearance: "drawer" inside rich text inline block
  packages/ui/src/fields/Relationship/Input.tsx
Labels: created-by: Payload team

#12581 feat: adds calling of before and after operation hooks to resetPassword
  packages/payload/src/auth/operations/local/resetPassword.ts
  packages/payload/src/auth/operations/resetPassword.ts
  packages/payload/src/collections/config/types.ts
  packages/payload/src/collections/operations/utils.ts
Labels: created-by: Payload team

#12555 fix(translations): improve Spanish translations
  packages/translations/src/languages/es.ts
  test/admin/e2e/general/e2e.spec.ts
  test/i18n/e2e.spec.ts
Labels: created-by: Payload team

#12583 fix(ui): oversized column selector pills
  packages/ui/src/elements/ColumnSelector/index.tsx
Labels: created-by: Payload team

#12597 fix(richtext-lexical): respect disableBlockName
  package.json
  packages/payload/src/utilities/getRequestLanguage.ts
  packages/richtext-lexical/src/features/blocks/client/component/index.tsx
  test/lexical/collections/Lexical/blocks.ts
  test/lexical/collections/Lexical/e2e/blocks/e2e.spec.ts
  test/lexical/collections/Lexical/e2e/main/e2e.spec.ts
  test/lexical/collections/Lexical/index.ts
  test/lexical/collections/LexicalLinkFeature/e2e.spec.ts
  test/lexical/collections/RichText/e2e.spec.ts
  test/lexical/collections/_LexicalFullyFeatured/e2e.spec.ts
  test/lexical/seed.ts
Labels: created-by: Payload team

#12515 fix: parseCookies ignore invalid encoded values
  packages/payload/src/utilities/parseCookies.ts
Labels: created-by: Contributor

#12599 refactor: use parseCookies method from Next.js
  packages/payload/src/auth/cookies.spec.ts
  packages/payload/src/auth/cookies.ts
Labels: created-by: Payload team

#12596 fix(db-*): disable DB connection for `payload migrate:create`
  packages/db-postgres/src/connect.ts
  packages/db-sqlite/src/connect.ts
  packages/db-sqlite/src/init.ts
  packages/db-vercel-postgres/src/connect.ts
  packages/drizzle/src/postgres/init.ts
  packages/payload/src/bin/migrate.ts
Labels: created-by: Payload team

#12590 fix(db-postgres): properly escape the `'` character
  packages/drizzle/src/schema/withDefault.ts
  test/database/config.ts
  test/database/int.spec.ts
  test/database/payload-types.ts
  test/database/up-down-migration/migrations/20250528_153134.json
  test/database/up-down-migration/migrations/20250528_153134.ts
  test/database/up-down-migration/migrations/index.ts
Labels: created-by: Payload team

#12613 templates: bump for v3.40.0
  templates/blank/package.json
  templates/blank/pnpm-lock.yaml
  templates/website/package.json
  templates/website/pnpm-lock.yaml
  templates/with-postgres/package.json
  templates/with-postgres/src/migrations/20250529_195145_initial.json
  templates/with-postgres/src/migrations/20250529_195145_initial.ts
  templates/with-postgres/src/migrations/index.ts
  templates/with-vercel-mongodb/package.json
  templates/with-vercel-postgres/package.json
  templates/with-vercel-postgres/src/migrations/20250529_195116_initial.json
  templates/with-vercel-postgres/src/migrations/20250529_195116_initial.ts
  templates/with-vercel-postgres/src/migrations/index.ts
  templates/with-vercel-website/package.json
  templates/with-vercel-website/src/migrations/20250529_195131_initial.json
  templates/with-vercel-website/src/migrations/20250529_195131_initial.ts
  templates/with-vercel-website/src/migrations/index.ts
Labels: area: templates, created-by: Payload team

#12561 refactor(translations): correct i18n translation for Mandarin
  packages/richtext-lexical/src/features/blockquote/server/i18n.ts
  packages/richtext-lexical/src/features/blocks/server/i18n.ts
  packages/translations/src/languages/zh.ts
Labels: created-by: Contributor

#12627 fix(richtext-lexical): export defaultColors for use in client components
  packages/richtext-lexical/src/exports/client/index.ts
Labels: created-by: Payload team
